### ISSUE TITLE
[Bug] <kuaikanmanhua and tohomh123>: <doesn't work>

### ISSUE THREAD

**Issue by zxhdmx** [tachiyomiorg/tachiyomi-extensions#4437] opened 2020-09-26 15:58 UTC
kuaikanmanhua can search
and Show chapters but can't read

tohomh123 It seems that the domain name has changed to tuhao456.com

**Comment by scb261** [comment] 2020-09-26 16:11
Open separate issues for different extensions. Would be also good if you provide information what exactly doesn't work and what error do you get. tohomh123 either down or just unavailable in my region

**Comment by scb261** [comment] 2021-02-12 17:11
Kuaikanmanhua - duplicate of #3335

tuhao456.com - many covers don't work and I didn't find any working chapter. I'll keep the issue open in case it's just temporary. Also they changed site (if it's actually new domain of tohomh123) and layout is similar to Manhuadui (ykmh.com) now. Just telling in case if it has too many similarities and could be done as multisrc

**Closed** 2021-05-24 13:01 UTC
Labels: bug
