### ISSUE TITLE
Source request

### ISSUE THREAD

**Issue by Okayama2** [tachiyomiorg/tachiyomi-extensions#9174] opened 2021-09-21 19:32 UTC
### Source name

truyenvn

### Source link

https://truyenvn.tv/

### Language

Vietnamese 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2021-09-21 19:38
Duplicate of #8731

**Closed by alessandrojean** 2021-09-21 19:38 UTC
Labels: Source request

**Comment by Okayama2** [comment] 2021-09-21 19:52
Plz!!I'm not very familiar with this, but could you please add the source I'm asking for?

**Comment by alessandrojean** [comment] 2021-09-21 19:54
It's already requested and there's already an open issue for it. Wait until someone have free time and wants to work on it, no ETA.

**Comment by Okayama2** [comment] 2021-09-22 01:17
Sorry for the problem. This is my first time using it, so I was a bit
confused. Thanks to your explanation, I understand better. Sorry to bother
you.

Vào 2:54, Th 4, 22 thg 9, 2021 Alessandro Jean ***@***.***>
đã viết:
