### ISSUE TITLE
Remove or add more rate limit to the source

### ISSUE THREAD

**Issue by LycNeptune** [tachiyomiorg/tachiyomi-extensions#13260] opened 2022-08-29 07:06 UTC
### Source information and language

Mangamax 1.3.8

### Steps to reproduce

Same with issue #13256
Error 429 when refreshing the library

### Expected behavior

No more error 429 and can refresh the library

### Actual behavior

Error 429 happen when we refresh the library..

### Tachiyomi version

0.1.3.6

### Android version

Android 7

### Other details

This is a continued issue because the previous issue #13256 as copy of another issue..so as i read about the another issue from the admin.. we need more rate limit that can refresh 1000 manga in 1 hour.. so we can at least refresh the library of manga on the app to avoid error 429 on app.. or we need to just remove the rate limit

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2022-08-29 09:47
Stop creating duplicate issues
Duplicate of #13182

**Closed by vetleledaal** 2022-08-29 09:47 UTC
Labels: Bug
