### ISSUE TITLE
Cyanide and Happiness source is not working

### ISSUE THREAD

**Issue by lucasbiondi** [tachiyomiorg/tachiyomi-extensions#10704] opened 2022-02-05 05:47 UTC
### Source information

Cyanide & Happiness

### Steps to reproduce

1. Go to Tachiyomi
2. Go to Extensions
3. Select Cyanide & Hapiness

Observed: 
No results found

This happens also for saved in library 

### Expected behavior

List comics by year and abilty to read comics 

### Actual behavior

No results founds

### Tachiyomi version

1.4.4

### Android version

Android 8.0.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment] 2022-02-05 05:57
>  I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open issue.

Duplicate of #10224

**Closed by curche** 2022-02-05 05:57 UTC
Labels: Bug
