### ISSUE TITLE
manhatic.com

### ISSUE THREAD

**Issue by Ghilas951** [tachiyomiorg/tachiyomi-extensions#8269] opened 2021-07-25 15:50 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

manhatic

### Source link

https://manhatic.com

### Language

Arabic

### Other details

![Capture+_2021-07-25-16-47-58_1](https://user-images.githubusercontent.com/87284048/126905274-88d218d7-b721-40da-95d0-f30bb0d8b430.png)

**Comment by alessandrojean** [comment] 2021-07-25 18:57
Duplicate of #8060

**Closed by alessandrojean** 2021-07-25 18:57 UTC
Labels: Source request
