### ISSUE TITLE
[Bug] <gmanga>: <index:8, size:7>

### ISSUE THREAD

**Issue by iForGamer** [tachiyomiorg/tachiyomi-extensions#6866] opened 2021-05-06 14:28 UTC
Chapters are not showing
![Screenshot_20210506-172532_Tachiyomi](https://user-images.githubusercontent.com/83744137/117315536-76684280-ae90-11eb-81ee-de1f91dc8d11.jpg)

**Comment by arkon** [comment] 2021-05-06 14:34
Duplicate of #6852

**Closed by arkon** 2021-05-06 14:34 UTC
Labels: bug
