### ISSUE TITLE
Mangahub Timeout

### ISSUE THREAD

**Issue by XYZ4114** [tachiyomiorg/tachiyomi-extensions#10889] opened 2022-02-21 17:32 UTC
### Source information

Mangahub 1.2.12

### Steps to reproduce

After clicking on mangahub source I wait for a minute and then it says timeout while other sources are working perfectly fine.

### Expected behavior

Normally mangahub would give me it's homepage of most popular in a few seconds.

### Actual behavior

Mangahub source is giving me timeout while my internet is working perfectly fine.

### Tachiyomi version

0.13.1

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-02-21 17:40
Duplicate of #10888

**Closed by arkon** 2022-02-21 17:40 UTC
Labels: Bug
