### ISSUE TITLE
[Bug] <Mangadex>: <502 an not download chapters>

### ISSUE THREAD

**Issue by Akazotik** [tachiyomiorg/tachiyomi-extensions#6013] opened 2021-03-01 04:50 UTC
## Device information
- Tachiyomi version: r3130
- Android version: 10

## Source information
- Name: Mangadex
- Extension version: 1.2.103

## Steps to reproduce
1. Update manga
2. Try to download chapters

### Expected behavior
Update and download

### Actual behavior
Don't update some titles and don't download chapters at all with 502 error. 

## Other details
I change image server to Rest of the world, but it don't help

**Comment by conztanz045** [comment] 2021-03-01 07:33
![Screenshot_2021-03-01-15-21-59](https://user-images.githubusercontent.com/79831076/109465586-536c7d00-7a60-11eb-91b5-5db51bab2478.png)

Same error here

**Comment by Akazotik** [comment] 2021-03-01 07:38
Webview works properly

**Comment by OncePunchedMan** [comment] 2021-03-01 09:34
they are being ddos'd

**Comment by scb261** [comment] 2021-03-01 10:29
Duplicate of #6012

**Closed by scb261** 2021-03-01 10:29 UTC
Labels: bug
