### ISSUE TITLE
MangaDex: Filter lists by scanlation group

### ISSUE THREAD

**Issue by muskette** [tachiyomiorg/tachiyomi-extensions#9258] opened 2021-09-27 08:42 UTC
### Describe your suggested feature

It would be nice to have more filter options when viewing chapter lists. 

### Other details

Mangadex supports multiple uploads under the same language.  Their webview handles all the extra entries with some extensive filtering options. Tachiyomi will retrieve them all (filtered by language options in the extension)
It would be nice to be able to filter out duplicates, ideally by the scanlation group so we can read a consistent translation.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jopejoe1** [comment] 2021-09-27 10:56
Duplicate of tachiyomiorg/tachiyomi#969

**Closed** 2021-09-27 13:44 UTC
Labels: Feature request
