### ISSUE TITLE
toonkor has updated url

### ISSUE THREAD

**Issue by kinzuailj** [tachiyomiorg/tachiyomi-extensions#19279] opened 2023-12-11 15:55 UTC
### Source information

Toonkor 1.4.4

### Source language

korean

### Source new URL

https://toonkor315.com/

### Other details

toonkor has new updated website please update

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2023-12-11 15:58
Duplicate of #18744. You can set the baseUrl in the extension settings, see https://github.com/tachiyomiorg/tachiyomi-extensions/issues/18430#issuecomment-1752007136.

**Closed by vetleledaal** 2023-12-11 15:58 UTC
Labels: Bug, Domain changed
