### ISSUE TITLE
Asurascans --- Most Manhwa/Manhua are not found

### ISSUE THREAD

**Issue by Lharci** [tachiyomiorg/tachiyomi-extensions#16295] opened 2023-05-04 00:48 UTC
### Source information

Asura Scans 1.4.45

### Source language

English

### Steps to reproduce

1. Tap on Browser
2. Tap on Asurascans
3. Open any manhwa 
4. Wait till it loads
5. Download or read online

### Expected behavior

This should happen....

After opening any manhwa(whether already added to library or not), it's supposed to to load new chapters after refreshing the page.

### Actual behavior

This happened instead...

I keep getting  HTTP Error 404 whenever I refresh... and when I try viewing said manhwa in browser mode, the page is not found. 
But when I open the Asurascans website, that said manhwa is available

### Tachiyomi version

0.14.6

### Android version

Android 10

### Other details

I think the Asurascans app needs an upgrade,  so please do so... thank you

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2023-05-04 00:58
Duplicate of #16251

**Closed by Seishirou101** 2023-05-04 00:58 UTC
Labels: Bug
