### ISSUE TITLE
MangaFire fetching entries issue

### ISSUE THREAD

**Issue by CasperKristiansson** [tachiyomiorg/tachiyomi-extensions#17893] opened 2023-09-10 21:36 UTC
### Source information

MangaFire 1.4.2

### Source language

English

### Steps to reproduce

Just try to fetch any individual item

### Expected behavior

Fetch data

### Actual behavior

Error when fetching info on items

  Expected start of the object '{', but had 'EOF' instead at path: $
JSON input: .....ets/t2/min/all.js?64fd070064fdb4f9"></script></body> </html>
  # MangaFire (EN)

### Tachiyomi version

App version: 0.14.6 

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2023-09-11 16:58
Duplicate of #17799

**Closed by vetleledaal** 2023-09-11 16:58 UTC
Labels: Bug
