### ISSUE TITLE
Yugen Mangas

### ISSUE THREAD

**Issue by Chellyph14** [tachiyomiorg/tachiyomi-extensions#19163] opened 2023-12-02 15:45 UTC
### Source information

 Yugen mangás 1.4.37

### Source language

Português (Brasil)

### Steps to reproduce

![Screenshot_20231202-113713_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/111191378/273268c2-c878-41c2-8fbd-e6aa54a9b470)

### Expected behavior

The series should be able to be updated without any problem

### Actual behavior

however I receive the message of no results found

### Tachiyomi version

0.14.7

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2023-12-02 15:48
Duplicate of #19030

**Closed by alessandrojean** 2023-12-02 15:48 UTC
Labels: Bug
