### ISSUE TITLE
HTTP error 429

### ISSUE THREAD

**Issue by CampingBoi** [tachiyomiorg/tachiyomi-extensions#12451] opened 2022-07-06 04:53 UTC
### Source information

"Mangabuddy"

### Steps to reproduce

1.add all mangas to one category 
2. try to update that category
3. some of them will fail

### Expected behavior

All 121 mangas should update 

### Actual behavior

18 mangas failed to update

### Tachiyomi version

0.13.4

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by DchanN** [comment] 2022-07-06 05:40
Duplicate of #12397

**Closed** 2022-07-06 05:42 UTC
Labels: Bug
