### ISSUE TITLE
HTTPS ERROR 400

### ISSUE THREAD

**Issue by Quicksilver08** [tachiyomiorg/tachiyomi-extensions#11091] opened 2022-03-12 14:19 UTC
### Source information

Imperfect Comics 1.2.20

### Steps to reproduce

After clicking on imperfect comics extension it shows http error 404

### Expected behavior

After clicking on extension it should have shown list of comics

### Actual behavior

It's showing http error 400

### Tachiyomi version

0.13.1

### Android version

Android 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-03-12 15:01
Duplicate of #11003

**Closed by arkon** 2022-03-12 15:01 UTC
Labels: Bug
