### ISSUE TITLE
MangaSwat: There are no chapters

### ISSUE THREAD

**Issue by yemenihandsome** [tachiyomiorg/tachiyomi-extensions#16742] opened 2023-06-15 06:31 UTC
### Source information

MangaSwat 1.4.33

### Source language

Arabic

### Steps to reproduce

Access to the source
Choose a business
Error does not show chapters

### Expected behavior

Chapters should appear

### Actual behavior

The chapters did not appear and an error appears that there are no chapters

### Tachiyomi version

0.14.6

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by 7allom** [comment] 2023-06-15 10:11
![Screenshot_2023-06-15-13-08-14-032_eu kanade tachiyomi sy](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/97411710/615e05e5-a594-4ae2-9297-4cb67f10c2a0)

**Comment by MoXerous** [comment] 2023-06-15 17:29
السلام عليكم ممكن نسخة التطبيق الي معدلها انت

**Comment by slimessan** [comment] 2023-06-15 18:18
> السلام عليكم ممكن نسخة التطبيق الي معدلها انت

هو مش معدل حاجة البرنامج نفسو فيه نسخ عديدة

**Comment by 7allom** [comment] 2023-06-15 23:38
> السلام عليكم ممكن نسخة التطبيق الي معدلها انت

هذا نسخة Tachiyomi SY

**Comment by arkon** [comment] 2023-06-17 02:22
Duplicate of #16740

**Closed by arkon** 2023-06-17 02:22 UTC
Labels: Bug
