### ISSUE TITLE
Swatmanga chapter not found

### ISSUE THREAD

**Issue by BLACKxSUN** [tachiyomiorg/tachiyomi-extensions#18083] opened 2023-09-21 23:30 UTC
### Source information

Mangaswat 1.4.39 arabic

### Source language

Arabic

### Steps to reproduce

1. Open mangaswat
2. Open webveiw and return
3. Open and manhuw
4. Chapter not found

### Expected behavior

Chapters should be showed

### Actual behavior

![Screenshot_٢٠٢٣٠٩٢٢-٠٢٢٧٣٦_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/93000786/d96cc841-30c4-4af6-a0ad-7056321a5b75)
![Screenshot_٢٠٢٣٠٩٢٢-٠٢٢٧٤٤_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/93000786/63f8923f-5ddc-4cfe-ac08-d0a87af04bdb)

### Tachiyomi version

0.14.6

### Android version

Android 9

### Other details

They changed their domina
I try change it from surorce settinge but it still dont work

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by MikeZeDev** [comment] 2023-09-26 09:20
domain changed to goldragon.me

**Comment by arkon** [comment] 2023-09-27 02:39
Duplicate of #18175

**Closed by arkon** 2023-09-27 02:39 UTC
Labels: Bug
