### ISSUE TITLE
Mangaraw issue and fix

### ISSUE THREAD

**Issue by sohilsayed** [tachiyomiorg/tachiyomi-extensions#18186] opened 2023-09-27 02:33 UTC
### Source information

Mangaraw 1.4.7

### Source language

Japanese 

### Steps to reproduce

Open a chapter

### Expected behavior

The chapter opens

### Actual behavior

The site is accessible but you can not read the chapters 
Which gives unknown error

### Tachiyomi version

Latest

### Android version

Android 8.1

### Other details

The problem is that the chapter image servers is blocked in alot of countries but it works with a japanese and Korean vpn as i tried but when using vpn the webview version is working but the error inside the app doesn't change

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-09-27 02:38
Duplicate of #17682

**Closed by arkon** 2023-09-27 02:38 UTC
Labels: Bug
