### ISSUE TITLE
Mango: Mismatching chapter number before chapter name

### ISSUE THREAD

**Issue by wisewtf** [tachiyomiorg/tachiyomi-extensions#7980] opened 2021-07-05 09:59 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android 11

### Source information

Mango 1.2.4

### Steps to reproduce

1. Install Mango on your system
2. Fill it with manga chapters (Ex: Manga 32 as the first chapter)
3. Install Mango Extension on Tachiyomi
4. Browse for the added manga
5. Chapter name is going to be "1 - Manga 32"

### Expected behavior

I read chapter 32, because my file's name is called "Manga 32", and Anilist gets updated as me having read Chapter 32.

### Actual behavior

Since the extension has added 1 - before my file name of "Manga 32", Tachiyomi will instruct Anilist to track me having read Chapter 1 instead.

### Other details

Either this should be removed 

https://github.com/tachiyomiorg/tachiyomi-extensions/blob/778ed078f09a0eac4a9dd3e4ad6e37a47ab13b9b/src/all/mango/src/eu/kanade/tachiyomi/extension/all/mango/Mango.kt#L147

or it should be fixed in a way that the added chapter number before the actual chapter file name is the same as the actual chapter's number in the file's name.

To simplify: If the chapter file name is Manga 32, then 1 - should NOT be added to the name in Tachiyomi when the first file isn't 1. This happens because the extension will just add 1 starting from the first file, regardless of what it actually is.

This causes tracking on Anilist (and others) to break as the first parsed number is the one before the name itself, meaning that if I read Chapter 32, but 1 - is before the file name, Tachiyomi's tracker will update Anilist with having read chapter 1 instead of 32.

**Comment by henry726** [comment] 2021-07-06 00:17
If I'm not mistaken, mango itself does not give chapter numbers and instead, the chapter number is determined by alphabetical order. Sadly, I don't think there would be any way to fix this unless there was a specific file naming scheme for all chapters (which there isn't). If you were to add all the chapters before "Manga 32" (Manga 1, Manga 2, etc.) Manga 32 would appear as chapter 32. Other than this, it might be best to just turn off the tracker and input your manga updates automatically.

**Comment by wisewtf** [comment] 2021-07-06 03:26
> If I'm not mistaken, mango itself does not give chapter numbers and instead, the chapter number is determined by alphabetical order. Sadly, I don't think there would be any way to fix this unless there was a specific file naming scheme for all chapters (which there isn't). If you were to add all the chapters before "Manga 32" (Manga 1, Manga 2, etc.) Manga 32 would appear as chapter 32. Other than this, it might be best to just turn off the tracker and input your manga updates automatically.

Would it not be more sane to just remove this part entirely and just let Tachiyomi order chapters by filename and not with the number you add?

No other extension does this and I don't want think it's needed, plus turning off tracking kinda defeats the purpose of using Tachiyomi, wouldn't it?

As for adding other chapters, sure... But in many cases it's either not possible or not sane. For example, some books might start with VOLUMES and then move on to CHAPTERS, becoming V1, V2 and then going to CH35. Sometimes the source material isn't there. 

I could add dummy chapters but then it would make my Mango interface ugly, even tho that would work.

Please consider this change, or explain to me why this is required in your opinion because I honestly don't think it's a good thing to have.

**Comment by henry726** [comment] 2021-07-06 04:08
To be clear, chapters are not automatically sorted alphabetically. Without chapter numbers, chapters are sorted randomly (by time added, which for mango is often random). That's why the chapter numbers needed to be added to the metadata so that they would at least be sorted in alphabetical order. Adding the chapter number to the title was separate from adding the chapter number to the metadata and wasn't completely necessary. I just felt that it was nice to know what Tachiyomi viewed as the chapter number internally. This is also basically the same way chapter names and numbers are handled in the Komga extension (another self manga hoster)

**Comment by wisewtf** [comment] 2021-07-06 04:12
In that regard, since the numbers don't start with 0 but with 1... etc, Tachiyomi still orders everything out of place once it gets to 10, that said I'd much rather sort manually in Tachiyomi which seems to be working more than fine even for the Mango extension than do everything else manually. 

Thank you for your cooperation though!

**Comment by henry726** [comment] 2021-07-06 04:16
What do you mean that it's out of order after 10?

**Comment by henry726** [comment] 2021-07-06 04:22
Naming your chapters in the format "Volume X Chapter X" or just "Volume X"  I believe should fix any misordering problems caused by chapters being out of alphabetical order.

**Comment by wisewtf** [comment] 2021-07-06 06:21
This is what I get as soon as I open the series on Tachiyomi:

![out-of-order](https://user-images.githubusercontent.com/33370380/124551061-e6b02780-de31-11eb-9623-1cd7951747ac.jpg)

This is what I get after I sort by chapter number from Tachiyomi itself:

![ordered](https://user-images.githubusercontent.com/33370380/124551036-df891980-de31-11eb-9dde-097b88e40732.jpg)

Now, I don't know if it's because of my naming scheme ("Series Name #Chapter Number"), or because the chapter names start with a 1 and not a 01, meaning that it would get confused between 1 and 10 and 2 and 20 and so on so forth.

Unfortunately I don't have experience with Kotlin or Android development at all, otherwise I would've compiled my own version without what I think is the string of code that adds the number before the chapter number and see for myself.

Doesn't Tachiyomi sort the chapters from parsing the filenames? I was told it also parses the file name when syncing to Anilist. If that were the case there shouldn't be a need for Mango do add chapter numbers like you said.

If there's really no way to fix this I must make sure every time to put in ALL the chapters and/or create dummy chapters for situations when I cannot have all of the files. (Like I said in the case that my series starts with volumes and ends with chapters, tracking would be impossible for that as it would jump from 1 to 2 to 3 and switch to 50 when the volumes end)

(Or move back to Komga)

**Comment by henry726** [comment] 2021-07-06 06:53
I'm sorry that I haven't really been able to provide a solution to your problem. The second screenshot does look like it's working as intended. The reason why most other extensions work alot better with tachiyomis tracking is because the apis for such websites give alot more information for their manga, such as chapter and volume number. Mango on the other hand only provides the title and date added for each chapter. And again sadly, because there is not standard for chapter and volume naming in mango, I don't believe it's possible to be able to parse titles for chapter and volume numbers. If you want, I can compile a version of the extension for you that removes the number from the title, but keep in mind, it will not fix the tracking issues.

The only way I see you could fix the tracking would be to edit the app to parse your own custom naming scheme such as "Volume X Chapter X". I would be willing to try and do this for you. My kotlin knowledge is also very limited but I'd be willing to try.

**Comment by curche** [comment] 2021-07-06 07:31
Hi, I sent them here from #support in Discord server

Had to recheck this since my initial assumption was wrong, the way tracking works is by using the `chapter_number`
https://github.com/tachiyomiorg/tachiyomi/blob/040bac3da2a215802ebad02f8e6a418bb200cb9c/app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderPresenter.kt#L701

the same `chapter_number` that Mango ext sets should have worked 
https://github.com/tachiyomiorg/tachiyomi-extensions/blob/778ed078f09a0eac4a9dd3e4ad6e37a47ab13b9b/src/all/mango/src/eu/kanade/tachiyomi/extension/all/mango/Mango.kt#L146

As far as I understand, the tracking problem (where Anilist tracks it as 1 when it is to be 35) comes up since the `chapter_number` is `1` for the Chapter titled by Tachi from Mango as `"#1 - Chapter #35"` ("$chapter_number - $display_name")

As for solutions, not really a dev but some ideas would be:
- you could have `chapter_number` made from parsing the `display_name` and hope it works fine. 
- perhaps this might not be the right direction, but you can also have a look at how [Local Source](https://tachiyomi.org/help/guides/reading-local-manga/#folder-structure) works 
https://github.com/tachiyomiorg/tachiyomi/blob/040bac3da2a215802ebad02f8e6a418bb200cb9c/app/src/main/java/eu/kanade/tachiyomi/source/LocalSource.kt#L165

sorting could just be left to the App which already provides Sort options in chapter list

**Comment by Soitora** [comment] 2021-07-18 11:47
/edit-title "Mango: Mismatching chapter number before chapter name"

**Comment by henry726** [comment] 2021-07-18 19:16
Source Code: [https://pastebin.com/raw/pi6wQJ9R](https://pastebin.com/raw/pi6wQJ9R)
APK: [https://drive.google.com/file/d/1Lkh-aQR_E2MLNxgHLt5xdNbeKwqF1f7J/view?usp=sharing](https://drive.google.com/file/d/1Lkh-aQR_E2MLNxgHLt5xdNbeKwqF1f7J/view?usp=sharing)

I've made a version here that should solve your problems, but I'm hesitant to create a pull request as I'm unsure that this solution will work for everyone as different people may name their chapters differently.

**Comment by curche** [comment] 2021-08-17 13:49
I think you can open a PR. Once you PR, reviewers will take a look at it and then it can be merged or closed.

**Closed** 2021-09-26 12:22 UTC
Labels: Bug
