### ISSUE TITLE
Problema 404

### ISSUE THREAD

**Issue by simonflo-afk** [tachiyomiorg/tachiyomi-extensions#9970] opened 2021-12-01 22:40 UTC
### Source information

Phoenix fansub

### Steps to reproduce

No salen los capítulos y aparece error 404

### Expected behavior

Verse los capítulos

### Actual behavior

No hay capítulos

### Tachiyomi version

0.12.3

### Android version

11

### Other details

Error 404 pero si aparece las portadas 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2021-12-01 22:45
Duplicate of #9888

**Closed by arkon** 2021-12-01 22:45 UTC
Labels: Bug
