### ISSUE TITLE
Mangaswat image couldn't be loaded 

### ISSUE THREAD

**Issue by 7allom** [tachiyomiorg/tachiyomi-extensions#14938] opened 2023-01-14 07:31 UTC
### Source information and language

Mangaswat 1.3.28 arabic

### Steps to reproduce

https://user-images.githubusercontent.com/97411710/212461375-2d9087d5-1720-4594-a72c-845ed045bcaf.mp4

### Expected behavior

.

### Actual behavior

.

### Tachiyomi version

1.8.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Sultanabdo1** [comment] 2023-01-14 08:23
They changed the domain from .me to .net

**Comment by alessandrojean** [comment] 2023-01-14 13:21
Duplicate of #14926

**Closed by alessandrojean** 2023-01-14 13:21 UTC
Labels: Bug

**Comment by 7allom** [comment] 2023-01-14 13:59
> Duplicate of #14926

Bro i know u updated the domain but this issue is new

**Comment by alessandrojean** [comment] 2023-01-14 14:02
Issues related to this source won't be fixed as the source is going to be removed. It was added back as a mistake.

**Comment by 7allom** [comment] 2023-01-14 14:09
Ok 👍
