### ISSUE TITLE
[Source Request]<mangallama>

### ISSUE THREAD

**Issue by abdallahbassim** [tachiyomiorg/tachiyomi-extensions#6599] opened 2021-04-18 00:15 UTC
## Source website
- Name: mangallama
- Link: https://mangallama.com
- Language(s): EN

**Comment by keinezeit8** [comment] 2021-04-18 18:25
Duplicate of #3572

Maybe that also should be closed, because back then someone asked it not to be implemented.
But I don't know if they ever followed through

**Closed** 2021-04-18 18:26 UTC
Labels: Source Request

**Comment by abdallahbassim** [comment] 2021-04-18 19:49
Did he follow through is he the owner of the site if he didn't can you open it

**Comment by keinezeit8** [comment] 2021-04-18 19:51
the original is still open
but this is a duplicate, that's why its closed

**Comment by abdallahbassim** [comment] 2021-04-19 03:06
Ok thank u
