### ISSUE TITLE
[Bug] Mangadex: mangadex doesn't show updated chapters even after refreshing 

### ISSUE THREAD

**Issue by Samk19** [tachiyomiorg/tachiyomi-extensions#6028] opened 2021-03-01 22:57 UTC
## Device information
- Tachiyomi version: 0.10.9
- Android version: 11

## Source information
- Name: mangadex
- Extension version: 1.2.103

## Steps to reproduce
1. Search god slayer manga
2. Mark as favorite 
3. now compare chapters in app and using web mode latest chapters not shown

## Expected behavior
Should show latest chapters as shown using webview

### Actual behavior
Doesn't show latest chapters even after refreshing a couple of times.

## Other details
Also downloading of chapters of any titles from mangadex are not working

Screenshots for reference 
Inapp 
![Screenshot_20210302-041629_Tachiyomi.jpg](https://user-images.githubusercontent.com/36104528/109569982-52deef80-7b0f-11eb-88c3-2a24e883fc04.jpg)

Webview
![Screenshot_20210302-041644_Tachiyomi.jpg](https://user-images.githubusercontent.com/36104528/109569996-596d6700-7b0f-11eb-84fe-dcbccdd9e25c.jpg)

**Comment by CrepeTF** [comment] 2021-03-01 22:57
> MangaDex's site is being attacked with a DDoS attack, expect their site and API to be inaccessible during this time.

**Comment by LoLyeah** [comment] 2021-03-03 23:43
Yeah, this happened to me too. Just to add that it's still happens today.

![Screenshot_2021-03-04-06-39-05-391_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/11774211/109887736-dab22e80-7cb4-11eb-8099-a3cc38acb41f.jpg)
![Screenshot_2021-03-04-06-39-20-778_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/11774211/109887744-de45b580-7cb4-11eb-8899-f7863fd93a55.jpg)

**Comment by scb261** [comment] 2021-03-04 10:11
Duplicate of #5780

**Closed by scb261** 2021-03-04 10:11 UTC
Labels: bug
