### ISSUE TITLE
Por favor cambiar el url de olympuscalation

### ISSUE THREAD

**Issue by Lightdennn** [tachiyomiorg/tachiyomi-extensions#15480] opened 2023-02-26 02:29 UTC
### Source information and language

Olympusscalation.com

### Source new URL

https://olympusscans.com/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2023-02-26 02:31
Duplicate of #15330

**Closed by Seishirou101** 2023-02-26 02:31 UTC
Labels: Bug, Domain changed
