### ISSUE TITLE
[Source Request] Comick.fun

### ISSUE THREAD

**Issue by meotimdihia** [tachiyomiorg/tachiyomi-extensions#6262] opened 2021-03-24 00:40 UTC
## Source website
- Name: comick
- Link: https://comick.fun
- Language(s): multi-languages

## Other details
https://comick.fun is the Mangadex mirror. It has whole Mangadex comics.
And while Mangadex is down. Comick is still alive, update comics.
In the future, it could have diverse other sources

Comick.fun has integrated with Graphql API . It is very easy to intergrate, I think.

**Comment by scb261** [comment] 2021-03-24 02:32
Duplicate of #5680

**Closed by scb261** 2021-03-24 02:32 UTC
Labels: Source Request

**Comment by meotimdihia** [comment] 2021-03-24 02:36
Sorry, I don't think someone created it here when Comickis is new O_O.
