### ISSUE TITLE
[Bug] <Sleeping Knight Scans>: <Error 404>

### ISSUE THREAD

**Issue by hjdrm** [tachiyomiorg/tachiyomi-extensions#6190] opened 2021-03-16 16:57 UTC
---

## Device information
- Tachiyomi version: J2K 1.0.10
- Android version: 10

## Source information
- Name: Sleeping Knight Scans
- Extension version: 1.2.1

## Steps to reproduce
1. Open Sleeping Knight Scans source
2. 

### Expected behavior
After clicking the source, it should show the manhwa/manga done by the group

### Actual behavior
After clicking the source it just shows Error:404

## Other details
Opening the source's webview mode doesn't give Error:404. I read on Sleeping Knight scans discord that they changed something on their website

**Comment by curche** [comment] 2021-03-16 16:58
duplicate of #6178

**Closed** 2021-03-16 17:02 UTC
Labels: bug
