### ISSUE TITLE
Kemeno Updates Failed

### ISSUE THREAD

**Issue by duck781** [tachiyomiorg/tachiyomi-extensions#18623] opened 2023-10-19 23:07 UTC
### Source information

Kemeno 1.4.7 Version

### Source language

English

### Steps to reproduce

1. Referesh via global update of a category
2. New update(s) failed shows

### Expected behavior

1. Referesh via global update of a category
2. Updates pushed without an error notification.

### Actual behavior

"! Expected start of the array 'T, but had 'EOF'
instead at path: $
JSON input: ... URL manually please check
your spelling and try again.</p>
# Kemono (ALL)"

Source update error 6x notification

### Tachiyomi version

App version: 0.14.6 (standard, c615f4d, 101, 2023-04-16T15:14Z)

### Android version

Android version: 13 (SDK 33)

### Other details

![Screenshot_20231019_180627_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/148504200/005e894b-b3f7-4132-b82b-57b47b4fd5f5)
![Screenshot_20231019_180645_FX](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/148504200/ad141d99-f492-4e6c-879c-a87d7273c164)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2023-10-19 23:18
Duplicate of #18617

**Closed by Seishirou101** 2023-10-19 23:18 UTC
Labels: Bug
