### ISSUE TITLE
Mintmanga source is changed

### ISSUE THREAD

**Issue by helltraitor** [tachiyomiorg/tachiyomi-extensions#18072] opened 2023-09-20 23:16 UTC
### Source information

Mintmanga 1.4.66

### Source language

Russian

### Source new URL

https://mintmanga.live

### Other details

For now can be fixed via settings, but it seems like previous one will never be valid manga source

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-09-27 02:41
Duplicate of #18134

**Closed by arkon** 2023-09-27 02:41 UTC
Labels: Bug, Domain changed
