### ISSUE TITLE
Neox Scan "too many follow up requests: 21" error

### ISSUE THREAD

**Issue by Tsurip** [tachiyomiorg/tachiyomi-extensions#11990] opened 2022-05-26 23:09 UTC
### Source information

Neox Scanlator 1.2.33

### Steps to reproduce

1. Open extension from neox
2. Get the error

### Expected behavior

Should open the extension view with the mangas

### Actual behavior

Showing the "too many follow-up requests: 21" error

### Tachiyomi version

App version: 0.13.4

### Android version

Android 10.0

### Other details

The web view open normally.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-05-26 23:14
Duplicate of #11953

>  I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open issue.

**Closed by alessandrojean** 2022-05-26 23:14 UTC
Labels: Bug
