### ISSUE TITLE
MangaKatana - Image array not found

### ISSUE THREAD

**Issue by raphael-s-souza** [tachiyomiorg/tachiyomi-extensions#13193] opened 2022-08-25 20:53 UTC
### Source information and language

MangaKatana 1.3.7

### Steps to reproduce

Try to open/download and Tachiyomi throws the image array not found error.

### Expected behavior

Open/download charpters.

### Actual behavior

Error while trying to open/download charpters.

### Tachiyomi version

Stable 0.13.6

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by happywillow0** [comment] 2022-08-26 02:01
Duplicate of #13193. (PR #13194)

**Comment by Kuroyuusha** [comment] 2022-08-26 02:21
I am also facing the same issue in mangakatana. Such as, image array not found.

**Comment by MikeZeDev** [comment] 2022-08-26 18:13
Only having this issue on Black Clover chapter 335. Not sure if info is useful.

**Comment by happywillow0** [comment] 2022-08-26 18:18
@MikeZeDev Have you tried to clear the chapter cache within the settings?

**Comment by raphael-s-souza** [comment] 2022-08-26 18:18
> Only having this issue on Black Clover chapter 335. Not sure if info is useful.

They already updated and is working on mine. Update the extension, empty the download queue and try downloading again.

**Closed** 2022-08-26 18:19 UTC
Labels: Bug

**Comment by MikeZeDev** [comment] 2022-08-26 18:25
Its fixed, thanks !
