### ISSUE TITLE
Mangahub   http error 403

### ISSUE THREAD

**Issue by MLGrugu** [tachiyomiorg/tachiyomi-extensions#12817] opened 2022-07-31 06:16 UTC
### Source information and language

Mangahub 1.3.18

### Steps to reproduce

1.opening Mangahub
2.opening a manga
3.opening a chapter
4.goes back to chapter list and shows http error 400

### Expected behavior

After opening the manga and clicking on chapter it should show open up like regular  so we can read the chapter

### Actual behavior

1.opening Mangahub
2.opening a manga
3.opening a chapter
4.goes back to chapter list and shows http error 400

### Tachiyomi version

0.13.5

### Android version

Android 11.

### Other details

Nothing

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2022-07-31 06:42
Please provide an example manga and chapter.

Mangahub 1.3.18 doesn't exist (yet), did you mean MangaHub (EN) 1.3.14 or Mangahub (RU) 1.3.15?

If this is MangaHub (EN), some chapters now require that you log in. You can check the WebView for this.

**Comment by Lucifer20008** [comment] 2022-07-31 08:08
None of manga  is opening that came for mangahub
If we click on the chapter it loading and goes back to chapter list

**Comment by kazrnum** [comment] 2022-07-31 12:37
> Please provide an example manga and chapter.
> 
> Mangahub 1.3.18 doesn't exist (yet), did you mean MangaHub (EN) 1.3.14 or Mangahub (RU) 1.3.15?
> 
> If this is MangaHub (EN), some manga now require that you log in. You can check the WebView for this.

If you open the webview it goes to an another site

**Comment by Lucifer20008** [comment] 2022-07-31 12:46
All rounder chapter 48
Solo leveling full chapters

**Comment by samlux04** [comment] 2022-07-31 17:28
Confirmed the update working fine now. Close this

**Comment by Tommyvercityy** [comment] 2022-07-31 18:40
It says manga hub is obsolete here and not working

**Comment by loocool2** [comment] 2022-07-31 19:53
Duplicate of #12773 
Update your Tachiyomi Extension. If your "Mangahub" extension is on v1.2.10 and is marked OBSOLETE, uninstall it and install the "MangaHub" extension v1.3.14. You will not lose any manga in your library.
If you have any downloads make sure to rename the source download folder from "Mangahub" -> "somethingelse" -> "MangaHub" to retain any downloads.

**Closed by loocool2** 2022-07-31 19:53 UTC
Labels: Bug

**Comment by kazrnum** [comment] 2022-08-02 06:45
> 

Tnx brother it worked
