### ISSUE TITLE
Xoxocomics.net has changed to xoxocomics.net

### ISSUE THREAD

**Issue by joshua-cotugno** [tachiyomiorg/tachiyomi-extensions#19437] opened 2023-12-26 20:15 UTC
### Source information

Xoxocomics.net

### Source language

England

### Steps to reproduce

1. Add the Xoxocomics extension
2. search for anything

### Expected behavior

Comics should appear and be able to view

### Actual behavior

Nothing is shown. I looked at the code for it, and saw it uses the old Xoxocomics link, and after looking in the dev settings on chrome, the page structure is different 

### Tachiyomi version

App version: 0.14.7 (standard, c8d6859, 102, 2023-10-25T16:11Z) Android version: 14 (SDK 34) Android build ID: UP1A.231005.007.A336BXXU7DWK6 Device brand: samsung Device manufacturer: samsung Device name: a33x Device model: SM-A336B Device product name: a33xnseea

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2023-12-26 20:39
Duplicate of #19388

**Closed by vetleledaal** 2023-12-26 20:39 UTC
Labels: Bug
