### ISSUE TITLE
Doujindesu

### ISSUE THREAD

**Issue by BANANA25323** [tachiyomiorg/tachiyomi-extensions#12572] opened 2022-07-13 07:21 UTC
### Source information

Doujindesu 1.3.2

### Steps to reproduce

1.open tachiyomi apps
2.move to browse menu
3.select doujindesu source
4.its showing page with many comics without cover pict

### Expected behavior

Showing page with many comics with cover pict

### Actual behavior

It showing page without cover pict.

### Tachiyomi version

0.13.5

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2022-07-13 09:40
Duplicate of #11662

**Closed by vetleledaal** 2022-07-13 09:40 UTC
Labels: Bug
