### ISSUE TITLE
Backup to drive

### ISSUE THREAD

**Issue by AbdallahAhmedHamda** [tachiyomiorg/tachiyomi-extensions#19426] opened 2023-12-25 15:48 UTC
### Describe why this should be added

Okay so i hope there is a way for the app to backup into drive or into online storage for example because if for some reason something happens to my phone and i cant open it sadly there are no accounts so my data is not saved so the only way i can retrieve it is using backups and i wont be able to access the backup if i cant open the phone of course all of this is in case the person doesnt use tracking and that he only use tachiyomi for manga saving

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment] 2023-12-25 15:53
> - [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).

Isn't this a feature that can only be added to the app, and not to the extension?
If that's true, then you have the wrong Repo

**Comment by arkon** [comment] 2023-12-25 15:53
> If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).

Duplicate of https://github.com/tachiyomiorg/tachiyomi/issues/912

**Closed** 2023-12-25 15:53 UTC
Labels: Meta request
