### ISSUE TITLE
[Bug] Mangalib.me Error 403

### ISSUE THREAD

**Issue by MM001-r** [tachiyomiorg/tachiyomi-extensions#6428] opened 2021-04-05 06:56 UTC
Mangalib hasn't been working for more than 6 days! Are you going to decide?
Device information
Tachiyomi version: 0.10.9
Android version: 9
Device: honor 9 lite
Steps to reproduce
Just update the manga list
Expected behavior
Long-awaited manga update

Actual behavior
No update and IS REPORTED 403

Other details

**Comment by Seishirou101** [comment] 2021-04-05 08:11
duplicate of #6376

**Closed** 2021-04-05 12:24 UTC
Labels: bug
