### ISSUE TITLE
Change URL

### ISSUE THREAD

**Issue by HT-05** [tachiyomiorg/tachiyomi-extensions#18288] opened 2023-10-01 11:34 UTC
### Source information

Mangalek

### Source language

Arabic

### Source new URL

https://manga-lek.net

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by 7allom** [comment] 2023-10-01 12:54
Changed to 
https://manga-like.net

**Comment by arkon** [comment] 2023-10-01 14:02
Duplicate of #18124

**Closed by arkon** 2023-10-01 14:02 UTC
Labels: Bug, Domain changed
