### ISSUE TITLE
Kumanga: JSON parsing fail

### ISSUE THREAD

**Issue by edmxn** [tachiyomiorg/tachiyomi-extensions#11894] opened 2022-05-17 02:23 UTC
### Source information

Kumanga 1.2.7

### Steps to reproduce

1. I open tachiyomi
2. I look for the source and open it
3. A message appears that does not allow me to have any action within the souce

### Expected behavior

The font should work like any other

### Actual behavior

An unknown message appears, and when trying to see the WebView, another one appears that does not allow me to interact with the web

![Screenshot_20220516-201930_Tachiyomi](https://user-images.githubusercontent.com/101371218/168715450-238197ff-966f-4f04-a20c-efaee40c51ac.jpg)
![Screenshot_20220516-202002_Tachiyomi](https://user-images.githubusercontent.com/101371218/168715459-d0261764-3f2e-4988-babe-67eb03d14dec.jpg)

### Tachiyomi version

0.13.4

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Lenoyr** [comment] 2022-07-15 06:21
Please fix this
The hope is the last thing you lose

**Comment by alessandrojean** [comment] 2022-08-09 19:39
Duplicate of #10414

**Closed by alessandrojean** 2022-08-09 19:39 UTC
Labels: Bug
