### ISSUE TITLE
[Feature Request] Komga: mark issues as read in Komga when read in Tachiyomi

### ISSUE THREAD

**Issue by amatriain** [tachiyomiorg/tachiyomi-extensions#5886] opened 2021-02-16 19:34 UTC
When an issue is read in Komga, Tachiyomi knows it's been read, which can be used for filtering.

However issues marked as read in Tachiyomi are not automatically marked as read in Komga, which forces the user to go to the native Komga interface and mark them as read.

It would be nice if marking issues as read in Tachiyome also marked them as read in Komga when the library is synced.

**Comment by arkon** [comment] 2021-02-16 19:39
Duplicate of https://github.com/tachiyomiorg/tachiyomi/issues/4282

**Closed by arkon** 2021-02-16 19:39 UTC
Labels: enhancement
