### ISSUE TITLE
Tohomh123 : No Result Found

### ISSUE THREAD

**Issue by Bishopop6** [tachiyomiorg/tachiyomi-extensions#11452] opened 2022-04-13 02:42 UTC
### Source information

Tohomh123 1.2.3

### Steps to reproduce

1. Download extension
2. Went into extension
3. No result found
4. Went into website url
5. No result found

### Expected behavior

Able to access website manhua.

### Actual behavior

No result found

### Tachiyomi version

0.13.2

### Android version

Android 11

### Other details

Change website url.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by anenasa** [comment] 2022-04-15 06:48
Duplicate of https://github.com/tachiyomiorg/tachiyomi-extensions/issues/7600

**Closed** 2022-04-15 14:13 UTC
Labels: Bug, Source is down
