### ISSUE TITLE
Cant seem to pass cloudflare

### ISSUE THREAD

**Issue by thelastman112** [tachiyomiorg/tachiyomi-extensions#12655] opened 2022-07-21 01:14 UTC
### Source information

Allporncomic

### Steps to reproduce

1. Open the source in browse
2. "Cant bypass cloudflare" And open webview
3. Shown checking browser and give Hcaptcha
4. Solve Hcaptcha and checking browser 

### Expected behavior

It should pass the captcha and redirect to the site

### Actual behavior

Looping checking browser and solving captcha forever

### Tachiyomi version

0.13.5

### Android version

Android 11

### Other details

Its using supervpn region japan and Singapore, wifi and not wifi 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2022-07-21 01:21
Duplicate of #9318

**Closed by Seishirou101** 2022-07-21 01:21 UTC
Labels: Bug
