### ISSUE TITLE
VyvyManga: Covers not loading and Opening via Webview redirects to Google

### ISSUE THREAD

**Issue by jeronelailo** [tachiyomiorg/tachiyomi-extensions#15488] opened 2023-02-26 13:22 UTC
### Source information and language

VyvyManga 1.4.4 (English)

### Steps to reproduce

1. Open VyvyManga source and save a manga to your library.
2. Once saved, exit and reopen app, and open the saved manga from VyvyManga. At this point the cover image will not load.
4. Click the "Open in Webview" button. This will load the manga page first, then it will redirect to Google.

### Expected behavior

Cover image should load and when the manga is opened in Webview, it should stay on the page and not redirect to Google.

### Actual behavior

Cover images are not loading
Opening the manga through webview redirects to google

### Tachiyomi version

0.14.5

### Android version

Android 13

### Other details

https://user-images.githubusercontent.com/31534891/221412833-f028046d-c8fe-49d9-aa1d-5bc23e46b419.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by jeronelailo** [comment] 2023-02-26 13:25
https://user-images.githubusercontent.com/31534891/221413090-e450f89b-68ac-4bd9-9a21-02a5b18c4092.mp4

**Comment by DchanN** [comment] 2023-03-07 14:07
maybe duplicate of #15035

**Closed** 2023-03-07 14:10 UTC
Labels: Bug
