### ISSUE TITLE
Error 429

### ISSUE THREAD

**Issue by biliarsilby** [tachiyomiorg/tachiyomi-extensions#11317] opened 2022-04-03 12:52 UTC
### Source information

1st kiss 

### Steps to reproduce

1. tried updating my list
2. Met with error 429

### Expected behavior

Be able to update and read manhwa

### Actual behavior

Blocked from updating since ive been readinh too fast

### Tachiyomi version

0.13.1

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment] 2022-04-03 12:55
>  I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open issue.

Duplicate of #11280

**Closed by curche** 2022-04-03 12:55 UTC
Labels: Bug
