### ISSUE TITLE
Doujindesu: Changed their domain

### ISSUE THREAD

**Issue by Matmatew** [tachiyomiorg/tachiyomi-extensions#11439] opened 2022-04-12 08:57 UTC
### Source information

Doujindesu 1.2.2

### Steps to reproduce

1. The domain changed
2. I open 212.32.226.234: NXDOMAIN
3. I open it through the browser doujindesu.xxx the domain becomes 212.32.226.234

### Expected behavior

N/A

### Actual behavior

N/A

### Tachiyomi version

0.13.2

### Android version

Android 6.0

### Other details

please fix the incomplete genre filter

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Cadangan19** [comment] 2022-04-12 17:40
👆👆👆

**Comment by TheKingTermux** [comment] 2022-04-13 02:21
Duplikasi dari #11401 dan #11411 / Duplicate of #11401 dan #11411 
Alasan / Reason
Ganti domain / They change the domain

**Comment by Doujinlovers334** [comment] 2022-04-18 16:04
so what's the solution? doujindesu can't be opened

**Comment by TheKingTermux** [comment] 2022-04-19 02:49
> so what's the solution? doujindesu can't be opened

Just waiting team for repair the extension

**Comment by Icefire113** [comment] 2022-04-22 19:47
Changing the base url from doujindesu.xxx to 212.32.226.234 _should_ fjx this

**Comment by alessandrojean** [comment] 2022-04-22 20:03
Using naked IPs are a non secure measure. Indonesian ISPs are blocking some domains, you should try this instead:

![image](https://user-images.githubusercontent.com/14254807/164786035-765428c5-189b-4328-a18e-409ca4315051.png)

**Comment by TheKingTermux** [comment] 2022-04-22 23:36
> Using naked IPs are a non secure measure. Indonesian ISPs are blocking some domains, you should try this instead:
> 
> ![image](https://user-images.githubusercontent.com/14254807/164786035-765428c5-189b-4328-a18e-409ca4315051.png)
> 
> There's nothing wrong in the extension as it's working in other countries.

Telah diperiksa.
Dan itu bekerja dengan menggunakan VPN (Saya menggunakan psiphon) dengan tidak menggunakan DoH, dan ekstensi bekerja dengan normal.

Has been checked.
And it works by using a VPN (I use psiphon) by not using DoH, and the extension works normally.

**Closed** 2022-04-22 23:47 UTC
Labels: Bug
