### ISSUE TITLE
Yaoimangaonline: missing chapters

### ISSUE THREAD

**Issue by saturnedlexx** [tachiyomiorg/tachiyomi-extensions#12454] opened 2022-07-06 08:24 UTC
### Source information

Yaoimangaonline 1.2.2

### Steps to reproduce

The chapter lists of every manga is unavailable. Although it show's 1 chapter but when you open it, it say's that there are no pages.![Screenshot_20220706-160059_TachiyomiSY](https://user-images.githubusercontent.com/66194787/177503617-bb1cc62f-a06c-4c59-987c-617e5d377ac4.jpg)

### Expected behavior

It should view chapter list since in webview, the source is up.

### Actual behavior

I tried to open the extension in webview and there are available chapters there but in tachiyomi itself, there are no available chapters
![Uploading Screenshot_20220706-162019_TachiyomiJ2K.jpg…]()

### Tachiyomi version

Tachiyomi SY 1.8.3 , TachiJ2K 1.5.4 , Tachiyomi 0.13.4

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2022-11-29 11:42
Duplicate of #11175

**Closed by vetleledaal** 2022-11-29 11:42 UTC
Labels: Bug
