### ISSUE TITLE
[Bug] MyReadingManga (EN) : Some covers do not load/appear in Library and Source

### ISSUE THREAD

**Issue by ad-co1997** [tachiyomiorg/tachiyomi-extensions#18907] opened 2023-11-10 02:24 UTC
### Source information

Name: MyReadingManga     Extension version: 1.4.47

### Source language

ALL

### Steps to reproduce

1. First Step: Open library or extension, no covers appear on titles present
2. Second Step: Go to info of a manga entry, open webview, manga no shows cover

### Expected behavior

This should have happened: Covers should appear in library and source

### Actual behavior

This happens instead: Some covers do not appear

### Tachiyomi version

Tachiyomi version: 0.14.7  

### Android version

Android version: 12

### Other details

examples (censored):

![Imagen de WhatsApp 2023-11-09 a las 20 16 45_9ade42a0](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/150403915/2e1d62f1-a368-462d-b77b-f758c3ca32e9)
![Imagen de WhatsApp 2023-11-09 a las 20 16 48_6e1e1622](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/150403915/85382350-5b7e-4c1e-8852-bed99d0a4ec3)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2023-11-11 10:17
Duplicate of #15367

**Closed by vetleledaal** 2023-11-11 10:17 UTC
Labels: Bug
