### ISSUE TITLE
Magus Manga: No results found

### ISSUE THREAD

**Issue by ibrahem51** [tachiyomiorg/tachiyomi-extensions#12442] opened 2022-07-05 06:28 UTC
### Source information

Magus Manga 1.3.14

### Steps to reproduce

1: open Magus manga
2: No results found 

### Expected behavior

View manga list

### Actual behavior

No results found 

### Tachiyomi version

0.13.4

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-08-19 23:49
Duplicate of #11081

**Closed by alessandrojean** 2022-08-19 23:49 UTC
Labels: Bug
