### ISSUE TITLE
Http 429 Too many requests

### ISSUE THREAD

**Issue by Yuri4evr** [tachiyomiorg/tachiyomi-extensions#12406] opened 2022-07-02 06:39 UTC
### Source information

Mangabuddy

### Steps to reproduce

Trying to update my libary 
When trying to refresh on updates it says it failed

### Expected behavior

Tried waiting it out for a day but not sure how long it is, I expected a warning or a pop up if it ever happened

### Actual behavior

Just said it failed 

### Tachiyomi version

0. 13. 4

### Android version

Android 2017

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment] 2022-07-02 06:57
Duplicate of #12397

**Closed by curche** 2022-07-02 06:57 UTC
Labels: Bug
