### ISSUE TITLE
Error 400 

### ISSUE THREAD

**Issue by akshar2324** [tachiyomiorg/tachiyomi-extensions#15307] opened 2023-02-11 07:27 UTC
### Source information and language

1st Kiss  1.3.36

### Steps to reproduce

1.open extension
2. It showing error 400
3. Web view is fine
4. But i am getting updates and new chapter 

### Expected behavior

It should show list of manga

### Actual behavior

![Screenshot_20230211_125209](https://user-images.githubusercontent.com/90042795/218246254-e0585b00-31ad-4ba9-8793-2e0f05a534bf.jpg)

### Tachiyomi version

0.14.4

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-02-11 15:57
Duplicate of #15281

**Closed by arkon** 2023-02-11 15:57 UTC
Labels: Bug
