### ISSUE TITLE
Image not loading in tachiyomisy

### ISSUE THREAD

**Issue by Revenant-Paul** [tachiyomiorg/tachiyomi-extensions#16832] opened 2023-06-23 04:24 UTC
### Source information

Toongod 1.4.33

### Source language

English

### Steps to reproduce

1.Open tachiyomisy
2.Select manga in source 

### Expected behavior

Opens manga in source 

### Actual behavior

Unable to load image

### Tachiyomi version

App version: 1.9.3

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment] 2023-06-23 04:50
> I have updated the app to version [0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest).

fwiw, TachiyomiSy is that way -> https://github.com/jobobby04/TachiyomiSY/issues

>  I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open or closed issue.

Duplicate of https://github.com/tachiyomiorg/tachiyomi-extensions/issues/15980

**Closed by curche** 2023-06-23 04:50 UTC
Labels: Bug
