### ISSUE TITLE
ColoredManga: Failed to bypass Cloudflare

### ISSUE THREAD

**Issue by Chimminiii123** [tachiyomiorg/tachiyomi-extensions#14118] opened 2022-11-03 22:14 UTC
### Source information and language

Colored Manga 1.3.25 (English)

### Steps to reproduce

1. coloredmanga.com failed to bypass cloudflare everytime I open the extension

### Expected behavior

1. The extension should bypass the cloudflare like the other extensions I use.

### Actual behavior

1. The extension cannot bypass the cloudflare no matter what I do

### Tachiyomi version

0.14.2

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-11-03 22:17
Duplicate of #14113

**Closed by alessandrojean** 2022-11-03 22:17 UTC
Labels: Bug
