### ISSUE TITLE
Webtoonxyz stuck cloudflare 

### ISSUE THREAD

**Issue by jonfrahrj** [tachiyomiorg/tachiyomi-extensions#12538] opened 2022-07-11 12:46 UTC
### Source information

WebtoonXYZ 1.3.24

### Steps to reproduce

Opening WebtoonXYZ extension doesn't show the list
Opening WebtoonXYZ on WebView shows the Cloudflare screen but it doesn't get pass that so I can't view the webtoons on Tachiyomi
Opening  in browser works but when i Come back and try again on WebView i'm stick on the cloudflare loop

### Expected behavior

It should redirect on WebtoonXYZ website

### Actual behavior

I'm stuck on cloudflare screen

### Tachiyomi version

 0.13.5

### Android version

 Android 12

### Other details

everything works perfecty on chrome 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-07-11 13:54
Duplicate of #6738

**Closed by alessandrojean** 2022-07-11 13:54 UTC
Labels: Bug
