### ISSUE TITLE
Doujindesu page list os empty

### ISSUE THREAD

**Issue by NameLess1909** [tachiyomiorg/tachiyomi-extensions#19307] opened 2023-12-14 03:18 UTC
### Source information

Doujindesu 1.4.5

### Source language

Indonesia

### Steps to reproduce

![Screenshot_2023-12-14-10-03-07](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/131794600/e232fd60-45d8-4e52-aae8-55b67d8d81e6)

### Expected behavior

Can watch the chapter i open

### Actual behavior

Chapter list is empty

### Tachiyomi version

V8.7.5-az

### Android version

Android 5

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-12-14 03:24
Duplicate of #19288

**Closed by arkon** 2023-12-14 03:24 UTC
Labels: Bug

**Comment by NameLess1909** [comment] 2023-12-14 03:34
> Duplicate of #19288

How its duplicate? Im using tachiyomi az, and the bug still not fixed yet in my taxhiyomi az
