### ISSUE TITLE
Hitomi.la not working 

### ISSUE THREAD

**Issue by Mtkmanjaro** [tachiyomiorg/tachiyomi-extensions#10856] opened 2022-02-18 04:10 UTC
thachiyomi version: 0.13.1  (74)
Android versión: 12

when open hitomi.la extension doesn't load nothing only a log http error 403, but is working well in web view mode.

hitomi.la in tachiyomi app
![](https://i.imgur.com/1MHWsG3.png)

hitomi la in web view mode
![](https://i.imgur.com/Ibflqgw.png)

**Comment by arkon** [comment] 2022-02-18 04:15
Duplicate of #10319

**Closed by arkon** 2022-02-18 04:15 UTC

**Comment by Mtkmanjaro** [comment] 2022-02-18 04:37
ok time to leave Hitomi.la
