### ISSUE TITLE
MangaSwat changed their website 

### ISSUE THREAD

**Issue by Tian-77** [tachiyomiorg/tachiyomi-extensions#17208] opened 2023-07-22 00:11 UTC
### Source information

ar.mangaswat 1.4.35

### Source language

"Arabic"

### Steps to reproduce

1. Open any manhwa
2. It'll show 0 chapter and the message " no chapters found" will appear

### Expected behavior

The chapters should show up but this doesn't happen 

### Actual behavior

"no chapters found"

### Tachiyomi version

1.9.3

### Android version

Android 13

### Other details

They were saying something about changing their website to a new one

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2023-07-22 04:24
Duplicate of #16952

**Closed by vetleledaal** 2023-07-22 04:24 UTC
Labels: Bug
