### ISSUE TITLE
MangaSwat chapter pages give a 403 (forbidden) status code

### ISSUE THREAD

**Issue by ig4e** [tachiyomiorg/tachiyomi-extensions#13036] opened 2022-08-17 03:52 UTC
### Source information and language

MangaSwat 1.3.24

### Steps to reproduce

1. Open/download a chapter

### Expected behavior

Chapter Pages load normally 

### Actual behavior

Chapter pages gives an error (403 status code)
![Screenshot_2022-08-17-05-53-21-700_eu.kanade.tachiyomi.j2k.jpg](https://user-images.githubusercontent.com/50212311/185031543-6a34234e-a7a5-4ee8-a8da-17cc4ccc9332.jpg)
![Screenshot_2022-08-17-05-55-54-592_eu.kanade.tachiyomi.j2k.jpg](https://user-images.githubusercontent.com/50212311/185031558-b1b8563a-1609-4b7d-abc3-f743e4c7e4b2.jpg)

### Tachiyomi version

Tachyomi v0.13.6

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ig4e** [comment] 2022-08-17 03:54
![Uploading Screenshot_2022-08-17-05-53-21-700_eu.kanade.tachiyomi.j2k.jpg…]()

**Comment by 7allom** [comment] 2022-08-17 10:17
I have the same issue

**Comment by arkon** [comment] 2022-08-17 13:20
Duplicate of #13021, probably.

**Closed by arkon** 2022-08-17 13:20 UTC
Labels: Bug

**Comment by ig4e** [comment] 2022-08-18 04:01
> Duplicate of #13021, probably.
probably manga swat added some image protection to prevent something like tachyomi this issue needs some testing/confirmation before closing it

**Comment by 7allom** [comment] 2022-08-18 15:43
> 

Bro the issue needs to be solved
