### ISSUE TITLE
Extention not working 

### ISSUE THREAD

**Issue by hydrayash** [tachiyomiorg/tachiyomi-extensions#14238] opened 2022-11-12 15:31 UTC
### Source information and language

Webcomics 1.3.3

### Steps to reproduce

![Screenshot_20221112_204721](https://user-images.githubusercontent.com/56506857/201481457-1c982b07-92d2-4d0e-966f-d9e9d900db7f.jpg)
![Screenshot_20221112_204714](https://user-images.githubusercontent.com/56506857/201481462-f3923490-2ff8-40f8-aeb8-1be0e7a603ac.jpg)

### Expected behavior

Should display Manhuas

### Actual behavior

No results found 

### Tachiyomi version

0.14.2

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment] 2022-11-13 23:02
Duplicate of #10959

**Closed** 2022-11-13 23:12 UTC
Labels: Bug
