### ISSUE TITLE
CoCoManhua Decryption failed

### ISSUE THREAD

**Issue by Sean1781031** [tachiyomiorg/tachiyomi-extensions#11354] opened 2022-04-07 01:29 UTC
### Source information

CoCoManhua (OhManhua) 1.2.10

### Steps to reproduce

1.Download or reading new chapters
2.Decryption failed

### Expected behavior

Chapter should be readable or downloading as usual

### Actual behavior

shows Decryption failed

### Tachiyomi version

0.13.1

### Android version

12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-04-07 01:32
> I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open issue.

Duplicate of #11345

**Closed by arkon** 2022-04-07 01:32 UTC
Labels: Bug
