### ISSUE TITLE
AllPornComic (eng) make the app load second pages, third pages and so on when scrolling results

### ISSUE THREAD

**Issue by Palloxin** [tachiyomiorg/tachiyomi-extensions#12697] opened 2022-07-22 23:06 UTC
### Source name and language

AllPornComic 1.3.23

### Describe your suggested feature

When i scroll entries on the extension with no filter applied (so the "home screen") the app loads the pages (group of comics) while if i use the filter option the results are only 20 so i suggest to make the app load automatically the secomd page of comics and so on.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-07-22 23:12
Duplicate of #11722

**Closed by alessandrojean** 2022-07-22 23:12 UTC
Labels: Feature request
