### ISSUE TITLE
Error 429

### ISSUE THREAD

**Issue by AKrocks94** [tachiyomiorg/tachiyomi-extensions#14868] opened 2023-01-09 13:25 UTC
### Source information and language

1st kiss 1.3.34 (english)

### Steps to reproduce

Whenever i try to update the manga it shows http error 429
It starts to happen as soon as i did the tachiyomi update and extension update

### Expected behavior

It should just update as it is intended to do not just show failed to update

### Actual behavior

When i do global update it shows failed to update

### Tachiyomi version

0.14.3

### Android version

Miui 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-01-09 13:36
Duplicate of #14850

**Closed** 2023-01-09 13:36 UTC
Labels: Bug
