### ISSUE TITLE
League of Legends: No pages found

### ISSUE THREAD

**Issue by Fooftilly** [tachiyomiorg/tachiyomi-extensions#11501] opened 2022-04-17 14:40 UTC
### Source information

League of Legends 1.2.1

### Steps to reproduce

1. Click on any manga chapter in League of Legends source.
2. No pages found issue

### Expected behavior

The chapter should load manga

### Actual behavior

No pages found issue

### Tachiyomi version

Preview r4266

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ObserverOfTime** [comment] 2023-03-25 10:35
I can't reproduce this. Does it happen on a specific language?

**Comment by arkon** [comment] 2023-05-26 21:18
In an effort to have a more manageable issue backlog, we're closing older requests that weren't addressed since there's a low chance of it being addressed if it hasn't already. If your request is still relevant, please [open a new request](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).

**Closed by arkon** 2023-05-26 21:18 UTC
Labels: Bug
