### ISSUE TITLE
[Source Request] Shit Scans

### ISSUE THREAD

**Issue by IRawXI** [tachiyomiorg/tachiyomi-extensions#7822] opened 2021-06-22 22:16 UTC
## Source website
- Name: Shit Scans
- Link: https://shitscans.com/
- Language(s): English

## Other details
Site looks custom to me

**Comment by arkon** [comment] 2021-06-22 22:21
Duplicate of #7445

**Closed by arkon** 2021-06-22 22:21 UTC
Labels: Source Request

**Comment by IRawXI** [comment] 2021-06-22 22:43
Thanks you (searching the issues for "shit" does not bring up that issue) :(
