### ISSUE TITLE
only load 1 page per chapter

### ISSUE THREAD

**Issue by khoa53** [tachiyomiorg/tachiyomi-extensions#13064] opened 2022-08-18 13:02 UTC
### Source information and language

Mangakatana 1.2.6 (English)

### Steps to reproduce

Only 1 page per chapter, reading on the website is normal

### Expected behavior

all pages should load

### Actual behavior

only 1 page loads

### Tachiyomi version

0.13.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-08-18 13:02
Duplicate of #13062

**Closed by arkon** 2022-08-18 13:02 UTC
Labels: Bug
