### ISSUE TITLE
Mangakyo: Can't load any manga chapters 

### ISSUE THREAD

**Issue by Raptor-bit** [tachiyomiorg/tachiyomi-extensions#14312] opened 2022-11-20 05:05 UTC
### Source information and language

Mangakyo 1.3.21 (Indonesia)

### Steps to reproduce

When open mangakyo
1. Open manga
2. No chapters shown 

### Expected behavior

In webview it just works fine 
![Screenshot_2022-11-20-11-33-46-62_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/53387197/202885941-9aa8dbde-1727-4364-8a54-6df164e11abc.png)

### Actual behavior

But i get this
![Screenshot_2022-11-20-11-32-55-68_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/53387197/202885859-ee56de4d-7e23-4485-8d59-a03917d9802c.png)

### Tachiyomi version

0.14.2

### Android version

Android 9

### Other details

When Try to open it in manga section webview
![IMG_20221120_115236](https://user-images.githubusercontent.com/53387197/202886277-446b874b-b44b-4145-add8-48262f0e88aa.jpg)

It send me to their homepage not into the manga itself
![Screenshot_2022-11-20-11-52-08-03_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/53387197/202886356-e1dc9c68-b60c-4ad8-8289-cbd3ed748adf.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-11-20 06:09
Duplicate of #14267. Please don't close open issues that to bump new ones.

**Closed by alessandrojean** 2022-11-20 06:09 UTC
Labels: Bug
