### ISSUE TITLE
403 error opening hitomila

### ISSUE THREAD

**Issue by haotianliang** [tachiyomiorg/tachiyomi-extensions#10466] opened 2022-01-15 05:30 UTC
### Source information

Hitomi.la

### Steps to reproduce

![Screenshot_2022-01-15-13-28-34-968_eu kanade tachiyomi](https://user-images.githubusercontent.com/97282580/149610282-e340d160-de32-4ee0-824c-9bfc95ef38ad.jpg)
![Screenshot_2022-01-15-13-23-38-877_eu kanade tachiyomi](https://user-images.githubusercontent.com/97282580/149610297-8878bb1c-d1ed-4543-9a8a-e775e07a0fb2.jpg)

### Expected behavior

Page appears

### Actual behavior

404 error opening hitomila

### Tachiyomi version

0.12.3

### Android version

Android11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment] 2022-01-15 11:59
@haotianliang don't post nsfw screenshots

**Comment by arkon** [comment] 2022-01-15 13:51
Duplicate of #10319

**Closed by arkon** 2022-01-15 13:51 UTC
Labels: Bug
