### ISSUE TITLE
Manga Owl No pages Found

### ISSUE THREAD

**Issue by HimenoKazehito** [tachiyomiorg/tachiyomi-extensions#10787] opened 2022-02-10 23:24 UTC
### Source information

Manga Owl 1.2.24.

### Steps to reproduce

1. Click on manga/manhwa
2. Loads then says no pages found
3. Source website does have pages, but refuses to load in app

### Expected behavior

The chapter should load

### Actual behavior

Instead they load and then says no pages found

### Tachiyomi version

App version: 0.13.1-4139 

### Android version

Android 10

### Other details

The previous cases have closed

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-02-10 23:25
Duplicate of #10463

**Closed by arkon** 2022-02-10 23:25 UTC
Labels: Bug
