### ISSUE TITLE
Sekaikomik (Cloudflare doesn't allow me access website in the WebView)

### ISSUE THREAD

**Issue by Chan220** [tachiyomiorg/tachiyomi-extensions#7983] opened 2021-07-05 15:02 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1.

### Android version

Android 8.0.0

### Source information

Sekaikomik 1.2.14

### Steps to reproduce

1. Open Source
2.  Error 403
3.  Check in Webview
4.  Error 1020 Acces Denied

### Expected behavior

Show the manga list

### Actual behavior

Extension doesn't show the list of manga. Error 403. After check in webview Error 1020 Acces Denied

**Comment by Clouddark75** [comment] 2021-07-06 13:46
Duplicate of #7439 and #7457.

**Comment by Clouddark75** [comment] 2021-07-06 13:47
It's intentional, for now you best shot is to migrate another source.

**Closed** 2021-07-06 13:49 UTC
Labels: Bug
