### ISSUE TITLE
 Hattori Manga: HTTP error 404

### ISSUE THREAD

**Issue by Heraeon** [tachiyomiorg/tachiyomi-extensions#19507] opened 2023-12-31 12:21 UTC
### Source information

Hattori Manga 1.4.31

### Source language

Turkish

### Steps to reproduce

1. Open hattori manga
2. it says: Http Error 404
3. Open webview
4. It opens in webview but not in the app.

### Expected behavior

The source should open in the application without any problem

### Actual behavior

But the source does not open and gives a error 404. 

### Tachiyomi version

0.14.7

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2023-12-31 17:16
Duplicate of #17840

**Closed by vetleledaal** 2023-12-31 17:16 UTC
Labels: Bug
