### ISSUE TITLE
Imperfect Comics not loading manga

### ISSUE THREAD

**Issue by shawnnguyen1** [tachiyomiorg/tachiyomi-extensions#11034] opened 2022-03-06 21:13 UTC
### Source information

Imperfect Comics 1.2.20

### Steps to reproduce

Browse imperfect comics manga: HTTP error 400: Check website in WebView

### Expected behavior

Expected to see list of manga

### Actual behavior

Browse imperfect comics manga: HTTP error 400: Check website in WebView

### Tachiyomi version

0.13.1

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2022-03-06 21:14
Duplicate of #11003

**Closed by Seishirou101** 2022-03-06 21:14 UTC
Labels: Bug
