### ISSUE TITLE
Hentaidexy Http 404 error loop

### ISSUE THREAD

**Issue by kingmj2000** [tachiyomiorg/tachiyomi-extensions#15172] opened 2023-01-29 19:00 UTC
### Source information and language

Hentaidexy 1.3.31

### Steps to reproduce

1. Open Tachiyomi
2. Choose Hentaidexy in Sources 

### Expected behavior

It should load library of manga

### Actual behavior

Shows "Http error 404: Che k in Webview"

But when I check in webview it is working fine and after going back to app, again it shows the same error message.

### Tachiyomi version

0.14.3

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment] 2023-01-30 11:00
Duplicate of #15167

**Closed by stevenyomi** 2023-01-30 11:00 UTC
Labels: Bug
