### ISSUE TITLE
Mangasee not downloading certain chapters in a manga / mangasee download fails but when read online it has no problems

### ISSUE THREAD

**Issue by channylabs** [tachiyomiorg/tachiyomi-extensions#7950] opened 2021-07-02 23:49 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android 11

### Source information

Mangasee 1.2.24

### Steps to reproduce

1. Download manga update
2. Reaches to full download but fails when almost done
3. Download fails and notifies

### Expected behavior

When you download a manga in bulk or you download a new update, it should download smoothly

### Actual behavior

It fails instead when its almost finished

### Other details

![Screenshot_2021-07-03-07-47-01-390_eu kanade tachiyomi](https://user-images.githubusercontent.com/86859252/124336984-f0881f80-dbd2-11eb-89ba-db29c65f82ea.jpg)
![Screenshot_2021-07-03-07-47-17-739_eu kanade tachiyomi](https://user-images.githubusercontent.com/86859252/124336991-f67e0080-dbd2-11eb-967e-e43b9bde63e4.jpg)
See screenshots for proof

**Comment by Seishirou101** [comment] 2021-12-19 16:42
Is this still happening to you? usually this issue is caused by your connection to them or them to you. If it does, can you check the file manager for the chapter in question and see if the last page is actually downloaded?

**Comment by Seishirou101** [comment] 2022-05-13 04:19
closed as no answer

**Closed by Seishirou101** 2022-05-13 04:19 UTC
Labels: Bug
