### ISSUE TITLE
امبراطورية الويب تون

### ISSUE THREAD

**Issue by BungeeGUN** [tachiyomiorg/tachiyomi-extensions#9925] opened 2021-11-25 16:07 UTC
### Source name

امبراطورية الويب تون

### Source link

https://empirewebtoon.com/

### Language

Arabic

### Other details

Well in the Arabic section there's no any extension for bl mnwha and manga , this site has a lot of it and we need it on tachiyomi so bad. I've another recommendation as well and I hope both be accepted.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2021-11-25 16:13
Duplicate of #9453

**Closed** 2021-11-25 16:13 UTC
Labels: Source request
