### ISSUE TITLE
Mangabat URL

### ISSUE THREAD

**Issue by Scyth3rGG** [tachiyomiorg/tachiyomi-extensions#10642] opened 2022-02-01 06:19 UTC
### Source information

Mangabat 1.2.9

### Steps to reproduce

Mangabat URL leads to the old site, which means that your have to manually click on 'Webview' to redirect to their current page, and even then it rarely ever works when trying to open a manga.

### Expected behavior

Mangabat should automatically redirect to the current website.

### Actual behavior

Instead, it uses the old URL, making the manga load really slow or unable to work at all.

### Tachiyomi version

0.13.0

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.0](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by jopejoe1** [comment] 2022-02-01 07:43
Duplicate of #10198

**Closed** 2022-02-01 12:15 UTC
Labels: Bug
