### ISSUE TITLE
Field 'data' error on 1manga.co extension 

### ISSUE THREAD

**Issue by Drack31** [tachiyomiorg/tachiyomi-extensions#12975] opened 2022-08-13 18:15 UTC
### Source information and language

1manga.co English 1.3.6

### Steps to reproduce

On any manga, click any chapter 

### Expected behavior

Download and show the pages of the manga

### Actual behavior

Getting the pop-up "field 'data'is required for type with serial name <xxxx>, but is missing"

### Tachiyomi version

App version: 0.13.5 (standard, 26ddc6e, 81, 2022-07-08T20:12Z) Android version: 11 (SDK 30) Android build ID: RKQ1.200826.002 test-keys Device brand: POCO Device manufacturer: Xiaomi Device name: vayu Device model: M2102J20SG Device product name: vayu_eea

### Android version

Android 11 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-08-13 18:28
Duplicate of #12959

**Closed by arkon** 2022-08-13 18:28 UTC
Labels: Bug
