### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by LucasRyuy** [tachiyomiorg/tachiyomi-extensions#18106] opened 2023-09-23 03:59 UTC
### Source information

goldenmangatop

### Source language

Português PTBR

### Steps to reproduce

This is causing manga updates to not occur

![Screenshot_20230922-235303_TachiyomiJ2K](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/145422272/7c81586d-b66b-4783-9c1e-9411d787dfa4)

### Expected behavior

Aparecer os manhwas/manhwas/manga

### Actual behavior

Não aparece nada

### Tachiyomi version

J2k 1.6.6

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2023-09-23 04:04
Duplicate of #18098

**Closed by Seishirou101** 2023-09-23 04:04 UTC
Labels: Bug
