### ISSUE TITLE
[Source Request] <Doujindesu>

### ISSUE THREAD

**Issue by dimbaii** [tachiyomiorg/tachiyomi-extensions#5615] opened 2021-02-01 17:38 UTC
## Source website
- Name: **Doujindesu**
- Link: www.doujindesu.site / www.doujindesu.info
- Language(s): Indonesia

## Other details
This is one of Indonesian web translators for manga, manhwa, etc

**Comment by scb261** [comment] 2021-02-01 22:22
doujindesu.info - duplicate of #5470
doujindesu.site - looks like it has different content, but I'm not sure

**Comment by dimbaii** [comment] 2021-02-16 08:50
@scb261 
There's a different web, doujindesu.info especially for read online
doujindesu.site can able to download and read online
So I give '/' on it

**Comment by dimbaii** [comment] 2021-02-16 08:51
> doujindesu.info - duplicate of #5470
> doujindesu.site - looks like it has different content, but I'm not sure

**Comment by yoshino36** [comment] 2021-05-09 21:53
We Need This Extensions ASAP

**Comment by curche** [comment] 2021-07-01 19:17
Both sites now point to the same site doujindesu.info which makes it a duplicate to #5470

**Closed by curche** 2021-07-01 19:17 UTC
Labels: Source request
