### ISSUE TITLE
Mangaworld New Domain

### ISSUE THREAD

**Issue by ed0fl3da** [tachiyomiorg/tachiyomi-extensions#9301] opened 2021-10-01 07:51 UTC
### Source information

Mangaworld

### Steps to reproduce

Open source Mangaworld
Open a manga in the source

### Expected behavior

You can read the manga

### Actual behavior

The manga doesn't load

### Tachiyomi version

0.12.2

### Android version

Latest

### Other details

New Domain: https://www.mangaworld.in/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment] 2021-10-01 09:33
read the Acknowledgements
>  I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open issue.

Duplicate of #9291

**Closed** 2021-10-01 09:34 UTC
Labels: Bug
