### ISSUE TITLE
Webtoon.com error

### ISSUE THREAD

**Issue by Poncow5** [tachiyomiorg/tachiyomi-extensions#13157] opened 2022-08-23 16:57 UTC
### Source information and language

Webtoon 1.2.35 (All)

### Steps to reproduce

1. Updating manga from webtoon
2. Can't update the manga giving error SSL handshake aborted

### Expected behavior

Should update normally

### Actual behavior

Got error ssl handshake instead

### Tachiyomi version

8.7.1-AZ

### Android version

Android 5

### Other details

![Screenshot_2022-08-23-23-49-47-87](https://user-images.githubusercontent.com/72888366/186218045-77b4d166-9e1f-4a0d-a97a-1ccf76f1fd48.png)
I'm using tachiyomi AZ

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ObserverOfTime** [comment] 2022-08-24 10:07
Looks like #9977 is back.

**Comment by scb261** [comment] 2022-08-24 17:52
Yeah, it's server side again, just different issue.

The issue is that after some time of **not** using webtoons.com, the first network call will fail with the error that says that connection was reset by peer (meaning reset by server). So if you didn't use the app for some time and then update your library - the first entry from webtoons.com will fail, while others will update fine. The same if you open the source after some time of not using it.

You can easily test it with `openssl`. Just use the command below few times in a row. First time it will fail, while following ones will work fine.
`openssl s_client -connect m.webtoons.com:443`

Browsers probably handle this issue better (tested only in chrome, lazy to check other browsers). Maybe the extension could catch this error and retry, but maybe it's worth waiting a bit in case they fix it on their side.

**Comment by Amejonah1200** [comment] 2022-08-25 22:48
Does only the webpages which is affected or also their app API?

**Comment by CapoFantasma97** [comment] 2022-09-22 00:27
> Yeah, it's server side again, just different issue.
> 
> The issue is that after some time of **not** using webtoons.com, the first network call will fail with the error that says that connection was reset by peer (meaning reset by server). So if you didn't use the app for some time and then update your library - the first entry from webtoons.com will fail, while others will update fine. The same if you open the source after some time of not using it.
> 
> You can easily test it with `openssl`. Just use the command below few times in a row. First time it will fail, while following ones will work fine.
> `openssl s_client -connect m.webtoons.com:443`
> 
> Browsers probably handle this issue better (tested only in chrome, lazy to check other browsers). Maybe the extension could catch this error and retry, but maybe it's worth waiting a bit in case they fix it on their side.

I receive this error daily on both of the devices I use Tachiyomi on, so maybe it isn't time sensitive as suggested

**Comment by scb261** [comment] 2022-09-24 12:18
> I receive this error daily on both of the devices I use Tachiyomi on, so maybe it isn't time sensitive as suggested

I'm pretty sure it's time sensitive. Force closing the app, using a fork, clearing cache/cookies, using different device on the same network - nothing of this will bring the error back. If you are continuously reading - the are also no errors. But after 5+ minutes of not using the source, the error will appear again (yeah, I did some tests and measured it while writing this). It's probably linked to user's IP.

If anyone is willing to fix this, you could add an interceptor that would catch the error and retry once. Doesn't look like they are fixing it on the server side, and I feel like it's intentional.

**Closed** 2022-09-26 21:44 UTC
Labels: Bug
