### ISSUE TITLE
Mangaswat: chapter pages giving 403 response

### ISSUE THREAD

**Issue by ig4e** [tachiyomiorg/tachiyomi-extensions#17091] opened 2023-07-12 19:32 UTC
### Source information

MangaSwat 1.4.34

### Source language

Arabic 

### Steps to reproduce

1. Open a manga (for example eleceed)
2. Open a chapter
3. The images won't load properly
4. 
![Screenshot_2023-07-12-22-29-47-298_eu kanade tachiyomi j2k](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/50212311/30c7c1e0-63ee-489c-8ed2-983aa96535cc)

### Expected behavior

The chapter pages should load fine

### Actual behavior

The chapter pages doesn't load at all but works fine in the WebView

![Screenshot_2023-07-12-22-29-47-298_eu kanade tachiyomi j2k](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/50212311/df35e206-358d-408c-9ecf-934562c21c2f)
![Screenshot_2023-07-12-22-32-45-614_eu kanade tachiyomi j2k](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/50212311/826f4359-c08b-40bb-8f80-a5db6a9ee0b9)

### Tachiyomi version

J2K 1.6.6 (should be the latest)

### Android version

12, with MIUI 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-07-15 23:02
Duplicate of #16952

**Closed** 2023-07-15 23:03 UTC
Labels: Bug, Duplicate
