### ISSUE TITLE
[Source Request] Travis Translations

### ISSUE THREAD

**Issue by AsimpleGuy** [tachiyomiorg/tachiyomi-extensions#6486] opened 2021-04-10 01:18 UTC
### Source website

Name: Travis Translations
Link: https://travistranslations.com
Language(s): English

**Comment by CrepeTF** [comment] 2021-04-10 01:38
WP MangaStream

**Comment by Riztard** [comment] 2021-04-10 04:34
Duplicate of #5200

**Closed by Riztard** 2021-04-10 04:34 UTC
Labels: Factory Source, Source Request
