### ISSUE TITLE
HTTP error 429

### ISSUE THREAD

**Issue by Yamiyie** [tachiyomiorg/tachiyomi-extensions#11291] opened 2022-04-01 03:12 UTC
### Source information

1st kiss

### Steps to reproduce

Whenever i read it says HTTP erorr 429

### Expected behavior

I was going to read and update my library 

### Actual behavior

And then it says HTTP erorr 429

### Tachiyomi version

0.13.1

### Android version

Android 11

### Other details

Uhm they said I'm banned from reading too fast. Can you help me fix this?i want to read and update ny library:( it was okay before I'm still new here I'm not familiar with the app and its restrictions ☹️ Tachiyomi is the only app where i read manga/manwha/manhua.Pls fix this.This is my 2nd report already

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-04-01 03:22
Duplicate of #11280

**Closed by arkon** 2022-04-01 03:22 UTC
Labels: Bug
