### ISSUE TITLE
Mangahub extension HTTP error 403

### ISSUE THREAD

**Issue by Yoohru** [tachiyomiorg/tachiyomi-extensions#12802] opened 2022-07-30 11:25 UTC
### Source information and language

Mangahub 1.3.13 18+

### Steps to reproduce

1. Open any manga to read
2. read any chapters
3. goes back to chapter list then says HTTP error 403

### Expected behavior

Be able to read any chapters

### Actual behavior

![Screenshot_20220730_192301](https://user-images.githubusercontent.com/110288440/181908701-7f219b5a-ca4b-4392-9dca-fb95a3151efe.jpg)

### Tachiyomi version

0.13.5

### Android version

9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment] 2022-07-30 11:32
Duplicate of #12794

**Closed by loocool2** 2022-07-30 11:32 UTC
Labels: Bug
