### ISSUE TITLE
[Source Request] https://www.mangasaki.com/

### ISSUE THREAD

**Issue by hjdrm** [tachiyomiorg/tachiyomi-extensions#5640] opened 2021-02-05 16:37 UTC
---

## Source website
- Name: Mangasaki
- Link: https://www.mangasaki.com/
- Language(s): English

## Other details
Fast updates and has raws uploaded

**Comment by scb261** [comment] 2021-02-05 16:40
Duplicate of #4757

**Closed by scb261** 2021-02-05 16:40 UTC
Labels: Source Request
