### ISSUE TITLE
WeLoveManga: domain changed

### ISSUE THREAD

**Issue by Endowpea** [tachiyomiorg/tachiyomi-extensions#12199] opened 2022-06-14 10:44 UTC
### Source information

WeLoveManga 1.3.9

### Steps to reproduce

Open WeLoveManga

### Expected behavior

load manga list

### Actual behavior

Http error 404
open in WebView, the url redirect to https://5slive.net/

### Tachiyomi version

0.13.4

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment] 2022-06-15 10:53
duplicate of #11719

**Closed by Riztard** 2022-06-15 10:53 UTC
Labels: Bug
