### ISSUE TITLE
manga tales

### ISSUE THREAD

**Issue by hani1998** [tachiyomiorg/tachiyomi-extensions#8228] opened 2021-07-22 13:53 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

manga tales

### Source link

http://mangatales.com

### Language

Aerobic

### Other details

Please, please, please, add this source for app extensions

**Comment by hani1998** [comment] 2021-07-22 13:59
@CarlosEsco Is this good

**Comment by CarlosEsco** [comment] 2021-07-22 14:00
i had already renamed all your old tickets, there was no reason to close them and open new ones

**Comment by hani1998** [comment] 2021-07-22 14:13
@CarlosEsco Thank you very much my brother and I apologize how do I delete the new one

**Comment by alessandrojean** [comment] 2021-07-24 01:51
Duplicate of #7488

**Closed by alessandrojean** 2021-07-24 01:51 UTC
Labels: Source request
