### ISSUE TITLE
Read and Download error

### ISSUE THREAD

**Issue by shadoupasu** [tachiyomiorg/tachiyomi-extensions#8263] opened 2021-07-25 07:51 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android 9

### Source information

Manga-TR

### Steps to reproduce

Downloading up to the fourth picture and then giving an error

### Expected behavior

Read and download

### Actual behavior

Does not detect pages so reading and downloading are not happening

**Comment by FourTOne5** [comment] 2021-07-25 13:55
Duplicate of #8233

**Closed** 2021-07-25 14:00 UTC
Labels: Bug
