### ISSUE TITLE
Comick website search error 

### ISSUE THREAD

**Issue by Hawksaran** [tachiyomiorg/tachiyomi-extensions#17904] opened 2023-09-11 20:13 UTC
### Source information

Comick 1.4.34

### Source language

Multi

### Steps to reproduce

Chapter works fine but suddenly not able.to.search anything it shows error and the search option in full.searxh also shows error
/
![Screenshot_2023-09-12-01-41-30-08_79aa9bf7c61e266c5f841e42245e214b](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/132247482/768130a4-9c35-419c-a511-6c9e93a1fa68)

### Expected behavior

Usually search works 

### Actual behavior

Nows it shows error 

### Tachiyomi version

R6048

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2023-09-14 07:23
Duplicate of #17337

**Closed by vetleledaal** 2023-09-14 07:23 UTC
Labels: Bug
