### ISSUE TITLE
Extension-roumanwu is no longer accessiable and error at opening

### ISSUE THREAD

**Issue by hongyanhongxue** [tachiyomiorg/tachiyomi-extensions#19042] opened 2023-11-20 16:41 UTC
### Source information

Extension-roumanwu1.4.5

### Source language

Chinese

### Steps to reproduce

open roumanwu from source directly or open any book from roumanwu resource
error message: Fields [headline, best, hottest, daily, recentUpdatedBooks, enedBooks] are required for type with serial name 'eu.kanade.tachiyomi.extension.zh.roumanwu.HomePage', but they were missing at path: 
.props.pageProps at path: $.props.pageProps

### Expected behavior

Should open book or webpage from roumanwu as normal

### Actual behavior

Error msg and cannot view book from that source any longer.

### Tachiyomi version

0.14.7

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment] 2023-11-21 16:47
Duplicate of #18960

**Closed** 2023-11-21 16:47 UTC
Labels: Bug, Duplicate
