### ISSUE TITLE
Doujindesu - Cover/thumbnail image do not showing

### ISSUE THREAD

**Issue by frrrrrits** [tachiyomiorg/tachiyomi-extensions#11832] opened 2022-05-13 00:13 UTC
### Source information

Doujindesu 1.2.2

### Steps to reproduce

open doujindesu

### Expected behavior

open usually

### Actual behavior

![Screenshot_20220513_070511](https://user-images.githubusercontent.com/59435336/168186975-3855fd47-a256-41b6-a67a-bf4619004e63.jpg)
![Screenshot_20220513_070528](https://user-images.githubusercontent.com/59435336/168186969-effbbd94-ef2c-4fb5-8e9c-964809f0d332.jpg)

### Tachiyomi version

0.13.4

### Android version

Android 9

### Other details

if you open in webview it will open usually

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-05-13 01:19
Duplicate of #11662

**Closed by alessandrojean** 2022-05-13 01:19 UTC
Labels: Bug
