### ISSUE TITLE
HTTP Error 403

### ISSUE THREAD

**Issue by riju561** [tachiyomiorg/tachiyomi-extensions#9496] opened 2021-10-16 06:22 UTC
### Source information

1st Kiss 1.2.17

### Steps to reproduce

Try to open any manga or manhwa, it will show Http error 403: Check website in Webview
![image](https://user-images.githubusercontent.com/63897835/137576191-8fdf94a8-1f52-440c-8703-0efa38183f86.png)

### Expected behavior

The mangas or manhwas should show

### Actual behavior

HTTP Error 403,  Open in web view

### Tachiyomi version

0.12.3

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment] 2021-10-16 06:23
Duplicate of #9377

**Closed by loocool2** 2021-10-16 06:23 UTC
Labels: Bug
