### ISSUE TITLE
[Feature Request] MangaKatana: Implement Filtering by Author and Genre.

### ISSUE THREAD

**Issue by MercerBoi** [tachiyomiorg/tachiyomi-extensions#5639] opened 2021-02-05 14:58 UTC
## What feature should be added to this source?
Unlike most other sources, this one doesn't have any filter options to narrow the search results down to what the user wants to see. 

I checked the website and it does offer filtering by genres (accessed from the hamburger menu on the left) and filtering by author (by simply tapping on one's name from the manga's info page).

**Comment by Riztard** [comment] 2021-02-05 15:21
duplicate of #5128

**Closed by Riztard** 2021-02-05 15:21 UTC
Labels: enhancement
