### ISSUE TITLE
japscan have a problem

### ISSUE THREAD

**Issue by babacool1712** [tachiyomiorg/tachiyomi-extensions#12565] opened 2022-07-12 22:02 UTC
### Source information

Japscan  v1.3.29

### Steps to reproduce

1 go to source japscan 
2 choose a manga
3 choose a chapter
4 chapter not loading

(sorry my english is bad, i'm french)

### Expected behavior

normally the chapter should have worked

### Actual behavior

the chapter does not load

### Tachiyomi version

0.13.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-07-12 22:04
Duplicate of #12491

**Closed** 2022-07-12 22:04 UTC
Labels: Bug
