### ISSUE TITLE
Doujindesu: NXDOMAIN

### ISSUE THREAD

**Issue by Richie012301** [tachiyomiorg/tachiyomi-extensions#11515] opened 2022-04-18 09:56 UTC
### Source information

Doujindesu 1.2.2

### Steps to reproduce

1. Open tachiyomi application
2. Opens the doujindesu extension in app
2. Result shows NXDOMAIN

### Expected behavior

Showing manga and doujin lists available in the extension 

### Actual behavior

Shown error sign that says:
212.32.226.234: NXDOMAIN

### Tachiyomi version

Tachiyomi 0.13.3

### Android version

Android 7.1.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment] 2022-04-18 10:23
>  I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open issue.

Duplicate of #11439

**Closed by curche** 2022-04-18 10:23 UTC
Labels: Bug
