### ISSUE TITLE
New chapter update problem

### ISSUE THREAD

**Issue by MRmustafa478** [tachiyomiorg/tachiyomi-extensions#16775] opened 2023-06-17 13:39 UTC
### Source information

MangaSwat 1.4.33

### Source language

Arabic

### Steps to reproduce

1.the source don't update new chapters in tachiyomi only
2.there in no problem with old chapters they all work well
3.in web view there isn't any problems and the new chapters are Exists and can be open 

### Expected behavior

Please look at the problem 

### Actual behavior

Floating message say "no chapters found"

### Tachiyomi version

0.14.6

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-06-17 14:00
Duplicate of #16740

**Closed by arkon** 2023-06-17 14:00 UTC
Labels: Bug
