### ISSUE TITLE
Manhwafreak: No pages found

### ISSUE THREAD

**Issue by NerdEmbryo** [tachiyomiorg/tachiyomi-extensions#17654] opened 2023-08-24 18:04 UTC
### Source information

Manhwafreak 1.4.27

### Source language

English

### Steps to reproduce

1. Manhwas not updating.
2. While opening chapters shows no pages found
3. On webview for individual manhwa it goes to manhwafreak homepage instead of respective manhwa page

### Expected behavior

1. Should update chapters normally
2. Should show the pages for the respective chapters
3. On webview should open the manhwa page instead of homepage

### Actual behavior

1. Show error while updating
2. While opening chapters shows no pages found
3. On webview for individual manhwa it goes to manhwafreak homepage instead of respective manhwa page

### Tachiyomi version

0.14.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AriaDeAzure** [comment] 2023-08-25 00:05
Just to add the information that there was an URL change (according to the official announcement in their discord). Currently, the URL is: https://manhwa-freak.com/
Their manga branch URL was also updated to: https://freakcomic.com/ (I'm not sure if this one has its own extension )

**Comment by AwkwardPeak7** [comment] 2023-08-25 11:20
duplicate of #17658

**Closed** 2023-08-25 11:51 UTC
Labels: Bug
