### ISSUE TITLE
Reaperscans needs an update

### ISSUE THREAD

**Issue by NotPageD** [tachiyomiorg/tachiyomi-extensions#9943] opened 2021-11-27 05:52 UTC
### Source information

Reaperscans 1.2.14

### Steps to reproduce

click any series on reaperscans

### Expected behavior

it should display the chapter numbers

### Actual behavior

blank

### Tachiyomi version

tachiyomisy preview r414

### Android version

android 8

### Other details

i have tried using the filter function where it ignores the website information and it just display the chapter number and not as what the source titles it but it also doesn't work because all the chapters are named as chapter 1.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2021-11-27 05:57
Duplicate of #9934

**Closed by alessandrojean** 2021-11-27 05:57 UTC
Labels: Bug
