### ISSUE TITLE
Kuaikuai Manhua 3(快快漫画3) is unable to load comic images.

### ISSUE THREAD

**Issue by hsiayuchih** [tachiyomiorg/tachiyomi-extensions#19595] opened 2024-01-08 03:22 UTC
### Source information

Kuaikuai Manhua 3(快快漫画3)

### Source language

Chinese

### Steps to reproduce

https://github.com/tachiyomiorg/tachiyomi-extensions/issues/19411  same issues

### Expected behavior

Images from 'Kuaikuai Manhua 3' can be accessed normally.

### Actual behavior

It always returns "The image couldn't be loaded."

### Tachiyomi version

0.14.7

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ZerOri** [comment] 2024-01-08 06:16
#19411 Don't post duplicate issue.

**Comment by yigedajiaque** [comment] 2024-01-08 06:30
I have the same problem.

**Comment by stevenyomi** [comment] 2024-01-08 14:54
Duplicate of #19411

**Closed by stevenyomi** 2024-01-08 14:54 UTC
Labels: Bug
