### ISSUE TITLE
Cannot begin reading element

### ISSUE THREAD

**Issue by Kareem3ouf** [tachiyomiorg/tachiyomi-extensions#18431] opened 2023-10-08 02:31 UTC
### Source information

dragontea 1.4.33

### Source language

English

### Steps to reproduce

Enter extension 
select anything
Click read
Then the error
![Screenshot_20231005_103229](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/147290110/b6511654-abb2-492c-a6a4-cbaa622e8e8d)

### Expected behavior

Chapter loading starts normally

### Actual behavior

gives me an error
#
![Screenshot_20231005_103229](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/147290110/8837d114-1008-40a3-bbc8-49fdfb2320d9)

### Tachiyomi version

0.14.6

### Android version

Emui 12.0.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by DchanN** [comment] 2023-10-08 11:25
Duplicate of #17616

**Closed** 2023-10-08 11:51 UTC
Labels: Bug

**Comment by Kareem3ouf** [comment] 2023-10-08 14:19
Well neither one of the two duplicates had any solution
