### ISSUE TITLE
Mizumangas:changed domain

### ISSUE THREAD

**Issue by Raidre** [tachiyomiorg/tachiyomi-extensions#16615] opened 2023-05-30 05:44 UTC
### Source information

Mizumangas 1.4.29

### Source language

Português

### Steps to reproduce

changed domain 

### Expected behavior

does not enter

### Actual behavior

...

### Tachiyomi version

O.14.6

### Android version

Android 11

### Other details

...

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2023-05-30 11:46
Duplicate of #16286 + wrong issue template

**Closed by alessandrojean** 2023-05-30 11:46 UTC
Labels: Bug
