### ISSUE TITLE
Can we request another extension? 

### ISSUE THREAD

**Issue by Yaoiislife** [tachiyomiorg/tachiyomi-extensions#9082] opened 2021-09-16 03:35 UTC
### Source name

Mangabuddy

### Source link

https://mangabuddy.com/

### Language

English

### Other details

I do hope that we would be able to download the chapters.

Thank you for be able to read my request and so hope that it will be added.

Have a wonderful Day/Noon/Evening! 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment] 2021-09-16 03:39
Duplicate of #8908

**Closed by loocool2** 2021-09-16 03:39 UTC
Labels: Source request
