### ISSUE TITLE
Japscan : Isolated cases of scrambled images

### ISSUE THREAD

**Issue by aboudiom59** [tachiyomiorg/tachiyomi-extensions#12935] opened 2022-08-10 23:17 UTC
### Source information and language

Japscan 1.3.32

### Steps to reproduce

1. Open a manga where the scramble occurs fir example "Thermae Romae"
2. Open a chapter
3. The image loaded is scrambled and unreadable 

### Expected behavior

The image loaded is normal and readable 

### Actual behavior

The image is scrambled and unreadable 

### Tachiyomi version

0.13.5

### Android version

Android 11

### Other details

The bug only occurs for certain chapters of certain manga, sometimes it affects all the chapters in the manga like the aforementioned "Thermae Romae" or  other times just certain chapters like the manga "Pline" where chapters 1 through 21.5 and chapters 29 through 42.5 are scrambled while the rest are normal.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-08-10 23:22
Duplicate of #9374

**Closed by alessandrojean** 2022-08-10 23:22 UTC
Labels: Bug
