### ISSUE TITLE
Manga Şehri is giving HTTP 404 error and in web view its not opening the manga

### ISSUE THREAD

**Issue by Leucosia1** [tachiyomiorg/tachiyomi-extensions#18949] opened 2023-11-13 07:05 UTC
### Source name

Manga Şehri 1.4.31

### Source language

Turkish

### Source link

https://manga-sehri.com/

### Other details

I am using this source a lot so I hope you can solve this problem. I can't download from Manga Şehri and in web view, mangas not opening please help
![Screenshot_20231113-100413_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/148116909/611bd38c-3ebe-406d-ab5c-d05aca94331c)
![Screenshot_20231113-100340_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/148116909/904f3947-5705-4622-b30f-85735b3ee992)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2023-11-13 09:46
Duplicate of #18715

**Closed by vetleledaal** 2023-11-13 09:46 UTC
Labels: Source is down
