### ISSUE TITLE
Manganato not loading past 1 or 2 pages

### ISSUE THREAD

**Issue by hclw343** [tachiyomiorg/tachiyomi-extensions#18855] opened 2023-11-03 18:11 UTC
### Source information

Manganato 1.4.7

### Source language

English

### Steps to reproduce

1. Open any series with a reasonable amount of pages through tachiyomi
2. Go to 2nd or 3rd or 4th page

### Expected behavior

Page loads and you can read

### Actual behavior

"the image could not be loaded" text appears with the retry button, despite the page loading in webview

### Tachiyomi version

0.14.7

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2023-12-14 16:56
Duplicate of #18309

**Closed by vetleledaal** 2023-12-14 16:56 UTC
Labels: Bug
