### ISSUE TITLE
1manga.io showing API rate limit excessd

### ISSUE THREAD

**Issue by akshar2324** [tachiyomiorg/tachiyomi-extensions#13075] opened 2022-08-19 03:22 UTC
### Source information and language

1Manga.co 1.3.9

### Steps to reproduce

1. Open 1manga.co and open any manga
2. Read some chapter
3. After some time it will show API rate limit excessed and can't read chapter

### Expected behavior

It should let us read manga 

### Actual behavior

![Screenshot_20220819_084532](https://user-images.githubusercontent.com/90042795/185535716-d6e0d83f-55db-461b-b2af-916e95e18835.jpg)

Showing this error when opening any chapter " API rate limit excessed! go to mangahub.io to continue reading!"

### Tachiyomi version

0.13.6

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2022-08-19 03:27
Duplicate of #13040

**Closed by Seishirou101** 2022-08-19 03:27 UTC
Labels: Bug
