### ISSUE TITLE
Hatachi Manga (HachiRaw)

### ISSUE THREAD

**Issue by atuy1219** [tachiyomiorg/tachiyomi-extensions#16555] opened 2023-05-22 07:06 UTC
### Source information

Hatachi Manga 1.4.31

### Source language

Japanese

### Steps to reproduce

Search through the search section of the library.

### Expected behavior

Search results are displayed.

### Actual behavior

It says "Already on the Last Page!"

### Tachiyomi version

0.14.6

### Android version

Android13

### Other details

![Screenshot_20230522-160536](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/130917473/f34e1fef-6cf8-4b95-913b-db5a576a686a)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by DchanN** [comment] 2023-05-22 16:49
Duplicate of #15618 ,  domain change with new theme (MangaRaw theme) https://github.com/tachiyomiorg/tachiyomi-extensions/issues/15618#issuecomment-1484168470 , contributor said Might as well replace this extension with a new one. and become source request instead Bug ( https://github.com/tachiyomiorg/tachiyomi-extensions/issues/15618#issuecomment-1500499634 )

**Closed** 2023-12-02 15:41 UTC
Labels: Bug, Source is down
