### ISSUE TITLE
Manga-TR chapters not open

### ISSUE THREAD

**Issue by Kingsama13** [tachiyomiorg/tachiyomi-extensions#19268] opened 2023-12-11 00:30 UTC
### Source information

Manga-TR 1.49

### Source language

Turkish

### Steps to reproduce

1-Manga-TR  open
2-Try to open any mangapage 
3-not loading error

### Expected behavior

pages need to be loaded

### Actual behavior

pages not loading

### Tachiyomi version

0.14.7

### Android version

12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2023-12-11 15:06
Duplicate of #16013

**Closed by vetleledaal** 2023-12-11 15:06 UTC
Labels: Bug
