### ISSUE TITLE
Java.lang Exception: Failed to bypass Cloudflare in MangaOwl

### ISSUE THREAD

**Issue by ByChrsM** [tachiyomiorg/tachiyomi-extensions#9255] opened 2021-09-27 06:12 UTC
### Source information

Mangaowl 1.2.22

### Steps to reproduce

I always using Mangaowl extension for read several manga. I open it and it always running well. But a month ago I always get troubled about Java.lang Exception: Failed to bypass Cloudflare.
I tried the troubleshooting guide but nothing happens.

### Expected behavior

When I updated manga in my library all new chapters has shown.
I can browse any manga too in Mangaowl extension.

### Actual behavior

But when I tried to read the chapters it's always Java.lang Exception: Failed to bypass Cloudflare.

### Tachiyomi version

0.12.2

### Android version

Android 6

### Other details

![Screenshot_20210924-194013](https://user-images.githubusercontent.com/91451128/134853735-9a016c20-332b-47f7-878e-f403c2f3224e.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by FourTOne5** [comment] 2021-09-27 08:53
If the troubleshoot doesn't fix it the only thing you can do is use another source.

**Comment by arkon** [comment] 2021-10-02 16:31
Duplicate of #8456

**Closed by arkon** 2021-10-02 16:31 UTC
Labels: Bug
