### ISSUE TITLE
LegionAsia

### ISSUE THREAD

**Issue by Asura0818** [tachiyomiorg/tachiyomi-extensions#8162] opened 2021-07-17 23:38 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

LegionAsia

### Source link

https://legionasia.com/

### Language

Spanish (Es)

### Other details

Adjunto logo de la fuente
![Logo - LegionAsia](https://user-images.githubusercontent.com/87270586/126051580-df69c689-7856-4660-91f4-9e0ab44f4d97.png)

**Comment by alessandrojean** [comment] 2021-07-17 23:40
Duplicate of #7420.

**Closed by alessandrojean** 2021-07-17 23:40 UTC
Labels: Source request
