### ISSUE TITLE
[Bug] Leviatan Scans: Unable to open Manhua

### ISSUE THREAD

**Issue by kenshin657** [tachiyomiorg/tachiyomi-extensions#8290] opened 2021-07-27 02:15 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android  11 (Oxygen OS)

### Source information

Leviatan Scans 1.2.12

### Steps to reproduce

1. Open Leviatan Scans Extension
2. Select a Manhua to read

### Expected behavior

Manhua should open with no issues. User is able to see and read chapters from extension.

### Actual behavior

When Manhua is opened a Toast Notification pops up showing
`For input string:""`

![Screenshot_20210727-095840](https://user-images.githubusercontent.com/41324650/127083722-24edf52a-7448-48d0-80eb-c2ae44d31c8c.jpg)

### Other details

I already tried clearing chapter cache, cookies, and database. Changing DNS over HTTPS did change the results. Using a VPN did not change anything.

Webview is working fine.

Opening Manhwa works correctly.

![Screenshot_20210727-100903](https://user-images.githubusercontent.com/41324650/127084230-b2509189-c05d-4ace-bc69-dbf945a086ae.jpg)

**Comment by Paladawn** [comment] 2021-07-27 07:20
God of Deception,
The Blade of Evolution Walking Alone In The Dungeon,
Craftsman,
Lord of Catastrophe,
Throne of the Dragon King,
Martial God Asura

These are all bilibili comics, you can find these on the bilibilicomics extension. they are an official translation team (they work on martial god asura, haven't checked what other ones they do)

**Comment by alessandrojean** [comment] 2021-07-27 19:33
Duplicate of #7992

**Closed by alessandrojean** 2021-07-27 19:33 UTC
Labels: Bug
