### ISSUE TITLE
Queen scan not working 

### ISSUE THREAD

**Issue by Hawksaran** [tachiyomiorg/tachiyomi-extensions#17689] opened 2023-08-26 17:12 UTC
### Source information

Queen Scans 1.4.26

### Source language

English 

### Steps to reproduce

Suddenly not working and it seems the domain is changed 
/ To fairymanga.com
![Screenshot_2023-08-26-22-40-56-57_79aa9bf7c61e266c5f841e42245e214b](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/132247482/7c32a5de-22c6-444f-96c6-902f7cb2df06)

### Expected behavior

Usually chapter shown

### Actual behavior

Now http 404 error

### Tachiyomi version

R6019

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment] 2023-08-26 17:34
duplicate of #17620

**Closed** 2023-08-26 17:38 UTC
Labels: Bug
