### ISSUE TITLE
Madaradex: Pages do not load

### ISSUE THREAD

**Issue by kingmj2000** [tachiyomiorg/tachiyomi-extensions#9449] opened 2021-10-12 09:41 UTC
### Source information

Madaradex 1.2.14

### Steps to reproduce

1. Open any manga from madaradex
2. Click on the chapter or download
3. If reading, then no page load shows "retry", and if downloaing then download doesn't start.

### Expected behavior

If click on chapter, then the chapter should parse images and should be available for reading.
If download, then download should pr9gress until eventually it is completed.

### Actual behavior

During reading any chapter, keep getting "retry"
During download, the download doesn't start

### Tachiyomi version

0.12.3

### Android version

Android 11

### Other details

https://user-images.githubusercontent.com/91054160/136932015-0f495456-4a82-4615-ad1d-4dd72fd06bcb.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment] 2021-11-10 06:53
Related PR fix was [closed](https://github.com/tachiyomiorg/tachiyomi-extensions/pull/9313)

**Comment by kingmj2000** [comment] 2021-11-24 19:42
I wonder, if anyone is ever gonna try to solve this issue soon😞😞😞

**Comment by kingmj2000** [comment] 2021-11-24 19:44
madaradex, is the one for all the need you would ever need for manga, manhwa or manhua, bit it just doesn't work roght in tachiyomi. I just hope the developers can find some way around it soon.

**Comment by gan-of-culture** [comment] 2022-02-23 13:36
I am having the same issue. Unfortunately the PR was closed with no explanation.

**Comment by jferdous70** [comment] 2022-02-23 13:39
You can open another PR with the exact changes as the closed one https://github.com/tachiyomiorg/tachiyomi-extensions/pull/9313

**Comment by CarlosEsco** [comment] 2022-02-23 13:42
@nar1n white list a normal UA and it will be merged

**Comment by quangkieu** [comment] 2022-03-13 09:48
Hey @CarlosEsco i could not find the pull request you are mentioning

**Comment by FourTOne5** [comment] 2022-03-13 10:06
> Hey @CarlosEsco i could not find the pull request you are mentioning

#9313 the whitelisted UA is not something that's gonna get merged.

**Comment by VespasianGod** [comment] 2022-04-18 12:36
Anyone know how to fix this?

**Comment by gan-of-culture** [comment] 2022-04-18 12:43
> Anyone know how to fix this?

We cannot fix this. The owner of the website has to change the whitelisted User-Agent to something else, since the proposed change was declined by the tachiyomi maintainers.

**Comment by CrepeTF** [comment] 2022-04-18 13:01
/lock since the issue is known already

**Comment by arkon** [comment] 2023-05-26 21:14
In an effort to have a more manageable issue backlog, we're closing older requests that weren't addressed since there's a low chance of it being addressed if it hasn't already. If your request is still relevant, please [open a new request](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).

**Closed by arkon** 2023-05-26 21:14 UTC
Labels: Bug
