### ISSUE TITLE
Manga-TR image problem

### ISSUE THREAD

**Issue by conveyorBeltOverlord** [tachiyomiorg/tachiyomi-extensions#16299] opened 2023-05-04 05:54 UTC
### Source information

Manga-TR 1.4.9

### Source language

Turkish

### Steps to reproduce

Try reading any manga from Manga-TR
![Screenshot_20230504-084938_Tachiyomi](https://user-images.githubusercontent.com/100721282/236121990-f6a4f156-fa5f-4d9a-9b48-b11f0e17c285.jpg)

(don't care about vpn, i'm at school right now and i am doing this to use school internet. The same problem happens when I'm at home.)

### Expected behavior

Chapters can be seen and readable

### Actual behavior

This happened instead

![Screenshot_20230504-085323_Tachiyomi](https://user-images.githubusercontent.com/100721282/236122149-253117c9-d275-4937-8dd5-5fee19f3e22b.jpg)

(don't care about vpn, i'm at school right now and i am doing this to use school internet. The same problem happens when I'm at home.)

### Tachiyomi version

0.14.6

### Android version

Android 8.0.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment] 2023-07-25 12:41
Duplicate of #16013

**Closed by stevenyomi** 2023-07-25 12:41 UTC
Labels: Bug
