### ISSUE TITLE
Yugen Mangas - not working

### ISSUE THREAD

**Issue by gatinhecomunista** [tachiyomiorg/tachiyomi-extensions#19078] opened 2023-11-23 00:51 UTC
### Source information

Yugen Mangas - Português

### Source language

Português

### Steps to reproduce

The URL was changed this week, but the app is not working. I've already checked that the exchange was informed and apparently made, but it still doesn't work for me. I open the application and all the works have errors, I open the source and it is empty

### Expected behavior

May the works appear and I can read

### Actual behavior

Empty gallery, gives error when updating, it's just not working

### Tachiyomi version

0.14.7

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2023-11-23 05:00
Duplicate of #19030

**Closed by alessandrojean** 2023-11-23 05:00 UTC
Labels: Bug
