### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by mopoi90** [tachiyomiorg/tachiyomi-extensions#12090] opened 2022-06-06 00:26 UTC
### Source information

mangaswat 1.3.21

### Steps to reproduce

It always says "no page found " when l try to read any chapter at any manga .
It was working perfectly well 4 days ago but suddenly this issue started. 

### Expected behavior

When l want to read a new chapter , l click on it and start to read

### Actual behavior

When l want to read a new chapter , l click on it and  a message says  "no page found " when l try to read any chapter at any manga .

### Tachiyomi version

last version

### Android version

8.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-06-06 00:36
Duplicate of #10318

**Closed by arkon** 2022-06-06 00:36 UTC
Labels: Bug
