### ISSUE TITLE
The extension is down 

### ISSUE THREAD

**Issue by Credits125** [tachiyomiorg/tachiyomi-extensions#15805] opened 2023-03-23 06:25 UTC
### Source information and language

Simply hentai (spanish)

### Steps to reproduce

Does not load the content of the page, the extension is totally down 😔

### Expected behavior

It does not work 

### Actual behavior

The extension does not work.

### Tachiyomi version

1.4.6

### Android version

Android 13

### Other details

It does not work

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2023-03-23 06:29
Duplicate of #11617 probably

**Closed by Seishirou101** 2023-03-23 06:29 UTC
Labels: Bug
