### ISSUE TITLE
MangaMX

### ISSUE THREAD

**Issue by andysan02** [tachiyomiorg/tachiyomi-extensions#14504] opened 2022-12-09 08:39 UTC
### Source information and language

MangaMx Español 1.3.13

### Source new URL

https://manga-oni.com/

### Other details

MangaMx cambió de URL y nombre a MangaOni

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2022-12-11 01:40
Duplicate of #14227

**Closed by vetleledaal** 2022-12-11 01:40 UTC
Labels: Bug, Domain changed
