### ISSUE TITLE
[Source Request] <manga-raw.club> 

### ISSUE THREAD

**Issue by Xanaxus** [tachiyomiorg/tachiyomi-extensions#5614] opened 2021-02-01 15:06 UTC
## Source website
- Name: manga-raw.club
- Link: https://www.manga-raw.club/
- Language(s): English

## Other details
there is a similar extension but it's a different site

**Comment by scb261** [comment] 2021-02-01 22:15
Duplicate of #3754

**Closed by scb261** 2021-02-01 22:15 UTC
Labels: Source Request
