### ISSUE TITLE
Zahard extension not working

### ISSUE THREAD

**Issue by MrPerfectGamer** [tachiyomiorg/tachiyomi-extensions#16029] opened 2023-04-11 10:51 UTC
### Source information

Zahard 1.4.7

### Source language

English

### Steps to reproduce

On opening zahard, no content is shown.
![Screenshot_20230411_144945_TachiyomiSY](https://user-images.githubusercontent.com/130457499/231138276-25149f61-3e96-41f7-b7c4-1a45a39cb4da.jpg)
HTTP Error 404 is shown.
![Screenshot_20230411_161726_TachiyomiSY](https://user-images.githubusercontent.com/130457499/231138410-0eb58857-91a4-4069-b9f6-643d4e8d4e2b.jpg)

### Expected behavior

Contents should have been fetched and shown.

### Actual behavior

No content is shown.

### Tachiyomi version

0.14.5

### Android version

Android 11

### Other details

Zahard Domain has changed to https://zahard.xyz/.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by scb261** [comment] 2023-04-11 11:53
Duplicate of #13491

**Closed by scb261** 2023-04-11 11:53 UTC
Labels: Bug
