### ISSUE TITLE
Add New Tracking Source

### ISSUE THREAD

**Issue by bgmondy** [tachiyomiorg/tachiyomi-extensions#11166] opened 2022-03-18 11:55 UTC
### Describe why this should be added

![Screenshot_2022-03-18-18-46-33-56](https://user-images.githubusercontent.com/76152689/158997872-fc15943c-91b1-4229-a4b5-d261219517e4.png)
1. open setting
2. klik tracking
![Uploading IMG_20220318_185006.jpg…]()
1. open anything comic
2. klik that circle

### Other details

![Screenshot_2022-03-18-18-41-45-06](https://user-images.githubusercontent.com/76152689/158998640-a9bfcf78-d3a9-4c0e-8486-57de6107455b.png)
Please add new tracking source " https://www.anime-planet.com/ ". You know some comic weren't found in any of the tracking databases.
![Uploading Screenshot_2022-03-18-18-47-14-03.png…]()
like that
![Uploading Screenshot_2022-03-18-18-47-22-18.png…]()

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by bgmondy** [comment] 2022-03-18 12:13
![IMG_20220318_185006](https://user-images.githubusercontent.com/76152689/159000836-2908668a-08a6-49b3-9326-c8fee3126fca.jpg)
you can use like that
1. open any comic
3. klik the circle sign

**Comment by bgmondy** [comment] 2022-03-18 12:14
![Screenshot_2022-03-18-18-47-22-18](https://user-images.githubusercontent.com/76152689/159001136-340215a5-9366-419a-8b46-b95098696f12.png)
but not found

**Comment by arkon** [comment] 2022-03-18 12:26
Wrong repo and duplicate of https://github.com/tachiyomiorg/tachiyomi/issues/1785

**Closed by arkon** 2022-03-18 12:26 UTC
Labels: Meta request
