### ISSUE TITLE
MangaHub: Incomplete images/pages in chapter and Fix broken page images of chapter

### ISSUE THREAD

**Issue by PheonixGamer09** [tachiyomiorg/tachiyomi-extensions#15796] opened 2023-03-22 06:16 UTC
### Source information and language

Mangahub 1.4.27(English)

### Steps to reproduce

1. Read manga/manhwa chapter from the app and the chapter has incomplete chapter images/pages.
2. Check the chapter in the website it has complete images/pages.
3. Check another manga title, also have incomplete image/pages.
4. When app opened and click on any manga chapter page images are not loaded.
5. In a chapter 2-3 pages shows "Image couldn't be loaded" and rest are clearly shown.
6. Pages shows "Image couldn't be loaded".
7. Read any new chapters of manga/manhwa it shows "No Pages Found".

### Expected behavior

1. It should have all pages/images exactly the same as the website.
2. All pages images should have uploaded properly.

### Actual behavior

1. The app only have 2-3 of the pages/images count from the website while the rest of the pages/images are missing.
2. It shows image couldn't be loaded.
3. It also shows no pages found

### Tachiyomi version

0.14.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by mobi2002** [comment] 2023-03-23 05:16
duplicate of #15684

**Closed** 2023-03-23 06:22 UTC
Labels: Bug
