### ISSUE TITLE
Manhua Plus still saying no pages found

### ISSUE THREAD

**Issue by Izunyaaan** [tachiyomiorg/tachiyomi-extensions#8861] opened 2021-08-26 17:29 UTC
### Source information

Manhua Plus 1.2.15

### Steps to reproduce

Open any title under manhua plus. Select a chapter and wait.

### Expected behavior

Chapter load as usual.

### Actual behavior

No pages found toast shows up.

### Tachiyomi version

0.12.1

### Android version

Android 10

### Other details

Occured and reported and Closed #8702 via #8854.
Still same fix uninstall and reinstall the extension. Not really sure what causes it to happen.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Clouddark75** [comment] 2021-08-28 16:31
Can you be more specific about "which" titles? After the fix, the Mangas "new" chapters on the site load just fine. And I just tested it with recent some Mangas that was updated in the following hours and they load just fine on my side.

**Comment by Izunyaaan** [comment] 2021-08-28 19:50
When it happens all titles under manhua plus shows no pages even though chapters show up as usual.

When using webview though the pages are there

**Comment by Clouddark75** [comment] 2021-08-28 21:29
Before all the "new" chapters since last week couldn't be seen because they update the tag selectors and I updated them to the new ones. I have been checking at random times to see if I can duplicate the problem, but everything loads just fine as it should (tested with different devices). 

Try to clean your cookies and cache.

**Comment by Quicksilver08** [comment] 2021-08-29 15:44
Titles load fine but when you click on chapter it says no pages found

**Comment by Clouddark75** [comment] 2021-08-29 21:13
> Titles load fine but when you click on chapter it says no pages found

That's what I'm saying, you couldn't read them because they updated the tags, and isn't the fitst time they do it, tho'. Do you keep having the same behavior yet? I have checked for a couple days now and is working as intended. The only thing that come to my mind is an isolated situation for you at this point.

**Comment by Izunyaaan** [comment] 2021-08-30 00:01
> > Titles load fine but when you click on chapter it says no pages found
> 
> That's what I'm saying, you couldn't read them because they updated the tags, and isn't the fitst time they do it, tho'. Do you keep having the same behavior yet? I have checked for a couple days now and is working as intended. The only thing that come to my mind is an isolated situation for you at this point.

Ok, I just force stopped tachiyomi and started it again and when I open a title, martial peak for example, I see all the chapters just fine. Older chapters load just fine but newer ones say no pages found.

I have both manhua plus 1.2.15 and madara (multiple sources) obsolete 1.2.180 installed.

This is probly whats causing this bug?

**Comment by logix10** [comment] 2021-08-30 16:13
I am also having the same issue
When i update the library the new chapters appear for me but i can't open or download them it says "no pages found"
This had been going for around a week now
Tachiyomi and manhua plus extension are up to date i tried to clear cache and cookies but it doesn't help.
I hope it will be fixed soon

**Comment by Clouddark75** [comment] 2021-08-31 01:32
> > > Titles load fine but when you click on chapter it says no pages found
> > 
> > 
> > That's what I'm saying, you couldn't read them because they updated the tags, and isn't the fitst time they do it, tho'. Do you keep having the same behavior yet? I have checked for a couple days now and is working as intended. The only thing that come to my mind is an isolated situation for you at this point.
> 
> Ok, I just force stopped tachiyomi and started it again and when I open a title, martial peak for example, I see all the chapters just fine. Older chapters load just fine but newer ones say no pages found.
> 
> I have both manhua plus 1.2.15 and madara (multiple sources) obsolete 1.2.180 installed.
> 
> This is probly whats causing this bug?

You see? Now we talking. The new one won't work right if you have a deprecated version of Madara, because Tachi will load the old one, that's the reason that when you do reinstall it, it does starts working. So when you restart or open Tachi again, it will load the old version from MS Madara extension.

**Comment by Izunyaaan** [comment] 2021-08-31 16:26
Alright, confirmed that having the obsolete extensions was causing the
trouble. It was painful but removing it and installing all the extensions
manually does the trick. Not looking forward to the 60+ extension updates
every week or so xD.
Thank you

**Comment by logix10** [comment] 2021-08-31 17:04
Deleting the madara extension fixed the issue for me as well.
Thank you all

**Comment by Clouddark75** [comment] 2021-08-31 18:19
> Alright, confirmed that having the obsolete extensions was causing the trouble. It was painful but removing it and installing all the extensions manually does the trick. Not looking forward to the 60+ extension updates every week or so xD. Thank you

You're welcome. Just remember that any little info counts!

This ticket can be closed.

**Closed** 2021-08-31 18:26 UTC
Labels: Bug
