### ISSUE TITLE
No pages found 

### ISSUE THREAD

**Issue by MoXerous** [tachiyomiorg/tachiyomi-extensions#12132] opened 2022-06-09 03:24 UTC
### Source information

MangaSwat 1.3.21

### Steps to reproduce

When I opened a chapter for one of the webtoon on the MangaSwat extensionion the app continues to tell me that "No pages found" then I opened the site from Google and I opened the same webtoon And I found that there were pages.

### Expected behavior

There are pages, so the chapters must open.

### Actual behavior

There's no chapter of MangaSwat extensionion works

### Tachiyomi version

0.13.4

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Saud-97** [comment] 2022-06-09 03:25
Duplicate of https://github.com/tachiyomiorg/tachiyomi-extensions/issues/10318

**Closed** 2022-06-09 03:26 UTC
Labels: Bug
