### ISSUE TITLE
Reaper scans

### ISSUE THREAD

**Issue by Akashi123-deep** [tachiyomiorg/tachiyomi-extensions#13438] opened 2022-09-11 12:43 UTC
### Source information and language

Reaper scans 1.3.30 ( English )

### Steps to reproduce

![Screenshot_20220911-134133_Tachiyomi](https://user-images.githubusercontent.com/102795903/189528108-58796809-ff5b-4c61-82e8-1719eaaff902.jpg)

### Expected behavior

![Uploading Screenshot_20220911-134133_Tachiyomi.jpg…]()

### Actual behavior

![Uploading Screenshot_20220911-134133_Tachiyomi.jpg…]()

### Tachiyomi version

0.13.6

### Android version

10

### Other details

![Uploading Screenshot_20220911-134133_Tachiyomi.jpg…]()

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-09-11 12:48
Reaper is under maintenance for a few days. HTTP error 5xx are server side errors we can't fix in the extension side too.

Duplicate of #13410

**Closed by alessandrojean** 2022-09-11 12:48 UTC
Labels: Bug
