### ISSUE TITLE
I can't open my mangarolls extension

### ISSUE THREAD

**Issue by Fein-x** [tachiyomiorg/tachiyomi-extensions#18645] opened 2023-10-21 14:00 UTC
### Source information

MangaRolls

### Source language

English

### Steps to reproduce

1. I go to the browse section
2. I click on mangarolls
3. ![Screenshot_20231021_122657_TachiyomiJ2K](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/148632500/3d6bd92e-f9eb-4d5b-bb3e-6e5e9cbf464b)
And I got greeted by that

### Expected behavior

It should've open just fine 

### Actual behavior

It says that "no address associated with host name"

### Tachiyomi version

App version: 1.7.1

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by KirinRaikage** [comment] 2023-10-21 18:01
Duplicate of #18625

**Closed** 2023-10-21 18:05 UTC
Labels: Bug
