### ISSUE TITLE
Mangadex: content rating not respected

### ISSUE THREAD

**Issue by mobi2002** [tachiyomiorg/tachiyomi-extensions#14045] opened 2022-10-30 15:00 UTC
### Source information and language

Mangadex 1.3.172

### Steps to reproduce

0. Enable all the content filters in extension settings.
1. Open the extension browse.
2. Search for title with pornographic rating.

### Expected behavior

The search result should contain that title

### Actual behavior

It doesn't include that title

### Tachiyomi version

0.14.1

### Android version

Android 12

### Other details

1. It works fine from the global search screen.

2.1. if I enable the content filter in browse>mangadex>filter and apply 
2.2. then disable the filter again from there
2.3. it starts working

3. I also tested this in 0.13.6 and it works fine there, with the latest version of the extension.
So I am unsure if this issue should be reported in the app repo or not...

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-10-30 15:05
I would guess it's probably something related to the app not applying the filters, but I can't reproduce. There's a few things you may try:

- Make a backup and reinstall the app (sometimes the APK gets corrupted and cause these weird behaviours)
- Enable the erotica and pornographic content rating in the Mangadex extension settings to it apply automatically to all searches.

**Comment by mobi2002** [comment] 2022-10-30 15:08
Alright, will try with a fresh install

**Comment by alessandrojean** [comment] 2022-10-30 15:09
Managed to reproduce with latest Preview now, will try to narrow down what's causing the issue 👍🏻

**Comment by alessandrojean** [comment] 2022-10-30 15:40
Opened an issue in the app repository, indeed something that needs to be fixed in the app. In the meanwhile, a temporary fix for the MangaDex extension was submitted.

See tachiyomiorg/tachiyomi#8364.

**Closed** 2022-10-30 15:47 UTC
Labels: Bug
