### ISSUE TITLE
Multporn: No chapters found

### ISSUE THREAD

**Issue by Marshfellow2** [tachiyomiorg/tachiyomi-extensions#15005] opened 2023-01-18 01:11 UTC
### Source information and language

Multporn 1.3.3 (English)

### Steps to reproduce

1. Search for a comic (or author)
2. Can't find comic

### Expected behavior

The comic (or series of comics) should be there

### Actual behavior

A screen of "No results found" appears 

### Tachiyomi version

0.14.3-5452

### Android version

Android 12

### Other details

When entering the "Recent" page, every other recent comic appears

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment] 2023-01-18 04:14
Duplicate of #8069

**Closed by stevenyomi** 2023-01-18 04:14 UTC
Labels: Bug
