### ISSUE TITLE
NineAnime extension problem 

### ISSUE THREAD

**Issue by Notim2461** [tachiyomiorg/tachiyomi-extensions#13322] opened 2022-09-02 15:11 UTC
### Source information and language

NineAnime EN V 1.2.3

### Steps to reproduce

I try opening up a manga that I'm reading and then I get the all_imgsurl not found pop up

### Expected behavior

Should load right into the manga

### Actual behavior

Instead a pop up appears saying all_imgsurl not found 

### Tachiyomi version

0.13.6

### Android version

Android 12

### Other details

All the information I have is what is written above in the other sections.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-09-02 18:50
Duplicate of #13315

**Closed by alessandrojean** 2022-09-02 18:50 UTC
Labels: Bug
