### ISSUE TITLE
WNACG extension requires update.

### ISSUE THREAD

**Issue by tatular** [tachiyomiorg/tachiyomi-extensions#9124] opened 2021-09-19 03:02 UTC
### Source information

WNACG 1.2.5

### Steps to reproduce

Some of the mangas in the wnacg web are not searchable using Tachiyomi wnacg extension.

### Expected behavior

All manga can be search using the extension.

### Actual behavior

Some of the mangas are not searchable using the extension.

### Tachiyomi version

0.12.2

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2021-09-19 03:03
Duplicate of #7828

**Closed** 2021-09-19 03:03 UTC
Labels: Bug
