### ISSUE TITLE
Olympus scanlation

### ISSUE THREAD

**Issue by Hayashi13q4** [tachiyomiorg/tachiyomi-extensions#15541] opened 2023-03-01 20:51 UTC
### Source information and language

Olympus scanlation 1.4.28 (español)

### Steps to reproduce

the extension no longer works, it has been changed. 

### Expected behavior

The manhwa should be updated but it doesn't

### Actual behavior

You cannot enter the extension and when you open the webview it redirects you to another page that would be the new extension but in tachiyomi it does not appear

### Tachiyomi version

0.14.5

### Android version

Android 13

### Other details

![Screenshot_20230301_145107_Tachiyomi](https://user-images.githubusercontent.com/109044821/222262212-c5749374-8cda-4a01-aba1-e150a1239a9e.jpg)
![Screenshot_20230301_145114_Tachiyomi](https://user-images.githubusercontent.com/109044821/222262224-5ae2fa9f-318d-425f-8673-267a7ea5e341.jpg)
`
![Uploading Screenshot_20230301_145122_Tachiyomi.jpg…]()
`

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2023-03-01 20:52
Duplicate of #15330

**Closed by Seishirou101** 2023-03-01 20:52 UTC
Labels: Bug
