### ISSUE TITLE
Inarimanga: Changed their domain

### ISSUE THREAD

**Issue by Suiren5** [tachiyomiorg/tachiyomi-extensions#13878] opened 2022-10-16 16:12 UTC
### Source information and language

InariManga 1.3.21

### Source new URL

https://inarimanga.com/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by suyash01** [comment] 2022-10-20 22:56
Loks like the URL is correct(opening in webview), but the website has been moved to another theme called Inarimace(could be custom).

**Comment by Suiren5** [comment] 2022-10-21 05:04
> Parece que la URL es correcta (se abre en la vista web), pero el sitio web se ha movido a otro tema llamado Inarimace (podría ser personalizado).

¿Se puede modificar en tachiyomi para que funcione?

**Comment by Clouddark75** [comment] 2022-10-23 00:45
Madara theme with some modifications.

**Comment by vetleledaal** [comment] 2022-11-28 22:22
Duplicate of #13752

**Closed by vetleledaal** 2022-11-28 22:22 UTC
Labels: Bug, Factory source, Domain changed
