### ISSUE TITLE
Mangafreak extension shows "No chapters found" on all of the mangas

### ISSUE THREAD

**Issue by Lickitahm** [tachiyomiorg/tachiyomi-extensions#8442] opened 2021-08-07 14:54 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.12.1

### Android version

Android 10

### Source information

Mangafreak 1.2.3

### Steps to reproduce

1. Downloaded Tachiyomi on my new tablet
2. Downloaded mangafreak extension
3. None of the series show any chapters 

### Expected behavior

There should be chapters for all the series as it works on my phone

### Actual behavior

All the series are empty

**Comment by arkon** [comment] 2021-08-07 14:55
Duplicate of #8182

**Closed by arkon** 2021-08-07 14:55 UTC
Labels: Bug
