### ISSUE TITLE
مانجا فليكس :The chapter number does not appear

### ISSUE THREAD

**Issue by yemenihandsome** [tachiyomiorg/tachiyomi-extensions#12733] opened 2022-07-25 14:58 UTC
### Source information and language

مانجا فليكس 1.3.23

### Steps to reproduce

1. Log in to the source
2. manga selection
3. The class date appears, but the number of the number does not appear

### Expected behavior

The chapter number and date should appear

### Actual behavior

The chapter number does not appear, only the date

### Tachiyomi version

0.13.5

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2022-07-25 16:42
Duplicate of #12716

**Closed by vetleledaal** 2022-07-25 16:42 UTC
Labels: Bug
