### ISSUE TITLE
Manhwaland.mom

### ISSUE THREAD

**Issue by kell20** [tachiyomiorg/tachiyomi-extensions#12621] opened 2022-07-18 16:18 UTC
### Source name

Manhwaland

### Source link

https://manhwaland.mom/

### Language

Indonesian 

### Other details

😐aaaa hope it's added 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment] 2022-07-18 23:47
Duplicate of #11540

**Comment by arkon** [comment] 2022-07-18 23:49
They look like different websites.

**Comment by TheKingTermux** [comment] 2022-07-18 23:59
> different websites.

Idk maybe the backup websites ?
I think they have 2 server
But it seem pretty similar to #11540 but the Logo's of the website is missing

**Comment by vetleledaal** [comment] 2022-07-19 00:54
This and #11540 both use the same image host, but the .pw domain appears to lack updates since March.

Uses WPMangaReader theme.

**Comment by kell20** [comment] 2022-08-18 13:25
when was it added

**Comment by vetleledaal** [comment] 2022-08-18 17:34
When someone wants to work on it. There's no ETA

**Comment by TheKingTermux** [comment] 2022-08-18 23:27
> when was it added 

I'm working for it
Just wait when I'm done dealing and testing with it

**Comment by kell20** [comment] 2022-08-19 02:02
> > kapan ditambahkan
> 
> Saya sedang mengerjakannya Tunggu saja ketika saya selesai berurusan dan mengujinya

ok i will wait for it

**Comment by kell20** [comment] 2022-08-19 02:03
Can the deleted extension be added again?

**Comment by TheKingTermux** [comment] 2022-08-19 05:35
> Can the deleted extension be added again?

I think no

**Comment by kell20** [comment] 2022-08-20 07:37
can't you add manhwaland?

**Comment by kell20** [comment] 2022-08-20 07:40
> > kapan ditambahkan
> 
> Saya sedang mengerjakannya Tunggu saja ketika saya selesai berurusan dan mengujinya

Did manhwaland test fail

**Comment by TheKingTermux** [comment] 2022-08-20 08:28
> Did manhwaland test fail 

Yeah it did
But i still try for sure

**Comment by kell20** [comment] 2022-08-20 09:15
> > Apakah tes manhwaland gagal?
> 
> Ya itu Tapi saya masih mencoba pasti

if it fails, then add the manhwadesu extension bro😅

**Comment by kell20** [comment] 2022-08-20 09:16
> > > Apakah tes manhwaland gagal?
> > 
> > 
> > Ya itu Tapi saya masih mencoba pasti
> 
> jika gagal, maka tambahkan ekstensi manhwadesu bro😅

If it keeps failing

**Closed** 2022-08-20 20:38 UTC
Labels: Source request, Factory source

**Comment by kell20** [comment] 2022-08-20 23:54
> > Apakah tes manhwaland gagal?
> 
> Ya itu Tapi saya masih mencoba pasti

Ok thanks for adding the extension bro
And it's time to read nsfw🤤

**Comment by TheKingTermux** [comment] 2022-08-21 08:38
> Ok thanks for adding the extension bro
> And it's time to read nsfw🤤

Haha 🤣
Thanks for telling me too 😂

**Comment by kell20** [comment] 2022-08-21 11:29
> > Ok terima kasih telah menambahkan ekstensi bro 
> > Dan saatnya membaca nsfw🤤
> 
> Ha ha🤣 Terima kasih sudah memberitahuku juga😂

![Screenshot_2022_0821_182646](https://user-images.githubusercontent.com/101073177/185788792-7cf5b2bb-6182-4954-a0a7-2ffaf6a13448.jpg)
This is the content of the extension, a little bro

**Comment by TheKingTermux** [comment] 2022-08-21 15:05
> This is the content of the extension, a little bro

Uhhh idk why it happen
In my test it load perfecly

**Comment by kell20** [comment] 2022-08-21 15:50
> > Ini dia isi extensionnya gan
> 
> Uhhh idk mengapa itu terjadi Dalam pengujian saya memuat dengan sempurna

I don't know if I'm just a fan of extensions

**Comment by kell20** [comment] 2022-08-21 15:51
> > Ini dia isi extensionnya gan
> 
> Uhhh idk mengapa itu terjadi Dalam pengujian saya memuat dengan sempurna

Will it be fixed?

**Comment by TheKingTermux** [comment] 2022-08-21 22:38
> Will it be fixed? 

Just create a new Issues
And attach evidence in the issue with detailed information

**Comment by kell20** [comment] 2022-08-22 09:13
> > Apakah akan diperbaiki?
> 
> Buat saja Masalah baru Dan lampirkan bukti dalam masalah dengan informasi terperinci

Manhwaland error 404
