### ISSUE TITLE
MangaHub: Uploaded incomplete chapters

### ISSUE THREAD

**Issue by TysonBlaze009** [tachiyomiorg/tachiyomi-extensions#15188] opened 2023-01-31 02:17 UTC
### Source information and language

Mangahub 1.3.23(English) 

### Steps to reproduce

1. Manga and Manhwa chapters are incomplete.
2. It only shows 6 pages in chapters.
3. It is happening after MangaHub extension new update.
4. Other extensions shows proper completed chapter.

### Expected behavior

It should have completed chapters of manga and Manhwa.

### Actual behavior

It only showing 6 pages after new update of MangaHub extension.

### Tachiyomi version

0.14.3

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-01-31 03:58
Duplicate of #15186

**Closed by arkon** 2023-01-31 03:58 UTC
Labels: Bug
