### ISSUE TITLE
[new filters] <filter by sources for library>

### ISSUE THREAD

**Issue by Unimatrix007** [tachiyomiorg/tachiyomi-extensions#6076] opened 2021-03-05 21:42 UTC
---

##  Why/Project's Benefit/Existing Problem

Hi,
I would like it if you could add a filter in the library section where we can filter our librarys to see which manga belong to which source and how many belong to which sources.
Im asking becouse right now i have close to 300 mangas\manhwas in my library. Some sources that i used are down or some sources like mangadex arent stable anymore. It is pretty frustrating to figure how many of my mangas belong to mangadex becouse i have to check all of them manualy, while if i had an option to filter them by source or just to divide\organize them by source. Well that would make my life easy and would allow me to better spread my library across multiple sources so that my chances of unstable sources with mangadex would be lessend. 

If you manage to implement this it would be awesome.

## Other Details
None that i can think of.

**Comment by CrepeTF** [comment] 2021-03-05 21:47
Won't repo,
Also you can filter to show manga from any source .
Read here:
https://github.com/tachiyomiorg/tachiyomi/issues/4469

**Comment by Unimatrix007** [comment] 2021-03-05 21:47
Adding the filter to one of these menus would be awesome
![Screenshot_20210305_224622_eu kanade tachiyomi](https://user-images.githubusercontent.com/79997908/110177140-c41aed00-7e04-11eb-8d5b-3fd7dbb6fcca.jpg)
![Screenshot_20210305_224616_eu kanade tachiyomi](https://user-images.githubusercontent.com/79997908/110177146-c54c1a00-7e04-11eb-95ed-ab3be6888108.jpg)

**Comment by Unimatrix007** [comment] 2021-03-05 22:00
Ohh so there is that way, wow i have like 117 items linked to mangadex. But that way is not efficient. I use a lot of extensions for sources and i cant remember tham all for a manual search. I still think that an dedicated filter that can be toogled on and off in menus would be better. Like when you want add a new manga and you search it trough all your sources, it should look like that but with only items from your library.

**Comment by scb261** [comment] 2021-03-05 22:15
1. Wrong repository.
1. If you want filter - use search by source name. If you want sort or categorize by source - duplicate of tachiyomiorg/tachiyomi#4560.
1. If you want to migrate from specific sources, just use `Browse > Migrate`.

**Closed by scb261** 2021-03-05 22:15 UTC
Labels: meta
