### ISSUE TITLE
Failed to bypass cloudflare

### ISSUE THREAD

**Issue by ifteqarahmed** [tachiyomiorg/tachiyomi-extensions#10581] opened 2022-01-26 07:25 UTC
### Source information

Toonily

### Steps to reproduce

Just go to the site it shows failed to bypass

### Expected behavior

Site should open

### Actual behavior

Site doesn't load

### Tachiyomi version

0.12.3

### Android version

12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-01-26 12:57
Duplicate of #5613

**Closed by arkon** 2022-01-26 12:57 UTC
Labels: Bug
