### ISSUE TITLE
Kumanga 

### ISSUE THREAD

**Issue by edmxn** [tachiyomiorg/tachiyomi-extensions#12919] opened 2022-08-09 19:37 UTC
### Source information and language

Kumanga 1.2.7 (Español)

### Steps to reproduce

1. Open the Kumanga extension

### Expected behavior

The manga on the Kumanga website should appear when you open it, just like any extension

### Actual behavior

The sleeves do not appear on the web, the following message is displayed
"Unexpected JSON token at offset 12: Expected EOF after parsing, but hadh instead"
File by attaching the screenshot below
I can't access the web content from WebView either, only from the normal browser.

### Tachiyomi version

0.13.5

### Android version

Android 12

### Other details

![Screenshot_20220809-034746_Tachiyomi](https://user-images.githubusercontent.com/101371218/183746138-fdb425b4-86f0-4603-8506-24e975e09eb9.jpg)
![Screenshot_20220809-034758_Tachiyomi](https://user-images.githubusercontent.com/101371218/183746144-7253acf2-c6c1-4a86-a097-6814dc0afa12.jpg)
![Screenshot_20220809-034838_Kiwi Browser](https://user-images.githubusercontent.com/101371218/183746149-0ed79e0d-2652-47d0-a757-7906aa93b190.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-08-09 19:39
Duplicate of #10414

**Closed by alessandrojean** 2022-08-09 19:39 UTC
Labels: Bug
