### ISSUE TITLE
Manhwas Men: HTTP error 404

### ISSUE THREAD

**Issue by Solovertical** [tachiyomiorg/tachiyomi-extensions#13870] opened 2022-10-16 02:35 UTC
### Source information and language

Manhwas Men 1.3.6

### Steps to reproduce

1.On opening the Extentsion
2.It's shows error
3.It didn't show anything 

### Expected behavior

It should open Normally and shows like others extensions 

### Actual behavior

It show error on showing manhwa
It should work Normally 
![Screenshot_2022-10-16-07-58-56-247_eu kanade tachiyomi](https://user-images.githubusercontent.com/109901807/196015090-498d24aa-8535-42d2-b0ff-8e0ca71c4a39.jpg)

### Tachiyomi version

Stable 0.13.6

### Android version

11

### Other details

Please Fix the Extention when you have time

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ff2400t** [comment] 2022-11-10 18:31
Duplicate of #13201

**Closed** 2022-11-10 18:36 UTC
Labels: Bug
