### ISSUE TITLE
[Bug] <Manhuascan>: <no pages found>

### ISSUE THREAD

**Issue by hdrhidari199** [tachiyomiorg/tachiyomi-extensions#7019] opened 2021-05-14 14:24 UTC
## Device information
- Tachiyomi version: 0.10.12
- Android version: 9

## Source information
- Name: Manhuascan
- Extension version: 1.2.4

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
The pages will be found even if I downloaded a  manga for offline read.. 

### Actual behavior
Can't download the manga since the pages aren't found..

**Comment by kedestin** [comment] 2021-05-14 14:26
Duplicate of #7011

**Comment by h-hyuuga** [comment] 2021-05-14 14:30
Duplicate of #7011

**Closed** 2021-05-14 14:37 UTC
Labels: bug
