### ISSUE TITLE
Toonily date issue

### ISSUE THREAD

**Issue by Pucut** [tachiyomiorg/tachiyomi-extensions#10788] opened 2022-02-11 00:18 UTC
### Source information

Toonily 1.2.20

### Steps to reproduce

Tachiyomi does not show the dates uploaded and when a new chapter from the extension is released, it is now included in updates below.

### Expected behavior

When a new chapter is released it should be included in the updates section.

### Actual behavior

I have to manually browse my library to see if a story gets updated in toonily

### Tachiyomi version

0.13.1

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2022-02-11 00:19
Duplicate of #10753

**Closed by Seishirou101** 2022-02-11 00:19 UTC
Labels: Bug
