### ISSUE TITLE
Too many request.

### ISSUE THREAD

**Issue by MusicWolf28** [tachiyomiorg/tachiyomi-extensions#14859] opened 2023-01-09 04:37 UTC
### Source information and language

1st Kiss (EN) 1.3.34

### Steps to reproduce

It begins the updating process
After some time it says 9 or 10 updates failed.
And says error 429.

### Expected behavior

Chapters updating and showing normally

### Actual behavior

HTTP error 429
  # 1st Kiss (EN)
    - My Wife is a Demon Queen
    - Of all things, I Became a Crow
    - Overgeared
    - Please Donâ€™t Come To The Villainessâ€™ Stationery Store!
    - Reality Quest
    - Taming Master
    - The Gamer
    - Today the Villainess has Fun Again
    - Trial Marriage Husband: Need to Work Hard

### Tachiyomi version

1.3.34

### Android version

Phone person 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2023-01-09 04:43
Duplicate of #14850

**Closed by alessandrojean** 2023-01-09 04:43 UTC
Labels: Bug
