### ISSUE TITLE
Toonily Search Issue in Tachiyomi

### ISSUE THREAD

**Issue by Alltothemoon123** [tachiyomiorg/tachiyomi-extensions#12977] opened 2022-08-13 23:27 UTC
### Source information and language

Toonily.com 1.3.31

### Steps to reproduce

1. Open Toonily source
2. Use search function
3. Shows "no results found" (Same happens when I use filters) 

### Expected behavior

Well, search and filters function should work as it should even though there are no problems. Do note that I always open in webview before I search for my desired titles and no problems there as I never have to bypass cloudflare. 

### Actual behavior

Always shows "no results found"

### Tachiyomi version

0.13.5

### Android version

Android 6

### Other details

Hope it gets fixed and thank you. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment] 2022-08-14 12:27
Duplicate of #12968

**Closed** 2022-08-14 12:41 UTC
Labels: Bug
