### ISSUE TITLE
Too many follow-up requests: 21

### ISSUE THREAD

**Issue by xEclipsee** [tachiyomiorg/tachiyomi-extensions#11986] opened 2022-05-26 15:12 UTC
### Source information

Neox Scanlator 1.2.33

### Steps to reproduce

Cant update the manga of the source

### Expected behavior

It should update the manga and new chapters

### Actual behavior

It doesn't update the manga and shows it's an error

### Tachiyomi version

0.13.4

### Android version

Android 12

### Other details

![Screenshot_20220526-120951_HTML Viewer](https://user-images.githubusercontent.com/106331873/170517404-b63d0af9-736f-4f70-886c-6b3a6f352571.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-05-26 15:56
Duplicate of #11953

>  I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open issue.

Please read what you acknowledge instead of just checking the boxes.

**Closed by alessandrojean** 2022-05-26 15:56 UTC
Labels: Bug
