### ISSUE TITLE
extension attempt to invoke

### ISSUE THREAD

**Issue by TachiApp** [tachiyomiorg/tachiyomi-extensions#12305] opened 2022-06-23 11:52 UTC
### Source information

manga swat 1.3.22

### Steps to reproduce

Enter to the tachiyomi application.
The choice of manhua of the same extension.
Choose a chapter and enter it.

### Expected behavior

![Screenshot_2022-06-23-12-41-17-299_eu kanade tachiyomi](https://user-images.githubusercontent.com/106177484/175291959-a12f2c13-b4d5-4bd0-aa49-cbda2e6e1c65.jpg)

### Actual behavior

![IMG_20220623_124427](https://user-images.githubusercontent.com/106177484/175291870-30433386-0247-40ae-bc40-3482b2bcf486.jpg)
attempt to invoke virtual metgod 'java.lang.String
org.jaoup nodes.elements.data()' on  a null object refrence

### Tachiyomi version

0.13.4

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by zbue** [comment] 2022-06-24 10:51
Duplicate of https://github.com/tachiyomiorg/tachiyomi-extensions/issues/12183

**Closed** 2022-06-24 11:15 UTC
Labels: Bug
