### ISSUE TITLE
DisasterScans not reachable in app

### ISSUE THREAD

**Issue by C0LiSii0N** [tachiyomiorg/tachiyomi-extensions#16597] opened 2023-05-27 10:02 UTC
### Source information

Disaster Scans 1.4.31

### Source language

English

### Steps to reproduce

Try to see the content of the website from Tachiyomi

### Expected behavior

We should have the manga list

### Actual behavior

We get a 404 error

### Tachiyomi version

0.14.6

### Android version

Android 13

### Other details

When we go on webview, it work, but from the extension in the app, it doens't.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment] 2023-05-27 10:03
Duplicate of #16596

**Closed by AntsyLich** 2023-05-27 10:03 UTC
Labels: Bug
