### ISSUE TITLE
Painful night won't show images

### ISSUE THREAD

**Issue by samanta-widjaja** [tachiyomiorg/tachiyomi-extensions#11151] opened 2022-03-16 22:10 UTC
### Source information

Painful nightz scan 1.2.17

### Steps to reproduce

Painful nightz chapter won't show any images. Always retry. But when open through browser it show images. 

Url example https://painfulnightz.com/manga/coffee-and-vanilla/chapter-80/

### Expected behavior

Show images and can be download

### Actual behavior

Images won't show and can't be download

### Tachiyomi version

0.13.1

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alekc** [comment] 2022-04-28 11:45
cannot reproduce

**Comment by arkon** [comment] 2023-05-26 21:16
In an effort to have a more manageable issue backlog, we're closing older requests that weren't addressed since there's a low chance of it being addressed if it hasn't already. If your request is still relevant, please [open a new request](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).

**Closed by arkon** 2023-05-26 21:16 UTC
Labels: Bug, Factory source
