### ISSUE TITLE
Manga-TX 1.3.26 (English) link change from manga-tx.com to mangatx.gg

### ISSUE THREAD

**Issue by GotsuZed** [tachiyomiorg/tachiyomi-extensions#14767] opened 2023-01-02 20:58 UTC
### Source information and language

Manga-TX 1.3.26 (English)

### Source new URL

Mangatx.gg

### Other details

If i click open in webview it's auto redirected to mangatx.gg

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2023-01-02 21:04
Duplicate of #14700

**Closed by alessandrojean** 2023-01-02 21:04 UTC
Labels: Bug, Domain changed
