### ISSUE TITLE
[Bug] <Lily Manga>: <No Chapters Found>

### ISSUE THREAD

**Issue by MemoriVR** [tachiyomiorg/tachiyomi-extensions#6349] opened 2021-03-29 20:06 UTC
## Device information
- Tachiyomi version: TachiyomiSY 348 Preview
- Android version: 10

## Source information
- Name: Lily Manga
- Extension version: 1.2.2

## Steps to reproduce
1. Add After the Curtain Call or Akuma No Riddle to your library
2. Update your Library via drag down
3. Open Log to see error

### Expected behavior
There should not be an error and the manga/webtoon should update. 

### Actual behavior
Error given is "Title (Lily Manga (EN)): No chapters found" and manga does not update.

**Comment by scb261** [comment] 2021-03-29 23:13
Duplicate of #6292

**Closed by scb261** 2021-03-29 23:13 UTC
Labels: bug
