### ISSUE TITLE
The manga list not connected to the source

### ISSUE THREAD

**Issue by Ammaralkaaki** [tachiyomiorg/tachiyomi-extensions#18621] opened 2023-10-19 18:34 UTC
### Source information

Mangaswat1.4.41

### Source language

Arabic

### Steps to reproduce

- Open the source 
- while in the app the manga list is not updated and show no chapters found.
- when open the manga in web from the app.
- it shows the manga list not the manga web site in the list 

### Expected behavior

Manga website in source must open.

### Actual behavior

The manga list website open.

### Tachiyomi version

0.14.6

### Android version

Android 13

### Other details

I think this is issue in the link between manga from the app and the manga website in the source website.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2023-10-21 11:17
Duplicate of #18000

**Closed by vetleledaal** 2023-10-21 11:17 UTC
Labels: Bug
