### ISSUE TITLE
Can't read chapter in 1manga.co

### ISSUE THREAD

**Issue by akshar2324** [tachiyomiorg/tachiyomi-extensions#12960] opened 2022-08-13 09:35 UTC
### Source information and language

1Manga.co 1.3.6

### Steps to reproduce

![Screenshot_20220813_145157](https://user-images.githubusercontent.com/90042795/184478069-02ee58ad-b360-4b80-b4c0-6670c694b788.jpg)

Showing this error when opening any chapter

### Expected behavior

It should work normal

### Actual behavior

![Screenshot_20220813_145157](https://user-images.githubusercontent.com/90042795/184478094-951cab25-9ce6-4107-8967-c5844539027b.jpg)

Showing this error when opening any chapter

### Tachiyomi version

0.13.5

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-08-13 14:15
Duplicate of #12959

**Closed by arkon** 2022-08-13 14:15 UTC
Labels: Bug
