### ISSUE TITLE
[Source Request] <Hatsuki manga>

### ISSUE THREAD

**Issue by Elcrack14** [tachiyomiorg/tachiyomi-extensions#7419] opened 2021-06-03 15:08 UTC
## Source website
- Name: Hatsuki Manga
- Link: https://hatsukimanga.com
- Language(s): Spanish (ES)

**Comment by loocool2** [comment] 2021-06-03 15:09
Duplicate of #4282.

**Closed by loocool2** 2021-06-03 15:09 UTC
Labels: Source Request
