### ISSUE TITLE
Olympus scan

### ISSUE THREAD

**Issue by JTwyla** [tachiyomiorg/tachiyomi-extensions#15517] opened 2023-02-28 12:24 UTC
### Source information and language

Olympus Scanlation

### Steps to reproduce

Falla al cargar debido al cambio de nombre de la pagina
https://olympusscanlation.com/ a https://olympusscans.com/

### Expected behavior

Esperaba entrar normal a esta extension

### Actual behavior

Es un cambio reciente pero me gustaria que cambien el nombre de la pagina para que no ocurra error en los guardados en biblioteca

### Tachiyomi version

0.14.5

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2023-02-28 12:28
Duplicate of #15330

**Closed by Seishirou101** 2023-02-28 12:28 UTC
Labels: Bug
