### ISSUE TITLE
Xcalibr Scans shows error 103

### ISSUE THREAD

**Issue by Itachi-Otsutsuki** [tachiyomiorg/tachiyomi-extensions#12429] opened 2022-07-04 05:22 UTC
### Source information

Xcalibr Scans 1.3.18

### Steps to reproduce

Whenever I click on xcalibr scans in sources it shows http error 103. And when I search for titles that I know r in xcalibr scans on global search xcalibr scans doesn't pop up

### Expected behavior

When I click on xcalibr scans it should show the titles available

### Actual behavior

They show error 103

### Tachiyomi version

0.13.4

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2022-07-04 05:39
Duplicate of #11907

**Closed by Seishirou101** 2022-07-04 05:39 UTC
Labels: Bug
