### ISSUE TITLE
Page not found and thumbnails not loading

### ISSUE THREAD

**Issue by Dfuhcfu** [tachiyomiorg/tachiyomi-extensions#15760] opened 2023-03-19 00:45 UTC
### Source information and language

Doujindesu 1.4.3 (indonesia)

### Steps to reproduce

.

### Expected behavior

.

### Actual behavior

.

### Tachiyomi version

Tachiyomi j2k v1.6.4

### Android version

Android 8

### Other details

Page not found

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by SmileeeOfficial** [comment] 2023-03-19 04:29
![Uploading Screenshot_20230319-112923.png…]()

**Comment by SmileeeOfficial** [comment] 2023-03-19 04:31
![Uploading Screenshot_20230319-112923.png…]()

**Comment by Shiin-79** [comment] 2023-03-19 06:08
![Screenshot_Tachiyomi](https://user-images.githubusercontent.com/56505683/226156869-b5c028fc-d9c3-4ad3-b9ad-4959fa6aaf91.png)

**Comment by SmileeeOfficial** [comment] 2023-03-19 08:08
![Screenshot_Tachiyomi](https://user-images.githubusercontent.com/119809410/226162104-008d601f-a424-4d8b-9c26-1fbb370ebf76.png)

**Comment by Riztard** [comment] 2023-03-19 08:20
@SmileeeOfficial dont post nsfw

**Comment by SmileeeOfficial** [comment] 2023-03-19 08:33
@Riztard ahh Sorry , i just want to point out that the DoujinDesu thumbnail is not error

**Comment by Dfuhcfu** [comment] 2023-03-19 09:46
Pada tanggal Min, 19 Mar 2023 15:33 Smile.Id79 ***@***.***
menulis:

**Comment by Dfuhcfu** [comment] 2023-03-19 09:47
why there are no thumbnails and no pages when I want to read


Pada tanggal Min, 19 Mar 2023 15:33 Smile.Id79 ***@***.***
menulis:

**Comment by stevenyomi** [comment] 2023-03-24 15:59
Duplicate of #11662 and #14004

**Closed by stevenyomi** 2023-03-24 15:59 UTC
Labels: Bug
