### ISSUE TITLE
Cosmic scans repeating scenes

### ISSUE THREAD

**Issue by e786** [tachiyomiorg/tachiyomi-extensions#14271] opened 2022-11-16 00:12 UTC
### Source information and language

Cosmic Scans 1.3.21 (English)

### Steps to reproduce

1. Find a series on Cosmic Scans
2. Get on the latest chapters of a series
3. Read a little bit until you see a scene repeat

### Expected behavior

Scenes don't repeat twice

### Actual behavior

The scenes repeated twice so the chapter was twice as long

### Tachiyomi version

0.14.2

### Android version

Android 11

### Other details

Only happens to the lastest chapters for cosmic scans.
Doesn't happen when using WebView 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment] 2022-11-17 10:34
Duplicate of #14266

**Closed by AntsyLich** 2022-11-17 10:34 UTC
Labels: Bug
