### ISSUE TITLE
Dragontranslation

### ISSUE THREAD

**Issue by MonarchodDead** [tachiyomiorg/tachiyomi-extensions#15912] opened 2023-03-31 02:00 UTC
### Source information and language

Spanish

### Steps to reproduce

http error 400 : Open site in website

### Expected behavior

show manhuas... but it doesn't show anything.... it just lets open it from the browser

### Actual behavior

Nothing .. justo error 400

### Tachiyomi version

0.14.5

### Android version

12

### Other details

Nothing

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by scb261** [comment] 2023-04-06 19:46
Duplicate of #15313

**Closed by scb261** 2023-04-06 19:46 UTC
Labels: Bug, Factory source
