### ISSUE TITLE
Loading issue with LectorManga extension

### ISSUE THREAD

**Issue by AguClips** [tachiyomiorg/tachiyomi-extensions#8894] opened 2021-08-29 18:04 UTC
### Source information

LectorManga 1.2.19

### Steps to reproduce

When I open the chapters of any manga, I get "retry" and the chapters never load.

### Expected behavior

What should happen is that the chapters load normally, and if "retry" appeared when reloading it, the chapters could now be viewed.

### Actual behavior

Capter do not load the no matter how long you wait. The "retry" button does nothing.
![Screenshot_20210829-133621](https://user-images.githubusercontent.com/79488349/131260698-f94ad5e1-7d9c-447e-b80c-73ae3fafcd2c.png)

### Tachiyomi version

0.12.1

### Android version

Android 11 (Moto G9 Play) and Android 9 (Moto X4)

### Other details

I tried uninstalling the extension and installing it again but the problem is still there. TuMangaOnline works fine instead.

On my brother's phone (Moto G9 Plus, Android 10) works fine. A friend of mine also have the same issue as me.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2021-08-29 18:11
Duplicate of #8859

**Closed by alessandrojean** 2021-08-29 18:11 UTC
Labels: Bug
