### ISSUE TITLE
Manhwa18: Error 404

### ISSUE THREAD

**Issue by AimannQn** [tachiyomiorg/tachiyomi-extensions#9959] opened 2021-11-29 15:59 UTC
### Source information

Manhwa18 1.2.6

### Steps to reproduce

1. Open Manhwa18

### Expected behavior

Manga/Manhwa/Manhua pop up

### Actual behavior

When Open Manhwa18 it's show Error 404

### Tachiyomi version

Stable 0.12.3

### Android version

Android 11

### Other details

Extension Broke after Manhwa18 Website gone (to void).
![Screenshot_20211129-234846_Discord](https://user-images.githubusercontent.com/84202326/143900217-f358431a-69cb-49cc-9188-28fe0831f9da.jpg)
But Manhwa18 Website is back (that has been missing inside void)
![Screenshot_20211129-235409_Discord](https://user-images.githubusercontent.com/84202326/143900791-bb88b45c-1159-4b3a-9626-412007609cc1.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by keinezeit8** [comment] 2021-11-30 21:31
duplicate of #9935

**Closed** 2021-11-30 22:03 UTC
Labels: Bug
