### ISSUE TITLE
[Source request]http://www.acggd.com/

### ISSUE THREAD

**Issue by voltes2** [tachiyomiorg/tachiyomi-extensions#7860] opened 2021-06-25 09:53 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

http://www.acggd.com/

### Source link

http://www.acggd.com/

### Language

chinese

### Other details

this site has many nique chinese manga

**Comment by loocool2** [comment] 2021-06-25 09:55
Duplicate of #7859. Just edit your other issue

**Closed by loocool2** 2021-06-25 09:55 UTC
Labels: Source request
