### ISSUE TITLE
Update error on manhuaren

### ISSUE THREAD

**Issue by Nam1031** [tachiyomiorg/tachiyomi-extensions#16920] opened 2023-06-29 14:46 UTC
### Source information

Manhuaren 1.4.8

### Source language

Chinese

### Steps to reproduce

When refreshing the book list, it shows the Mangas cannot be updated.
And Manhuaren's shows "No value of Response"

### Expected behavior

I expected my booklist can be updated

### Actual behavior

When refreshing the book list, it shows the Mangas cannot be updated.
And Manhuaren's shows "No value of Response"

### Tachiyomi version

0.14.6

### Android version

Android11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2023-06-29 14:47
Duplicate of #16909

**Closed by alessandrojean** 2023-06-29 14:47 UTC
Labels: Bug
