### ISSUE TITLE
Http error 429

### ISSUE THREAD

**Issue by MochaChoc1** [tachiyomiorg/tachiyomi-extensions#13352] opened 2022-09-05 07:35 UTC
### Source information and language

Manga buddy 1.13.10

### Steps to reproduce

Step 1: went to updates
Step 2: I updated manhwa's I read to see if there was new chapter
Step 3: I got notification saying that "update failed
Step 4: I tapped the notification to see what's wrong
Step 5: I went ahead and report it here

### Expected behavior

After I updated my manhwa compilations I got the notification saying there was an error. So I got up and and did what was instructed and here I am reporting the issue

### Actual behavior

It usually just gives me list of new chapters to read and download it

### Tachiyomi version

0.13.6

### Android version

Android 11

### Other details

It said to be http error 429 and said that an error happened because I read too fast

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2022-09-05 10:20
Duplicate of #13182

**Closed by vetleledaal** 2022-09-05 10:20 UTC
Labels: Bug

**Comment by MochaChoc1** [comment] 2022-09-05 11:53
I'm sorry I don't really get it

**Comment by vetleledaal** [comment] 2022-09-05 12:03
It's the same underlying issue as with MangaBuddy, wait for someone to address #13182
