### ISSUE TITLE
漫画人无法使用

### ISSUE THREAD

**Issue by yuduotianguang** [tachiyomiorg/tachiyomi-extensions#18862] opened 2023-11-04 05:57 UTC
### Source information

漫画人1.4.14

### Source language

中文

### Steps to reproduce

打开本插件

### Expected behavior

显示漫画

### Actual behavior

显示no value for response, webview显示 "签名错误"，下载原APP进入后方可使用

### Tachiyomi version

0.14.7

### Android version

Android13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2023-11-11 09:46
Duplicate of #17971

**Closed by vetleledaal** 2023-11-11 09:46 UTC
Labels: Bug
