### ISSUE TITLE
Com-x не засчитывается капча

### ISSUE THREAD

**Issue by astraker55** [tachiyomiorg/tachiyomi-extensions#11745] opened 2022-05-05 10:43 UTC
### Source information

Com-x 1.2.16

### Steps to reproduce

Открываю приложение
Открываю любой комикс в com-x, получаю сообщение "404, возможно антибот"
Открываю webview, прохожу капчу
Пытаюсь открыть комикс, снова получаю сообщение о капче

### Expected behavior

Должен засчитать капчу и открыть комикс

### Actual behavior

Комикс доступен только через вебвью

### Tachiyomi version

0.13.4

### Android version

Android 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-05-05 20:30
Duplicate of #11635

**Closed by alessandrojean** 2022-05-05 20:30 UTC
Labels: Bug
