### ISSUE TITLE
(Lily Manga) App doesn't fins chapters

### ISSUE THREAD

**Issue by Esqueleta** [tachiyomiorg/tachiyomi-extensions#8213] opened 2021-07-21 23:36 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

11

### Source information

Lily Manga 1.2.7

### Steps to reproduce

Open Lily Manga's extension
Open any manga there
Issue here 

### Expected behavior

Chapters should appear on the screen
![Screenshot_2021-07-21-20-33-12-806_eu kanade tachiyomi](https://user-images.githubusercontent.com/73192472/126572691-1cb16e0c-217a-41f5-883b-24bd16c9892d.jpg)

### Actual behavior

They don't 
![IMG-20210721-WA0019](https://user-images.githubusercontent.com/73192472/126572783-3db2ed77-0c75-46cd-b0d2-7d8cbda5b764.jpg)

**Comment by alessandrojean** [comment] 2021-07-21 23:40
Duplicate of #8030

**Closed by alessandrojean** 2021-07-21 23:40 UTC
Labels: Bug
