### ISSUE TITLE
Manhwa.met

### ISSUE THREAD

**Issue by Stevenss20907** [tachiyomiorg/tachiyomi-extensions#7962] opened 2021-07-03 20:16 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

Manhwas.net

### Source link

https://manhwas.net/es

### Language

Español 

### Other details

![Screenshot_20210703-151616_Tachiyomi](https://user-images.githubusercontent.com/86885343/124365980-aa9e7c00-dc11-11eb-918f-570b0704f5eb.jpg)

**Comment by arkon** [comment] 2021-07-03 20:26
Duplicate of #5347

**Closed by arkon** 2021-07-03 20:26 UTC
Labels: Source request
