### ISSUE TITLE
[Bug] <Hentaivn>: <cannot open the main page>

### ISSUE THREAD

**Issue by Dumanotucghe** [tachiyomiorg/tachiyomi-extensions#5725] opened 2021-02-09 07:31 UTC
---

## Device information
- Tachiyomi version: newest
- Android version: 6+

## Source information
- Name: Hentaivn
- Extension version: 1.2.5

## Steps to reproduce
1. Open extension
2. 
![Screenshot_2021-02-09-14-16-45](https://user-images.githubusercontent.com/78786149/107329893-633d1500-6ae3-11eb-9ed0-5f63485c3d94.png)

### Expected behavior
Describe what should have happened

### Actual behavior
Describe what happens instead

**Comment by scb261** [comment] 2021-02-09 07:46
Duplicate of #3623

**Closed by scb261** 2021-02-09 07:46 UTC
Labels: bug
