### ISSUE TITLE
Mangapark: missing chapters

### ISSUE THREAD

**Issue by GodSlayer99** [tachiyomiorg/tachiyomi-extensions#9167] opened 2021-09-21 12:59 UTC
### Source information

Mangapark

### Steps to reproduce

The extension is not updating

### Expected behavior

The extension should update

### Actual behavior

The extension is not updating

### Tachiyomi version

0.12.2

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rymesaint** [comment] 2021-09-23 07:16
is there any fix soon?

**Comment by FourTOne5** [comment] 2021-09-23 19:20
Duplicate of #9129

**Closed** 2021-09-23 19:51 UTC
Labels: Bug
