### ISSUE TITLE
Mangacrab cloudflare problem.

### ISSUE THREAD

**Issue by Hayashi13q4** [tachiyomiorg/tachiyomi-extensions#12532] opened 2022-07-10 21:51 UTC
### Source information

Mangacrab 

### Steps to reproduce

cloudflare problem.

### Expected behavior

Debería de abrí la biblioteca de mangas pero no lo hace y los mangas agregados ya no se pueden ver

### Actual behavior

No se ve ningún capitulo de ningún manga 

### Tachiyomi version

0.13.5

### Android version

Android 11

### Other details

Java.lang Exception: Failed to bypass Cloudflare

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-07-11 13:57
Duplicate of #12130

**Closed by alessandrojean** 2022-07-11 13:57 UTC
Labels: Bug
