### ISSUE TITLE
[Source Request] <Mangaworld>

### ISSUE THREAD

**Issue by edofl3da** [tachiyomiorg/tachiyomi-extensions#6541] opened 2021-04-14 11:56 UTC
## Source website
- Name: Mangaworld
- Link: ?
- Language(s): Italian
The site Mangaworld has been updated, so the extension must be updated.

**Comment by Riztard** [comment] 2021-04-14 12:00
1. its not source request
2. duplicate of #6534

**Closed by Riztard** 2021-04-14 12:00 UTC
Labels: Source Request, duplicate
