### ISSUE TITLE
[Bug] <Japanread>: <No chapter found>

### ISSUE THREAD

**Issue by Ferreoly** [tachiyomiorg/tachiyomi-extensions#7506] opened 2021-06-06 19:21 UTC
## Device information
- Tachiyomi version: v 0.11.1
- Android version: 9

## Source information
- Name: Japanread
- Extension version: 1.2.7

## Steps to reproduce
1. Go to the Explorer
2. Click on Sources
2. Click on the Source Japanread
3. No pictures are displayed
4. Click on a Manga (No pictures displayed)
5. No chapter found
### Expected behavior
When i click on the source Japanread, i should see the mangas with their pictures and when i click on a manga i should see the chapters.
### Actual behavior
When i click on the source Japanread, the manga names appear but there are no pictures and when i click on a manga after charging, it displays the message no chapter found.
## Other details
Nothing else

**Comment by xavimaa** [comment] 2021-06-30 22:55
1.2.8 does not solve the problem

**Comment by arkon** [comment] 2021-10-02 16:28
Duplicate of #7173

**Closed by arkon** 2021-10-02 16:28 UTC
Labels: Bug
