### ISSUE TITLE
[Source Request] Gdrive 

### ISSUE THREAD

**Issue by chaitanyakr** [tachiyomiorg/tachiyomi-extensions#7815] opened 2021-06-22 11:25 UTC
## Why/User Benefit/User Problem
Users can use it to read files directly from gdrive, less rate limits if using their own client I'd and secret (cloud console).

**Comment by CrepeTF** [comment] 2021-06-22 11:27
Just use [komga](https://komga.org/guides/tachiyomi.html)

**Comment by loocool2** [comment] 2021-06-22 12:22
Duplicate of #2989

**Closed by loocool2** 2021-06-22 12:22 UTC
Labels: Source Request
