### ISSUE TITLE
MangaOwl: Error

### ISSUE THREAD

**Issue by Dayron15atn** [tachiyomiorg/tachiyomi-extensions#8526] opened 2021-08-11 21:10 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.12.1

### Android version

Android 9

### Source information

MangaOwl 1.2.20

### Steps to reproduce

Paso 1:Abro Tachiyomi 
Paso 2:Busco un manga en ''Manga Owl 1.2.20'' para descargarlo y leerlo.

### Expected behavior

Deberia descargarse y abrirse el manga que elegi 

### Actual behavior

No se abre o descargar el manga

**Comment by arkon** [comment] 2021-10-02 16:31
Duplicate of #8456

**Closed by arkon** 2021-10-02 16:31 UTC
Labels: Bug
