### ISSUE TITLE
Can't pass cloudflare even succeed pass it with "open by browser"

### ISSUE THREAD

**Issue by ByChrsM** [tachiyomiorg/tachiyomi-extensions#10114] opened 2021-12-15 06:45 UTC
### Source information

Mangaowl 1.2.23

### Steps to reproduce

MangaOwl extension in my device have trouble : 
Java.lang Exception: Failed to bypass Cloudflare

I'm trying open webview so I can pass the cloudflare, but when I open webview : 
net::ERR_TIMED_OUT

Then I open it at browser (open by browser) and mangaowls.com can load normally also pass the cloudflare.
Then I'm back to Tachiyomy and still have trouble Java.lang Exception: Failed to bypass Cloudflare even already pass the cloudflare by browser.

### Expected behavior

After passing cloudflare from webview or open by browser can access the extension in Tachiyomi.

### Actual behavior

After passing cloudflare from open by browser still have notice :
Java.lang Exception: Failed to bypass Cloudflare

### Tachiyomi version

0.12.3

### Android version

Android 6

### Other details

How to fix this problem?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2021-12-19 15:29
Duplicate of #8456

**Closed by alessandrojean** 2021-12-19 15:29 UTC
Labels: Bug
