### ISSUE TITLE
Hattori Manga 

### ISSUE THREAD

**Issue by ArminArlert31** [tachiyomiorg/tachiyomi-extensions#18486] opened 2023-10-11 10:25 UTC
### Source information

Hattori Manga 1.4.31

### Source language

Turkish

### Steps to reproduce

1)open hattori manga
2)http error 404
3)open webview
4)The website opens but the app does not open 

### Expected behavior

It needs to be opened both in the application and in webview, and it should not error 404 

### Actual behavior

😮‍💨

### Tachiyomi version

Stable 0.14.16

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2023-10-21 10:56
Duplicate of #17840

**Closed by vetleledaal** 2023-10-21 10:56 UTC
Labels: Bug
