### ISSUE TITLE
[Bug] <Sekai Komik>: <Can't open this extension>

### ISSUE THREAD

**Issue by Ciel-kun** [tachiyomiorg/tachiyomi-extensions#7492] opened 2021-06-05 21:38 UTC
## Device information
- Tachiyomi version: 0.10.12
- Android version: 7.1.1

## Source information
- Name: Sekai Komik
- Extension version: 1.2.12

## Steps to reproduce
1. HTTP Error 403

### Expected behavior
Can't open this extension cause Error 403

### Actual behavior
After updated to the latest version i can't open this extension because HTTP Error 403. I try troubleshooting buy I Can't work and i check the webview but it cant even though in website Sekai Komik its normal.

## Other details
![Screenshot_2021-06-06-04-34-22-12](https://user-images.githubusercontent.com/81224499/120906092-ce0cf000-c680-11eb-9098-56382e77a470.png)

**Comment by h-hyuuga** [comment] 2021-06-06 07:20
Duplicate of #7457

**Closed** 2021-06-09 18:18 UTC
Labels: bug
