### ISSUE TITLE
Maximum pages in a manga in MangaKatana extension is not normal

### ISSUE THREAD

**Issue by RayeShin** [tachiyomiorg/tachiyomi-extensions#13065] opened 2022-08-18 14:32 UTC
### Source information and language

MangaKatana 1.3.6 (english)

### Steps to reproduce

1. Open MangaKatana extension 
2. Choose any manga
3. Choose any chapter of the manga

### Expected behavior

![Screenshot_20220818-222445_Tachiyomi](https://user-images.githubusercontent.com/111516954/185420262-b8c1ca76-dcf2-4abe-935c-52533455c521.jpg)

### Actual behavior

![Screenshot_20220818-222223_Tachiyomi](https://user-images.githubusercontent.com/111516954/185420417-639bf9fb-4574-4b01-aa4e-8289d15dffc4.jpg)

### Tachiyomi version

0.13.6

### Android version

Android 9

### Other details

The MangaKatana website is working fine but using the MangaKatana extension from the Tachiyomi, the chapters of the mangas will only consist of 1 page.

### Acknowledgements

- [ ] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2022-08-18 14:50
Duplicate of #13062

**Closed by Seishirou101** 2022-08-18 14:50 UTC
Labels: Bug
