### ISSUE TITLE
[Bug] <Japscan>: <White page when download>

### ISSUE THREAD

**Issue by JeremieBergeron** [tachiyomiorg/tachiyomi-extensions#6165] opened 2021-03-13 03:05 UTC
## Device information
- Tachiyomi version: Stable 0.10.9
- Android version: 10

## Source information
- Name: Japscan
- Extension version: 1.2.25

## Steps to reproduce
1. Try to download the first chapter of I am a hero (https://www.japscan.se/lecture-en-ligne/i-am-a-hero/1/1.html)
2. The page 3 is white.

### Expected behavior
The page 3 should not be white.

### Actual behavior
The page 3 is white.

## Other details
Thank you very much

**Comment by scb261** [comment] 2021-03-13 03:23
Duplicate of #4792

**Closed by scb261** 2021-03-13 03:23 UTC
Labels: bug
