### ISSUE TITLE
Olympus Scanlation No results found 

### ISSUE THREAD

**Issue by Unknoweird** [tachiyomiorg/tachiyomi-extensions#15600] opened 2023-03-06 00:13 UTC
### Source information and language

Olympus Scanlation 1.4.28 (Spanish)

### Steps to reproduce

1. Enter Olympus Scanlation extension
2. No results found 

### Expected behavior

When I enter Olympus Scanlation extension, I usually read the Manhwa I searched 

### Actual behavior

Now the Olympus Scanlation extension don't have any Manhwa, Manga, etc. I suppose than this is because the official page moved away.

### Tachiyomi version

TachiJ2K 1.6.2

### Android version

Android 10

### Other details

None

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-03-06 00:14
Duplicate of #15330

**Closed by arkon** 2023-03-06 00:14 UTC
Labels: Bug
