### ISSUE TITLE
[Source Request] <Hatsuki Manga>

### ISSUE THREAD

**Issue by ErickM505** [tachiyomiorg/tachiyomi-extensions#7659] opened 2021-06-15 01:58 UTC
## Source website
- Name: Hatsuki Manga
- Link: https://hatsukimanga.com/
- Language (s): Spanish

## Other details

**Comment by alessandrojean** [comment] 2021-07-24 01:54
Duplicate of #4282

**Closed by alessandrojean** 2021-07-24 01:54 UTC
Labels: Source request
