### ISSUE TITLE
ManhwaID

### ISSUE THREAD

**Issue by ellodandra** [tachiyomiorg/tachiyomi-extensions#8191] opened 2021-07-20 03:16 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

ManhwaID

### Source link

https://manhwaid.co/

### Language

Indonesia

### Other details

![Screenshot_2021-07-20-10-16-00-40](https://user-images.githubusercontent.com/81138524/126256596-fd579295-fd46-435c-8af6-5e91da9db740.png)
This extension not available in tachiyomi

**Comment by loocool2** [comment] 2021-07-20 03:17
Duplicate of #6223

**Closed by loocool2** 2021-07-20 03:17 UTC
Labels: Source request
