### ISSUE TITLE
MangaHub:Page Issue

### ISSUE THREAD

**Issue by TysonBlaze009** [tachiyomiorg/tachiyomi-extensions#15437] opened 2023-02-21 14:51 UTC
### Source information and language

MangaHub 1.4.27

### Steps to reproduce

1. When app opened and click on any manga Pages shows "Image couldn't be loaded".
2. This issue is also shown in old uploaded chapters
3. This issue is before and after the update of Tachiyomi app also MangaHub extension.

### Expected behavior

Normally in mangahub extension when opened any manga chapter it shows all uploaded images.

### Actual behavior

It shows pages couldn't be loaded when opened any manga chapter. Whether it is new coming manga or old ongoing manga.
![216808881-d1da2d03-5057-47f9-849d-7247c63e5f36](https://user-images.githubusercontent.com/124012561/220377838-7bed2038-dea5-49b5-a1be-625c91704980.jpg)

### Tachiyomi version

0.14.5

### Android version

Android 12

### Other details

This issue is for way to long. Please resolve this issue.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2023-02-21 20:06
Duplicate of #14736

**Closed by vetleledaal** 2023-02-21 20:06 UTC
Labels: Bug
