### ISSUE TITLE
TeamX : The maximum chapter width limit is 100 only

### ISSUE THREAD

**Issue by yemenihandsome** [tachiyomiorg/tachiyomi-extensions#14823] opened 2023-01-06 09:45 UTC
### Source information and language

TeamX 1.2.10

### Steps to reproduce

1- Access to the source
2- Open the manga 
3-Only the last 100 chapters appear

### Expected behavior

All chapters must appear

### Actual behavior

لم تظهر جميع الفصول

### Tachiyomi version

0.14.2

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2023-01-06 12:22
Duplicate of #14811

**Closed by alessandrojean** 2023-01-06 12:22 UTC
Labels: Bug
