### ISSUE TITLE
[Source Request] <DoujinDesu>

### ISSUE THREAD

**Issue by ellodandra** [tachiyomiorg/tachiyomi-extensions#6245] opened 2021-03-22 06:14 UTC
## Source website
- Name: DoujinDesu
- Link: doujindesu.info
- Language(s): Indonesian

## Other details
- I have checked that the extension does not already exist:
  - In the list of existing extensions in the application

**Comment by scb261** [comment] 2021-03-22 06:21
Duplicate of #5470

**Closed by scb261** 2021-03-22 06:21 UTC
Labels: Source Request
