### ISSUE TITLE
Webtoon Tr No chapter founds error

### ISSUE THREAD

**Issue by Nurullahgrlk** [tachiyomiorg/tachiyomi-extensions#11413] opened 2022-04-09 22:17 UTC
### Source information

Webtoon TR 1.2.20

### Steps to reproduce

No chapter 
![Screenshot_20220410_003230_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/97397847/162593242-fe19de1b-c06c-42f7-a318-6da423db92c8.jpg)

### Expected behavior

Idnt know

### Actual behavior

Idnt know (bad englısh sorry for that) 

### Tachiyomi version

0.13.1

### Android version

10

### Other details

Nothing

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-04-09 22:23
Duplicate of #11371

**Closed by arkon** 2022-04-09 22:23 UTC
Labels: Bug
