### ISSUE TITLE
Mangakatana source again shows only one page

### ISSUE THREAD

**Issue by Krish2301** [tachiyomiorg/tachiyomi-extensions#13504] opened 2022-09-18 03:10 UTC
### Source information and language

Mangakatana 1.3.8 (English)

### Steps to reproduce

A month back this issue of only one page showing started but was sorted out. Now the issue has cropped up again and need some info on what is happening. 
![Screenshot_20220918-083747](https://user-images.githubusercontent.com/43061926/190883943-8381fd78-d554-4d99-94a1-920c6adc9614.jpg)
![Screenshot_20220918-083848](https://user-images.githubusercontent.com/43061926/190883951-8573c49c-eca9-4f80-b3ab-891f688a8f48.jpg)

### Expected behavior

Expected behaviour should be as to have all pages in the chapter

### Actual behavior

Instead of that only one page is being shown.

### Tachiyomi version

"0.13.6"

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by mobi2002** [comment] 2022-09-18 03:12
Duplicate of  #13486

**Closed** 2022-09-18 04:05 UTC
Labels: Bug
