### ISSUE TITLE
CopyManga java.lang.String error

### ISSUE THREAD

**Issue by jwstaceyOvO** [tachiyomiorg/tachiyomi-extensions#8944] opened 2021-09-03 03:15 UTC
### Source information

CopyManga 1.2.11

### Steps to reproduce

1. Read or download new chapter.
2. It shows the error and you can not read or download. In the webview, you can read normally.

### Expected behavior

Normal reading and downloading.

### Actual behavior

It shows the error and quits reading or downloading.

### Tachiyomi version

0.12.1

### Android version

Andriod 9

### Other details

![Screenshot_2021-09-03-11-02-46](https://user-images.githubusercontent.com/38880537/131945233-968c7f23-f91f-4fe5-b0c1-453199adfc7a.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2021-09-03 03:21
Duplicate of #8934

**Closed** 2021-09-03 03:21 UTC
Labels: Bug
