### ISSUE TITLE
kuaikanmanhua(快看漫画) extension was failed

### ISSUE THREAD

**Issue by ZerOri** [tachiyomiorg/tachiyomi-extensions#12578] opened 2022-07-14 06:30 UTC
### Source information

kuaikanmanhua 1.3.9

### Steps to reproduce

As like this:

![QQ图片20220714142457](https://user-images.githubusercontent.com/46775615/178915405-00645578-ccdf-4785-8d9d-aa41a29a4bca.jpg)

### Expected behavior

no

### Actual behavior

no

### Tachiyomi version

0.1.35

### Android version

android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2022-07-14 09:33
Duplicate of #12480

**Closed by vetleledaal** 2022-07-14 09:33 UTC
Labels: Bug
