### ISSUE TITLE
Download problem 

### ISSUE THREAD

**Issue by Ammaralkaaki** [tachiyomiorg/tachiyomi-extensions#17015] opened 2023-07-04 15:09 UTC
### Source information

Mangaswat1.4.34

### Source language

Arabic

### Steps to reproduce

Downloading chapters is pending and not starting.

### Expected behavior

For chapters to be downloaded.

### Actual behavior

Keep pending and ongoing.

### Tachiyomi version

0.14.6

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment] 2023-07-05 09:19
Duplicate of #16952

**Closed by stevenyomi** 2023-07-05 09:19 UTC
Labels: Bug
