### ISSUE TITLE
Jinmantiantang: Chapter images are downloaded as `.bin` files

### ISSUE THREAD

**Issue by tatular** [tachiyomiorg/tachiyomi-extensions#11370] opened 2022-04-08 04:10 UTC
### Source information

jinmantiantang 1.2.24

### Steps to reproduce

1. select any source from jinmantiantang
2. download it
3. all downloaded files are in .bin file format instead of jpg

### Expected behavior

downloaded files are supposed to be in jpg file format and able to open in tachiyomi.

### Actual behavior

downloaded files are all in .bin file format and not able to open in tachiyomi. it says no page found.

### Tachiyomi version

0.13.1

### Android version

android 12

### Other details

![SmartSelect_20220408-120806_My Files](https://user-images.githubusercontent.com/90957871/162360799-56437d0e-69e5-4583-8588-b462bd0779a0.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by kasperskier** [comment] 2022-06-03 19:11
Cannot reproduce here. PR fixes the media type anyway, so the issue should be addressed by it.

**Closed** 2022-06-04 16:42 UTC
Labels: Bug
