### ISSUE TITLE
HTTP Error 429

### ISSUE THREAD

**Issue by ahkazak23** [tachiyomiorg/tachiyomi-extensions#11287] opened 2022-03-31 18:39 UTC
### Source information

1st Kiss 1.2.23

### Steps to reproduce

1. Updating  libray
2. Can't update files
3. Error 429

### Expected behavior

Should  update without error

### Actual behavior

HTTP error 429

### Tachiyomi version

0.13.1

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-03-31 18:45
Duplicate of #11280

**Closed by alessandrojean** 2022-03-31 18:45 UTC
Labels: Bug
