### ISSUE TITLE
Manhuaren have no value of response

### ISSUE THREAD

**Issue by Nam1031** [tachiyomiorg/tachiyomi-extensions#17884] opened 2023-09-10 14:37 UTC
### Source information

Manhuaren 1.4.13

### Source language

Chinese

### Steps to reproduce

Manhuaren shows have no value of response and it cannot refresh or even enter the sourse. 

### Expected behavior

It should be able to see the Manga in the library. 

### Actual behavior

It has no response and cannot open every Manga in library. 

### Tachiyomi version

App version: 0.14.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2023-09-11 17:02
Duplicate of #17170

**Closed by vetleledaal** 2023-09-11 17:02 UTC
Labels: Bug
