### ISSUE TITLE
Komikcast (ID)

### ISSUE THREAD

**Issue by Ktslovers99** [tachiyomiorg/tachiyomi-extensions#11977] opened 2022-05-25 15:46 UTC
### Describe your suggested feature

Min, I ask that the Komikcast(id) extension can be used / Change to server 2 because server 1 often has errors

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment] 2022-06-09 05:43
![Screenshot_2022-06-09-12-41-17-65_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/50316075/172772932-264e1d5c-7806-4334-b08b-bf7bbce1541e.jpg)
![Screenshot_2022-06-09-12-41-02-88_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/50316075/172772937-359a1b2c-63c6-4f70-b53d-e97c90b4fce9.jpg)
![Screenshot_2022-06-09-12-40-45-20_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/50316075/172772940-2c838825-886f-4c60-b371-334bdcb5a2de.jpg)


Punya saya aman

**Comment by Ktslovers99** [comment] 2022-06-09 05:47
> Closed due duplicate. Replaced by #12126 with the newest domain.

sekarang udah aman... dulu down... tapi kalau bisa sih yah tambahin fitur ganti server 2..

**Comment by TheKingTermux** [comment] 2022-06-09 05:51
> > Closed due duplicate. Replaced by #12126 with the newest domain.
> 
> sekarang udah aman... dulu down... tapi kalau bisa sih yah tambahin fitur ganti server 2..

Klo gtu, nanti KC ada 2
Soalnya gabisa 1 ekstensi 2 domain seingetku

**Comment by Ktslovers99** [comment] 2022-06-09 05:54
> > > Closed due duplicate. Replaced by #12126 with the newest domain.
> > 
> > 
> > sekarang udah aman... dulu down... tapi kalau bisa sih yah tambahin fitur ganti server 2..
> 
> Klo gtu, nanti KC ada 2 Soalnya gabisa 1 ekstensi 2 domain seingetku

yah sekarang aman sih... jadi gausah dulu gpp... cuman ntah lelet aja tapi bisa kok... 😂

**Comment by TheKingTermux** [comment] 2022-07-16 09:09
`Clossed due not planned`
Duplicate of #10039

**Comment by vetleledaal** [comment] 2022-07-16 10:35
Site/extension uses server 2 by default now

**Closed by vetleledaal** 2022-07-16 10:35 UTC
Labels: Feature request
