### ISSUE TITLE
[Source Request] <DoujinDesu>

### ISSUE THREAD

**Issue by Ciel-kun** [tachiyomiorg/tachiyomi-extensions#6255] opened 2021-03-23 09:13 UTC
## Source website
- Name: DoujinDesu
- Link: https://doujindesu.info/
- Language(s): Indonesian

## Other details
- I have checked that the extension does not already exist:
  - In the list of existing extensions in the application

**Comment by Riztard** [comment] 2021-03-23 09:27
duplicate of #5470

next time read the instruction and check

> - I have searched the existing GitHub issues and this extension does **NOT** have an open request

**Closed by Riztard** 2021-03-23 09:27 UTC
Labels: Source Request
