### ISSUE TITLE
MangaPark v3 unexpected JSON token

### ISSUE THREAD

**Issue by KanXser** [tachiyomiorg/tachiyomi-extensions#13042] opened 2022-08-17 11:14 UTC
### Source information and language

MangaPark v3 1.3.16 (English)

### Steps to reproduce

I have the latest MangaPark v3 extension on the app, and I'm currently reading manga from it.
When I read any manga from MangaPark v3 extension on the app, I receive a message detailing unexpected JSON token.
This issue started a few days ago.

### Expected behavior

When I click on any chapter of any manga from this extension, I should be able to read it 

### Actual behavior

But an error message shows up instead.
" Unexpected JSON token at offset 17:
Expected EOF after parsing, but had = instead at path: $
JSON input: document.domain = 'mangapark.net' "

### Tachiyomi version

0.13.6

### Android version

Android 12

### Other details

![Screenshot_20220817-184159_Tachiyomi](https://user-images.githubusercontent.com/111430503/185105091-174c3d01-9b3f-48ef-885c-62d112bba44b.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-08-17 13:19
Duplicate of #12963

**Closed by arkon** 2022-08-17 13:19 UTC
Labels: Bug
