### ISSUE TITLE
Mangasusu: Changed their domain

### ISSUE THREAD

**Issue by uzumakhiadi** [tachiyomiorg/tachiyomi-extensions#12751] opened 2022-07-27 08:02 UTC
### Source name

Mangasusu

### Source link

http://194.233.87.209/

### Language

Indonesia

### Other details

18+

http://194.233.87.209/
or
http://mangasusu.co.in/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment] 2022-07-27 15:24
Duplicate of #11019

**Closed** 2022-07-27 15:31 UTC
Labels: Source request
