### ISSUE TITLE
Leviatan Scans (For input String :"" error)

### ISSUE THREAD

**Issue by Andi234Pisces** [tachiyomiorg/tachiyomi-extensions#7992] opened 2021-07-06 05:08 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android 7.0

### Source information

All Leviatan Scans 1.2.12

### Steps to reproduce

1. open a manga
2. chapter list should load
3. no chapter load, and a message pops up saying For Input String : ""
![Screenshot_20210705-092857](https://user-images.githubusercontent.com/7387311/124544951-bd57c180-de5a-11eb-9aed-4c5244651f5e.png)
![Screenshot_20210706-125305](https://user-images.githubusercontent.com/7387311/124544984-cb0d4700-de5a-11eb-9499-a0574c482176.png)

### Expected behavior

chapter list should load

### Actual behavior

there a message pops up
![Screenshot_20210706-125305](https://user-images.githubusercontent.com/7387311/124545140-0c9df200-de5b-11eb-9569-16c98754a7c5.png)

### Other details

there many error diffrent for inp
![Screenshot_20210705-092857](https://user-images.githubusercontent.com/7387311/124545218-36efaf80-de5b-11eb-86e9-c4027f86de9f.png)
ut string

**Comment by Clouddark75** [comment] 2021-07-06 06:20
Those with the "tag" Bilibili from LeviatanS aren't available on the page, it's just for info. They're on Bilibili website.

**Comment by Andi234Pisces** [comment] 2021-07-06 06:43
> Those with the "tag" Bilibili from LeviatanS aren't available on the page, it's just for info. They're on Bilibili website.

so its should migrate to another source ?

**Comment by Clouddark75** [comment] 2021-07-06 12:39
> > Those with the "tag" Bilibili from LeviatanS aren't available on the page, it's just for info. They're on Bilibili website.
> 
> so its should migrate to another source ?

To the Bilibili source, there's a extension for it.

This can be close.

**Comment by arkon** [comment] 2021-07-06 12:40
The source should probably throw a better exception in this case.

**Comment by Clouddark75** [comment] 2021-07-06 12:49
Oh, yah, you're right. I didn't notice the first one from LeviatanS. My bad.

**Comment by Andi234Pisces** [comment] 2021-07-06 12:50
> The source should probably throw a better exception in this case.

should i close this issue ?

**Comment by arkon** [comment] 2021-07-06 13:06
No.

**Comment by Clouddark75** [comment] 2021-07-06 13:15
Maybe he has an old version 

> > The source should probably throw a better exception in this case.
> 
> should i close this issue ?

Just migrate the ones you have with the tag with Bilibili, those aren't store on all the scan sites that are working for Bilibili projects. And no, let the ticket open.

**Comment by Andi234Pisces** [comment] 2021-07-06 13:24
> Maybe he has an old version
> 
> > > The source should probably throw a better exception in this case.
> > 
> > 
> > should i close this issue ?
> 
> Just migrate the ones you have with the tag with Bilibili, those aren't store on all the scan sites that are working for Bilibili projects. And no, let the ticket open.

can u tell me what version for the new extension ?

**Comment by CarlosEsco** [comment] 2021-07-06 13:26
This isn't a chat.  Check in the app if you have an update.  IF so update and if the issue is resolved close the ticket.  If not leave it open and wait for a fix

**Comment by arkon** [comment] 2023-05-26 21:14
In an effort to have a more manageable issue backlog, we're closing older requests that weren't addressed since there's a low chance of it being addressed if it hasn't already. If your request is still relevant, please [open a new request](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).

**Closed by arkon** 2023-05-26 21:14 UTC
Labels: Bug
