### ISSUE TITLE
Mangaowl

### ISSUE THREAD

**Issue by Haesoo2** [tachiyomiorg/tachiyomi-extensions#10468] opened 2022-01-15 12:46 UTC
### Source information

Mangaowl 1.2.24

### Steps to reproduce

![Uploading Screenshot_20220115-204401_Tachiyomi.jpg…]()

### Expected behavior

The extension should open.

### Actual behavior

But it cannot fing the https

### Tachiyomi version

0.12.3

### Android version

Andoid 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-01-15 13:49
Duplicate of #10463

**Closed by arkon** 2022-01-15 13:49 UTC
Labels: Bug
