### ISSUE TITLE
MangaDemon.org hiding manga chapter

### ISSUE THREAD

**Issue by carloshpb** [tachiyomiorg/tachiyomi-extensions#17445] opened 2023-08-08 19:27 UTC
### Source information

MangaDemon 1.4.1

### Source language

English 

### Steps to reproduce

1. Open chapter 179 from Survival Story of a Sword King in a Fantasy World;
2. Go to the bottom;
3. See that there the chapter is incomplete.

### Expected behavior

It should be possible to see the whole chapter.

### Actual behavior

MangaDemon.org is doing the most possible to mess with aggregator websites, so they won't download their chapters automatically from their website. Sadly, this has started to mess up with the last chapters gotten from their website this week.
They've used a button to hide most of the chapters' pages, so it won't load all of them just by opening the chapters' address.

Here is the example: https://mangademon.org/manga/Survival-Story-of-a-Sword-King-in-a-Fantasy-World/chapter/179-raw

### Tachiyomi version

0.14.6

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment] 2023-08-14 13:24
fixed in #17526

**Comment by stevenyomi** [comment] 2023-08-14 13:27
Duplicate of #17516

**Closed by stevenyomi** 2023-08-14 13:27 UTC
Labels: Bug
