### ISSUE TITLE
HTTP error 429

### ISSUE THREAD

**Issue by gali039** [tachiyomiorg/tachiyomi-extensions#18957] opened 2023-11-13 22:03 UTC
### Source information

999hentai

### Source language

English

### Steps to reproduce

HTTP error 429

### Expected behavior

Should be open

### Actual behavior

HTTP error 429

### Tachiyomi version

0.14.7

### Android version

POCO X5 Pro 5G

### Other details

No response

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2023-11-13 22:06
Duplicate of #18950

**Closed by vetleledaal** 2023-11-13 22:06 UTC
Labels: Bug
