### ISSUE TITLE
Source doesn't work 

### ISSUE THREAD

**Issue by 1231971** [tachiyomiorg/tachiyomi-extensions#18423] opened 2023-10-07 17:32 UTC
### Source information

"Manga Starz 1.4.35"

### Source language

"Arabic"

### Steps to reproduce

Web view is working but the source gives "HTTP error  404"

### Expected behavior

![Screenshot_20231007_202656_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/97354788/8db046b6-7975-459c-97bb-683efb015722)

### Actual behavior

![Uploading Screenshot_20231007_202649_Tachiyomi.jpg…]()

### Tachiyomi version

"0.14.6"

### Android version

"Android 11"

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment] 2023-10-08 11:50
Duplicate of #17917

**Closed by AntsyLich** 2023-10-08 11:50 UTC
Labels: Bug
