### ISSUE TITLE
Toonkor extension is outdated.

### ISSUE THREAD

**Issue by KazoEmma** [tachiyomiorg/tachiyomi-extensions#12665] opened 2022-07-21 11:34 UTC
### Source information

Toonkor version1.2.3

### Steps to reproduce

1. Hit on extension to view titles.
2. Shows up nothing.

### Expected behavior

Expect to see the titles load from the toonkor homepage.

### Actual behavior

Shows error 'failed to connect to /99.83.154.118 (port 443) from /192.168.29.243 (port 49962) after 30000ms

### Tachiyomi version

o.13.5

### Android version

Android 10

### Other details

The site tkor.dog has expired and doesn't exist now.
Toonkor extension (korean) doesn't work cuz the site keeps changing the domain every once in a while. the current extension redirects to (tkor.dog) which is an expired domain. 
I'd request to use the toonkor domain links (like toonkor128.com) since I find it more often than tkor domain links.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by DchanN** [comment] 2022-07-21 13:08
Duplicate of #12514

**Closed** 2022-07-21 13:12 UTC
Labels: Bug
