### ISSUE TITLE
MangaDex: Create a preference to change default sort

### ISSUE THREAD

**Issue by Signum21** [tachiyomiorg/tachiyomi-extensions#9160] opened 2021-09-21 00:34 UTC
### Describe your suggested feature

I know I'm spamming at this point and I'm sorry but this could have been avoided by giving me the time to answer by not closing my issue (https://github.com/tachiyomiorg/tachiyomi-extensions/issues/9159) right away ignoring the fact that MangaDex search is not working properly.

I understand that when you browse the extension for the first time it's better to have the most followed manga on top but what about the other 100 times that I have to search for a specific manga? It takes 5 more clicks/taps to fix the sorting and find what you're looking for (eg: Naruto, Akira).

This can be fixed by giving us the possibility to change the default sort order in [this](https://imgur.com/fnHAveh) page.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2021-09-21 00:45
Duplicate of tachiyomiorg/tachiyomi#1484

**Comment by Signum21** [comment] 2021-09-21 00:52
That's an issue from three years ago, wouldn't be bad in the meantime to have the option in the MangaDex extension.

**Comment by paulo27ms** [comment] 2021-09-21 11:52
Instead of hoping an issue from 3 years ago actually gets implemented, we can think of a solution that makes sense for MangaDex given the options it provides.

Relevance exists and obviously makes the most sense in a search but maybe not necessarily on the first screen where nothing is being searched.

Hence, we could potentially check if the search is empty and if it is, we sort by follows, if the search actually has something then automatically default to sorting by relevance.

**Comment by CarlosEsco** [comment] 2021-09-21 13:13
> 
> 
> Instead of hoping an issue from 3 years ago actually gets implemented, we can think of a solution that makes sense for MangaDex given the options it provides.
> 
> Relevance exists and obviously makes the most sense in a search but maybe not necessarily on the first screen where nothing is being searched.
> 
> Hence, we could potentially check if the search is empty and if it is, we sort by follows, if the search actually has something then automatically default to sorting by relevance.

problem with this approach is what if i want to search and i want it sorted by follows.  It will keep changing to relevant

**Comment by CarlosEsco** [comment] 2021-09-21 13:14
I see no reason a default sort option can't be set like the other defaults in the extension settings

**Comment by alessandrojean** [comment] 2021-09-21 15:02
/edit-title "MangaDex: Create a preference to change default sort"

**Comment by peepincreepin** [comment] 2021-12-29 02:27
Just want to add a voice and examples to this issue. IMO the default should be 'Best Match' / 'Most Relevant' as that is the default on the MD site itself. But if not, then we really need an option to change the default sort option to what we need. Because the default sort is by 'Number of Follows', there have been many instances where I couldn't find a manga I was looking for, even though it was actually on MD.

For example:

Searching for the manga MADK on Tachiyomi: Literally cannot find it; there are too many irrelevant results

Searching for the manga MADK on MD direct: 1st result on the page.

**Comment by CarlosEsco** [comment] 2021-12-29 11:58
@peepincreepin Do you have a screenshot that the UI is using most relevant?

**Comment by peepincreepin** [comment] 2021-12-29 13:56
> @peepincreepin Do you have a screenshot that the UI is using most relevant?

Yep!

So this is what I see when I search "MADK" directly on MD:

![Screenshot_20211229-134943_Chrome](https://user-images.githubusercontent.com/83149496/147668948-b49342ef-b2b3-4c23-aa09-73879e5750ad.jpg)

As you can see the default sort is set to Best Match / Most Relevant.

This is what I see when I search through Tachiyomi:

![Screenshot_20211229-022404_Tachiyomi](https://user-images.githubusercontent.com/83149496/147669187-3f1c135d-6e0a-413b-8bc5-4552d8e3170e.jpg)
![Screenshot_20211229-022443_Tachiyomi](https://user-images.githubusercontent.com/83149496/147669191-73d37a20-4336-4d38-997b-d2e76906da04.jpg)

You can see it is because the default order is Number of Followers:

![Screenshot_20211229-135200_Tachiyomi](https://user-images.githubusercontent.com/83149496/147669423-20c76b6f-99cf-4e75-8450-08708b143fba.jpg)


When I change it to Most Relevant, then I get actually good results (the same as the default results when searching MD directly on 'Best Match'):

![Screenshot_20211229-135219_Tachiyomi](https://user-images.githubusercontent.com/83149496/147669472-91486b02-93db-40e1-9728-258f748bf2ee.jpg)
![Screenshot_20211229-135229_Tachiyomi](https://user-images.githubusercontent.com/83149496/147669474-dbab005e-aae4-482a-81e7-67337004480a.jpg)

**Comment by CarlosEsco** [comment] 2021-12-29 13:59
definitely don't mind it switching to relevant, though i remember having some issues  with results before when using it

**Comment by peepincreepin** [comment] 2021-12-29 14:04
> definitely don't mind it switching to relevant, though i remember having some issues with results before when using it

Ahh I see. If it helps I am happy to help test or something to see what the issues with Relevant are? Although I am not a dev so don't really know much!

**Comment by peepincreepin** [comment] 2022-05-29 00:32
Is there any update on this issue? It has gotten even more annoying recently. Before, if you searched the name of the manga using the original Japanese kanji/kana characters, it would give you only the exact result even though the sorting was set to Followers. Now Mangadex has improved their search algorithm, so searching using exact kana/Kanji will produce more results. So I am having to switch to sorting by Relevant almost every single time and it's really annoying how many extra steps it takes.

**Comment by alessandrojean** [comment] 2022-05-29 01:15
There's no ETA. It will get addressed if someone wants to fix this and wants to work on it.

**Comment by curche** [comment] 2022-06-11 06:08
Hello,
Have recently updated MangaDex extension to use Sort by Relevance to match with the same thing that the website Search uses. You can try the search again 
While its technically possible to add a Default Sort, I'm not fine with having 6 sort options each with asc/descending order to choose ~12 options: it's confusing and the UX is better. 
So unless we figure out a better way to do this, continuing to match the default sort with whatever Search uses would be the best alternative

**Comment by Signum21** [comment] 2022-06-11 22:01
It's much better, thanks. The search is still not perfect (Bastard, Akira, Gon) but that depends on MangaDex.

**Comment by peepincreepin** [comment] 2022-06-12 03:08
Thanks so much for this, I really appreciate it.  It's much much better now!

**Comment by alessandrojean** [comment] 2022-06-12 16:48
Closing since it's kinda fixed now, and the search results is now totally up on Dex to fix it if there are any issues.

**Closed by alessandrojean** 2022-06-12 16:48 UTC
Labels: Feature request
