### ISSUE TITLE
Webtoons.com: Not showing results properly in global search

### ISSUE THREAD

**Issue by vipzzx** [tachiyomiorg/tachiyomi-extensions#13222] opened 2022-08-27 02:11 UTC
### Source information and language

Webtoons.com 1.3.35 (All Language)

### Steps to reproduce

1. Search a title in global search Ex: Good Luck, Hero!
2. Scroll down to webtoons.com

### Expected behavior

Show results

### Actual behavior

There is empty space before the webtoons results. Have to scroll over to select it

![Screenshot_20220826-175329_TachiyomiJ2K](https://user-images.githubusercontent.com/59638889/187010186-efeef7ef-892c-4ade-b3f4-83d079c94574.jpg)

### Tachiyomi version

j2k 1.5.8

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ObserverOfTime** [comment] 2022-08-27 18:11
Probably a duplicate of #13157

**Comment by vipzzx** [comment] 2022-08-27 18:55
It doesn't look like a duplicate

**Comment by ObserverOfTime** [comment] 2022-08-27 19:34
It's most likely caused by the same SSL error.

**Comment by Vilacard** [comment] 2023-01-12 01:01
No clue if I have the same issue or not, but the first 3-4 results from webtoons show up as broken images:
https://cdn.discordapp.com/attachments/330794217859186689/1062896322946027530/Screenshot_20230111_184858_Tachiyomi.jpg
If I try to open one, it gives me an error:
https://cdn.discordapp.com/attachments/330794217859186689/1062896322484641873/Screenshot_20230111_184905_Tachiyomi.jpg
Scrolling right on the results will give me actual working ones after those first 3-4.

**Closed** 2023-02-03 18:25 UTC
Labels: Bug
