### ISSUE TITLE
Url change : Azora

### ISSUE THREAD

**Issue by Asmamanhwa** [tachiyomiorg/tachiyomi-extensions#14947] opened 2023-01-14 19:42 UTC
### Source information and language

Azora: ar.azora version 1.3.31

### Source new URL

https://azoranov.com/

### Other details

Arabic application 
Change it fast please

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2023-01-14 19:49
Duplicate of #14925

**Closed by alessandrojean** 2023-01-14 19:49 UTC
Labels: Bug, Domain changed
