### ISSUE TITLE
Truyenqq is broken please fix 

### ISSUE THREAD

**Issue by takahashikajima** [tachiyomiorg/tachiyomi-extensions#10425] opened 2022-01-11 03:40 UTC
### Source information

Truyenqq 1.2.5

### Steps to reproduce

Truyenqq is broken but truyenqq changer domain to
Http://truyenqqvip.com
Please fix the source tks dev

### Expected behavior

Please fix source truyenqq change domain to truyenqqvip.com

### Actual behavior

Broken domains

### Tachiyomi version

0.12.3

### Android version

9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-01-11 03:46
Duplicate of #10321

**Closed by arkon** 2022-01-11 03:46 UTC
Labels: Bug
