### ISSUE TITLE
Asurascans old link

### ISSUE THREAD

**Issue by DrPulver21** [tachiyomiorg/tachiyomi-extensions#16290] opened 2023-05-03 17:14 UTC
### Source information

Asura scans 1.4.45

### Source language

English

### Steps to reproduce

1. Search for example for Player who can't level up on Asura scans host
2. Press "Webview" 
3. Error 404: File not found

### Expected behavior

What should happen is that you reach the page of the manhwa Player who can't level up 

### Actual behavior

Instead, you reach what I guess is an old link to where the manhwa was before. You can find the manhwa if you search for it while on webview, but can't see the new chapters on the Tachiyomi app

### Tachiyomi version

0.14.6

### Android version

Android 13

### Other details

![Screenshot_20230503_185400_Tachiyomi](https://user-images.githubusercontent.com/132485969/235990250-dbfd5e17-9e12-433f-9dad-fff8d372a449.jpg)
![Screenshot_20230503_185326_Tachiyomi](https://user-images.githubusercontent.com/132485969/235990263-94b4c45f-e7ba-4059-b233-53ee395e2fe5.jpg)
![Screenshot_20230503_185354_Tachiyomi](https://user-images.githubusercontent.com/132485969/235990273-a2d19bec-83e4-42ef-a7c1-8d500400ca36.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2023-05-03 17:17
Duplicate of #16251

**Closed by Seishirou101** 2023-05-03 17:17 UTC
Labels: Bug
