### ISSUE TITLE
Http error 404

### ISSUE THREAD

**Issue by DarkSan-cloud** [tachiyomiorg/tachiyomi-extensions#16305] opened 2023-05-04 09:50 UTC
### Source information

Mizumanga 1.4.29

### Source language

Português Brasil 

### Steps to reproduce

The site went through some changes by the developers, where it was offline, but is now operating again 

### Expected behavior

website working

### Actual behavior

not working 

### Tachiyomi version

0.14.6

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2023-05-04 14:32
Duplicate of #16286

**Closed by alessandrojean** 2023-05-04 14:32 UTC
Labels: Bug
