### ISSUE TITLE
The image couldn't load

### ISSUE THREAD

**Issue by hidayatsohif** [tachiyomiorg/tachiyomi-extensions#12774] opened 2022-07-29 07:25 UTC
### Source information and language

Mangahub 1.2.10 (English)

### Steps to reproduce

1. Open the chapter that I want to read.
2. Error appeared.
3. Click on the retry button, and the same error appears.
4. Open the webview, and complete the captcha.
5.  Exit the webview, and the same error appeared.

### Expected behavior

The images should appear after the loading process is done.

### Actual behavior

The notice that said "The image couldn't be reloaded" appeared instead of the images.

### Tachiyomi version

0.13.5

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment] 2022-07-29 07:30
duplicate of #12773

**Closed by Riztard** 2022-07-29 07:30 UTC
Labels: Bug
