### ISSUE TITLE
[Source Request] Website DoujinDesu

### ISSUE THREAD

**Issue by SokKeras** [tachiyomiorg/tachiyomi-extensions#5810] opened 2021-02-12 22:08 UTC
## Source website
- Name: DoujinDesu
- Link: https://doujindesu.info
- Language(s): Indonesian

## Other details
You Create This Extension I'll Give You A Coffe

**Comment by scb261** [comment] 2021-02-12 22:19
Duplicate of #5470

**Closed by scb261** 2021-02-12 22:19 UTC
Labels: Source Request
