### ISSUE TITLE
[CatManga] Chapters not updating

### ISSUE THREAD

**Issue by AcidRav3N1** [tachiyomiorg/tachiyomi-extensions#9270] opened 2021-09-28 11:24 UTC
### Source information

CatManga 1.2.4

### Steps to reproduce

1. Go to library
2. Update library

### Expected behavior

New chapters to be seen

### Actual behavior

![Uploading Screenshot_20210928-132623_Chrome.jpg…]()

### Tachiyomi version

0.12.2

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2021-09-28 11:37
Duplicate of #9256

**Closed** 2021-09-28 11:36 UTC
Labels: Bug
