### ISSUE TITLE
Add new website

### ISSUE THREAD

**Issue by Semq245** [tachiyomiorg/tachiyomi-extensions#10330] opened 2022-01-04 05:19 UTC
### Source name

Swatmanga , goldenmanga

### Source link

https://swatmanga.co/ , https://golden-manga.com/

### Language

Arabic

### Other details

 can u add these 2 websites please ! bc the linkes have changed  💔

https://swatmanga.co/
https://golden-manga.com/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment] 2022-01-04 05:40
Make a issue for a single thing at a time. Duplicate of #10318

**Closed by loocool2** 2022-01-04 05:40 UTC
Labels: Source request
