### ISSUE TITLE
All 1st kiss extension cannot update the manga or show no page found

### ISSUE THREAD

**Issue by Yuiling** [tachiyomiorg/tachiyomi-extensions#14956] opened 2023-01-15 12:49 UTC
### Source information and language

1st kiss English 1.3.35

### Steps to reproduce

![Screenshot_20230115_203452_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/70065844/212541223-a8cd5d8f-072a-487b-ad27-648c4e7c239e.jpg)
 It show the extension didn't support user agent option. And all my manga from this source just went missing or show no page found

![Screenshot_20230115_203523_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/70065844/212541275-217a0dcc-e191-45c6-8ee1-76d2c892aac5.jpg)
 It show no page found when i press any of the chapter. 

### Expected behavior

It should be update the chapter and able to read the manga. 

### Actual behavior

![Screenshot_20230115_204718](https://user-images.githubusercontent.com/70065844/212541429-29ed21cc-97fb-4148-a5b7-f2a8c6cbfdf4.jpg)
 All the 1st kiss related extension have the same issue. 

### Tachiyomi version

TachitomiJ2k App version: 1.6.0 (standard, 6cb319244, 98, 2022-12-17T21:46Z) Android version: 10 (SDK 29) Android build ID: YAL-L61 10.1.0.250(C636E3R2P1) Device brand: HUAWEI Device manufacturer: HUAWEI Device name: HWYAL Device model: YAL-L21 Device product name: YAL-L21H

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment] 2023-01-15 12:55
Duplicate of #14916

**Closed by AntsyLich** 2023-01-15 12:55 UTC
Labels: Bug
