### ISSUE TITLE
Mangas-Origines - image could'nt be loaded

### ISSUE THREAD

**Issue by NeverReset** [tachiyomiorg/tachiyomi-extensions#15629] opened 2023-03-07 23:21 UTC
### Source information and language

Mangas Origines 1.14.31 (French)

### Steps to reproduce

1. Install "Mangas Origines" extension if not already installed
2. Select a random serie
3. Try to read a chapter
4. Every other pages "The image could'nt be loaded"

Or

1. Install "Mangas Origines" extension if not already installed
2. Select a random serie
3. Try to download a chapter
4. Download error "Unexpected URL scheme 'http' or 'https' no scheme was found for ..."

![image](https://user-images.githubusercontent.com/79910346/223574382-60293829-d50c-4990-9a51-11cd6004efb8.png)
![image](https://user-images.githubusercontent.com/79910346/223574427-dd9645b9-db4d-44ce-a89f-079ba756a1f7.png)

### Expected behavior

All images should be loaded or download should be successful

### Actual behavior

We got all the number of pages when you try to read / download a chapter but :

- When reading a chapter every other image shows "Image couldn't be loaded"
- The download fails with error message "Unexpected URL scheme 'http' or 'https' no scheme was found for ..."

### Tachiyomi version

0.14.5

### Android version

Android 12

### Other details

- Webview working to see the images
- We can see the number of pages in the chapter
- Already tried with another User-Agents, same result

- I made some tests on my pc, when I remove in the header the "referer" this one gives me an error 403 on the request to get one image.
I don't know if this can help

I removed the information that probably caused the auto-close, I don't know if there was another way. If there was, I'm sorry in advance.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment] 2023-03-07 23:43
Duplicate of #15628

**Closed by curche** 2023-03-07 23:43 UTC
Labels: Bug
