### ISSUE TITLE
Reaper Scans Not Working Due To Site Update

### ISSUE THREAD

**Issue by ChillyCrimson45** [tachiyomiorg/tachiyomi-extensions#13726] opened 2022-10-06 06:02 UTC
### Source information and language

Reaper Scans 1.3.31

### Steps to reproduce

1. Open The Browse Tab
2. Click On Reaper Scans
3. Http Error 404

### Expected behavior

It Should Open Normally

### Actual behavior

Http Error 404

### Tachiyomi version

0.13.6

### Android version

Android 7

### Other details

The Site Updated And The Extension Needs An Update

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment] 2022-10-06 06:08
Duplicate of #13726

**Closed by loocool2** 2022-10-06 06:08 UTC
Labels: Bug
