### ISSUE TITLE
Manta extension outdated

### ISSUE THREAD

**Issue by sashakeista** [tachiyomiorg/tachiyomi-extensions#14724] opened 2022-12-29 21:19 UTC
### Source information and language

Manta 1.3.3

### Steps to reproduce

When trying to open a chapter, it gives black pages in the middle until the end

### Expected behavior

All pages should be load with images instead black blank page

### Actual behavior

All of the pages are black blank page instead with images

### Tachiyomi version

0.14.2

### Android version

Android 12

### Other details

None

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-12-29 21:24
Duplicate of #14240

**Closed by alessandrojean** 2022-12-29 21:24 UTC
Labels: Bug
