### ISSUE TITLE
Mangasusu No Chapters Found

### ISSUE THREAD

**Issue by Nvbeh6** [tachiyomiorg/tachiyomi-extensions#14435] opened 2022-12-01 22:11 UTC
### Source information and language

Mangasusu 1.3.22 (Indonesia)

### Steps to reproduce

1.Open Tachiyomi 
2.Open Any Manga/Manhwa From Mangasusu Extension
3.Error No Chapters Found

### Expected behavior

Open Normally 

### Actual behavior

![Screenshot_2022-12-02-05-09-42-491_xyz jmir tachiyomi mi](https://user-images.githubusercontent.com/103346344/205169636-1120526b-85ad-47e4-8d3a-3e9981f0a30e.jpg)

### Tachiyomi version

0.14.2

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment] 2022-12-02 11:39
Duplicate of #14353

**Closed** 2022-12-02 11:51 UTC
Labels: Bug
