### ISSUE TITLE
[Bug] <Neox Scanlator>: <Cloudflare error>

### ISSUE THREAD

**Issue by thanosluyang** [tachiyomiorg/tachiyomi-extensions#6207] opened 2021-03-17 22:02 UTC
## Device information
- Tachiyomi version: 0.10.9
- Android version: 7

## Source information
- Name: Neox Scanlator
- Extension version: 1.2.2

## Steps to reproduce
1. Click on the extension or latest.

### Expected behavior
Access content.

### Actual behavior
java.lang.Exception: Failed to bypass Cloudflare error.

## Other details
In webview, Cloudflare page never load, the page is in a loop, but when accessed by the browser, it loads normally. After they have changed their domain, this error happens quite often.

**Comment by MrChuw** [comment] 2021-03-17 23:21
disable google chrome, force the tachiyomi to stop there, open the neox and go to the webview.

**Comment by thanosluyang** [comment] 2021-03-18 00:09
This error with the extension does not always happen, this morning it worked, in the afternoon, coincidentally when they posted Solo Leveling, the error started. The same error happened a few days ago, so I think it has nothing to do with any browser.

**Comment by MrChuw** [comment] 2021-03-18 00:21
I had the problem last time too, and doing this solved the problem (the webview managed to get through cloudflare) I just went to see the error now, and this time it didn't solve it, I'm trying to find a way.

**Comment by thanosluyang** [comment] 2021-03-18 00:50
Thanks for the help, but I think using VPN only to access the site isn't so worth, some incompatibility between the app/extension and Cloudflare mechanism may be causing this problem.

**Comment by alessandrojean** [comment] 2021-03-18 01:30
This is a known issue related to the WebView and happens with [some other sources](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/4804#issuecomment-766463958).

In general, there's nothing that can be done on the extension side to fix it.

I can only suggest waiting a while and see if the site fixes itself or migrate to another source.

**Comment by thanosluyang** [comment] 2021-03-18 04:30
Thanks again for the suggestion, MrChuw, it worked for me too, and thanks for the information, alessandrojean. If you guys want to close this report, I will leave it open in case someone may have the same problem.

**Comment by maz1no** [comment] 2021-03-18 20:58
Since we’re talking about the Neox extension; Instead of having cloudfare issue, I'm having 404 error sometimes, and it will not fix until I reinstall the extension. I wonder what or why is causing this...

**Comment by alessandrojean** [comment] 2021-03-18 21:03
@maz1no HTTP error 404 means page not found. Maybe they're changing the URLs of the mangas or chapters.

**Comment by maz1no** [comment] 2021-03-18 21:05
yeah I know what it means, but this is happening with the whole website, when I click 'browse' or 'recents' for example.

**Comment by alessandrojean** [comment] 2021-03-18 21:16
What happens if you open in WebView when this error occurs?

**Comment by maz1no** [comment] 2021-03-18 21:18
The webview works perfectly fine.

**Comment by alessandrojean** [comment] 2021-03-18 21:20
Then it is something related to the Madara endpoints. I will take a look later.

**Comment by maz1no** [comment] 2021-03-18 21:23
Thank you for your attention 🙏 if you need more info feel free to ask

**Comment by alessandrojean** [comment] 2021-05-13 14:02
@maz1no Are you still having the Error 404 problem in Browse or Recents? I tried to reproduce it on my end, but it's working fine.

**Comment by maz1no** [comment] 2021-05-13 15:08
I was having this issue again in the last 2 days but I solved someway, I think it was the Cloudfare DNS I just activated in the settings. Apparently Neox did some mistakes again. The troubleshooting didn't help anything. @alessandrojean

**Comment by alessandrojean** [comment] 2021-05-13 15:18
> Obs: It was just the manga page having error 404, not the browse or recents.

Then it's them changing the manga URLs, nothing that can be done to fix in the extension. You can however migrate these mangas that are with error from Neox to Neox to update the URL, it will probably solve your issue.

I will submit a PR later to add a warning about this and alert the users to migrate.

I am closing this issue since the Cloudflare loop is gone and the error in the mangas (that is off-topic) can be solved by migration.

**Closed by alessandrojean** 2021-05-13 15:18 UTC
Labels: bug
