### ISSUE TITLE
Mangastk : Extension can be removed 

### ISSUE THREAD

**Issue by Lenoyr** [tachiyomiorg/tachiyomi-extensions#16518] opened 2023-05-20 08:11 UTC
### Source name

Mangastk

### Source language

Spanish

### Source link

https://mangastk.net

### Other details

Dead Site
"Good evening/good day/good afternoon, please receive a warm greeting everyone. This message is to inform you that 'MANGASTK' is permanently closed. We reserve our privacy policy. Thank you and goodbye." 
It is a message from your Telegram.

![imagen](https://github.com/dazedcat19/FMD2/assets/65477084/c6c338c7-8632-4fd7-bc99-f80a5d24e0f3)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment] 2023-05-20 10:04
Duplicate of #16016

**Closed by stevenyomi** 2023-05-20 10:04 UTC
Labels: Source is down
