### ISSUE TITLE
YugenMangas

### ISSUE THREAD

**Issue by KasukeLp23** [tachiyomiorg/tachiyomi-extensions#13710] opened 2022-10-04 15:33 UTC
### Source information and language

YugenMangas 1.3.27

### Steps to reproduce

Go to extension
Open extension

### Expected behavior

Titles usually appear in the extension

### Actual behavior

HTTP ERROR 404

### Tachiyomi version

0.13.6

### Android version

Android 11

### Other details

Apparently they redesigned the page and caused this problem
In Webview it opens normally

![Screenshot_2022-10-04-17-21-45-240_eu kanade tachiyomi](https://user-images.githubusercontent.com/70596255/193862449-09793d72-fbdc-4954-be03-f2d5907e185b.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-10-04 15:35
Duplicate of #13709

**Closed by alessandrojean** 2022-10-04 15:35 UTC
Labels: Bug
