### ISSUE TITLE
Can't view or download from Bato.to English

### ISSUE THREAD

**Issue by Killuanaa** [tachiyomiorg/tachiyomi-extensions#12031] opened 2022-06-01 03:22 UTC
### Source information

Batot.to 1.2.22

### Steps to reproduce

1. Select a manga.
2. Read the manga.

### Expected behavior

Should open the manga directly on the app.

### Actual behavior

Can't read or download from Batot.to in the app I have to go to the website.

### Tachiyomi version

0.13.4

### Android version

Android 8.1.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-06-01 03:23
Duplicate of #12026

**Closed by arkon** 2022-06-01 03:23 UTC
Labels: Bug
