### ISSUE TITLE
Worldmanhwas

### ISSUE THREAD

**Issue by Start38** [tachiyomiorg/tachiyomi-extensions#16457] opened 2023-05-16 02:03 UTC
### Source information

Worldmanhwas 1.4.30

### Source language

Indonesian 

### Steps to reproduce

1.Open the worldmanhwas extension 
2.Select the comic you want to read
3.And select the comic chapter, And the image can't be loaded

### Expected behavior

It should display the chapter image 

### Actual behavior

Not displaying 

### Tachiyomi version

0.14.6

### Android version

11

### Other details

![Screenshot_2023_0516_090209](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/120931895/90e7e003-a065-4e3c-a3a8-f4a9e4c113f3)

On the website can display chapters

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Start38** [comment] 2023-06-17 10:30
when will this be fixed

**Comment by scb261** [comment] 2023-06-23 16:10
Duplicate of #16793

**Closed by scb261** 2023-06-23 16:10 UTC
Labels: Bug
