### ISSUE TITLE
PMScans/Rackusreads, not manga showing

### ISSUE THREAD

**Issue by VgX-LeGenDz** [tachiyomiorg/tachiyomi-extensions#17752] opened 2023-08-31 22:08 UTC
### Source information

PMScans 1.4.29

### Source language

English 

### Steps to reproduce

When browsing for manga, no results are found

### Expected behavior

Expected behaviour is to show the collection of media on the website 

### Actual behavior

What actually happens is nothing appearing 

### Tachiyomi version

0.14.6

### Android version

Android 11

### Other details

It seems like the website is correct but there are just no results showing

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2023-09-15 14:22
Duplicate of #14331

**Closed by vetleledaal** 2023-09-15 14:22 UTC
Labels: Bug
