### ISSUE TITLE
Mangaowl1.2.23

### ISSUE THREAD

**Issue by Delmarcop52** [tachiyomiorg/tachiyomi-extensions#10460] opened 2022-01-14 14:09 UTC
### Source information

Mangaowl1.2.23

### Steps to reproduce

Fixing mangaowl

### Expected behavior

It says no pages found

### Actual behavior

Mangaowl1.2.23 is not working and it keeps saying that no pages found

### Tachiyomi version

0.12 .23

### Android version

Motola 1999

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-01-14 14:10
Duplicate of #10453

**Closed by arkon** 2022-01-14 14:10 UTC
Labels: Bug
