### ISSUE TITLE
[Feature Request] <Viz>: <Read history is reset after logout>

### ISSUE THREAD

**Issue by autive42** [tachiyomiorg/tachiyomi-extensions#7052] opened 2021-05-16 19:57 UTC
## What feature should be added to this source?
Viz read history is reset for all non-free chapters each time viz auto logs out. It would be very nice to have read history persist across logouts.

**Comment by alessandrojean** [comment] 2021-05-16 20:11
The extension only shows the locked chapters if you are logged in, and for precaution hide them when the session expires, it's how it works. I am not sure and don't know how the app handles this chapter list changes, but I don't think there's anything that can be done to fix this on the extension side, it's probably an app issue.

Closing this since hiding the locked chapters when the user is logged out and only showing them when the user is logged in is the intended behavior.

**Closed by alessandrojean** 2021-05-16 20:11 UTC
Labels: enhancement
