### ISSUE TITLE
MangasTK doesn't load chapters 

### ISSUE THREAD

**Issue by cruzerzix** [tachiyomiorg/tachiyomi-extensions#14362] opened 2022-11-24 01:33 UTC
### Source information and language

MangasTK 1.3.27

### Steps to reproduce

1. Open a manga
2. Select the only chapter available (show a different update date )
3. Don't show pages

### Expected behavior

Should show the chapters for his lecture 

### Actual behavior

Doesn't show the chapters 

### Tachiyomi version

0.14.2 

### Android version

12 (SDK31)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment] 2022-12-24 09:22
duplicate of #14175

**Closed by Riztard** 2022-12-24 09:22 UTC
Labels: Bug, Factory source
