### ISSUE TITLE
Manhwa-Latino no pages

### ISSUE THREAD

**Issue by Zer03021** [tachiyomiorg/tachiyomi-extensions#15389] opened 2023-02-17 19:49 UTC
### Source information and language

Manhwa-Latino 1.4.22 (Español)

### Steps to reproduce

1. Open extension
2. Choose any manga/manhwa from the library
3. View any chapter

### Expected behavior

![Screenshot_2023-02-17-15-33-03-08_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/94061318/219776285-3b50a877-e156-4840-8294-d53dc18375ec.jpg)

### Actual behavior

![Screenshot_2023-02-17-15-33-06-55_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/94061318/219776459-02624587-662e-4ef0-972f-539cd58676f1.jpg)

### Tachiyomi version

0.14.4

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2023-02-17 20:11
Duplicate of #15356

**Closed by alessandrojean** 2023-02-17 20:11 UTC
Labels: Bug
