### ISSUE TITLE
Mangahub Error 403

### ISSUE THREAD

**Issue by 77k4** [tachiyomiorg/tachiyomi-extensions#12930] opened 2022-08-10 18:21 UTC
### Source information and language

Mangahub 1.3.14

### Steps to reproduce

Manga from mangahub source can't update

### Expected behavior

Can open source and update from source

### Actual behavior

Can't update and open source

### Tachiyomi version

1.13.5

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2022-08-10 18:23
Duplicate of #12929

**Closed by Seishirou101** 2022-08-10 18:23 UTC
Labels: Bug
