### ISSUE TITLE
1st kiss and mangachill giving http error 400

### ISSUE THREAD

**Issue by 4cactusjackburgers** [tachiyomiorg/tachiyomi-extensions#15314] opened 2023-02-11 15:56 UTC
### Source information and language

1stKiss Manga 1.4.36. English and Mangachill 1.4.34 English 

### Steps to reproduce

Opens a title sourcing from 1st kiss manga or mangachill
Source shows http error 400 
The cover doesn't load and it says no chapter found

### Expected behavior

Should be able to update and read as per usual 

### Actual behavior

Doesn't load anything sourcing from those websites 

### Tachiyomi version

0.14.4

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2023-02-11 16:02
Please open one issue per source next time.

Duplicate of #15281

**Closed by alessandrojean** 2023-02-11 16:02 UTC
Labels: Bug
