### ISSUE TITLE
Problem with the extension Dragontranslation 

### ISSUE THREAD

**Issue by JuanCRMorenoo** [tachiyomiorg/tachiyomi-extensions#15981] opened 2023-04-06 19:25 UTC
### Source information

Dragontranslation 1.4.32

### Source language

Spanish 

### Steps to reproduce

1. Won't let the extension open 
2. I tried to solve it with the help troubleshooting  that tachyomi provides regarding this problem.
3. After doing what the help tells me to the corresponding error that is "HTTP error 400" Nothing works.

### Expected behavior

be able to open the extension 

### Actual behavior

be able to open the extension 

### Tachiyomi version

1.6.4

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by scb261** [comment] 2023-04-06 19:45
Duplicate of #15313

**Closed by scb261** 2023-04-06 19:45 UTC
Labels: Bug
