### ISSUE TITLE
Library feature

### ISSUE THREAD

**Issue by demon456blade** [tachiyomiorg/tachiyomi-extensions#13100] opened 2022-08-20 02:56 UTC
### Source name and language

Nhentai 

### Describe your suggested feature

So the feature I wanted to request was being able to make specific extension not be able to update for example like nhentai and the reason I say this is because nhentai do not continue the multi work series but instead have another doujin part 2 of a multiple work series ,so nhentai being updated in library is just useless.

### Other details

It could be like specific extensions can update their manga or doujins for example hentai2read update their multi work series

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-08-20 03:05
Duplicate of tachiyomiorg/tachiyomi#6539

**Closed by alessandrojean** 2022-08-20 03:05 UTC
Labels: Feature request
