### ISSUE TITLE
Source Image Fail

### ISSUE THREAD

**Issue by BaoBunni** [tachiyomiorg/tachiyomi-extensions#14024] opened 2022-10-29 05:01 UTC
### Source name and language

Bato.to

### Describe your suggested feature

![Screenshot_20221028_235935_Tachiyomi](https://user-images.githubusercontent.com/110514042/198814792-f40754f1-2044-4bce-8be1-ed04dd7eafde.jpg)

When visiting this source, the images show no image and just a ripped paper. Other sources has no issues bar this one in specific 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.0](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-10-29 10:32
Wrong form (should be issue report instead) and duplicate of #12849.

**Closed by alessandrojean** 2022-10-29 10:32 UTC
Labels: Feature request

**Comment by BaoBunni** [comment] 2022-10-30 02:33
Oh sorry, I didn't know which to choose, I'll redo it! Thank you!!Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Alessandro Jean ***@***.***> Date: 10/29/22  5:32 AM  (GMT-06:00) To: tachiyomiorg/tachiyomi-extensions ***@***.***> Cc: BaoBunni ***@***.***>, Author ***@***.***> Subject: Re: [tachiyomiorg/tachiyomi-extensions] Source Image Fail (Issue #14024) 
Wrong form (should be issue report instead) and duplicate of #12849.

**Comment by alessandrojean** [comment] 2022-10-30 02:43
No need, there's already an open issue for this issue.
