### ISSUE TITLE
Http error 404 not correct

### ISSUE THREAD

**Issue by Farisgamil** [tachiyomiorg/tachiyomi-extensions#16330] opened 2023-05-06 10:31 UTC
### Source information

Asura scans 1.4.45

### Source language

English

### Steps to reproduce

Example:
Step one : go to a certain manga in this source
Step two: refresh this manga
Step three: says https error 404

### Expected behavior

It should load the new chapters

### Actual behavior

But it says to me error and The Source is not dead I made sure it's not dead

### Tachiyomi version

0.14.6

### Android version

Android 12

### Other details

A lot of warnings that a lot of different mongers from the same source might hurt the source I tried clearing the cache clearing the data uninstalling and reinstalling tachiyomi didn't work

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by kyoyacchi** [comment] 2023-05-06 10:48
https://github.com/tachiyomiorg/tachiyomi-extensions/issues/16251

**Comment by arkon** [comment] 2023-05-06 14:06
Duplicate of #16251

**Closed by arkon** 2023-05-06 14:06 UTC
Labels: Bug
