### ISSUE TITLE
No Pages Found

### ISSUE THREAD

**Issue by Rouruki** [tachiyomiorg/tachiyomi-extensions#9917] opened 2021-11-23 23:07 UTC
### Source information

manga-raw.club

### Steps to reproduce

No pages found

### Expected behavior

N/A

### Actual behavior

No pages found on opening chapters even visiting the site thru webview is fine. Happens last night just reporting the issue just now coz its still not fix.

### Tachiyomi version

0.12.3

### Android version

Android 10

### Other details

This issue happens back then days ago.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vipzzx** [comment] 2021-11-23 23:23
This is a known issue.

**Comment by arkon** [comment] 2021-11-23 23:28
Duplicate of #9876

Don't bump issues.

**Closed by arkon** 2021-11-23 23:28 UTC
Labels: Bug
