### ISSUE TITLE
Doujindesu: cover not showing

### ISSUE THREAD

**Issue by 5cmperS3K0N** [tachiyomiorg/tachiyomi-extensions#11674] opened 2022-04-30 02:22 UTC
### Source information

Doujindesu 1.2.2

### Steps to reproduce

open the doujindesu extension, all the comics have no cover.

### Expected behavior

cover loaded properly

### Actual behavior

the cover does not appear and is not updated

### Tachiyomi version

0.13.4

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-04-30 02:26
Duplicate of #11662

**Closed by alessandrojean** 2022-04-30 02:26 UTC
Labels: Bug
