### ISSUE TITLE
1st Kiss : Thumbnails/Cover image not showing

### ISSUE THREAD

**Issue by Beji-kun** [tachiyomiorg/tachiyomi-extensions#8979] opened 2021-09-05 23:16 UTC
### Source information

1st Kiss v1.2.16

### Steps to reproduce

1. open library dont show cover/thumbnails (its same in update and migration when I open 1st Kiss)
Other extensions no problem.

### Expected behavior

Not showing thumbnails 

### Actual behavior

Thumbnails of 1st Kiss not showing. I try on 2 phone and result its same. Other extensions its OK - 1st Kiss Manga.love v1.2.11, 1st Kiss Manhua v1.2.13, manga-raw.club v1.2.3, and other OK

### Tachiyomi version

v0.12.1

### Android version

Android 10(Huawei P30 Lite) and Android 8(Honor 8)

### Other details
**Screenshots of bugs**
[https://drive.google.com/drive/folders/1AI_LbfK37mh60QT1epf_4kifTOArrUA0?usp=sharing](url)
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2021-09-05 23:41
Duplicate of #8726

**Closed** 2021-09-05 23:42 UTC
Labels: Bug

**Comment by Rhymee09** [comment] 2021-09-06 10:18
I have the same problem too. How can I fix this? 🥲
