### ISSUE TITLE
Toongod

### ISSUE THREAD

**Issue by Natoram** [tachiyomiorg/tachiyomi-extensions#10887] opened 2022-02-21 14:42 UTC
### Source information

Toongod 1.2.17

### Steps to reproduce

On clicking the extension showing retry error but toongod website working fine . But extension not working at all please fix the issue please.

### Expected behavior

Extension should open normally

### Actual behavior

On clicking the extension showing retry error but toongod website working fine . But extension not working at all please fix the issue please.

### Tachiyomi version

0.13.1

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Shadow10969** [comment] 2022-03-01 07:31
Toongod 1.2.18 still not working for me 
Android 11 
Tachiyomi 0.13.1

**Comment by Shadow10969** [comment] 2022-03-01 07:33
I hope this issue will be fixed soon i have a specific manhwa that toongod only has an update

**Comment by vetleledaal** [comment] 2022-03-21 00:08
Duplicate of #9738

**Closed** 2022-03-21 00:09 UTC
Labels: Bug
