### ISSUE TITLE
The chapters of this extension are not loading

### ISSUE THREAD

**Issue by AlexDvorak7** [tachiyomiorg/tachiyomi-extensions#14985] opened 2023-01-16 22:54 UTC
### Source information and language

Mangabuddy 1.3.12 (English)

### Steps to reproduce

1-Access the extension 
2-Choose a manga and try to read a chapter 
3-Chapter images do not load.

### Expected behavior

should show up in the global search normally and load the chapters.

### Actual behavior

in the global search the error 404 appears and the chapters do not load.

### Tachiyomi version

0.14.3

### Android version

Android 11

### Other details

Works normally on WebView but not in the app.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment] 2023-01-16 22:59
>  I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open or closed issue.

Duplicate of #14967

**Closed by curche** 2023-01-16 22:59 UTC
Labels: Bug
