### ISSUE TITLE
Extension "Manhwas Men" is not opening, giving error HTTP 404.

### ISSUE THREAD

**Issue by Fakhr456** [tachiyomiorg/tachiyomi-extensions#14213] opened 2022-11-10 06:15 UTC
### Source information and language

Manhwas Men 1.3.6 (English)

### Steps to reproduce

1. I opened the app and clicked the extension.
2. After trying to establish a connection it gave the error "HTTP error 404: Check website in WebView".
3. The website was opening in WebView. 
4. After closing WebView, I tried to open the extension again, but it gave the same error. 
![Screenshot_20221110-105911_Tachiyomi](https://user-images.githubusercontent.com/31977994/201013973-f119d67a-3860-4f2b-886c-eb8b36e611c1.jpg)

### Expected behavior

If everything worked correctly the manhwa should have been displayed in the app, to read and download. 

### Actual behavior

Every time I open the extension, I get the error "HTTP error 404: Check website in WebView".

![Screenshot_20221110-105911_Tachiyomi](https://user-images.githubusercontent.com/31977994/201014055-4dc8a3ea-4d31-4e7c-a7cb-0531baef49be.jpg)

Even opening in WebView does not resolve the issue. 

Note: The website is opening in WebView, just not in the app. 

### Tachiyomi version

0.14.2

### Android version

10

### Acknowledgements

- [ ] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ff2400t** [comment] 2022-11-10 18:31
duplicate of #13201

**Comment by Fakhr456** [comment] 2022-11-13 06:12
Any eta on when the fix might arrive?

**Closed** 2022-11-17 10:36 UTC
Labels: Bug
