### ISSUE TITLE
Mangahub problem 

### ISSUE THREAD

**Issue by crazydevil9** [tachiyomiorg/tachiyomi-extensions#12778] opened 2022-07-29 10:07 UTC
### Source information and language

Mangahub

### Steps to reproduce

It won't load images of chapter from any manga from the source. If u try different one it won't load. 

### Expected behavior

What should happen is it should load the images. 

### Actual behavior

Hope it gets fix. 

### Tachiyomi version

App version: 0.13.5 

### Android version

Samsung galaxy s20 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment] 2022-07-29 10:45
>  I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open issue.

Duplicate of https://github.com/tachiyomiorg/tachiyomi-extensions/issues/12773

**Closed by curche** 2022-07-29 10:45 UTC
Labels: Bug
