### ISSUE TITLE
InariManga: No results found

### ISSUE THREAD

**Issue by Lanyxx** [tachiyomiorg/tachiyomi-extensions#17916] opened 2023-09-12 13:46 UTC
### Source information

InariManga 1.4.32

### Source language

Spanish

### Steps to reproduce

1. Open extension: https://inarimanga.com/
2. Get manhwa and all
3. Fetch the chapters

### Expected behavior

Search Manhwa name and put it in the library.

### Actual behavior

No results found.

![20230912_064610](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/87540723/84355a13-06ea-492e-9635-7f1777c63ff1)

### Tachiyomi version

1.6.6 (TachiJ2K)

### Android version

Android 13

### Other details

I use the TachiJ2K application version.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2023-09-15 14:22
Duplicate of #16426

**Closed by vetleledaal** 2023-09-15 14:22 UTC
Labels: Bug
