### ISSUE TITLE
Shinigami Cannot enter the website

### ISSUE THREAD

**Issue by RoSiCyBeR** [tachiyomiorg/tachiyomi-extensions#18709] opened 2023-10-25 12:41 UTC
### Source information

Shinigami 1.4.36

### Source language

Indonesia 

### Steps to reproduce

Open tachiyomi>shinigami

 

### Expected behavior

I'm using a coffee shop wifi but when I open shinigami in WebView the cloudflare it's loading to fast redirect to `blob:`
At the same time I use cellular data can verify it's says failure

### Actual behavior

Pls fix it 

### Tachiyomi version

0.14.6

### Android version

Android 10

### Other details

https://github.com/tachiyomiorg/tachiyomi-extensions/assets/34416860/feb3bb73-7b01-4e60-98e8-9a9dbe2f1f27

![Screenshot_20231025-194123](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/34416860/e8290ae2-5c25-49d5-8e98-abcc9f1ab14b)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-10-25 13:21
Duplicate of https://github.com/tachiyomiorg/tachiyomi/issues/10060

**Closed by arkon** 2023-10-25 13:21 UTC
Labels: Bug
