### ISSUE TITLE
ERROR 403

### ISSUE THREAD

**Issue by Jen0930** [tachiyomiorg/tachiyomi-extensions#9900] opened 2021-11-22 16:50 UTC
### Source information

"1st Kiss 1.2.18" & "1st Kiss Manga.love 1.2.12"

### Steps to reproduce

![Screenshot_20211123-002450_Tachiyomi](https://user-images.githubusercontent.com/77537166/142898943-2973e2f1-1532-45cd-9e55-f2db733d31cb.jpg)

### Expected behavior

This should happen in 1st kiss & 1st kiss manga.love when i click it show the manga books and you can read.

### Actual behavior

This happen instead in 1st kiss you click its show error 403 & on 1st kiss manga.love its show the manga books but when you click the chapter the chapter cannot load the image its say "Retry again" but i have a internet.

### Tachiyomi version

0.12.3

### Android version

Android 11

### Other details

![Screenshot_20211123-002625_Tachiyomi](https://user-images.githubusercontent.com/77537166/142901816-50295adf-450e-4801-b523-62c50835ab4e.jpg)
![Screenshot_20211123-002618_Tachiyomi](https://user-images.githubusercontent.com/77537166/142901824-7826850f-4485-4ae1-88b4-2f3c83b66e7c.jpg)
![Screenshot_20211123-002450_Tachiyomi](https://user-images.githubusercontent.com/77537166/142901834-9c30e4d4-abab-437f-b6a0-2b57cd7554d4.jpg)
![Screenshot_20211123-002437_Tachiyomi](https://user-images.githubusercontent.com/77537166/142901838-0d7127b9-4b96-43ac-b67a-58024d195117.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Monticellos** [comment] 2021-11-22 17:02
I've gotten this before. I cleared cache and everything and then restarted the app, but all that didnt work for me. I restarted my phone and then it started working.

**Comment by Kush-Patel** [comment] 2021-11-23 05:35
Please fix this ASAP

**Comment by Seishirou101** [comment] 2021-11-23 05:39
Duplicate of #9377

**Closed** 2021-11-23 05:39 UTC
Labels: Bug
