### ISSUE TITLE
[Source Request] <ScanSamurai>

### ISSUE THREAD

**Issue by Elcrack14** [tachiyomiorg/tachiyomi-extensions#7751] opened 2021-06-19 15:06 UTC
## Source website
- Name: ScanSamurai
- Link: https://samuraiscan.com/
- Language(s): Spanish (Es)

**Comment by Clouddark75** [comment] 2021-06-20 16:29
Duplicate of #7427
The source change to a new variation of CMS not supported by Tachi.

**Closed** 2021-06-20 16:30 UTC
Labels: Source Request
