### ISSUE TITLE
Manga Toon Bad URL created (NXDOMAIN)

### ISSUE THREAD

**Issue by KatoMegushua** [tachiyomiorg/tachiyomi-extensions#18523] opened 2023-10-13 02:08 UTC
### Source information

MangaToon (Limited) 1.4.4

### Source language

Multi language

### Steps to reproduce

1 installs extension
2 use extension

### Expected behavior

1 installs extension
2 use extension
3 read extension titles

### Actual behavior

1 install the extension
2 use the extension
3 when trying to read the titles of the extension it does not load and when trying to open in web view it shows an error in the url 

### Tachiyomi version

Stable 0.14.6

### Android version

Android 13

### Other details

![270234697-02048602-d9b8-42f3-9049-7c4a88b76d10](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/145884813/049329d0-1b16-4fb5-a779-3e819fe7ca1f)
![270234735-d6205602-9e38-42ae-9716-07a93e485ba2](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/145884813/4a0fd380-ea47-4104-b68d-d7747cc536a3)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment] 2023-10-13 09:56
Duplicate of #18137

**Closed by AntsyLich** 2023-10-13 09:56 UTC
Labels: Bug
