### ISSUE TITLE
webtoon.com mistakenly thinks it fails to update comics

### ISSUE THREAD

**Issue by JumperCzech** [tachiyomiorg/tachiyomi-extensions#13360] opened 2022-09-05 17:24 UTC
### Source information and language

Webtoons.com 1.3.36

### Steps to reproduce

1. add a comic from webtoons.com to your library and 2. try updating it (tested with Unordinary and one other forgot name)

### Expected behavior

no error

### Actual behavior

when there is an update to the comic, everything works properly and it gets updated, but when there isn't one, you get this error 
![IMG_20220905_191918](https://user-images.githubusercontent.com/83337894/188494526-fb340a64-ef94-4964-a043-4a8b9b4bcd9c.jpg)

### Tachiyomi version

App version: 0.13.6 (standard, 1f79444, 82, 2022-08-14T15:52Z) 

### Android version

Android version: 11 (SDK 30) Android build ID: RKQ1.211001.001

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ObserverOfTime** [comment] 2022-09-06 07:30
Duplicate of #13157

**Closed** 2022-09-06 12:09 UTC
Labels: Bug
