### ISSUE TITLE
Truyengihot change source 

### ISSUE THREAD

**Issue by Taki132** [tachiyomiorg/tachiyomi-extensions#17612] opened 2023-08-20 17:40 UTC
### Source information

Truyengihot 1.4.3

### Source language

Vietnamese 

### Source new URL

https://truyengihotnhat.com/

### Other details

The old source not work
![Screenshot_20230821_003543_TachiyomiJ2K](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/92381976/fcf3b442-ad63-45df-bcc0-e61cc53aa540)
![Uploading Screenshot_20230821_235927_Chrome.jpg…]()

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but I formative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by Taki132** [comment] 2023-08-21 16:51
I'm so sorry but correct source is [https://truyengihotnhat.com](https://truyengihotnhat.com)
Truyengihotvay.com is the fake link, I get the new link on [https://www.facebook.com/may2necacban?mibextid=ZbWKwL](Mary hạ lục 2) they have any update on this manhwa and they only work on truyengihot source

**Comment by vetleledaal** [comment] 2023-09-14 07:33
Duplicate of #17523

**Closed by vetleledaal** 2023-09-14 07:33 UTC
Labels: Bug, Domain changed
