### ISSUE TITLE
Chnage New Site WeLoveManga

### ISSUE THREAD

**Issue by JvstBolt** [tachiyomiorg/tachiyomi-extensions#12419] opened 2022-07-03 01:36 UTC
### Source information

WeLoveManga 1.3.10

### Steps to reproduce

Extension don't work

### Expected behavior

New Scans Website https://welovemanga.one/

### Actual behavior

Change to new site https://welovemanga.one/

### Tachiyomi version

0.13.4

### Android version

Android 11

### Other details

Change to new site https://welovemanga.one/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by DchanN** [comment] 2022-07-03 02:27
duplicate of #11719 , actually the real domain it's https://5slive.net/ , from original rawlh -> welovemanga ->nng9.com ->5slive.net

not sure about https://welovemanga.one/ can be count as new source or requested to be multisrc

**Comment by alessandrojean** [comment] 2022-07-03 18:23
As it's a new source, please open an source request issue if you want it to be added.

**Closed by alessandrojean** 2022-07-03 18:23 UTC
Labels: Bug
