### ISSUE TITLE
Manhuas.net not working 

### ISSUE THREAD

**Issue by Adrianfedz** [tachiyomiorg/tachiyomi-extensions#15597] opened 2023-03-05 18:12 UTC
### Source information and language

manhwas.net 1.4.5 (spanish)

### Steps to reproduce

It doesn't work I can't read any manga they have the 403 error

### Expected behavior

Open Extension
Manhwa/Manga Library loads

### Actual behavior

Open Extension
It shows "HTTP error 403: Check website on Webview

### Tachiyomi version

0.14.5

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2023-03-06 12:08
Duplicate of #15563

**Closed by alessandrojean** 2023-03-06 12:08 UTC
Labels: Bug
