### ISSUE TITLE
Mangakakalot.fun

### ISSUE THREAD

**Issue by vncrack** [tachiyomiorg/tachiyomi-extensions#12961] opened 2022-08-13 09:51 UTC
### Source information and language

Mangakakalot.fun 1.3.6

### Steps to reproduce

1. Open mangakakalot source
2. Choose a chapter

### Expected behavior

Chapter loads normally

### Actual behavior

Field 'data' is required for type with serial name

### Tachiyomi version

0.13.5

### Android version

Android 12

### Other details

Updates and webview work

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by dalex78** [comment] 2022-08-13 10:50
I have a similar error for `MangaOnline.fun 1.3.6`, `MangaToday 1.3.6` and `MangaHub 1.3.16`.
Exact error code is: `Field 'data' is required for type with serial name 'eu.kanade.tachiomi.multisrc.mangahub.GraphQLDataDto', but it was missing`

**Comment by ibitachi** [comment] 2022-08-13 12:39
same goes with MangaHub ext
![Uploading Screenshot_2022-08-13-20-21-14-756_eu.kanade.tachiyomi.jpg…]()

**Comment by arkon** [comment] 2022-08-13 14:15
Duplicate of #12959

**Closed by arkon** 2022-08-13 14:15 UTC
Labels: Bug

**Comment by Beji-kun** [comment] 2022-08-13 14:27
Same problem in 1manga.cc extension too

![Screenshot_2022-08-13-16-25-04-076_eu.kanade.tachiyomi.jpg](https://user-images.githubusercontent.com/63636174/184498545-4f2c8201-46d3-453d-ae4b-89e4dcf71dee.jpg)
