### ISSUE TITLE
Mangakatana 

### ISSUE THREAD

**Issue by Viva1HA** [tachiyomiorg/tachiyomi-extensions#13078] opened 2022-08-19 06:25 UTC
### Source information and language

Mangakatana version 1.2.8

### Steps to reproduce

Opened the app, and clicked on new chapters of tokyo revengers and eleceed

### Expected behavior

More than 1 page per chapter 😂

### Actual behavior

Many mangas had 1 page per chapter 
![Screenshot_20220819-022231](https://user-images.githubusercontent.com/95601264/185556191-c151928f-e296-4ce6-9607-4dc804a68b07.png)

### Tachiyomi version

App version: 0.13.6 

### Android version

9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by flgsercan** [comment] 2022-08-19 10:09
Same problem here. I don't know if it will be helpful but here is some extra info.
Before this bug, I got 502 bad gateway error from mangakatana twice and when it loaded there would be random pages not loaded at all.

**Comment by KIDNDM** [comment] 2022-08-19 11:26
duplicate of #13062

**Closed** 2022-08-19 11:30 UTC
Labels: Bug
