### ISSUE TITLE
Aresmanga 

### ISSUE THREAD

**Issue by Tadaningenda** [tachiyomiorg/tachiyomi-extensions#14691] opened 2022-12-27 16:33 UTC
### Source information and language

"aresmanga 1.3.23 Arabic"

### Source new URL

https://aresmanga.net/

### Other details

Thanks

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2022-12-27 16:59
Duplicate of #14676

**Closed by vetleledaal** 2022-12-27 16:59 UTC
Labels: Bug, Domain changed
