### ISSUE TITLE
MangaHub: Chapters are not loading

### ISSUE THREAD

**Issue by Davidbolt121199** [tachiyomiorg/tachiyomi-extensions#15197] opened 2023-01-31 14:24 UTC
### Source information and language

MangaHub 1.3.23

### Steps to reproduce

1. After new update chapters are not loading.
2. While browsing website it shows chapters and all pages.
3. After new update chapters pages where incomplete it only shows 6 pages.

### Expected behavior

It should have uploaded new chapters with all pages.

### Actual behavior

Instead showing
![Screenshot_2023-01-30-20-42-04-244_eu kanade tachiyomi-edit 1](https://user-images.githubusercontent.com/121578582/215785781-265b7663-22b7-472d-a220-09063d43fdf0.jpg)
![Screenshot_2023-01-31-09-37-02-354_eu kanade tachiyomi 1](https://user-images.githubusercontent.com/121578582/215785458-fe286e46-053b-4d62-aa45-2d43296aceb9.jpg)

### Tachiyomi version

0.14.3

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-01-31 14:26
Duplicate of #15196

**Closed by arkon** 2023-01-31 14:26 UTC
Labels: Bug
