### ISSUE TITLE
CopyManga

### ISSUE THREAD

**Issue by sunze1016** [tachiyomiorg/tachiyomi-extensions#9178] opened 2021-09-22 04:54 UTC
### Source information

CopyManga 1.2.15

### Steps to reproduce

Not available

### Expected behavior

Not available

### Actual behavior

Not available

### Tachiyomi version

0.12.2

### Android version

11

### Other details

Did you give up this plugin?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment] 2021-09-22 07:01
Duplicate of #9114

**Closed by loocool2** 2021-09-22 07:01 UTC
Labels: Bug
