### ISSUE TITLE
Mangarolls is down

### ISSUE THREAD

**Issue by Baymax325** [tachiyomiorg/tachiyomi-extensions#18044] opened 2023-09-19 08:08 UTC
### Source information

MangaRolls

### Source language

English

### Steps to reproduce

Open extension
Open manhwa

### Expected behavior

Should be able to read manhwa

### Actual behavior

Does not show manhwa
Timeout and failed to connect keep in appearing 

### Tachiyomi version

0.14.6

### Android version

Android 13

### Other details

It started 3 days ago but it worked for a short time 2 days ago. Now it won't work.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2023-09-30 12:34
Can't reproduce. Timeouts usually indicate an issue with the site itself, but it seems to have fixed itself. I'm closing this issue, but if you are still experiencing issues with the extension, do comment with the manhwa and chapter you are trying to read.

**Closed by vetleledaal** 2023-09-30 12:34 UTC
Labels: Bug
