### ISSUE TITLE
1st kiss the chapters won't load

### ISSUE THREAD

**Issue by fuentez145** [tachiyomiorg/tachiyomi-extensions#9356] opened 2021-10-04 02:21 UTC
### Source information

1st kiss 1.12.17

### Steps to reproduce

1. 1st kiss extension
2. Any manhwas in that extension
3. Open any chapters
4. Won't load

### Expected behavior

The chapters should be loaded

### Actual behavior

But every time I tried to open chapters and any manhwas it wont load. Its automatically stop to load like "retry"

### Tachiyomi version

0.12.2

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment] 2021-10-04 02:21
Duplicate of #7810

**Closed by loocool2** 2021-10-04 02:21 UTC
Labels: Bug

**Comment by fuentez145** [comment] 2021-10-04 02:31
The issues for #7810 was on june, its expected that the website improves

**Comment by loocool2** [comment] 2021-10-04 02:32
If it hasn't been closed yet, assume that it's still a issue
