### ISSUE TITLE
Mangafire extension not loading content

### ISSUE THREAD

**Issue by Sapon40** [tachiyomiorg/tachiyomi-extensions#17915] opened 2023-09-12 13:35 UTC
### Source information

Mangafire 

### Source language

English

### Steps to reproduce

1. Open mangafire extension 

### Expected behavior

Content should load when extension is opened

### Actual behavior

![Screenshot_20230912_153340_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/101672142/9ca60462-f2c9-43ae-a000-ce8eebc38ddb)

### Tachiyomi version

0.14.6

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2023-09-12 13:39
Duplicate of #17715

**Closed by Seishirou101** 2023-09-12 13:39 UTC
Labels: Bug
