### ISSUE TITLE
PMScans: Displaying fake chapters

### ISSUE THREAD

**Issue by Eragonnogare** [tachiyomiorg/tachiyomi-extensions#12541] opened 2022-07-11 17:00 UTC
### Source information

PMScans 1.3.16

### Steps to reproduce

1. Open a series from PMScans
2. Try to load/download a chapter

### Expected behavior

The actual chapter should load

### Actual behavior

The chapter is covered by black boxes/shuffled around/has fake text/etc

### Tachiyomi version

0.13.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2022-10-02 01:19
Can't reproduce. Do you have an example manga and chapter where this occurs?

**Comment by Seishirou101** [comment] 2022-11-22 15:07
closing as op did not respond

**Closed by Seishirou101** 2022-11-22 15:07 UTC
Labels: Bug
