### ISSUE TITLE
API LIMIT EXCEED

### ISSUE THREAD

**Issue by Szeroo91** [tachiyomiorg/tachiyomi-extensions#17152] opened 2023-07-17 04:17 UTC
### Source information

mangahub.io

### Source language

english

### Steps to reproduce

![Screenshot_2023-07-17-11-39-25-084_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/139734012/8d4264e9-4d76-49d2-9bad-aa0927970b75)
i cant acces the chapters how do i fix this
it's always like this.

### Expected behavior

i should be reading the chapters but i can't open it

### Actual behavior

![Screenshot_2023-07-17-11-39-25-084_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/139734012/9178eb80-6a21-47fd-8ec2-94ab77325b6d)
this happened instead of reading

### Tachiyomi version

0.14.6

### Android version

Android 13

### Other details

it's already been months but its all thesame i cant read in the tachiyomi now

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment] 2023-07-17 04:27
Duplicate of #16481

**Closed** 2023-07-17 13:29 UTC
Labels: Bug
