### ISSUE TITLE
Webwiew manga pages not loading

### ISSUE THREAD

**Issue by ArminArlert31** [tachiyomiorg/tachiyomi-extensions#17246] opened 2023-07-24 18:54 UTC
### Source information

Manga-TR

### Source language

Turkish

### Steps to reproduce

1) open tachiyomi
2) open Manga-TR
3) open any manga
4) image not loaded error
5) open in webview
6) same error
7) when I open it in the browser. the images are loading

### Expected behavior

pages need to be loaded

### Actual behavior

pages are not loading

### Tachiyomi version

0.14.16

### Android version

Android 9

### Other details

Manga-TR version 1.4.9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment] 2023-07-25 12:41
Duplicate of #16013

**Closed by stevenyomi** 2023-07-25 12:41 UTC
Labels: Bug
