### ISSUE TITLE
[Extencion] <Mangatigre>

### ISSUE THREAD

**Issue by allastor007** [tachiyomiorg/tachiyomi-extensions#6105] opened 2021-03-09 01:37 UTC
*Hello, could you include support for mangatigre.com?

Name: manga tigre
Web: https://www.mangatigre.com
Spanish Language
  Note: As I am not a programmer, I cannot give more details. I'm sorry to ask too much with my request so poor.

**Comment by MerradOklom** [comment] 2021-03-09 02:15
Duplicate of #2821

**Closed** 2021-03-09 02:16 UTC
Labels: Source Request
