### ISSUE TITLE
Image opening error in Everia.club 1.2.2

### ISSUE THREAD

**Issue by esthapa** [tachiyomiorg/tachiyomi-extensions#11496] opened 2022-04-17 06:01 UTC
### Source information

Everia.club 1.2.2

### Steps to reproduce

Image is not opening

### Expected behavior

The image is there and the page number

### Actual behavior

It shows that:'The image couldn't be loaded'

### Tachiyomi version

"0.13.3"

### Android version

"Android 10"

### Other details

The image doesn't opening and main thumbnail is not loading 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-04-17 14:25
Duplicate of #10918

**Closed by alessandrojean** 2022-04-17 14:25 UTC
Labels: Bug
