### ISSUE TITLE
Hitomi.la doesn't work

### ISSUE THREAD

**Issue by Talbis** [tachiyomiorg/tachiyomi-extensions#10486] opened 2022-01-17 04:52 UTC
### Source information

Hitomi.la All 1.2.16

### Steps to reproduce

The extension doesn't produce any search results, even if you know a certain title is there.
Upon further checking, despite the site working fine, the extension gets an HTTP error 403.

The issue is most prevalent while searching. It prolongs the search by a large margin and produces no results, just wasting time.

### Expected behavior

It should produce a search result of some kind, especially when I know that a certain title is in fact on the website.

It should also produce a list of the newest titles when opened instead of an HTTP error 403.

### Actual behavior

It prolongs the loading of the search results, on one occasion even making it seem like Tachiyomi itself froze.

It produces an HTTP error 403 while trying to browse the extension contents itself, like the newest titles added.

### Tachiyomi version

0.12.3

### Android version

Android 11

### Other details

I admit it does sound like the Cloudflare issue and the WebView works fine, but that's a workaround, not a solution. If I wanted to use Hitomi.la website, I wouldn't need Tachiyomi in the first place. It worked fine just a week ago and now this... 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-01-17 13:18
Duplicate of #10319

**Closed by arkon** 2022-01-17 13:18 UTC
Labels: Bug
