### ISSUE TITLE
مانجا ليك

### ISSUE THREAD

**Issue by ShefOoO0** [tachiyomiorg/tachiyomi-extensions#12550] opened 2022-07-12 05:13 UTC
### Source information

مانجا ليك 1.3.22

### Steps to reproduce

Open the source and choose a manhwa to read
When clicking on the chapter
A message appear '' failed to bybass cloudflare '' and the chapter close on it's own

### Expected behavior

The chapter will open and i can read and download it

### Actual behavior

It didn't work and i can't download it 

### Tachiyomi version

0.13.5

### Android version

11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment] 2022-07-12 05:25
Duplicate of #11366

**Closed by loocool2** 2022-07-12 05:25 UTC
Labels: Bug
