### ISSUE TITLE
No chapters found 

### ISSUE THREAD

**Issue by Golisopod88** [tachiyomiorg/tachiyomi-extensions#8968] opened 2021-09-04 17:06 UTC
### Source information

Mangadex 1.2.111

### Steps to reproduce

Opening some doujins in mangadex doesn't work.
It keeps saying chapter not found

### Expected behavior

Chapter should be available

### Actual behavior

Chapter isn't available

### Tachiyomi version

Tachiyomi j2k 1.2.1

### Android version

MiUi 12.5

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment] 2021-09-04 18:03
Duplicate of #8937

**Closed** 2021-09-04 18:04 UTC
Labels: Bug
