### ISSUE TITLE
Extension roumanwu error failed to load manga

### ISSUE THREAD

**Issue by jiapenghe** [tachiyomiorg/tachiyomi-extensions#18908] opened 2023-11-10 02:59 UTC
### Source information

Roumanwu 1.4.5

### Source language

Chinese

### Steps to reproduce

1.Can't load manga, chapter.
2.extension main page error.
Fields [headline, best, hottest, daily, recentUpdatedBooks, endedBooks] are required for type withserial name 'eu.kanade.tachiyomi.extension.zh.roumanwu.HomePage' but they were missing at path$.props.pageProps

### Expected behavior

After selected the sources roumanwu, should come out the manga titles, cover.

### Actual behavior

Show below error code after selected the sources. 

Fields [headline, best, hottest, daily, recentUpdatedBooks, endedBooks] are required for type withserial name 'eu.kanade.tachiyomi.extension.zh.roumanwu.HomePage' but they were missing at path$.props.pageProps

@stevenyomi 

### Tachiyomi version

0.14.7

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment] 2023-11-21 16:46
Duplicate of #18960

**Closed** 2023-11-21 16:46 UTC
Labels: Bug, Duplicate
