### ISSUE TITLE
Doujin desu "No pages found" and Cover broken

### ISSUE THREAD

**Issue by Miellenials** [tachiyomiorg/tachiyomi-extensions#14221] opened 2022-11-10 17:48 UTC
### Source information and language

Doujindesu 1.3.3 (Indonesia)

### Steps to reproduce

1. Open in extension browser 
2. (Cover is broken)
![Screenshot_20221111-004420](https://user-images.githubusercontent.com/65380422/201168997-f4856b98-e425-441f-a461-6d5534f97398.png)

3. Open the manga
4. Open the chapter, shown "no pages found"
5. 
![Screenshot_20221111-004427](https://user-images.githubusercontent.com/65380422/201169058-82f50ab1-453e436f-8b16-68ed54bc6158.png)

6. Open in webview, all nornal. I can read it too like nornal

### Expected behavior

Can open nornally

### Actual behavior

No pages found

### Tachiyomi version

App version: 0.14.2-5202 (standard, 3733871d2, 91, 2022-11-05T21:10Z) Android version: 12 (SDK 31) Android build ID: SKQ1.211103.001 Device brand: lge Device manufacturer: LGE Device name: flashlmdd Device model: LM-V500N Device product name: flashlmdd_lao_com

### Android version

android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Miellenials** [comment] 2022-11-10 17:48
![Screenshot_20221111-004427](https://user-images.githubusercontent.com/65380422/201169446-41f304b3-ce15-489b-bbf2-c1e563e51a16.png)

**Comment by Miellenials** [comment] 2022-11-10 17:55
![Screenshot_20221111-005315](https://user-images.githubusercontent.com/65380422/201170394-ee05766c-a7b9-4b97-98d2-2da9ddcf84ab.png)
As additional information, i always using DoH from tachiyomi and i can open all of the banned 18+ extension normally. Like for example, porncomix and allporncomic. E-hentai, if doh disabled all of sites i mentioned sent different error

**Comment by arkon** [comment] 2022-11-10 17:57
Duplicate of #14004

**Closed by arkon** 2022-11-10 17:57 UTC
Labels: Bug
