### ISSUE TITLE
numbers marked as -1

### ISSUE THREAD

**Issue by Frozik29** [tachiyomiorg/tachiyomi-extensions#11980] opened 2022-05-26 03:51 UTC
### Source information

Neox Scanlator 1.2.33

### Steps to reproduce

Update the url, enter the source and enter any work

### Expected behavior

should show the right numbers as usual

### Actual behavior

is showing like -1

### Tachiyomi version

0.13.4

### Android version

11

### Other details

I always updated the url and this never occurred to me, I don't know if it was just me, but I waited a few days for an update to appear, but it didn't, I'm looking for some help I don't know if I'm using the site perfectly so please if anyone can let me know about something I'll be very grateful, and I've heard that the site has changed the layout if that is of any help

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-05-26 03:51
Duplicate of #11954

**Closed by alessandrojean** 2022-05-26 03:51 UTC
Labels: Bug
