### ISSUE TITLE
Vyvymanga needs an update 

### ISSUE THREAD

**Issue by Mashiyat14** [tachiyomiorg/tachiyomi-extensions#13753] opened 2022-10-07 21:38 UTC
### Source information and language

Vyvymanga 

### Steps to reproduce

It does not contain infinite scrolling. After 7 or 8 rows, previously updated mangas are showing again.

### Expected behavior

Vyvymanga should have infinite scrolling.

### Actual behavior

Normally every extension has infinite scrolling. But in vyvymanga same mangas are repeated after certain scrolling.

### Tachiyomi version

1.3.1

### Android version

11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-10-07 21:39
Duplicate of #12824

**Closed by arkon** 2022-10-07 21:39 UTC
Labels: Bug
