### ISSUE TITLE
MangaGeko extension not working...

### ISSUE THREAD

**Issue by Mara101-Anna** [tachiyomiorg/tachiyomi-extensions#18866] opened 2023-11-05 19:05 UTC
### Source information

MangaGeko  v 1.4.19

### Source language

English

### Steps to reproduce

.

### Expected behavior

.

### Actual behavior

MangaGeko v 1.4.19  is not working after the update today on Tachiyomi J2K.
It shows NO RESULT FOUND, while searching any Manga/Manhwa 

PLEASE HELP
I HAVE ALL MY MANGA ON THIS EXTENSION

![Screenshot_2023-11-06-00-34-28-32_5901a79de973a50c74cff4cbb6149856](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/149746498/6301c11c-68ad-4be0-ae64-d501f6c67b38)
![Screenshot_2023-11-06-00-33-27-39_5901a79de973a50c74cff4cbb6149856](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/149746498/3d74e3b1-549d-49d2-abdb-878eec713289)

### Tachiyomi version

Tachiyomi J2K  1.7.3

### Android version

13

### Other details

MangaGeko  v 1.4.19   is not working after the update today on Tachiyomi J2K.

It shows NO RESULT FOUND, while searching any Manga/Manhwa 

PLEASE HELP
I HAVE ALL MY MANGA ON THIS EXTENSION

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by pizidavi** [comment] 2023-11-05 19:14
Duplicate of #18861 and already fixed in #18854 
But the build is not completed, not related to the extension

**Comment by Mara101-Anna** [comment] 2023-11-07 04:25
All Good 😊

**Comment by Mara101-Anna** [comment] 2023-11-07 04:25
Awesome 😎

**Closed** 2023-11-07 04:25 UTC
Labels: Bug
