### ISSUE TITLE
Requesting a new JP and EN extension

### ISSUE THREAD

**Issue by GeassKnightmare** [tachiyomiorg/tachiyomi-extensions#14215] opened 2022-11-10 13:03 UTC
### Source name

Bilingualmanga 

### Source link

https://bilingualmanga.net

### Language

English and Japanese

### Other details

Very good website with JP raw and mangas completed translated to english 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-11-10 13:07
Duplicate of #7411, not possible to make it into an extension.

**Closed by alessandrojean** 2022-11-10 13:07 UTC
Labels: Source request

**Comment by GeassKnightmare** [comment] 2022-11-10 13:11
Oh that's a shame
