### ISSUE TITLE
[Bug] Martial scans>: <error 404>

### ISSUE THREAD

**Issue by mcOz1** [tachiyomiorg/tachiyomi-extensions#6195] opened 2021-03-17 08:33 UTC
## Device information
- Tachiyomi version: 0.10.9
- Android version:  5.1.1

## Source information
- Name: Martial Scans
- Extension version: 1.2.1

## Steps to reproduce
1. First Step open extensions
2. Second Step 

### Expected behavior
open normally

### Actual behavior
error 404 show up

**Comment by scb261** [comment] 2021-03-17 09:19
Duplicate of #5728

**Closed by scb261** 2021-03-17 09:19 UTC
Labels: bug
