### ISSUE TITLE
Sunshine Buttefly Scans: Changed their domain

### ISSUE THREAD

**Issue by Yumi182** [tachiyomiorg/tachiyomi-extensions#11908] opened 2022-05-18 23:54 UTC
### Source information

Sunshine Buttefly Scans 1.2.21

### Steps to reproduce

1. Download available Sunshine Buttefly Scans extension from app
2. Open extention
3. HTTP error 404

### Expected behavior

the titles should be loaded in the app

### Actual behavior

HTTP error 404 and when click on web view, website no longer exist under the same address
![Screenshot_20220518-165124_Chrome](https://user-images.githubusercontent.com/105827378/169173679-7e5ad0b5-3b40-4cd8-913c-ec9592410a63.jpg)

### Tachiyomi version

0.13.4

### Android version

Android 12

### Other details

New web address for the scan group is https://wings.sbs/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by zbue** [comment] 2022-06-24 10:57
Duplicate of https://github.com/tachiyomiorg/tachiyomi-extensions/issues/11200

**Closed** 2022-06-24 11:14 UTC
Labels: Bug, Domain changed
