### ISSUE TITLE
[Bug] Rain of Snow: Only loads first batch of images

### ISSUE THREAD

**Issue by DatHypnoboi** [tachiyomiorg/tachiyomi-extensions#6757] opened 2021-04-29 09:18 UTC
## Device information
- Tachiyomi version: SY 1.6.2
- Android version: 11

## Source information
- Name: Rain of Snow
- Extension version: 1.2.5

## Steps to reproduce
1. Open chapter 16 of "It All Starts With Playing Game Seriously"
2. Scroll to end, chapter is cut off part way through

### Expected behavior
It should have loaded the full chapter from the site

### Actual behavior
It only loads up until the first Read More button

## Other details
Seems to have been caused by the site loading images in batches separated by pressing a Read More button

**Comment by Seishirou101** [comment] 2021-04-29 09:22
duplicate of #6631

**Closed** 2021-04-29 10:14 UTC
Labels: bug
