### ISSUE TITLE
[Bug] <TCB Scans>: <Can someone please fix it>

### ISSUE THREAD

**Issue by FireNation323** [tachiyomiorg/tachiyomi-extensions#7434] opened 2021-06-03 22:01 UTC
## Device information
- Tachiyomi version: j2k 1.0.17
- Android version: Android 10

## Source information
- Name: TCB Scan
- Extension version: 1.2.3

## Steps to reproduce
1. Open the extension

### Expected behavior
It should show you the available manga

### Actual behavior
No result

## Other details
I know someone already reported this but it's been a month and it's still not fixed

**Comment by h-hyuuga** [comment] 2021-06-03 22:07
Duplicate of #6869 

Please remember that Tachiyomi is maintained by volunteers, and that filing duplicate bug reports is not conducive to a prompt response

**Closed** 2021-06-03 22:09 UTC
Labels: bug

**Comment by Titus30** [comment] 2021-06-04 09:36
It is still broken
