### ISSUE TITLE
Chapter not showing 

### ISSUE THREAD

**Issue by Xaijain** [tachiyomiorg/tachiyomi-extensions#9737] opened 2021-11-04 17:01 UTC
### Source information

Manga-raw.club

### Steps to reproduce

browsing manga-raw.club extension
you will only see 100 chapters other chapter doesn't shows

### Expected behavior

All chapter should have shown

### Actual behavior

Instead of showing all chapter it shows 100 chapter 

### Tachiyomi version

0.12.3

### Android version

Android 11

### Other details

![IMG_20211104_224532](https://user-images.githubusercontent.com/91004345/140384948-36f84e7f-2259-4aaa-bc00-3e78b47a01b7.jpg)
![Screenshot_2021-11-04-22-44-32-05_dd604340c1d7941d42aee14dd16e00e8](https://user-images.githubusercontent.com/91004345/140384962-23c16727-9130-40d3-bdf2-8f9f2d42c49e.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by CVIUS** [comment] 2021-11-04 17:19
Duplicate of #9643

**Closed** 2021-11-04 17:22 UTC
Labels: Bug
