### ISSUE TITLE
Baozi Manhua Connection reset

### ISSUE THREAD

**Issue by smarttommyau** [tachiyomiorg/tachiyomi-extensions#17381] opened 2023-08-04 13:28 UTC
### Source information

Baozi Manhua 1.4.20

### Source language

中文

### Steps to reproduce

read chapter or download a chapter

### Expected behavior

it should able to load image, or download the chapter

### Actual behavior

cannot load. when download chapter a socket connection reset message appears.

### Tachiyomi version

0.14.6

### Android version

Harmony os 3(AOSP Android 11)

### Other details

it should probably because the url change in the content part,  it always redirect to www. dzmanga.com for the content where this mirror does not exist in the extension. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment] 2023-08-04 13:35
Duplicate of #17322

**Closed by stevenyomi** 2023-08-04 13:35 UTC
Labels: Bug

**Comment by strbug** [comment] 2023-08-04 13:38
昨天晚上貌相就看不了图了，插件其他功能都正常，就是看漫画图片就显示无法加载该图片，也下载不了，试过换ip和改ua都没用。
