### ISSUE TITLE
[Source Request] <hentaidexy>

### ISSUE THREAD

**Issue by Saiyajin777** [tachiyomiorg/tachiyomi-extensions#6947] opened 2021-05-10 11:11 UTC
## Source website
- Name: hentaidexy
- Link: hentaidexy.com
- Language(s): english

**Comment by jopejoe1** [comment] 2021-05-10 13:53
Madara

**Comment by alessandrojean** [comment] 2021-06-04 02:45
Duplicate of #6413.

**Closed by alessandrojean** 2021-06-04 02:45 UTC
Labels: Source Request
