### ISSUE TITLE
arabshentai

### ISSUE THREAD

**Issue by Ghilas951** [tachiyomiorg/tachiyomi-extensions#8452] opened 2021-08-07 18:52 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

arabshentai

### Source link

https://arabshentai.com/manga

### Language

Arabic

### Other details

![Capture+_2021-08-07-19-51-56](https://user-images.githubusercontent.com/87284048/128611007-bfe889de-0287-4e87-88f7-29959226a66c.png)

**Comment by shipoxx** [comment] 2021-08-08 12:26
يا رجل لم اكن أعلم أن هناك مواقع هنتاي عربية هذا غريب!

**Comment by CHAOSX0** [comment] 2021-08-08 13:41
> يا رجل لم اكن أعلم أن هناك مواقع هنتاي عربية هذا غريب!

yeah that is weird af

**Comment by alessandrojean** [comment] 2021-08-08 15:58
Duplicate of #6189

**Closed by alessandrojean** 2021-08-08 15:58 UTC
Labels: Source request

**Comment by arkon** [comment] 2021-08-08 15:59
@Ghilas951 Do not post NSFW content on GitHub.
