### ISSUE TITLE
[Bug] Mangakakalot: Some Chapters don't load

### ISSUE THREAD

**Issue by Kazu-sama12** [tachiyomiorg/tachiyomi-extensions#4337] opened 2020-09-08 15:48 UTC
## Device information
Tachiyomi version: v0.10.4
Android version: 8.0.0

## Source information
- Name: Mangakakalot
- Extension version: 1.2.24

## Steps to reproduce
1. Open Chapter

### Expected behavior
Chapter Loads images 

### Actual behavior
Images don't load 

![Screenshot_20200908-233244](https://user-images.githubusercontent.com/65352930/92498907-c9b8c100-f22d-11ea-8a41-603345156a2a.jpg)

## Other details
Some of the chapters load but a few of them don't. For example what I am currrebtly reading "Martial Peak" chapter 81 doesn't load but other chapters load properly.

**Comment by Riztard** [comment] 2020-11-06 14:19
it work just fine :/ did you try check on webview?

**Comment by orhantopac** [comment] 2021-01-18 21:04
As Mangakakalot allows you to select 2 servers, sometimes, some files on server 1 is gone, on webview or on their site, you can select server 2, but this plugin automatically gets all the images frome server 1.  There may be a logic-added in to the extension, so if server 1 x page could not load, it may try to get the corresponding page from server 2. I got similar issues for some series, especially for older content.

**Comment by scb261** [comment] 2021-02-12 01:35
Original post - probably was temporary issue on their side, as it works fine for Riztard and me.
Comment about changing image server - duplicate of #2720.

**Closed by scb261** 2021-02-12 01:35 UTC
Labels: bug
