### ISSUE TITLE
Source/Data is Missing

### ISSUE THREAD

**Issue by David05-0** [tachiyomiorg/tachiyomi-extensions#12967] opened 2022-08-13 14:11 UTC
### Source information and language

MangaHub 1.3.16

### Steps to reproduce

![Screenshot_20220813_183715](https://user-images.githubusercontent.com/82562921/184497859-ebf5af79-85d2-4efa-b420-f9ca23673fd1.jpg)

### Expected behavior

This should redirect to the chapter 

### Actual behavior

![Screenshot_20220813_183715](https://user-images.githubusercontent.com/82562921/184497879-a41aa6d3-c209-42b2-8f0f-5d7c1936a989.jpg)

### Tachiyomi version

0.13.5

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-08-13 14:14
Duplicate of #12959

**Closed by arkon** 2022-08-13 14:14 UTC
Labels: Bug
