### ISSUE TITLE
comichub

### ISSUE THREAD

**Issue by wende1l** [tachiyomiorg/tachiyomi-extensions#10647] opened 2022-02-01 18:43 UTC
### Source information

comichub 1.2.15

### Steps to reproduce

try searching invincible compendium or invincible

### Expected behavior

source should be work fine

### Actual behavior

![Screenshot_2022_0201_213045](https://user-images.githubusercontent.com/98842384/152030601-42882d82-144b-48f6-be24-18291aecd3fe.jpg)
![Screenshot_2022_0201_213103](https://user-images.githubusercontent.com/98842384/152030628-732f48c9-7f85-41c1-b577-a2727a241b7e.jpg)
i try the read invincible compendium and i see source is dead. afyer trying the webview send me some movie website

### Tachiyomi version

0.13.1

### Android version

android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-02-01 18:50
Duplicate of #10578

**Closed by alessandrojean** 2022-02-01 18:50 UTC
Labels: Bug
