### ISSUE TITLE
Doujindesu: Changed their domain 

### ISSUE THREAD

**Issue by uzumakhiadi** [tachiyomiorg/tachiyomi-extensions#12750] opened 2022-07-27 07:59 UTC
### Source name

Doujindesu

### Source link

http://212.32.226.234/

### Language

Indonesia

### Other details

18+

http://212.32.226.234/
or
http://doujindesu.xxx/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment] 2022-07-27 15:21
Duplicate of #11662

**Indonesian NXDOMAIN error**
Indonesian carriers and ISPs are blocking sites using DNS, causing NXDOMAIN errors. They may prevent you from switching to other DNS providers using DNS hijacking/redirection, TCP reset attacks, SNI filtering, and Deep Packet Inspection.
**What can I do to fix it?**
Try turning on DNS over HTTPS under More 🡒 Advanced 🡒 DNS over HTTPS.
**That Didn't Work!**
Your ISP may be using the new blocking mechanism. Use a VPN or use a Deep Packet Inspection Bypass app like [DPITunnel-cli](https://github.com/zhenyolka/DPITunnel-android), [PowerTunnel](https://github.com/krlvm/PowerTunnel), or [GoodbyeDPI](https://github.com/ValdikSS/GoodbyeDPI)

**Closed** 2022-07-27 15:22 UTC
Labels: Source request
