### ISSUE TITLE
Completed Filter Doesn't Work on MangaDex Titles

### ISSUE THREAD

**Issue by zinklog2** [tachiyomiorg/tachiyomi-extensions#12976] opened 2022-08-13 21:22 UTC
### Source information and language

MangaDex 1.3.166

### Steps to reproduce

Try to filter any MangaDex Title as completed

### Expected behavior

Titles which have finished publishing should be shown

### Actual behavior

All titles are filtered out regardless of its publishing status

### Tachiyomi version

TachiyomiJ2k v1.5.6

### Android version

11

### Other details

Just a guess on my end but other sources show Completed tag on manga which are finished while mangadex shiws 'publishing finished'. Probably the completed filter is only checking for completed tag and thus filters all mangadex titles.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-09-27 19:31
I am not able to reproduce that, using the Status filter with `Completed` checked is working as expected on my end, by showing titles marked as either `Completed` or `Publishing Finished` only.

Please check if this is happening in Tachiyomi Stable.

**Comment by alessandrojean** [comment] 2022-10-24 23:07
Closing due to inactivity and not being able to reproduce. If you're still facing this please provide some examples and the issue can be reopened.

**Closed by alessandrojean** 2022-10-24 23:07 UTC
Labels: Bug
