### ISSUE TITLE
[Bug] TsukiMangas>: Pages not load

### ISSUE THREAD

**Issue by matheuswr89** [tachiyomiorg/tachiyomi-extensions#5207] opened 2020-12-19 23:10 UTC
## Device information
- Tachiyomi version: 0.10.6
- Android version: 10

## Source information
- Name: TsukiMangas
- Extension version: 1.2.7

### Expected behavior
The manga pages are expected to load, just like on the website

### Actual behavior
![Screenshot_20201219-200637](https://user-images.githubusercontent.com/44068234/102701467-0a18d980-4236-11eb-93a9-aed9d470872a.png)

You can see in the image above that the pages no longer load
## Other details
I believe that some changes were made to the links, to access the images

**Comment by matheuswr89** [comment] 2020-12-19 23:14
@alessandrojean foi mal atrapalhar o seu final de semana aí

**Comment by scb261** [comment] 2020-12-19 23:29
Duplicate of #5204, it was fixed, wait for update to 1.2.8

**Comment by arkon** [comment] 2020-12-19 23:31
Reopen this if 1.2.8 didn't work.

**Closed by arkon** 2020-12-19 23:31 UTC
Labels: bug
