### ISSUE TITLE
La biblioteca de los otakus

### ISSUE THREAD

**Issue by Elcrack1412** [tachiyomiorg/tachiyomi-extensions#7999] opened 2021-07-07 04:11 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

Otakuteka

### Source link

https://otakuteca.com

### Language

Spanish (Es)

**Comment by loocool2** [comment] 2021-07-07 11:09
Why are you using a alt account to post a duplicate of a closed issue? It's not going to change the outcome. Duplicate of #7585

**Closed by loocool2** 2021-07-07 11:09 UTC
Labels: Source request
