### ISSUE TITLE
Url for manhuas on 'comick' changed, error 404 thrown

### ISSUE THREAD

**Issue by ZerefTribbiani** [tachiyomiorg/tachiyomi-extensions#15407] opened 2023-02-19 22:33 UTC
### Source information and language

Comick 1.4.20 

### Steps to reproduce

Try to update Martial Peak

### Expected behavior

It updates

### Actual behavior

Error 404 is thrown

### Tachiyomi version

0.14.5

### Android version

Android 10

### Other details

Webview uses the link
https://comick.app/comic/martial-peak
The correct link for the website is 
https://comick.app/comic/martial-peak-2

This issue occurs for all the other manhuas (not manga) I read using this source (Apotheosis, Omniscient Reader's Viewpoint, The Gamer, The Legendary Moonlight Sculptor)
They all had a "-2" added to the url

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2023-02-21 20:18
Duplicate of #14788. For now you can try migrating from Comick to Comick.

**Closed by vetleledaal** 2023-02-21 20:18 UTC
Labels: Bug
