### ISSUE TITLE
Reaperscans.id change url to shinigami.id

### ISSUE THREAD

**Issue by FathiRaihan** [tachiyomiorg/tachiyomi-extensions#15409] opened 2023-02-20 00:12 UTC
### Source information and language

https://reaperscans.id/

### Source new URL

https://shinigami.id/

### Other details

The extension is a multi language extension. So it's better to separate and create a new extension 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2023-02-20 00:33
Duplicate of #15408

**Closed by alessandrojean** 2023-02-20 00:33 UTC
Labels: Bug, Domain changed
