### ISSUE TITLE
extension apk failing install

### ISSUE THREAD

**Issue by ghartwell** [tachiyomiorg/tachiyomi-extensions#8803] opened 2021-08-24 13:52 UTC
### Source information

tachiyomi-all.mangadex-v1.2.128.apk

### Steps to reproduce

When installing extension update through adb, install fails.
Command used:
$ adb -s emulator-5554 install tachiyomi-all.mangadex-v1.2.128.apk

Not the first new extension to throw error, other examples include
tachiyomi-en.mangahere-v1.2.17.apk
tachiyomi-en.mangapark-v1.2.22.apk
tachiyomi-en.mangalife-v1.2.22.apk

### Expected behavior

$ adb -s emulator-5554 install tachiyomi-v0.12.1.apk
Success

### Actual behavior

$ adb -s emulator-5554 install tachiyomi-en.mangalife-v1.2.22.apk 
adb: failed to install tachiyomi-en.mangalife-v1.2.22.apk: Failure [INSTALL_PARSE_FAILED_NOT_APK: Failed to parse /data/app/vmdl1296023422.tmp/base.apk]

### Tachiyomi version

0.12.1

### Android version

ChromeOS Version 92.0.4515.157 (Official Build) (64-bit)

### Other details

Split APK installer states no AndroidManifest.xml and fails with the same error.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2021-08-24 14:22
I've confirmed all those extensions install fine through normal android package manager, split apk installer, and adb.
Where are you getting the apks? The website? It's possible that your browser/file manager may be doing something funky to the downloads. Could you try to see if you can download on another device and transferring it over? preferably on a pc. If that doesn't work, it may be Chrome OS related as the extensions are made for Android

**Comment by ghartwell** [comment] 2021-08-24 15:08
I'm downloading directly from the github releases. I'll try the alternative download methods. I'm afraid it might be Chrome OS and the android side loading. The strange part is how it installed successfully under mangadex v1.2.127 but not v1.2.128 or maybe one of the couple chrome os updates since the last release.

**Comment by Seishirou101** [comment] 2021-08-24 15:14
By github releases you mean the [repo](https://github.com/tachiyomiorg/tachiyomi-extensions/tree/repo/apk) correct? If so then yeah other than corrupted download, I can't think of anything else. I don't think the extensions do anything fancy so the side loading of chrome os is just not compatible for whatever reason.

**Comment by arkon** [comment] 2021-09-01 17:24
Closing since this seems like a Chrome OS issue.

**Closed by arkon** 2021-09-01 17:24 UTC
Labels: Bug
