### ISSUE TITLE
Yaoi Manga Online unable to view and download

### ISSUE THREAD

**Issue by CactusTheGuy** [tachiyomiorg/tachiyomi-extensions#19257] opened 2023-12-10 03:54 UTC
### Source information

Yaoi Manga Online 1.4.2

### Source language

English

### Steps to reproduce

1. Open a comic, give an example comic name to search.
2. Start searching and press a random comic
3. When open, wait a few second untill a error at the bottom show "NullPointerException: null is show up" and only one chapter name "Chapter" is shown with the date is "today"
![Screenshot_2023-12-10-10-37-01-922_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/75614340/450a13de-816d-4422-a5d9-10b225677470)
4. Start download a chapter, wait untill a notification error shown "no page found"
![Screenshot_2023-12-10-10-37-29-285_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/75614340/2a27e6aa-bebb-4d71-8b67-f572207ab302)

### Expected behavior

Able to view all chapter as shown in the image and able to download all chapters
![Screenshot_2023-12-10-10-46-55-490_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/75614340/eb121ed7-ac29-4e4c-b9cd-7b8f8302f66c)

### Actual behavior

Error shown "NullPointerException: null is show up" and only one chapter name "Chapter" is shown with the date is "today"
Download is error with error shown "no page found"

### Tachiyomi version

0.14.7

### Android version

MIUI 14.0.8 Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2023-12-11 15:07
Duplicate of #14982

**Closed by vetleledaal** 2023-12-11 15:07 UTC
Labels: Bug
