### ISSUE TITLE
cocomanhua extension doesn't work since July 30th

### ISSUE THREAD

**Issue by mojunisme** [tachiyomiorg/tachiyomi-extensions#8359] opened 2021-08-01 20:03 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

cocomanhua 1.2.7 extension doesn't work since July 30th. I can't download or read pictures of coco manga on tachiyomi, but the website of cocomanhua is still working normally.

**Comment by loocool2** [comment] 2021-08-01 20:07
Duplicate of #8335

**Closed by loocool2** 2021-08-01 20:07 UTC
Labels: Feature request
