### ISSUE TITLE
تغير URL 

### ISSUE THREAD

**Issue by Safwam-daw** [tachiyomiorg/tachiyomi-extensions#14703] opened 2022-12-28 13:58 UTC
### Source information and language

ARESManga 1.3.23 (العربية)

### Source new URL

https://aresmanga.net/

### Other details

لقد تم تغير امتداد الاضافه  الى واحد جديد ولقد قمت بإعطائكم الجديد واتمنى منك اصلاح الامر بأسرع وقت و شكرا لمجهوداتكم الرائعة وهو افضل برنامج على الإطلاق 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-12-28 14:15
Duplicate of #14676

**Closed by alessandrojean** 2022-12-28 14:15 UTC
Labels: Bug, Domain changed
