### ISSUE TITLE
Shinigami error 403

### ISSUE THREAD

**Issue by pzmkr** [tachiyomiorg/tachiyomi-extensions#18422] opened 2023-10-07 17:18 UTC
### Source information

Shinigami 1.4.33

### Source language

indonesia

### Steps to reproduce

it shows error 403 when open the extensions, web view works

### Expected behavior

being able to read and download chapter

### Actual behavior

error 403

### Tachiyomi version

0.14.6

### Android version

android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment] 2023-10-08 07:19
Works for me

![Screenshot_2023-10-08-14-18-03-55_afd66b7916d19a60815f56273408b73e.jpg](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/50316075/c9485c73-e323-42be-b4e2-9ee65138513b)

![Screenshot_2023-10-08-14-17-41-48_afd66b7916d19a60815f56273408b73e.jpg](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/50316075/dd5a0f11-b81e-4148-916f-f45681df5ca2)

![Screenshot_2023-10-08-14-18-13-32_afd66b7916d19a60815f56273408b73e.jpg](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/50316075/4dd6eddb-f9e2-4651-a92a-f778a538511a)

**Comment by TheKingTermux** [comment] 2023-10-16 14:02
Duplicate of #18506

**Closed** 2023-10-16 15:07 UTC
Labels: Bug
