### ISSUE TITLE
Gmanga http error 103

### ISSUE THREAD

**Issue by hakudansho** [tachiyomiorg/tachiyomi-extensions#10786] opened 2022-02-10 16:24 UTC
### Source information

Gmanga 1.2.9

### Steps to reproduce

When i open any random chapter in any manga or ubdate any

### Expected behavior

They shoud open or updated

### Actual behavior

Nothing happens just HTTP error 103 appears.

### Tachiyomi version

0.13.1

### Android version

10

### Other details

Uploading Record_2022-02-10-18-23-45_afd66b7916d19a60815f56273408b73e.mp4…

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by hakudansho** [comment] 2022-02-10 16:26
https://user-images.githubusercontent.com/75262438/153451379-ce0a174a-dd9b-442f-a59a-10952e9d83f0.mp4

**Comment by curche** [comment] 2022-02-10 16:31
Duplicate of #10445

**Closed by curche** 2022-02-10 16:31 UTC
Labels: Bug

**Comment by jobobby04** [comment] 2022-02-10 16:37
Because its a duplicate of a issue already open

**Comment by jobobby04** [comment] 2022-02-10 16:42
Hmm, @curche they seem to be using the updated extension that fixed https://github.com/tachiyomiorg/tachiyomi-extensions/issues/10445
So maybe a different issue?

**Comment by hakudansho** [comment] 2022-02-10 16:53
An update to gmanga was released some days ago, it didn't help much.

**Comment by arkon** [comment] 2022-02-10 16:58
This is handled in an upcoming app update.

**Comment by hakudansho** [comment] 2022-02-10 17:04
Sorry, but do you mean that the problem has already been solved or there is going to be an update to solve it.

**Comment by curche** [comment] 2022-02-10 17:06
To elaborate, the pinned issue was closed since the extension was updated to handle this. However, the 103 Error popping up is just a Toast which needs to be now handled by the App: I have tried the source and it is working fine for me. The error being thrown isn't relevant and can be ignored.

If you aren't able to read, Try the Troubleshooting guide

cc @vetleledaal who worked on the issue
