### ISSUE TITLE
Sekte komik changed domain

### ISSUE THREAD

**Issue by JuliansThaGraet** [tachiyomiorg/tachiyomi-extensions#18604] opened 2023-10-18 10:08 UTC
### Source name

SekteKomik

### Source language

Indonesian

### Source link

https://sektekomik.com

### Other details

Domain changed

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment] 2023-10-19 17:31
Domain Change to
```
https://sektekomik.xyz
```

**This is a fake / false label**

Their domain changes, but the source doesn't down

**Comment by TheKingTermux** [comment] 2023-12-20 09:23
I just realized that this issue is a duplicate of #15262

**Closed** 2023-12-20 14:13 UTC
Labels: Bug, Domain changed
