### ISSUE TITLE
Override baseUrl

### ISSUE THREAD

**Issue by slimessan** [tachiyomiorg/tachiyomi-extensions#16487] opened 2023-05-18 20:09 UTC
### Source name

Gmanga.me

### Source language

Arabic

### Describe your suggested feature

Please add a way to change the link from the extension settings

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment] 2023-05-19 08:01
Duplicate of #9608

**Closed by AntsyLich** 2023-05-19 08:01 UTC
Labels: Feature request
