### ISSUE TITLE
can't read comic in tachiyomi app

### ISSUE THREAD

**Issue by Aril666** [tachiyomiorg/tachiyomi-extensions#15024] opened 2023-01-19 11:12 UTC
### Source information and language

DoujinDesu 1.3.3 (BAHASA INDONESIA)

### Steps to reproduce

![Screenshot_20230119-190410](https://user-images.githubusercontent.com/123074953/213426516-b9b02fe2-e09d-4a97-a2e2-3fcc884fc99b.png)
this problem keeps happening "page not found"

### Expected behavior

I hope this problem can be solved so that I can read comfortably on the tachiyomi application, I don't know if this is a problem in the URL section or in another section, maybe you guys know better

### Actual behavior

unable to open web page 

### Tachiyomi version

0.14.3

### Android version

Android 12

### Other details

and the comic thumbnail image is errored or can't be seen (disappeared)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment] 2023-01-19 11:28
Duplicate of #14004

**Closed by stevenyomi** 2023-01-19 11:28 UTC
Labels: Bug
