### ISSUE TITLE
Mangalek (failed to bypass cloudflare)

### ISSUE THREAD

**Issue by Thecultivator** [tachiyomiorg/tachiyomi-extensions#12080] opened 2022-06-05 16:39 UTC
### Source information

مانجا ليك: 1.2.21

### Steps to reproduce

1-Open app
2-Go to browse
3-Select مانجا ليك source
4-manga list appears
5-select any manga/manhwa
6-the chapters appear
7-when I select a chapter to read an error pops up (failed to bypass cloudflare)

### Expected behavior

The Chapter should work normally 

### Actual behavior

An Error pops up (failed to bypass cloudflare)

### Tachiyomi version

App version: 0.13.4 (standard)

### Android version

Android version: 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-06-05 16:49
Duplicate of #11366

**Closed by alessandrojean** 2022-06-05 16:49 UTC
Labels: Bug
