### ISSUE TITLE
Update Disaster Scans

### ISSUE THREAD

**Issue by AnonyAdmiral** [tachiyomiorg/tachiyomi-extensions#9869] opened 2021-11-21 02:18 UTC
### Source information

Disaster Scans 1.2.12

### Steps to reproduce

Open Disaster Scan Source

### Expected behavior

Load Manga

### Actual behavior

Nothing Is Found

### Tachiyomi version

0.12.3

### Android version

Android 11

### Other details

"HTTP error 403: Check website in WebView"

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by SoloLeveller1** [comment] 2021-11-21 06:49
Looks like another 1st kiss type of problem

**Comment by tyme2tb** [comment] 2021-11-21 19:01
Think this is a duplicate of #9852

**Closed** 2021-11-21 19:03 UTC
Labels: Bug
