### ISSUE TITLE
Extension failed to bypass cloudfair (mangaowl)

### ISSUE THREAD

**Issue by apostropheb4s** [tachiyomiorg/tachiyomi-extensions#8528] opened 2021-08-12 01:40 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.10.11

### Android version

android 5

### Source information

Mangaowl 1.2.20

### Steps to reproduce

Failure to bypass cloudfair

### Expected behavior

Opening episodes through the platform should be fine.

### Actual behavior

Failure to bypass cloudfair.

### Other details

Opening episodes through webview is fine but episodes cannot be downloaded because it says "failure to bypass cloudfair".

**Comment by alessandrojean** [comment] 2021-08-12 01:42
Duplicate of #8456

**Closed by alessandrojean** 2021-08-12 01:42 UTC
Labels: Bug
