### ISSUE TITLE
MangaFire - No Results Found

### ISSUE THREAD

**Issue by iMythCases** [tachiyomiorg/tachiyomi-extensions#17856] opened 2023-09-09 10:54 UTC
### Source information

MangaFire - 1.4.2

### Source language

English

### Steps to reproduce

Whenever I open the source, it shows "No results found"

![375200292_266387456338096_5373770458886518714_n](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/144530843/e54ba120-8848-43a5-af73-b9d63fcf5a48)

### Expected behavior

It should show all of the mangas the site has to offer

### Actual behavior

It shows "No Results Found"

### Tachiyomi version

0.14.6

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2023-09-09 12:56
Duplicate of #17715

**Closed by vetleledaal** 2023-09-09 12:56 UTC
Labels: Bug
