### ISSUE TITLE
toptoon

### ISSUE THREAD

**Issue by 64944646** [tachiyomiorg/tachiyomi-extensions#8531] opened 2021-08-12 08:22 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

toptoon

### Source link

https://www.toptoon.net/comic/epList/80907

### Language

中文 繁体

### Other details

能来一个中文的吗？我看软件里面的是英文的。。看不懂。

**Comment by alessandrojean** [comment] 2021-08-12 14:05
Duplicate of #3308

**Closed by alessandrojean** 2021-08-12 14:05 UTC
Labels: Source request
