### ISSUE TITLE
page not found error in manga

### ISSUE THREAD

**Issue by By-PorfecTo** [tachiyomiorg/tachiyomi-extensions#16254] opened 2023-04-30 21:22 UTC
### Source information

Asura Scans 1.4.45

### Source language

Turkish

### Steps to reproduce

i updated the library and when i try to read one of the new chapters i get a page not found error

### Expected behavior

reading the chapter

### Actual behavior

page not found

### Tachiyomi version

tachiyomi 0.14.6

### Android version

Android 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2023-04-30 21:31
Duplicate of #16251

**Closed by alessandrojean** 2023-04-30 21:31 UTC
Labels: Bug
