### ISSUE TITLE
DragonTranslation.net

### ISSUE THREAD

**Issue by Acsell7u7** [tachiyomiorg/tachiyomi-extensions#15066] opened 2023-01-22 06:10 UTC
### Source information and language

DragonTranslation 1.3.31 (español)

### Source new URL

https://dragontranslation.net/

### Other details

Cambió de Dominio

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment] 2023-01-22 06:32
Duplicate of #14972

**Closed by loocool2** 2023-01-22 06:32 UTC
Labels: Bug, Domain changed
