### ISSUE TITLE
EarlyManga change its domain.

### ISSUE THREAD

**Issue by Nialixus** [tachiyomiorg/tachiyomi-extensions#10454] opened 2022-01-14 03:18 UTC
### Source information

EarlyManga 1.2.16

### Steps to reproduce

So earlymanga change its domain from earlymanga.org to https://earlymangarelease.com/

### Expected behavior

I believe you just need to change the hostname

### Actual behavior

This is what happens in the moment:
Unable to resolve host "earlymanga.orghttps"

### Tachiyomi version

0.12.3

### Android version

Android 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-01-14 14:11
Duplicate of #9188

**Closed by arkon** 2022-01-14 14:11 UTC
Labels: Bug
