### ISSUE TITLE
Baozi Manhua：网页加载正常，软件加载不出来

### ISSUE THREAD

**Issue by SoupBagY** [tachiyomiorg/tachiyomi-extensions#16568] opened 2023-05-24 04:49 UTC
### Source information

Baozi Manhua 1.4.19

### Source language

Chinese

### Steps to reproduce

如下

### Expected behavior

![Screenshot_2023-05-24-12-38-43-19_afd66b7916d19a60815f56273408b73e](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/75820074/5924e3f9-ea94-44be-b2b2-92cd87bdec8a)
网页

### Actual behavior

![Screenshot_2023-05-24-12-38-29-22_afd66b7916d19a60815f56273408b73e](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/75820074/5bbc0cd0-ef3e-4d96-b0bc-b5dd9d7d2fcc)
软件

### Tachiyomi version

0.14.6

### Android version

Android 10

### Other details

不开vpn软件加载不出来，网页加载很快
软件开vpn才能加载出来

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by SoupBagY** [comment] 2023-05-24 05:04
https://cn.kukuc.co/
好像是新网址

**Comment by stevenyomi** [comment] 2023-07-08 04:16
Duplicate of #15352

**Closed by stevenyomi** 2023-07-08 04:16 UTC
Labels: Bug
