### ISSUE TITLE
Muctau

### ISSUE THREAD

**Issue by Fujin-sama** [tachiyomiorg/tachiyomi-extensions#12409] opened 2022-07-02 12:22 UTC
### Source information

Muctau 1.3.22

### Steps to reproduce

Opening the source will show manga

### Expected behavior

The manga, manhwa/manhua should show after opening the extension

### Actual behavior

But opening the source shows http error 400, but its working on the webview

### Tachiyomi version

0.13.4

### Android version

Android 9

### Other details

![Screenshot_20220702-201616_Tachiyomi](https://user-images.githubusercontent.com/97900048/177000567-418bfa4d-0604-40a0-b9d9-5476eb8d8c47.jpg)
![Screenshot_20220702-201632_Tachiyomi](https://user-images.githubusercontent.com/97900048/177000572-e446973d-39be-48ba-8e74-78c9abf5ca18.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-07-03 18:28
Duplicate of #12213

**Closed by alessandrojean** 2022-07-03 18:28 UTC
Labels: Bug
