### ISSUE TITLE
manga cover not showing

### ISSUE THREAD

**Issue by ArioVanish** [tachiyomiorg/tachiyomi-extensions#11684] opened 2022-04-30 19:34 UTC
### Source information

DoujinDesu 1.2.2

### Steps to reproduce

┐(´(エ)｀)┌

### Expected behavior

┐(´(エ)｀)┌

### Actual behavior

┐(´(エ)｀)┌

### Tachiyomi version

0.13.2

### Android version

Android 7

### Other details

![Screenshot_2022-05-01-02-24-45](https://user-images.githubusercontent.com/103365392/166120073-93c5ffbb-092a-41f3-b451-940632670f94.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment] 2022-04-30 19:36
Duplicate of #11662

**Closed by curche** 2022-04-30 19:36 UTC
Labels: Bug
