### ISSUE TITLE
Mangasusu no results found

### ISSUE THREAD

**Issue by niveanyctra** [tachiyomiorg/tachiyomi-extensions#19313] opened 2023-12-14 11:35 UTC
### Source information

Mangasusu 1.4.29

### Source language

Indonesia 

### Steps to reproduce

Open the extension
no results found
![Screenshot_2023-12-14-18-31-03-456_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/113758640/f1e42538-20bc-4327-89a2-2774de26111e)

### Expected behavior

show comic

### Actual behavior

no results found

### Tachiyomi version

0.14.7

### Android version

Android 13 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2023-12-14 16:15
Duplicate of #18698

**Closed by vetleledaal** 2023-12-14 16:15 UTC
Labels: Bug
