### ISSUE TITLE
Inarimanga

### ISSUE THREAD

**Issue by Suiren5** [tachiyomiorg/tachiyomi-extensions#14412] opened 2022-11-29 15:04 UTC
### Source information and language

InariManga 1.3.21

### Steps to reproduce

1. No reconoce la fuente, cuando entras pone que no existe
2. Se cambió la fuente por eso no la reconoce y no reconoce los Manhwas de la extension

![Screenshot_2022-11-29-07-50-21-969_eu kanade tachiyomi](https://user-images.githubusercontent.com/104227072/204564915-36d2289c-a319-4851-97aa-6335962cbe1a.jpg)
![Screenshot_2022-11-29-07-50-46-947_eu kanade tachiyomi](https://user-images.githubusercontent.com/104227072/204564919-286500e7-c692-49d2-947e-67559ec1a38c.jpg)

### Expected behavior

Debería reconocer los manhwas y poder leerse

### Actual behavior

No los reconoce porque se cambió la fuente que había en la extensión 

### Tachiyomi version

0.14.2

### Android version

Miui 13.0.3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2023-02-21 20:24
Duplicate of #12523

**Closed by vetleledaal** 2023-02-21 20:24 UTC
Labels: Bug, Factory source
