### ISSUE TITLE
Asura Sans Bookmark Problem and Updating Problem

### ISSUE THREAD

**Issue by CerealKiller7** [tachiyomiorg/tachiyomi-extensions#17025] opened 2023-07-05 08:23 UTC
### Source information

Asura Scans 1.4.48

### Source language

All

### Steps to reproduce

1.Open the extension to browse
2.Bookmark or save to library any manhwa
3.Refresh the manhwa
4.Exit the extension
5.Open the extension on browse again
6.Open the manhwa on webview that has been saved on the library
#### Other Problem
1.Open any manhwa
2. Try to refresh it
3. It may update
4. Close app and after some time maby 2 days
5. Repet step 1 to 2
6. You get message to migrate from Asura to Asura

### Expected behavior

Manhwa that are saved on the library from extension A should have an indication when browsing said extension A.
Manhwa should be actually updated with all the chapters that it has.

### Actual behavior

You can save the same manhwa more than once without limit. Migration doesn't help. Webview redirect's to the homepage of the extension. Updating the manhwa still loads the chapters.
Every time you want to update some entries chapters you have to migrate everytime.

### Tachiyomi version

Tachiyomi J2K 1.6.6

### Android version

Android 13

### Other details

When the extension was updated, a long time ago, I kept the older version as it worked having permanent URLs disabled. Only updated to the current version because the old one wasn't pointing at the correct URL of the extension. This issue was addressed by me some time ago but the new update not only didn't change anything other than adding the option to switch from permanent URLs and not, which by the way I don't know if it was added as an estetic change as it doesn't change anything, but it also created a bug with updating the normal way.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment] 2023-07-05 09:05
Duplicate of #17024

**Closed by stevenyomi** 2023-07-05 09:05 UTC
Labels: Bug
