### ISSUE TITLE
"Flamescans" french Extension URL change

### ISSUE THREAD

**Issue by Blanow** [tachiyomiorg/tachiyomi-extensions#16360] opened 2023-05-07 20:52 UTC
### Source information

flamscans

### Source language

French

### Source new URL

https://legacy-scans.com

### Other details

Hello, I don't really know where to put this but the FLAMESCAN site has changed address -->

https://legacy-scans.com

The flamescan extension is not working because of this

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment] 2023-05-07 20:59
You're at the correct place
But since there's already an issue that was accidentally closed, I'll reopen that in favor of this

Duplicate of #16359

**Closed by curche** 2023-05-07 20:59 UTC
Labels: Bug, Domain changed
