### ISSUE TITLE
Manhwas.net error+update: content must not be null

### ISSUE THREAD

**Issue by Theo-90** [tachiyomiorg/tachiyomi-extensions#14436] opened 2022-12-01 22:40 UTC
### Source information and language

Manwhas.net 1.3.3

### Steps to reproduce

No funciona 
no deja ver nada en cuanto entras

### Expected behavior

Que cuando vaya a la extensión de manhwas.net entre normal la biblioteca de series.

### Actual behavior

![IMG_20221201_162641](https://user-images.githubusercontent.com/119630574/205173199-c21b230a-01b7-465b-9bb8-acca08a15747.jpg)

![Screenshot_2022-12-01-16-26-12-598_eu kanade tachiyomi](https://user-images.githubusercontent.com/119630574/205173227-ad59fa04-4ef2-4462-b8e7-9a3a0701af4c.jpg)

### Tachiyomi version

App version: 0.13.6 (standard,) Device model: M2101K6G 

### Android version

Android 11

### Other details

![1669934096268](https://user-images.githubusercontent.com/119630574/205173508-ac68ec5f-834a-4b79-8fec-1ad41dfc994d.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2022-12-02 04:50
Duplicate of #13008

**Closed by vetleledaal** 2022-12-02 04:50 UTC
Labels: Bug
