### ISSUE TITLE
[Bug] Leviatan Scans: HTTP 404 error

### ISSUE THREAD

**Issue by Samk19** [tachiyomiorg/tachiyomi-extensions#6177] opened 2021-03-14 11:50 UTC
## Device information
- Tachiyomi version: 0.10.9
- Android version: 11

## Source information
- Name: Leviatan Scans
- Extension version: 1.2.2

## Steps to reproduce
1. Use leviatan scan extensions 

### Expected behavior
Manga titles should open 

### Actual behavior
Shows Error 404 
But is working in webview mode

## Other details
Extension not working 

Extension not working normally 
![Screenshot_20210314-171905_Tachiyomi.jpg](https://user-images.githubusercontent.com/36104528/111067271-87788100-84e9-11eb-874e-d3f680c9ec41.jpg)

Webview mode working fine
![Screenshot_20210314-171921_Tachiyomi.jpg](https://user-images.githubusercontent.com/36104528/111067299-a119c880-84e9-11eb-953d-07437da5fee5.jpg)

**Comment by curche** [comment] 2021-03-14 11:53
Likely related to #6162

**Comment by scb261** [comment] 2021-03-14 12:37
Duplicate of #6162

**Closed by scb261** 2021-03-14 12:37 UTC
Labels: bug
