### ISSUE TITLE
Actualización de extensión 

### ISSUE THREAD

**Issue by AlejandroTodoroki26** [tachiyomiorg/tachiyomi-extensions#13513] opened 2022-09-19 15:06 UTC
### Source name and language

Mangastk-Español

### Describe your suggested feature

La extensión de mangasTK no te muestra los mangas se queda en blanco 
![Screenshot_20220919-100443](https://user-images.githubusercontent.com/109183168/191049689-4fcbd91e-2b62-4064-a4e5-5d7daf86b206.png)

### Other details

Estaría bien que la actualizarán para que se mostrarán la página y los mangas 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-09-19 15:10
You should have open an issue report instead, this isn't the right form to report bugs and issues.

**Comment by alessandrojean** [comment] 2022-09-19 15:10
Also duplicate of #12366

**Closed by alessandrojean** 2022-09-19 15:10 UTC
Labels: Bug
