### ISSUE TITLE
[Bug] <myreadingmanga>: <not loading says no results found>

### ISSUE THREAD

**Issue by itiswhatitseems** [tachiyomiorg/tachiyomi-extensions#7015] opened 2021-05-14 01:32 UTC
## Device information
- Tachiyomi version: 1.5.0
- Android version: 10

## Source information
- Name: myreadingmanga.info
- Extension version: latest

## Steps to reproduce
1. First Step clicking on the extention myreading manga, it will spin for a second and then come up saying no results found
2. Second Step tried to uninstall and reinstall, nothing worked

### Expected behavior
Describe what should have happened

### Actual behavior
Describe what happens instead

**Comment by plW0lf** [comment] 2021-05-14 22:02
Next time write which version of the extension you are using. "Latest" doesn't say anything.

 Steps to fix said error:

1. Press "Open in WebView"
2. Wait until the page will load
3. Go back to Tachiyomi
4. Press "Retry"

This error is caused by Cloudflare. No changes in extension are needed.
Please close this issue

**Closed** 2022-08-29 14:04 UTC
Labels: Bug, Cloudflare protected
