### ISSUE TITLE
Request web Komikindo

### ISSUE THREAD

**Issue by Pecoriine** [tachiyomiorg/tachiyomi-extensions#7978] opened 2021-07-04 21:31 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

Komikindo

### Source link

https://komikindo.id/

### Language

Indonesia

### Other details

![komikindo](https://user-images.githubusercontent.com/85052642/124400027-ab3a2e00-dd49-11eb-9c7c-89e7485776fb.png)

**Comment by alessandrojean** [comment] 2021-07-04 21:33
Duplicate of #6031.

**Closed by alessandrojean** 2021-07-04 21:33 UTC
Labels: Source request
