### ISSUE TITLE
EarlyManga not loading chapters

### ISSUE THREAD

**Issue by OGr3y** [tachiyomiorg/tachiyomi-extensions#11882] opened 2022-05-16 01:00 UTC
### Source information

EarlyManga v1.2.17

### Steps to reproduce

1. Download and click on the extension
2. Click on any manga/manhua or manhwa and you'll see that there are no chapters for any of them

### Expected behavior

When you click on any specific thing u want to read, you should be able to see the chapters and click on them.

### Actual behavior

When you click on any specific thing u want to read, it's not showing any of the chapters, but when I click on webview it's showing everything.

### Tachiyomi version

1.5.2

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-05-16 15:41
Duplicate of #9188

**Closed by alessandrojean** 2022-05-16 15:41 UTC
Labels: Bug
