### ISSUE TITLE
EsNiadd

### ISSUE THREAD

**Issue by NarellaproA1** [tachiyomiorg/tachiyomi-extensions#8455] opened 2021-08-08 01:42 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

Niadd

### Source link

https://es.niadd.com/

### Language

Spanish (Es) 

### Other details
Porfa creenla se lo ruego se que capaz están ocupados pero su trabajo es tan grande y es fabuloso todo lo que logran hacer así que por favor creenlo estoy seguro que lo podrán ya que son los mejores al haber creado extensiones tan buenas

**Comment by CVIUS** [comment] 2021-08-08 01:58
duplicate of #1007

**Closed** 2021-08-08 02:11 UTC
Labels: Source request
