### ISSUE TITLE
[AllPornComic] Cloudflare issue

### ISSUE THREAD

**Issue by hyoretsu** [tachiyomiorg/tachiyomi-extensions#12212] opened 2022-06-15 11:04 UTC
### Source information

1.3.21

### Steps to reproduce

Try to do anything in the extension.

### Expected behavior

It should load, or at least be solvable.

### Actual behavior

It doesn't load due to yet another Cloudflare. Yes, I've read the sticky post and faced it many times before. But with this source, loading it in WebView doesn't even trigger a Cloudflare screen, much less solve it, nor does opening in browser.

In the past I could solve it sometimes, mostly randomly.

### Tachiyomi version

r4466

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-06-15 13:30
Duplicate of #9318

**Closed by alessandrojean** 2022-06-15 13:30 UTC
Labels: Bug
