### ISSUE TITLE
Vapo scan changed tittle 

### ISSUE THREAD

**Issue by Diegofsp98** [tachiyomiorg/tachiyomi-extensions#12243] opened 2022-06-19 11:34 UTC
### Source information

Vapo scan 1.3.22

### Steps to reproduce

The scan changed his title and site to olympus scan

### Expected behavior

New site https://br.olympusscanlation.com/
New tittle Olympus scan 

### Actual behavior

Old site and tittle 

### Tachiyomi version

0.13.4

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-06-19 14:42
Duplicate of #12235

**Closed by alessandrojean** 2022-06-19 14:42 UTC
Labels: Bug
