### ISSUE TITLE
[Mangadex] Title of manga "Ijiranaide, Nagatoro-san" doesn't show in the library

### ISSUE THREAD

**Issue by eredrolo** [tachiyomiorg/tachiyomi-extensions#9021] opened 2021-09-09 19:22 UTC
### Source information

Mangadex 1.2.131

### Steps to reproduce

1. Add the [manga](https://mangadex.org/title/d86cf65b-5f6c-437d-a0af-19a31f94ec55) to library.
2. See the title

### Expected behavior

The title of the manga should be displayed correctly.

### Actual behavior

The title is displayed as **"Unknown"**

### Tachiyomi version

App version: 0.12.1

### Android version

Android 11

### Other details

This is the only manga which has this problem (as far as I know), all others show the title correctly.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vengiare** [comment] 2021-09-09 19:23
Try `Settings › Advanced › Clear database`

**Comment by arkon** [comment] 2021-09-09 19:38
Duplicate of #8036

**Closed by arkon** 2021-09-09 19:38 UTC
Labels: Bug
