### ISSUE TITLE
Can't access hitomi.la

### ISSUE THREAD

**Issue by jadidiasarte** [tachiyomiorg/tachiyomi-extensions#10699] opened 2022-02-04 16:40 UTC
### Source information

Hitomi.la 1.2.16

### Steps to reproduce

1. Browse
2. Hitomi.la ”latest”
3. HTTP error 403

### Expected behavior

Can access Extension

### Actual behavior

HTTP error 403

### Tachiyomi version

0.13.1

### Android version

Android 11

### Other details

![Screenshot_2022-02-04-23-14-59-111_eu kanade tachiyomi](https://user-images.githubusercontent.com/67495493/152566964-48986125-2a81-4c95-978c-ca1693de287c.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-02-04 16:43
Duplicate of #10319

**Closed by alessandrojean** 2022-02-04 16:43 UTC
Labels: Bug
