### ISSUE TITLE
xCaliBR Scans - Mirror image

### ISSUE THREAD

**Issue by ARiyou2000** [tachiyomiorg/tachiyomi-extensions#10078] opened 2021-12-12 16:55 UTC
### Source information

xCaliBR Scans 1.2.14

### Steps to reproduce

Try to read new chapter

### Expected behavior

![Screenshot_2021-12-12-20-10-59](https://user-images.githubusercontent.com/35896230/145721399-56ea2743-e57f-4e0c-8127-ecfb43a7f84c.png)

### Actual behavior

![MGA_393_9](https://user-images.githubusercontent.com/35896230/145721833-23d93baa-7306-408b-96d1-45dce59c353b.jpg)

### Tachiyomi version

0.12.3

### Android version

Android 11

### Other details

It seems the xcalibrscans.com upload all images as mirrors [except for first one that contains the introduction and cover]
Then it use Css ot Js to mirror them again.

This way when others try to download image, the mirror image would be downloaded.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2021-12-12 22:44
Duplicate of #10077

**Closed by alessandrojean** 2021-12-12 22:44 UTC
Labels: Bug
