### ISSUE TITLE
HTTP error 429

### ISSUE THREAD

**Issue by ROHITHKANDUKURI** [tachiyomiorg/tachiyomi-extensions#14858] opened 2023-01-09 04:19 UTC
### Source information and language

1st Kiss 1.3.34 (English)

### Steps to reproduce

Update failed 

### Expected behavior

It should check for updates

### Actual behavior

HTTP error 429

### Tachiyomi version

0.14.3

### Android version

Android 12

### Other details

![Screenshot_2023-01-09-09-47-33-96_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/117616707/211240377-669d732c-3f4c-4e66-9f6b-5d3fa0812a85.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2023-01-09 04:43
Duplicate of #14850

**Closed by alessandrojean** 2023-01-09 04:43 UTC
Labels: Bug
