### ISSUE TITLE
XOXO Comics Extension "No Chapters Found, NullPointerException: Null"

### ISSUE THREAD

**Issue by Rinhaka** [tachiyomiorg/tachiyomi-extensions#19297] opened 2023-12-13 06:01 UTC
### Source information

XOXO Comics 1.4.4

### Source language

English

### Steps to reproduce

1. Browse for extension "XOXO Comics"
2. Install "XOXO Comics"
3. Navigate to the "Sources Tab"
4. Select XOXO Comics
5. When selected all books state "No Chapter Found" and provide the error "NullPointerException: Null"

### Expected behavior

When a book is selected the chapters should populate and allow downloading/adding to library

### Actual behavior

When selected all books state "No Chapter Found" and provide the error "NullPointerException: Null"

### Tachiyomi version

0.14.7

### Android version

Android 13

### Other details

The website is online, when opened in web view books are able to be read.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2023-12-13 16:39
Duplicate of #19132

**Closed by vetleledaal** 2023-12-13 16:39 UTC
Labels: Bug
