### ISSUE TITLE
HTTP Error 429

### ISSUE THREAD

**Issue by IAmNanahoshi** [tachiyomiorg/tachiyomi-extensions#14852] opened 2023-01-08 22:27 UTC
### Source information and language

1st Kiss Version 1.3.34

### Steps to reproduce

1. I scanned for updates as usual.
2. After I finished scanning, the manhuas that I took in the 1st Kiss source didn't  update and it said that those manhuas failed to update.

### Expected behavior

The manhuas should've updated smoothly.

### Actual behavior

The manhuas failed to update and resulted in an HTTP Error 429.

### Tachiyomi version

0.14.3

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment] 2023-01-08 22:46
Duplicate of #14850

**Closed** 2023-01-08 22:47 UTC
Labels: Bug
