### ISSUE TITLE
1stkissmanga broken. Web view works but chapters do not.

### ISSUE THREAD

**Issue by molitar** [tachiyomiorg/tachiyomi-extensions#9369] opened 2021-10-04 23:10 UTC
### Source information

1st Kiss 1.2.17

### Steps to reproduce

Try to read any chapters from 1st kiss

### Expected behavior

Should be able to read chapters

### Actual behavior

No error reports for checking new chapters and web view opens to the chapters properly and can be read in web view.

### Tachiyomi version

Preview r408

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment] 2021-10-04 23:16
Duplicate of #7810

**Closed by loocool2** 2021-10-04 23:16 UTC
Labels: Bug
