### ISSUE TITLE
ReManga (the Arabic one)

### ISSUE THREAD

**Issue by iRahmaniMed** [tachiyomiorg/tachiyomi-extensions#8204] opened 2021-07-20 18:26 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

ReManga

### Source link

https://re-manga.com/

### Language

Arabic

### Other details

This is another arabic website not the the existing Russian one

**Comment by Clouddark75** [comment] 2021-07-20 18:35
WP EastManga (a variant of WP MangaReader) theme. Currently not supported by Tachi multisrc extension.

**Comment by iRahmaniMed** [comment] 2021-07-20 21:10
Unfortunately

**Comment by alessandrojean** [comment] 2021-07-24 01:52
Duplicate of #7592

**Closed by alessandrojean** 2021-07-24 01:52 UTC
Labels: Source request
