### ISSUE TITLE
Cloudflare - WebtoonXYZ

### ISSUE THREAD

**Issue by Andres1ni** [tachiyomiorg/tachiyomi-extensions#12656] opened 2022-07-21 04:02 UTC
### Source information

WebtoonXYZ 1.3.25

### Steps to reproduce

1. Go to Explore
2. Select the WebtoonXYZ extension
3. The "failed to bypass Cloudflare" message should appear
4. Do the steps to "fix" it with the help of the troubleshooting guide

### Expected behavior

You should be able to actually fix the extension and be able to acces the catalogue of it

### Actual behavior

Both of the methods that fix the "failed to bypass the Cloudflare" don't work

### Tachiyomi version

0.13.5

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment] 2022-07-21 04:19
> I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open issue.

Duplicate of #6738

**Closed by curche** 2022-07-21 04:19 UTC
Labels: Bug
