### ISSUE TITLE
[Bug] Japscan: Can't download Solo Leveling 144 VF

### ISSUE THREAD

**Issue by Mitia99** [tachiyomiorg/tachiyomi-extensions#6283] opened 2021-03-25 09:28 UTC
## Device information
- Tachiyomi version: 1.0.10
- Android version: 10

## Source information
- Name: Japscan
- Extension version: 1.2.25

## Steps to reproduce
1. Add Solo Leveling to library
2. Download chapter 144 VF

### Expected behavior
Download should start

### Actual behavior
Stuck download![Screenshot_20210325_122526_eu.kanade.tachiyomi.j2k.jpg](https://user-images.githubusercontent.com/56766778/112450569-940c9d00-8d65-11eb-9c47-da18d2120ac6.jpg)

## Other details
Other chapters(145 for e.g) downloads are working

**Comment by scb261** [comment] 2021-03-25 10:07
Duplicate of #6166

**Closed by scb261** 2021-03-25 10:07 UTC
Labels: bug
