### ISSUE TITLE
sekte komik (id) cannot opened

### ISSUE THREAD

**Issue by dammxs** [tachiyomiorg/tachiyomi-extensions#13408] opened 2022-09-08 23:02 UTC
### Source information and language

Sekte Komik 1.3.25 (Indonesia)

### Steps to reproduce

it seems like the sites has blocking tachiyomi from accesing their website or etc, whenever you open the latest tab/normal tab it will give you feedback like source not found.

### Expected behavior

the extension may need to bypass cloudflare or etc, because when i see the wp preview they already change the web template

### Actual behavior

instead of loading to open the library, the extension only showing feedback as i explain before

### Tachiyomi version

0.13.6

### Android version

Android 12L

### Other details

![Screenshot_20220909-060130_Tachiyomi](https://user-images.githubusercontent.com/95095324/189240608-6ace06a6-f650-40c5-9abd-b18717e32794.png)
![Screenshot_20220909-060123_Tachiyomi](https://user-images.githubusercontent.com/95095324/189240642-1c702923-077b-467a-a24b-5e20688b309d.png)
![Screenshot_20220909-060025_Tachiyomi](https://user-images.githubusercontent.com/95095324/189240644-54ea2f66-dbfa-4c01-82a6-70660c0a0706.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment] 2022-09-14 11:44
duplicate of #12995

**Closed by Riztard** 2022-09-14 11:44 UTC
Labels: Bug
