### ISSUE TITLE
Simply Hentai: HTTP error 404

### ISSUE THREAD

**Issue by zztai37** [tachiyomiorg/tachiyomi-extensions#15095] opened 2023-01-24 21:50 UTC
### Source information and language

Simply Hentai 1.3.6

### Steps to reproduce

Just click on the source and try browsing it. It brings up a 404. I tried clearing cookies, cache and changing UA.

### Expected behavior

Source working as usual.

### Actual behavior

404 error, open in website

### Tachiyomi version

App version: 0.14.3 (standard, 817418f, 93, 2023-01-07T17:15Z) Android version: 12 (SDK 31)

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2023-03-23 06:29
Duplicate of #11617 probably

**Closed by Seishirou101** 2023-03-23 06:29 UTC
Labels: Bug
