### ISSUE TITLE
Infernal void scans is broken

### ISSUE THREAD

**Issue by ecv03** [tachiyomiorg/tachiyomi-extensions#12340] opened 2022-06-27 07:41 UTC
### Source information

Infernal Void Scans 1.3.18

### Steps to reproduce

1. Every time I refresh a manhwa using infernal void scans extension it always say "no chapters found"
2. I checked the webview and found new chapters

### Expected behavior

If you refresh a manhwa, new chapters should pop out

### Actual behavior

What happened is when I refresh a manhwa it says "no chapters found"

### Tachiyomi version

0.13.4

### Android version

Android 12

### Other details

Hope you can fix this, thank you for your hardwork:)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by keinezeit8** [comment] 2022-06-27 09:24
Duplicate of #12295

**Closed** 2022-06-27 13:58 UTC
Labels: Bug
