### ISSUE TITLE
Report Doujindesu

### ISSUE THREAD

**Issue by devxbs** [tachiyomiorg/tachiyomi-extensions#12194] opened 2022-06-14 07:46 UTC
### Source information

Doujindesu 1.3.2

### Steps to reproduce

Can't see the manga cover in that extensions

### Expected behavior

This should can see the manga cover

### Actual behavior

I dont know

### Tachiyomi version

0.13.4

### Android version

Android 12

### Other details

![Screenshot_2022-06-14-00-58-40-328_eu kanade tachiyomi](https://user-images.githubusercontent.com/34465013/173522404-2d27d882-0aef-4579-b4e8-26de0b988ad3.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment] 2022-06-14 10:50
Duplikasi dari #11662 // Duplicate of #11662

**Closed** 2022-06-14 11:04 UTC
Labels: Bug
