### ISSUE TITLE
Multporn Source not been working for months now

### ISSUE THREAD

**Issue by ifezcool** [tachiyomiorg/tachiyomi-extensions#13377] opened 2022-09-07 08:19 UTC
### Source information and language

Multporn 1.2.3

### Steps to reproduce

1.Install Multporn extension
2. Go to sources tab
3. Click the multporn extension in the sources tab

### Expected behavior

The list of comics should load.

### Actual behavior

No comics load and only an error shows, saying "List contains no element matching the predicate".

### Tachiyomi version

Stable 0.13.6

### Android version

Android 8

### Other details

The source is not completely broken because clicking "latest" on the multporn extension works, and loads comics that you can actually download. You just cant search anything or sort or look at it without looking through the latest.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-09-08 21:38
Duplicate of #8069

**Closed by alessandrojean** 2022-09-08 21:38 UTC
Labels: Bug
