### ISSUE TITLE
Swatmanga 

### ISSUE THREAD

**Issue by 5OSA** [tachiyomiorg/tachiyomi-extensions#18260] opened 2023-09-30 02:53 UTC
### Source information

Swatmanga 1.4.39

### Source language

العربية

### Steps to reproduce

Http error 404 

### Expected behavior

![Screenshot_20230930_054815_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/103575956/cb085e1a-3f45-46f2-84ef-ab04aad5fd2d)

### Actual behavior

Fix it please 

### Tachiyomi version

0.14.6

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2023-09-30 03:21
duplicate of #18175

**Closed by Seishirou101** 2023-09-30 03:21 UTC
Labels: Bug
