### ISSUE TITLE
ReadAllComics

### ISSUE THREAD

**Issue by Phusionraze** [tachiyomiorg/tachiyomi-extensions#8329] opened 2021-07-30 19:18 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

ReadAllComics

### Source link

http://readallcomics.com/

### Language

English

### Other details

Hosts western comics. Appears to hold a large amount of content not found in current western comic sources for Tachiyomi, or at least in a different format which may be easier to navigate. As example, compare http://readallcomics.com/category/green-lantern/ to "Green Lantern" search results on https://readcomiconline.li/ (readcomicsonline does unfortunately not offer static search URLs).

On a side note I will admit that I haven't actually checked the Github repository code to see if this website is supported because I don't know where to look (even after searching the repository files). I think it would be a useful feature if the Source Request guidelines explained exactly how to do that, such as by linking to the files or sub-pages needed. Currently it is difficult for non-programming/github-experienced users to follow this guideline step.

**Comment by alessandrojean** [comment] 2021-07-30 20:23
Duplicate of #6470

**Closed by alessandrojean** 2021-07-30 20:23 UTC
Labels: Source request
