### ISSUE TITLE
error exception

### ISSUE THREAD

**Issue by AhmedSamir899** [tachiyomiorg/tachiyomi-extensions#17702] opened 2023-08-27 18:15 UTC
### Source information

MangaSwat v1.4.37

### Source language

Arabic

### Steps to reproduce

when open extension error in screen shot appear

### Expected behavior

open normally and display manhwa 

### Actual behavior

error appear

### Tachiyomi version

0.14.6

### Android version

13

### Other details

![WhatsApp Image 2023-08-27 at 21 12 43](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/36117678/5c9f5d92-5e5f-4645-8c1d-0f95c95af9b3)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment] 2023-08-27 18:15
Duplicate of #17667

**Closed by AntsyLich** 2023-08-27 18:15 UTC
Labels: Bug
