### ISSUE TITLE
[Source Request] <Knight Scanlation>

### ISSUE THREAD

**Issue by Elcrack14** [tachiyomiorg/tachiyomi-extensions#7729] opened 2021-06-18 14:16 UTC
## Source website
- Name: Knight Scanlation
- Link: https://knightnoscanlation.com/
- Language(s): Spanish(Es)

**Comment by Seishirou101** [comment] 2021-06-18 14:24
You already opened an issue about this before, the answer is the same.

**Comment by Seishirou101** [comment] 2021-06-18 14:24
Duplicate of #4240

**Closed** 2021-06-18 14:24 UTC
Labels: Source Request
