### ISSUE TITLE
[Bug] <Japscan>: <not working >

### ISSUE THREAD

**Issue by Diego10pedro** [tachiyomiorg/tachiyomi-extensions#7161] opened 2021-05-21 19:55 UTC
## Device information
- Tachiyomi version: 0.10.12 
- Android version: 10

## Source information
- Name: japscan 
- Extension version: 1.2.27

## Steps to reproduce
1. Trying to read or download a chapter 
2. Infinite loading

**Comment by h-hyuuga** [comment] 2021-05-21 20:02
Duplicate of #6166 ?

**Comment by Diego10pedro** [comment] 2021-05-21 21:18
No, I think is différent. All chapters and webtoons don't work. And there are no ads.

**Closed** 2021-05-24 11:03 UTC
Labels: bug
