### ISSUE TITLE
extension changes Reaper Scans (Indonesia)

### ISSUE THREAD

**Issue by AccXyzAinz** [tachiyomiorg/tachiyomi-extensions#15431] opened 2023-02-21 09:52 UTC
### Source information and language

Reaper Scans 1.4.39 (multi/Indonesia)

### Source new URL

https://shinigami.id

### Other details

![Screenshot_2023-02-21-16-51-52-906_eu kanade tachiyomi](https://user-images.githubusercontent.com/125968640/220310469-7589285f-f621-4e89-8409-a1991a1be990.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2023-02-21 13:11
Duplicate of #15408

**Closed by alessandrojean** 2023-02-21 13:11 UTC
Labels: Bug, Domain changed
