### ISSUE TITLE
[Bug] <SekaiKomik>: <HTTP Error 404>

### ISSUE THREAD

**Issue by Ciel-kun** [tachiyomiorg/tachiyomi-extensions#6253] opened 2021-03-23 09:09 UTC
## Device information
- Tachiyomi version: Stable 0.10.9
- Android version: 7.1.1

## Source information
- Name: SekaiKomik
- Extension version: 1.2.2

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
Fix it cause the original website change domain from .com to .net

### Actual behavior
I cant open that extension

## Other details
Please fix it

**Comment by Riztard** [comment] 2021-03-23 09:11
duplicate of #6252

**Closed by Riztard** 2021-03-23 09:11 UTC
Labels: bug
