### ISSUE TITLE
Pmscans changed URL

### ISSUE THREAD

**Issue by Dark-Gizmoa** [tachiyomiorg/tachiyomi-extensions#14924] opened 2023-01-13 16:44 UTC
### Source information and language

PMScans 1.3.25 (english) 

### Source new URL

https://my.rackusreads.com/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2023-01-13 20:26
Duplicate of #14331

**Closed by alessandrojean** 2023-01-13 20:26 UTC
Labels: Bug, Domain changed
