### ISSUE TITLE
Cannot load the chapter

### ISSUE THREAD

**Issue by Jen0930** [tachiyomiorg/tachiyomi-extensions#9907] opened 2021-11-23 08:49 UTC
### Source information

"1st Kiss Manga.love 1.2.12"

### Steps to reproduce

In 1st Kiss manga.love
-First step when you click the site will show the books of manga
-Second step when you open chapter of a book of manga 
-The issue will show 
![Screenshot_20211123-162013_Tachiyomi](https://user-images.githubusercontent.com/77537166/142991352-4c891c42-7cc1-449d-8c58-0262a5a326de.jpg)

### Expected behavior

This should happen in 1st kiss manga.love when you open it will show the books and you can start reading

### Actual behavior

This happen instead in 1st kiss manga.love when you click the site it will show up the books but when you click a chapter to read it. It will show up the retry 

But still working in their main site and you can read

### Tachiyomi version

0.12.3

### Android version

Android 11

### Other details

![Screenshot_20211123-002625_Tachiyomi](https://user-images.githubusercontent.com/77537166/142991604-b90968cb-f2f2-4932-bd8d-724811b5840c.jpg)
![Screenshot_20211123-162013_Tachiyomi](https://user-images.githubusercontent.com/77537166/142991606-859939a4-398a-4d77-ba70-ff7b20fa91e2.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2021-11-23 08:50
Stop opening duplicate issues.

**Comment by Seishirou101** [comment] 2021-11-23 08:50
Duplicate of #9377

**Closed** 2021-11-23 09:00 UTC
Labels: Bug
