### ISSUE TITLE
Constellar Scans: No pages found

### ISSUE THREAD

**Issue by Poharan** [tachiyomiorg/tachiyomi-extensions#16927] opened 2023-06-29 16:47 UTC
### Source information

Constellar Scans

### Source language

English

### Steps to reproduce

Open extension
Open manga/manhwa
Try to read a chapter
"No pages found"

### Expected behavior

Able to read chapter

### Actual behavior

"No pages found"

### Tachiyomi version

0.14.6

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment] 2023-07-25 12:39
Duplicate of #17251

**Closed by stevenyomi** 2023-07-25 12:39 UTC
Labels: Bug
