### ISSUE TITLE
nettruyen extension changed Domain

### ISSUE THREAD

**Issue by hainguyen2757** [tachiyomiorg/tachiyomi-extensions#12759] opened 2022-07-27 18:17 UTC
### Source information and language

NetTruyen 1.3.10 (Vietnamese)

### Steps to reproduce

1. Install NetTruyen extension
2. Open NetTruyen
3. Failed to connect to www.nettruyenco.com/127.0.0.1:80

### Expected behavior

Connect to http://www.nettruyenme.com/ and show mangas

### Actual behavior

Failed to connect to www.nettruyenco.com/127.0.0.1:80 due to domain changing

### Tachiyomi version

0.13.5

### Android version

Android 12

### Other details

Extension changed hosting address from www.nettruyenco.com to www.nettruyenme.com

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2022-07-27 18:31
>  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

Duplicate of #12724

**Closed by vetleledaal** 2022-07-27 18:31 UTC
Labels: Bug
