### ISSUE TITLE
Manga covers not showing up

### ISSUE THREAD

**Issue by Vampyk** [tachiyomiorg/tachiyomi-extensions#8961] opened 2021-09-04 08:38 UTC
### Source information

kissmanga 1.2.13

### Steps to reproduce

![Screenshot_2021-09-04-13-57-04-858_eu kanade tachiyomi](https://user-images.githubusercontent.com/90088736/132088474-49cc1f87-52ac-4d39-bfc6-57b443636787.jpg)
 

Manga covers are not showing up

### Expected behavior

It should showed the Manga covers but it is not showing up

### Actual behavior

Cover are not showing properly even with the better network 

### Tachiyomi version

0.12.2

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment] 2021-09-04 10:40
Duplicate of #8835 
> I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open issue.

**Closed by curche** 2021-09-04 10:40 UTC
Labels: Bug
