### ISSUE TITLE
Hiveworks Comics: Unsupported chapter list (Tripping Over You)

### ISSUE THREAD

**Issue by Throun** [tachiyomiorg/tachiyomi-extensions#15162] opened 2023-01-28 18:33 UTC
### Source information and language

Hiveworks Comics 1.3.7

### Steps to reproduce

Open 'Tripping Over You' in Hiveworks and pull down to refresh.

### Expected behavior

The work updates its chapter list.

### Actual behavior

Tachiyomi gives the error "java.lang.Exception: This comic has a unsupported chapter list."

### Tachiyomi version

0.14.3

### Android version

OneUI 4.0 (Android 12)

### Other details

Other works from Hiveworks do not have this issue.
The comic seemed to work fine until I updated Tachiyomi to 0.14.3.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Efreak** [comment] 2023-02-08 18:46
There's actually several hiveworks comics that don't work with Tachiyomi. Misfile, The End, and Guilded Age are examples.

**Comment by vetleledaal** [comment] 2023-02-21 20:32
Duplicate of #3153

**Closed by vetleledaal** 2023-02-21 20:32 UTC
Labels: Bug
