### ISSUE TITLE
Asura Scans Follow up requests 

### ISSUE THREAD

**Issue by Grimmgingerk** [tachiyomiorg/tachiyomi-extensions#13057] opened 2022-08-17 23:07 UTC
### Source information and language

Asura Scans 1.3.33

### Steps to reproduce

Update tab
Refresh update button
Error

### Expected behavior

Get update for Retrun of the Disaster Class Hero

### Actual behavior

! Too many follow-up requests: 21
  # Asura Scans (EN)
    - Return of the Disaster-Class Hero

### Tachiyomi version

0.13.6

### Android version

12

### Other details

Has been going on for the past weeks.

I hope this hasn't been reported before, i looked through the open lists and didn't see Asura anywhere. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-08-18 13:04
Duplicate of #13014

**Closed by arkon** 2022-08-18 13:04 UTC
Labels: Bug
