### ISSUE TITLE
[Error] <Kumanga (ES)>: <does not load the list of sleeves due to error jsonReader.setLenient(true)>

### ISSUE THREAD

**Issue by jasshira266** [tachiyomiorg/tachiyomi-extensions#5955] opened 2021-02-21 21:33 UTC
## Device information
- Tachiyomi version: 0.10.9
- Android version: 10

## Source information
- Name: Kumanga (ES)
- Extension version: 1.2.6

## Steps to reproduce
1. Open the extension
2. Open the webview

### Expected behavior
Load list of mangas

### Actual behavior
Not load any manga

## Other details
![Screenshot_20210221-150525_Tachiyomi](https://user-images.githubusercontent.com/70398137/108638316-a5a80f80-745c-11eb-86d7-24774dbb0cc5.png)
![InShot_20210221_161535541](https://user-images.githubusercontent.com/70398137/108639089-ab075900-7460-11eb-8c8d-5d682c6fcbad.jpg)

**Comment by scb261** [comment] 2021-03-17 19:35
Duplicate of #4108, but now it returns different error. The site tries very hard to block developer tools and scrapers `¯\_(ツ)_/¯`

**Closed by scb261** 2021-03-17 19:35 UTC
Labels: bug
