### ISSUE TITLE
[Source Request] SekaiKomik

### ISSUE THREAD

**Issue by SokKeras** [tachiyomiorg/tachiyomi-extensions#5814] opened 2021-02-12 22:26 UTC
## Source website
- Name: Sekaikomik
- Link: https://sekaikomik.com
- Language(s): Indonesia

**Comment by scb261** [comment] 2021-02-12 22:28
Duplicate of #4645
Please, search opened issues before requesting bunch of sites

**Closed by scb261** 2021-02-12 22:28 UTC
Labels: Source Request
