### ISSUE TITLE
Kumanga not open

### ISSUE THREAD

**Issue by edmxn** [tachiyomiorg/tachiyomi-extensions#14020] opened 2022-10-28 22:48 UTC
### Source information and language

Kumanga 1.3.7

### Steps to reproduce

open source

### Expected behavior

the mangas that are on the web should be loaded

### Actual behavior

![Screenshot_20221028-163147_Tachiyomi](https://user-images.githubusercontent.com/101371218/198746331-b8a8b795-71fb-4775-a576-6ee03cac753f.jpg)
Idk what that's

### Tachiyomi version

0.14.0

### Android version

Android 12

### Other details

I don't have a vpn activated while opening the source

Also, the new version is a bit stuck, I would like to know if it is my problem or the optimization of the app

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.0](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-10-28 23:00
Duplicate of #10414

**Closed by alessandrojean** 2022-10-28 23:00 UTC
Labels: Bug
