### ISSUE TITLE
HTTP Error 400 1st Kiss Manga

### ISSUE THREAD

**Issue by IAmNanahoshi** [tachiyomiorg/tachiyomi-extensions#15294] opened 2023-02-10 10:54 UTC
### Source information and language

1st Kiss Version 1.3.36

### Steps to reproduce

1. I searched some manhwa titles on Tachiyomi.
2. Instead of the manhwa, an error that said HTTP 400 is instead shown.

### Expected behavior

The manhwa's title or similar should appear on the result after search.

### Actual behavior

The HTTP 400 error is instead shown.

### Tachiyomi version

0.14.4

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by gr8falcon** [comment] 2023-02-10 23:35
Same issue with me, is there any update on resolution??

**Comment by arkon** [comment] 2023-02-11 15:57
Duplicate of #15281

**Closed by arkon** 2023-02-11 15:57 UTC
Labels: Bug
