### ISSUE TITLE
The game that i came from

### ISSUE THREAD

**Issue by Jutsii** [tachiyomiorg/tachiyomi-extensions#13098] opened 2022-08-20 02:47 UTC
### Source information and language

Asura Scans 1.3.33

### Steps to reproduce

1. When I tried to refresh the manhwa, it shows no chapter found 
2. But in web view chapters are already updates
3. But in the app always so no chapters found

### Expected behavior

Chapters does not updating 

### Actual behavior

Shows no chapters found 

### Tachiyomi version

0.13.6

### Android version

Android 11

### Other details

Shows to many request 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-08-20 02:50
Duplicate of #13014

**Closed by arkon** 2022-08-20 02:50 UTC
Labels: Bug
