### ISSUE TITLE
Nothing can be opened or downloaded from it

### ISSUE THREAD

**Issue by ishita911** [tachiyomiorg/tachiyomi-extensions#8882] opened 2021-08-28 06:29 UTC
### Source information

Hentaifox Version:1.2.2

### Steps to reproduce

1.Open extension
2. click any manga you want to read
3.Does not load 
4. try downloading
5. doesn't download

### Expected behavior

when clicked should be opened to be read
when downloaded it should download

### Actual behavior

not loading for online reading
not downloading for offline reading

### Tachiyomi version

0.12.1

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2021-08-28 06:37
Duplicate of #8870

**Closed** 2021-08-28 14:07 UTC
Labels: Bug
