### ISSUE TITLE
[BUG] 8muses not working

### ISSUE THREAD

**Issue by prono69** [tachiyomiorg/tachiyomi-extensions#7307] opened 2021-05-30 08:47 UTC
8muses extension giving error. Sometimes working, sometimes not :(

![Here](https://telegra.ph/file/77fb262823b6bc0213f2e.jpg)

Please fix. Thank you :)

_Sent from my Redmi Note 4 using [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_

**Comment by CrepeTF** [comment] 2021-05-30 20:49
Can't reproduce, go through all the troubleshooting steps at:
https://tachiyomi.org/help/guides/troubleshooting/#diagnosis

And make sure you're up-to-date on your app and extensions

**Comment by CrepeTF** [comment] 2021-11-10 21:53
Closing as it's been 5 months and was not able to reproduce

**Closed by CrepeTF** 2021-11-10 21:53 UTC
