### ISSUE TITLE
Manhwas on Galaxy manga site are not updating

### ISSUE THREAD

**Issue by Jaj29** [tachiyomiorg/tachiyomi-extensions#17935] opened 2023-09-13 19:42 UTC
### Source information

جالاكسي مانجا 

### Source language

Arabic

### Steps to reproduce

I tried updating the manhwas but it's not updating instead it gives me this message and all the manhwas from this source are the same issue 
![Screenshot_20230913-192345_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/144594100/5113fa79-7cdf-46e8-ae8e-e9a8f76f851e)

### Expected behavior

They should be updated 

### Actual behavior

Manhwas on Galaxy manga source are not updating

### Tachiyomi version

O.14.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2023-09-14 07:14
Duplicate of #17927

**Closed by vetleledaal** 2023-09-14 07:14 UTC
Labels: Bug
