### ISSUE TITLE
BentoManga (JapanRead) No Result Found

### ISSUE THREAD

**Issue by VeryOldpApY** [tachiyomiorg/tachiyomi-extensions#16218] opened 2023-04-28 15:54 UTC
### Source information

fr.japanread.1.4.11

### Source language

French

### Steps to reproduce

In the application > Browse > Sources > BentoManga

### Expected behavior

Display of the source manga list.

### Actual behavior

Display of "No Result Found".

### Tachiyomi version

0.14.6-5725

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2023-04-29 01:53
Duplicate of #16146

**Closed by alessandrojean** 2023-04-29 01:53 UTC
Labels: Bug
