### ISSUE TITLE
Trouble in coomer and kemono

### ISSUE THREAD

**Issue by toto1414** [tachiyomiorg/tachiyomi-extensions#16915] opened 2023-06-29 00:44 UTC
### Source information

coomer and kemono

### Source language

All

### Steps to reproduce

The source of coomer brings only 37 chapters in all works, and the source of kemono records only 47 chapters. Will you be able to solve the problem?

### Expected behavior

Should bring all chapter 

### Actual behavior

It only brings 37 chapters 
It only brings 47 chapters

### Tachiyomi version

0.14.6

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2023-06-29 00:48
Duplicate of #16911

**Closed by alessandrojean** 2023-06-29 00:48 UTC
Labels: Bug
