### ISSUE TITLE
Meraki Scan

### ISSUE THREAD

**Issue by Nicolbr** [tachiyomiorg/tachiyomi-extensions#9549] opened 2021-10-19 21:30 UTC
### Source name

Meraki scan

### Source link

https://meraki801.com/

### Language

Spanish

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by paulo27ms** [comment] 2021-10-19 21:38
Consider removing your login details and changing your password... Whoever works on this can register.

**Comment by h-hyuuga** [comment] 2021-10-20 01:26
Duplicate of #9077

**Closed** 2021-10-20 02:05 UTC
Labels: Source request
