### ISSUE TITLE
[Source Request] <TRwebtoon>

### ISSUE THREAD

**Issue by onursedef** [tachiyomiorg/tachiyomi-extensions#5458] opened 2021-01-16 18:52 UTC
## Source Website
- Name: TRwebtoon
- Link: https://trwebtoon.com/
- Language(s): Turkish

## Other Details
Adult Webtoons

**Comment by scb261** [comment] 2021-01-16 19:01
Duplicate of #4733

**Closed** 2021-01-16 19:25 UTC
Labels: Source Request
