### ISSUE TITLE
Banana crítica 

### ISSUE THREAD

**Issue by Diegoberna** [tachiyomiorg/tachiyomi-extensions#15801] opened 2023-03-22 22:38 UTC
### Source information and language

Banana crítica 1.4.32

### Source new URL

http://bananacitrica.com

### Other details

O site da Scan caiu e ontem (21l03l2023) retornou com outro site.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by scb261** [comment] 2023-03-22 23:58
Duplicate of #15792

**Closed** 2023-03-22 23:58 UTC
Labels: Bug, Domain changed
