### ISSUE TITLE
Arabshentai

### ISSUE THREAD

**Issue by saidsahra15** [tachiyomiorg/tachiyomi-extensions#10504] opened 2022-01-18 19:15 UTC
### Source name

Arabshentai

### Source link

https://arabshentai.com/manga

### Language

Arab

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by saidsahra15** [comment] 2022-01-18 19:16
There is not hentai source in Arabic. I suggest this because it is the best

**Comment by arkon** [comment] 2022-01-18 19:45
Duplicate of #6189

**Closed by arkon** 2022-01-18 19:45 UTC
Labels: Source request
