### ISSUE TITLE
Http403 error but not in web view

### ISSUE THREAD

**Issue by Izunyaaan** [tachiyomiorg/tachiyomi-extensions#9891] opened 2021-11-21 22:54 UTC
### Source information

1st Kiss 1.2.18

### Steps to reproduce

1. Open any title from this source
2. Try to read a chaoter

### Expected behavior

Chaoter opens

### Actual behavior

Says http 403 error

### Tachiyomi version

0.12.3

### Android version

Android 10

### Other details

Earlier there was an update and just now 2 titles came up. I tried downloading both, 1 succeeded and the other failed. After deleting the downloaded one it says http 403 error again.

Both titles work when using webview so I dont think the ip is blocked. And no cloudflare captcha.

There was a similar ticket but on previous version of extension and closed without a fix though... Not looking so good for this ticket xD

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by samanta-widjaja** [comment] 2021-11-22 11:00
From the previous extension it is still not fix. And the thread is still open

**Comment by Izunyaaan** [comment] 2021-11-22 11:33
Oh was it still open? Sorry, I couldnt reply to the thread so I thought it
was closed

**Comment by arkon** [comment] 2021-11-22 13:30
Duplicate of #9377

**Closed by arkon** 2021-11-22 13:30 UTC
Labels: Bug
