### ISSUE TITLE
mangaswat doesn't work 

### ISSUE THREAD

**Issue by AhmedGamal09** [tachiyomiorg/tachiyomi-extensions#8079] opened 2021-07-12 18:30 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android 11

### Source information

MangaSwat 1.2.7

### Steps to reproduce

1. installed mangaswat extension and open it
2. it shows (site protected, open webview)
3. opening it in webview didn't do any thing and the problem still exists

### Expected behavior

when opening the source it must show the manhua

### Actual behavior

it shows (site protected, open webview)

### Other details

tried to use other versions of the app didn't solve it

**Comment by alessandrojean** [comment] 2021-07-15 20:31
Duplicate of #6678

**Closed by alessandrojean** 2021-07-15 20:31 UTC
Labels: Bug
