### ISSUE TITLE
Gmanga No Chapters Found

### ISSUE THREAD

**Issue by NaifAhmad** [tachiyomiorg/tachiyomi-extensions#9146] opened 2021-09-20 07:51 UTC
### Source information

"Gmanga 1.2.6"

### Steps to reproduce

1 - open Gmanga-extension 
2 - open manga

### Expected behavior

Manga Chapters should appear 

### Actual behavior

The manga chapters did not open, it was showing an error

### Tachiyomi version

0.12.2

### Android version

Android 11

### Other details

![Screenshot_٢٠٢١٠٩٢٠-١٠٣٧٣٧_Tachiyomi](https://user-images.githubusercontent.com/91052254/133970969-4d294e7e-da14-4e45-97ac-663458d509c7.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2021-09-20 12:53
Duplicate of #9125

**Closed by arkon** 2021-09-20 12:53 UTC
Labels: Bug
