### ISSUE TITLE
nHentai show gallery preview of pages manga pages

### ISSUE THREAD

**Issue by MatteCrystal** [tachiyomiorg/tachiyomi-extensions#5547] opened 2021-01-24 23:59 UTC
Many people like to glance over a few pages of a manga before favoriting or downloading. It can give insights into if you'll like the manga or and give you and idea of the art quality. Being able to see multiple pages in a thumbnail gallery would be great for this. 

If speed of the app is an issue (I don't think it should be considering web browser does it fast) But if it is for such a feature than I would argue you should implement one or both of the following. 

1. A drop down toggle that is initially closed that will show gallery view. 
2. A setting to allow users to decide if they want to show the gallery by default.

**Comment by scb261** [comment] 2021-01-25 00:02
Duplicate of https://github.com/tachiyomiorg/tachiyomi/issues/1632

**Closed** 2021-01-25 00:10 UTC
Labels: enhancement
