### ISSUE TITLE
Kumapoi change domain to komiksay

### ISSUE THREAD

**Issue by lossdol567** [tachiyomiorg/tachiyomi-extensions#16799] opened 2023-06-20 15:15 UTC
### Source name

Kumapoi 

### Source language

Indonesia 

### Source link

https://kumapoi.me

### Other details

Source link https://kumapoi.me change domain to https://komiksay.site  this is new source 
Please fix domain 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2023-06-20 18:39
Duplicate of #16626

**Closed by alessandrojean** 2023-06-20 18:39 UTC
Labels: Source is down
