### ISSUE TITLE
Zerobyw URL error

### ISSUE THREAD

**Issue by Zfeng-zhuang** [tachiyomiorg/tachiyomi-extensions#15700] opened 2023-03-14 03:15 UTC
### Source information and language

Zerobyw 1.4.13 (Chinese)

### Source new URL

https://www.zerobyw4090.com/

### Other details

![Screenshot_2023-03-14-11-10-42-37_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/67086289/224883692-0240abf1-af60-49bc-ace8-3d2861691e97.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment] 2023-03-14 03:23
Duplicate of #15134

**Closed by stevenyomi** 2023-03-14 03:23 UTC
Labels: Bug, Domain changed
