### ISSUE TITLE
1st Kiss (EN) rate limit

### ISSUE THREAD

**Issue by Doomking517** [tachiyomiorg/tachiyomi-extensions#11315] opened 2022-04-03 09:31 UTC
### Source information

1st Kiss (EN) 1.2.23

### Steps to reproduce

Step one: lots of manga from 1st kiss
Step two: update
Step three: get 429 error

### Expected behavior

Not get a 429 error

### Actual behavior

Getting a 429 error

### Tachiyomi version

Preview r4224

### Android version

Android 11

### Other details

Solution = add a rate limit

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment] 2022-04-03 09:37
Duplicate of #11280

**Closed by curche** 2022-04-03 09:37 UTC
Labels: Bug
