### ISSUE TITLE
[Bug] <Aloalivn>: <not smooth scrolling>

### ISSUE THREAD

**Issue by FlammFR** [tachiyomiorg/tachiyomi-extensions#5589] opened 2021-01-29 21:04 UTC
## Device information
- Tachiyomi version: 0.10.7
- Android version: 9

## Source information
- Name: Aloalivn
- Extension version: 1.2.176

## Steps to reproduce
1. Read Release That Witch or Martial God Asura (maybe there are others)
2. Scroll

### Expected behavior
Smooth scrolling, as usual

### Actual behavior
Jerky scrolling

## Other details
This doesn't happen to some other manga like Divine Emperor or Heavenly God Mnemonic

**Comment by scb261** [comment] 2021-01-29 21:32
Duplicate of https://github.com/tachiyomiorg/tachiyomi/issues/1908

**Closed by scb261** 2021-01-29 21:32 UTC
Labels: bug
