### ISSUE TITLE
No abre el capitulo

### ISSUE THREAD

**Issue by TUMAWA** [tachiyomiorg/tachiyomi-extensions#16210] opened 2023-04-27 22:57 UTC
### Source information

Leercapitulo versión  1.4.3

### Source language

Español

### Steps to reproduce

Al internar abrir el capitulo no habre y sale index: 92, size:41 y el número varía al intentar habriirlo de nuevo  o dependiendo del manhwa o manga.

### Expected behavior

Solo deberia habría el capitulo coj normalidad 

### Actual behavior

No debería salir lo indicado.

### Tachiyomi version

Stable 0.14.6

### Android version

Android 13

### Other details

Solo pasa con la fuente Leercapitulo

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2023-04-27 23:32
Duplicate of #16209

**Closed by alessandrojean** 2023-04-27 23:32 UTC
Labels: Bug
