### ISSUE TITLE
Inarimanga

### ISSUE THREAD

**Issue by Suiren5** [tachiyomiorg/tachiyomi-extensions#13424] opened 2022-09-10 09:49 UTC
### Source information and language

InariManga 1.3.21

### Steps to reproduce

1. No aparece ningún manhwa de la extensión, sale error
![Screenshot_2022-09-10-11-47-05-085_eu kanade tachiyomi](https://user-images.githubusercontent.com/104227072/189478051-073d6bb9-14cb-4fab-a38b-55b1fe218630.jpg)

### Expected behavior

Debería aparecer los manhwas de la extensión 

### Actual behavior

No aparece ningún manhwa a pesar de estar vinculado con la página 
![Screenshot_2022-09-10-11-47-15-013_eu kanade tachiyomi](https://user-images.githubusercontent.com/104227072/189478062-b437119f-140a-4c98-af46-acb27abd1360.jpg)

### Tachiyomi version

0.13.6

### Android version

Miui 13.0.2

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2022-10-01 23:41
Duplicate of #12523

**Closed by vetleledaal** 2022-10-01 23:41 UTC
Labels: Bug
