### ISSUE TITLE
Mangasusu has changed URL

### ISSUE THREAD

**Issue by harphobia** [tachiyomiorg/tachiyomi-extensions#11027] opened 2022-03-06 12:01 UTC
### Source information

Mangasusu 1.2.13

### Steps to reproduce

The extension uses an old URL from before they remade their website with a new URL.

### Expected behavior

Should be corrected to https://mangasusu.cc

### Actual behavior

The extension uses an old URL, so it comes back with an error message "NXDOMAIN"

### Tachiyomi version

0.13.1

### Android version

Android 11

### Other details

additional URL for mangasusu

1.https://mangasusu.cc
2.http://194.233.87.209/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment] 2022-03-06 12:32
>  I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open issue.

Duplicate of #11019

**Closed by curche** 2022-03-06 12:32 UTC
Labels: Bug
