### ISSUE TITLE
[Feature Request] : <Add Personal Notes>

### ISSUE THREAD

**Issue by alhatmy** [tachiyomiorg/tachiyomi-extensions#6102] opened 2021-03-08 19:42 UTC
## What feature should be added to this source?

To have small place to add personal notes saved in my app; if I want to add notes of current Arc / what's on this story .. Since there are many stories to add ...

**Comment by scb261** [comment] 2021-03-08 19:45
Duplicate of tachiyomiorg/tachiyomi#2155

**Closed by scb261** 2021-03-08 19:45 UTC
Labels: enhancement
