### ISSUE TITLE
A 429 error with 1st kiss extension 

### ISSUE THREAD

**Issue by Alaali03** [tachiyomiorg/tachiyomi-extensions#14883] opened 2023-01-10 17:20 UTC
### Source information and language

1st kiss / ver.1.3.34

### Steps to reproduce

Updating the library causes me to get a a failed update notification which consists of the manga/manwha that are from the 1st kiss extension in my library 
![Screenshot_20230110_145629_Brave](https://user-images.githubusercontent.com/95711137/211545537-55943510-39d3-4e55-9ba9-62cd8d6970aa.jpg)

### Expected behavior

Should show me new chapters 

### Actual behavior

Failed updates

### Tachiyomi version

0.14.3

### Android version

Android version 12 / one UI ver 4.1.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2023-01-10 17:20
Duplicate of #14850

**Closed by alessandrojean** 2023-01-10 17:20 UTC
Labels: Bug
