### ISSUE TITLE
Mangarolls webpage is missing 

### ISSUE THREAD

**Issue by Baymax325** [tachiyomiorg/tachiyomi-extensions#18643] opened 2023-10-21 11:49 UTC
### Source information

Mangarolls 

### Source language

English

### Steps to reproduce

1. Open extension
2. Won't open

### Expected behavior

I should be able to browse manhwa

### Actual behavior

Can't browse 

### Tachiyomi version

0.14.6

### Android version

Android 13

### Other details

It's says unknown host exception 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by KirinRaikage** [comment] 2023-10-21 18:00
Duplicate of #18625

**Closed** 2023-10-21 18:05 UTC
Labels: Bug
