### ISSUE TITLE
Asurascan tr no Page 

### ISSUE THREAD

**Issue by Nurullahgrlk** [tachiyomiorg/tachiyomi-extensions#16312] opened 2023-05-04 20:10 UTC
### Source information

1.4.45

### Source language

Turkısh 

### Steps to reproduce

Page not found 

### Expected behavior

Fix 

### Actual behavior

Fix

### Tachiyomi version

0.14.6

### Android version

Android 13

### Other details

When I try to read manga it gives page not found error

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by luigiMinardi** [comment] 2023-05-04 20:16
Probably a duplicate of #16251

**Closed** 2023-05-05 14:59 UTC
Labels: Bug
