### ISSUE TITLE
Niadd

### ISSUE THREAD

**Issue by mariaotaku** [tachiyomiorg/tachiyomi-extensions#10640] opened 2022-01-31 21:17 UTC
### Source name

Niadd

### Source link

https://es.niadd.com

### Language

Spanish

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by jopejoe1** [comment] 2022-01-31 22:45
Duplicate of #8743

**Comment by mariaotaku** [comment] 2022-01-31 22:57
> Duplicate of #8743

No es un duplicado, ya que estamos pidiendo la web de Niadd no de Ninemanga, por favor añadir Niadd

**Comment by mariaotaku** [comment] 2022-01-31 22:59
> Duplicate of #8743

¿No encuentro Niadd, dónde la puedo agregar a extensiones en Tachiyomi?

Por favor, todos los fans latinoamericanos lo estamos pidiendo

**Closed** 2022-01-31 23:01 UTC
Labels: Source request
