### ISSUE TITLE
Extension changed site URL 

### ISSUE THREAD

**Issue by Diegofsp98** [tachiyomiorg/tachiyomi-extensions#12418] opened 2022-07-02 23:38 UTC
### Source information

Tatakae scan 1.3.22

### Steps to reproduce

Extension don't work 

### Expected behavior

New scan site https://tatakaescan.com/

### Actual behavior

Change to new site https://tatakaescan.com/ 

### Tachiyomi version

0.13.4

### Android version

Android 11

### Other details

The extension changed site, the new one is https://tatakaescan.com/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-07-02 23:57
Duplicate of #12417

**Closed by alessandrojean** 2022-07-02 23:57 UTC
Labels: Bug
