### ISSUE TITLE
Change of domain

### ISSUE THREAD

**Issue by Alrimack** [tachiyomiorg/tachiyomi-extensions#14242] opened 2022-11-13 06:13 UTC
### Source information and language

Vcp (Es) 1.3.6

### Steps to reproduce

"No results found" 

### Expected behavior

the font should work properly and have access to the font content

### Actual behavior

When opening to the VCP source (ES) the text "no results found" is displayed 

### Tachiyomi version

0.14.2

### Android version

Android 12

### Other details

Previously this happened due to the change of domain of the page recently the page changed domain again

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by UniverseCodex01** [comment] 2022-11-15 00:00
Entiendo tú dolor, hace dos meses ya que yo hice el mismo reporte y todavía no lo solucionan. Ya lleva tiempo que la extensión está caída.

**Comment by alessandrojean** [comment] 2022-11-15 00:28
Duplicate of #13623

**Closed by alessandrojean** 2022-11-15 00:28 UTC
Labels: Bug
