### ISSUE TITLE
MangaMx change to MangaOni (category in spanish)

### ISSUE THREAD

**Issue by Saintiti** [tachiyomiorg/tachiyomi-extensions#14510] opened 2022-12-10 08:22 UTC
### Source information and language

MangaOni

### Source new URL

https://manga-oni.com/

### Other details

https://user-images.githubusercontent.com/120244504/206840827-2f5dc463-95fd-408b-89a5-145f362bc691.mp4

When entering the past version (MangaMx) it shows a category reduced to the current one in MangaOni. A and also the search bar does not work very well with this extension I hope you can solve it good luck and thanks.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2022-12-10 23:12
Duplicate of #14504

**Closed by vetleledaal** 2022-12-10 23:12 UTC
Labels: Bug, Domain changed
