### ISSUE TITLE
[Source Request] Turkish Resources

### ISSUE THREAD

**Issue by onursedef** [tachiyomiorg/tachiyomi-extensions#5318] opened 2021-01-05 12:06 UTC
## Source Website
- Name: LovableSubs
- Link: https://lovablesubs.com/
- Language(s): Turkish
- Note: Using Madara

## Source Website
- Name: Manga Tepesi
- Link: https://mangatepesi.com/
- Language(s): Turkish

## Source Website
- Name: Gecenin Lordu
- Link: https://geceninlordu.com/
- Language(s): Turkish
- Note: Using Madara

## Other Details
Gecenin Lordu has some adult mangas. You can tag it as NSFW.

**Comment by scb261** [comment] 2021-01-05 12:24
Manga Tepesi - duplicate of #4671
As for others - separate issue for each source

**Closed** 2021-01-05 13:24 UTC
Labels: Source Request
