### ISSUE TITLE
Komik Cast: No pages found

### ISSUE THREAD

**Issue by Babu610** [tachiyomiorg/tachiyomi-extensions#12149] opened 2022-06-10 06:55 UTC
### Source information

Komikcast Ver 1.3.25

### Steps to reproduce

.

### Expected behavior

 The chapter in manga, manhwa, manhua should view its pages

### Actual behavior

 It say's No pages found when opening a chapter/download in all manga, manhwa, manhua

### Tachiyomi version

0.13.4

### Android version

Android 10

### Other details

But I can read the manga, manhwa, manhua i downloaded yesterday.
I think its bug because the domain changed, but I don't know either lmao
![Screenshot_20220610-134816_Tachiyomi](https://user-images.githubusercontent.com/107239631/173008060-d92f8be1-0b0d-407b-8540-d9c4b80a5bd4.jpg)

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment] 2022-06-10 09:00
duplicate of #12147

**Closed by Riztard** 2022-06-10 09:00 UTC
Labels: Bug
