### ISSUE TITLE
Mangademon http error 404 

### ISSUE THREAD

**Issue by Hawksaran** [tachiyomiorg/tachiyomi-extensions#17968] opened 2023-09-16 07:09 UTC
### Source information

Mangademon 1.4.4

### Source language

English 

### Steps to reproduce

![Screenshot_2023-09-16-12-37-24-36_79aa9bf7c61e266c5f841e42245e214b](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/132247482/08ea7c64-6f98-4a63-ab36-fee805cd2e14)

### Expected behavior

Usually able to.view chapter 

### Actual behavior

 Http error 404 

### Tachiyomi version

R6049

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2023-09-16 07:42
Duplicate of #17742

**Closed by vetleledaal** 2023-09-16 07:42 UTC
Labels: Bug
