### ISSUE TITLE
GMANGA: Add an option to choose the quality of the chapters.

### ISSUE THREAD

**Issue by iRahmaniMed** [tachiyomiorg/tachiyomi-extensions#8181] opened 2021-07-19 13:22 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

Provide an option that allows users to choose the quality of the chapters (medium or high quality)

### Other details

GMANGA website already provides this option

**Comment by arkon** [comment] 2021-07-19 13:28
Duplicate of #7802

**Closed by arkon** 2021-07-19 13:28 UTC
Labels: Feature request
