### ISSUE TITLE
Error 404 for manhwa.men

### ISSUE THREAD

**Issue by Marinx211** [tachiyomiorg/tachiyomi-extensions#13272] opened 2022-08-30 08:51 UTC
### Source information and language

Manhwa men 1.36

### Steps to reproduce

Error 404

### Expected behavior

It should work fine

### Actual behavior

![Screenshot_2022_0830_164857](https://user-images.githubusercontent.com/106808221/187393317-ad7fd1f4-dc6d-4168-bfeb-b3bcc458b0aa.png)

### Tachiyomi version

Im using tachij2k ver. 1.5.8

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2022-08-30 11:32
Duplicate of #13201

**Closed by Seishirou101** 2022-08-30 11:32 UTC
Labels: Bug
