### ISSUE TITLE
Manatoki Override BaseURL gets ignored

### ISSUE THREAD

**Issue by FoxSays** [tachiyomiorg/tachiyomi-extensions#11558] opened 2022-04-21 18:28 UTC
### Source information

NewToki / ManaToki v.1.2.22

### Steps to reproduce

1. Install Tachiyomi 0.13.2 or later
2. Change Override BaseURL setting on "NewToki / ManaToki" v.1.2.22
3. Open any comic from this source or attempt to browse this source.

### Expected behavior

Tachiyomi should connect to the URL provided in Override BseURL setting.

### Actual behavior

Instead, it ignores the setting completely and attempts to connect to manatoki161.net - the default setting. Since the URL leads nowhere, nothing from this source gets loaded.

### Tachiyomi version

0.13.2 and 0.13.3

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment] 2022-04-21 18:39
Can't Reproduce at my end
Tested on Stable 0.13.3 and Preview r4266 and worked fine

Make sure that:
- you have entered the new manatoki url (you haven't specified the new url in your issue. Eg: 128 instead of 161)
- you are entering the url correctly including the https part
- you are restarting the app (or force close and open again) after the baseUrl setting was changed. The app already tells to do that
- you checked WebView and solved the Captcha that is shown and refreshed the manga afterwards

Closing this for now. In case you still face issues after trying the above and going through [Troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/), feel free to comment again or reach out to us at the [Discord](https://discord.gg/tachiyomi)

**Comment by FoxSays** [comment] 2022-04-22 03:00
I have gone through all the usual steps - these are the same steps that I have to go through to make this work for 0.13.1 and earlier. I change the URL by only changing the number value in what is already there in the setting, save the setting, close the app and restart. 

So far, I have attempted the following:

- Install 0.13.0 (working), update to 0.13.1 (working), update to 0.13.2 (fails)
- Install 0.13.1 (working), update to 0.13.2 (fails), update to 0.13.3 (fails)
- Install 0.13.1 (working), update to 0.13.3 (fails)
- Install 0.13.2 (fails)
- Install 0.13.3 (fails)

Capcha was only a problem one time. I think it was when I first updated to 0.13.1. But at the time, the error was different, and web view was taking me to the correct URL. Besides, I only had to do that the one time. In all my other installs, this was not a necessary step.  In .2 and .3 it keeps trying to connect to 161 no matter what I do.

**Comment by curche** [comment] 2022-04-22 17:15
could you upload a video of how you're reproducing this (just need to install 0.13.3, change the extension settings and show webview showing unchanged url; no need to show updating from .1 to .2 or .3 etc)

**Comment by arkon** [comment] 2022-04-22 17:23
Reopening for now so it doesn't get auto-locked.

**Comment by FoxSays** [comment] 2022-05-24 03:12
Apologies for leaving this hanging... I had been away on a business trip. 

Just installed 0.13.4 and the issue happened again... but this time, I tried a few more times and found that the issue seems to be present when there is preexisting data for the plugin or when I restore the data from backup first before attempt to change the URL setting. Here is a video of what happens when the problem presents itself.

https://we.tl/t-JX3HpgvVKB

However, when I change the setting first, everything was fine.

**Comment by curche** [comment] 2022-05-24 10:45
No worries

> when I change the setting first, everything was fine.

This likely means the website url was set correctly and the backup restore process was able to pick up on that. 

Could you try a fresh install of the app, restore a backup, change the url setting, force close the app, and then: try migrating one of the broken manga from ManaToki to Manatoki and see if that works

**Closed** 2022-09-23 21:44 UTC
Labels: Bug
