### ISSUE TITLE
WNACG No Results Found in App

### ISSUE THREAD

**Issue by MitoMoto** [tachiyomiorg/tachiyomi-extensions#17315] opened 2023-07-30 04:04 UTC
### Source information

WNACG 1.4.14

### Source language

Chinese

### Steps to reproduce

The extension doesn't work in app but worked in WebView. Tried changing every single domain but still it's not working.

### Expected behavior

There should be results shown instead of no results found.

### Actual behavior

![image](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/140215708/a2af2bf5-b4bf-457b-8a14-667f3ed5400a)

### Tachiyomi version

TachiyomiJ2K 1.6.6

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment] 2023-07-30 07:49
Duplicate of #17266

**Closed by stevenyomi** 2023-07-30 07:49 UTC
Labels: Bug
