### ISSUE TITLE
Broken source

### ISSUE THREAD

**Issue by Demkids** [tachiyomiorg/tachiyomi-extensions#11449] opened 2022-04-12 22:02 UTC
### Source information

MyHentaiComic

### Steps to reproduce

Once you click the extension it says error http 404

### Expected behavior

Should show comics

### Actual behavior

Says error http 404

### Tachiyomi version

The latest one....

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment] 2022-04-13 02:15
Duplicate of #11044

**Closed** 2022-04-13 02:21 UTC
Labels: Bug
