### ISSUE TITLE
MangaPlex: Changed their theme on Beta site

### ISSUE THREAD

**Issue by AnshumanSarkar2001** [tachiyomiorg/tachiyomi-extensions#17793] opened 2023-09-04 06:59 UTC
### Source information

MangaPlex v1.4.1

### Source language

English

### Steps to reproduce

1. Redirect to new site https://beta.mangaplex.com/
2. Get manhuas and all
3. Fetch the chapters.

### Expected behavior

Get mangas and all .

### Actual behavior

Can't fetch anything

### Tachiyomi version

0.14.6

### Android version

Android 10

### Other details

Extension can't fetch chapters and is going to https://mangaplex.com/ instead of https://beta.mangaplex.com/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2023-09-14 07:26
Duplicate of #14308

**Closed by vetleledaal** 2023-09-14 07:26 UTC
Labels: Bug
