### ISSUE TITLE
HTTP ERROR 429 

### ISSUE THREAD

**Issue by NatuRao** [tachiyomiorg/tachiyomi-extensions#13340] opened 2022-09-04 08:41 UTC
### Source information and language

MangaBuddy

### Steps to reproduce

Getting HTTP 429 ERROR while refreshing manga chapters. It's saying 51 mangas failed to update.

### Expected behavior

Update all the chapters in MangaBuddy

### Actual behavior

Getting HTTP ERROR 429

### Tachiyomi version

0.13.6

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2022-09-04 14:13
Duplicate of #13182

**Closed by vetleledaal** 2022-09-04 14:13 UTC
Labels: Bug
