### ISSUE TITLE
Error pururin

### ISSUE THREAD

**Issue by uu88ww** [tachiyomiorg/tachiyomi-extensions#10442] opened 2022-01-13 05:51 UTC
### Source information

Pururin 1.2.6

### Steps to reproduce

Pururin extension 1.2.6 have different search results when open it with extension 1.2.4

### Expected behavior

I want 2 extension have same results with different version

### Actual behavior

![IMG-20220113-WA0007](https://user-images.githubusercontent.com/97656573/149273021-1248c97c-4b39-4b18-a13f-5cabc9d77927.jpg)
![Screenshot_2022-01-13-12-36-48-302_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/97656573/149273042-9f2e2cf8-825a-43c8-9fe6-94ef527e5add.jpg)

The one with 5 chapter is 1.2.4 and the other is 1.2.6
I want at 1.2.6 have 5 chapter

### Tachiyomi version

1.0.16

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ObserverOfTime** [comment] 2022-01-13 08:43
Duplicate of #9875

**Closed** 2022-01-13 08:50 UTC
Labels: Bug
