### ISSUE TITLE
Kuaikanmanhua: No results found

### ISSUE THREAD

**Issue by kitsu2** [tachiyomiorg/tachiyomi-extensions#17777] opened 2023-09-02 20:11 UTC
### Source information

kuaikanmanhua 1.4.10

### Source language

China

### Steps to reproduce

1.open the kuaikanmanhua extension 
2.No comics are shown

### Expected behavior

It should feature comics 

### Actual behavior

No comics are shown 

### Tachiyomi version

0.14.6

### Android version

Android 11

### Other details

![Screenshot_2023_0903_031040](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/137640168/1cafbe92-9617-43b2-b361-150ca1f10665)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2023-12-11 15:14
Duplicate of #17403

**Closed by vetleledaal** 2023-12-11 15:14 UTC
Labels: Bug
