### ISSUE TITLE
Mangaswat issue 

### ISSUE THREAD

**Issue by salah2021ss** [tachiyomiorg/tachiyomi-extensions#18235] opened 2023-09-28 23:34 UTC
### Source information

Mangaswat 1.4. 39

### Source language

Arabic

### Steps to reproduce

1. When i open extension i get this : 
![Screenshot_20230927_110904_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/89791415/d465698f-afb7-434d-b4a2-8f008fa00a04)
2. When i open viewbrowser its open google search not manga swat website 
![Screenshot_20230927_110322_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/89791415/a572ae80-ace2-443a-aa1e-5679072bc567)

### Expected behavior

Open mangaswat website 

### Actual behavior

Its open google search not manga swat website 

### Tachiyomi version

0.14.6

### Android version

Android 10 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-09-29 00:41
Duplicate of #18175

**Closed by arkon** 2023-09-29 00:41 UTC
Labels: Bug
