### ISSUE TITLE
problem opening Doujindesu

### ISSUE THREAD

**Issue by Pengamen1kaos** [tachiyomiorg/tachiyomi-extensions#13490] opened 2022-09-16 20:32 UTC
### Source information and language

Indonesia 1.3.2

### Steps to reproduce

1. when I want to open doujindesu as usual but this time it's different, usually there is a comic or something, now it says " no results found" 

### Expected behavior

can open doujindesu as usual and I'm already using vpn 

### Actual behavior

as soon as possible 

### Tachiyomi version

0.13.6

### Android version

Android 10

### Other details

![Uploading Screenshot_20220917-032102_Tachiyomi.jpg…]()

### Acknowledgements

- [ ] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment] 2022-09-17 13:27
Duplicate of #13444

**Closed** 2022-09-17 13:32 UTC
Labels: Bug
