### ISSUE TITLE
Zinchanmanga unable to resolve host 

### ISSUE THREAD

**Issue by aomicat** [tachiyomiorg/tachiyomi-extensions#15260] opened 2023-02-07 13:12 UTC
### Source information and language

ZinChanManga 1.3.5

### Steps to reproduce

Extension not opening up updates or any data

### Expected behavior

No address associated with host name

### Actual behavior

No address associated with host name

### Tachiyomi version

0.14.4

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment] 2023-02-10 15:10
Duplicate of #15276

**Closed by stevenyomi** 2023-02-10 15:10 UTC
Labels: Bug
