### ISSUE TITLE
Sekaikomik domain change

### ISSUE THREAD

**Issue by bgmondy** [tachiyomiorg/tachiyomi-extensions#11183] opened 2022-03-20 05:40 UTC
### Source name

Sekaikomik

### Source link

http://www.sekaikomik.best/

### Language

Indonesia

### Other details

![Screenshot_2022-03-20-12-28-29-53](https://user-images.githubusercontent.com/76152689/159149735-9c17a765-73dd-4e5d-a919-640912e33cc3.png)

sekaikomik source link has changed to sekaikomik.best

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by bgmondy** [comment] 2022-03-20 05:42
btw, can I open the webview through Yandex

**Comment by alessandrojean** [comment] 2022-04-03 23:23
Duplicate of #8220

**Closed by alessandrojean** 2022-04-03 23:23 UTC
Labels: Source request
