### ISSUE TITLE
MangaSwat: Image could not be loaded

### ISSUE THREAD

**Issue by Mhmd-Kamal** [tachiyomiorg/tachiyomi-extensions#16974] opened 2023-07-02 10:12 UTC
### Source information

MangaSwat

### Source language

Arabic 

### Steps to reproduce

Opening any manga fails and shows "image could not be loaded"

### Expected behavior

Displays the selected manga 

### Actual behavior

Opening any manga fails and shows "image could not be loaded"

### Tachiyomi version

App version: 0.14.6 

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by 7allom** [comment] 2023-07-02 19:38
#16952 you can change the url yourself

**Comment by stevenyomi** [comment] 2023-07-05 09:18
Duplicate of #16952

**Closed by stevenyomi** 2023-07-05 09:18 UTC
Labels: Bug

**Comment by Mhmd-Kamal** [comment] 2023-07-05 11:46
> #16952 you can change the url yourself

How?

**Comment by 7allom** [comment] 2023-07-05 12:46
> > #16952 you can change the url yourself
> 
> How?


https://github.com/tachiyomiorg/tachiyomi-extensions/assets/97411710/6f4aac54-fa12-47fc-8b86-ba19eec01b3f
