### ISSUE TITLE
pls fix alphascans 

### ISSUE THREAD

**Issue by NotPageD** [tachiyomiorg/tachiyomi-extensions#10489] opened 2022-01-17 12:48 UTC
### Source information

Alpha Scans 1.2.12

### Steps to reproduce

read any manga om the website

### Expected behavior

should work fine

### Actual behavior

some of the pages won't load no matter what. 

### Tachiyomi version

tachiyomisy preview r427

### Android version

android 10

### Other details

i know this issue has been opened already, i just wanted to remind you guys, thank you. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-01-17 12:57
Duplicate of #10071

**Closed by alessandrojean** 2022-01-17 12:57 UTC
Labels: Bug
