### ISSUE TITLE
changing URL for extension ReaperScans to ShinigamiID

### ISSUE THREAD

**Issue by fulfoo** [tachiyomiorg/tachiyomi-extensions#15414] opened 2023-02-20 07:47 UTC
### Source information and language

ReaperScans (Indonesian)

### Source new URL

shinigami.id

### Other details

please update this extension 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2023-02-20 08:47
Duplicate of #15408

**Closed by Seishirou101** 2023-02-20 08:47 UTC
Labels: Bug, Domain changed

**Comment by kolinrno** [comment] 2023-02-22 19:24
> Duplikat #15408

will reaperscan not get an existence update?
