### ISSUE TITLE
Asurascans changed some links

### ISSUE THREAD

**Issue by Hrym1337** [tachiyomiorg/tachiyomi-extensions#16310] opened 2023-05-04 18:43 UTC
### Source information

Asura Scans 1.4.45

### Source language

english

### Steps to reproduce

refreshing manhwa (for example Doom breaker/ Reincarnation of the suicidal battle god)
Manually refresh by pulling down.
on the bottom shows up a message that says Http error 404
check web view  and i see that the url changed

### Expected behavior

Refreshes

### Actual behavior

Http error 404

### Tachiyomi version

0.14.6

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2023-05-04 19:23
Duplicate of #16251

**Closed by alessandrojean** 2023-05-04 19:23 UTC
Labels: Bug
