### ISSUE TITLE
Doujindesu not pop anything.

### ISSUE THREAD

**Issue by Kiki88x** [tachiyomiorg/tachiyomi-extensions#14560] opened 2022-12-15 07:28 UTC
### Source information and language

Doujindesu 1.3.3 (indonesia) 

### Steps to reproduce

1. Open doujindesu
2. Open library
3. Read/search in doujindesu 

### Expected behavior

There's should be appear an images in the library of doujindesu. And the comics can be readied. 

### Actual behavior

Only blank part, with name the comics, nothing can do.
It can't be readed, download, etc. 

### Tachiyomi version

0.14.2

### Android version

Android 9

### Other details

![Screenshot_20221215-162704](https://user-images.githubusercontent.com/70476061/207798796-d9164872-c4d9-4312-b363-66f8f621ee29.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2022-12-15 19:59
Duplicate of #14004 and #11662

**Closed by vetleledaal** 2022-12-15 19:59 UTC
Labels: Bug
