### ISSUE TITLE
MangaHub: Failed to Load Pages in Manga and Manhwa

### ISSUE THREAD

**Issue by PheonixGamer09** [tachiyomiorg/tachiyomi-extensions#16347] opened 2023-05-07 05:00 UTC
### Source information

Mangahub 1.4.28

### Source language

English

### Steps to reproduce

1. When open any Manga and Manhwa it shows Failed to load Pages.
![image](https://user-images.githubusercontent.com/128516302/236658349-7eecf0c3-25d3-4edd-bc50-cf3d62a479ad.png)

### Expected behavior

All Manga and Manhwa Chapter Pages should be uploaded without any issue

### Actual behavior

It Shows "Failed to Load Pages"
![image](https://user-images.githubusercontent.com/128516302/236658584-f6400330-f6fb-4f68-a043-3e40665fb893.png)
![image](https://user-images.githubusercontent.com/128516302/236658588-34af6cbe-524e-4193-89a6-ebe459d86897.png)

### Tachiyomi version

0.14.6

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment] 2023-05-07 05:16
Duplicate of #16297

**Closed by stevenyomi** 2023-05-07 05:16 UTC
Labels: Bug
