### ISSUE TITLE
[Source Request] <Manga Rock Team>

### ISSUE THREAD

**Issue by zishann** [tachiyomiorg/tachiyomi-extensions#7706] opened 2021-06-17 15:46 UTC
## Source website
- Name: Manga Rock Team
- Link: https://mangarockteam.com/home/
- Language(s): English

**Comment by Seishirou101** [comment] 2021-06-17 15:57
already exists.

**Comment by Seishirou101** [comment] 2021-06-17 15:57
Duplicate of #2872

**Closed** 2021-06-17 16:01 UTC
Labels: Source Request
