### ISSUE TITLE
MangaOwl: No pages found

### ISSUE THREAD

**Issue by lmaocarsi** [tachiyomiorg/tachiyomi-extensions#11182] opened 2022-03-20 02:00 UTC
### Source information

MangaOwl 1.2.24

### Steps to reproduce

1. Click the manga
2. Click the chapters
3. It doesn't load and says "No pages found"

### Expected behavior

The chapter should have opened after waiting for it to load

### Actual behavior

Even after refreshing and re-installing MangaOwl the chapters doesn't load

### Tachiyomi version

Tachiyomi 0.13.1

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2022-03-20 23:25
Duplicate of #10463

**Closed** 2022-03-20 23:26 UTC
Labels: Bug
