### ISSUE TITLE
Cambio de dominio

### ISSUE THREAD

**Issue by Pokoma** [tachiyomiorg/tachiyomi-extensions#12517] opened 2022-07-10 06:10 UTC
### Source information

MangasTK 1.3.21

### Steps to reproduce

La extensión de MnagasTk.com cambió a MangasTK.net

### Expected behavior

.

### Actual behavior

.

### Tachiyomi version

0.13.5

### Android version

12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2022-07-10 06:33
Duplicate of #12366

**Closed by vetleledaal** 2022-07-10 06:33 UTC
Labels: Bug
