### ISSUE TITLE
Chapter loading problem

### ISSUE THREAD

**Issue by Masrurkeepit** [tachiyomiorg/tachiyomi-extensions#14782] opened 2023-01-03 09:43 UTC
### Source information and language

Photos18 1.3.1 (All)

### Steps to reproduce

1. Select the title
2. Choose the chapter
3. The image couldn't be loaded

### Expected behavior

1. Select the title
2. Choose the chapter
3. Pictures starts loading 

### Actual behavior

1. Select the title 
2. Choose the chapter
3. Pictures starts loading

### Tachiyomi version

Tachiyomi Sy 1.8.5

### Android version

12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment] 2023-01-17 21:19
Duplicate of #14763

**Closed** 2023-01-17 21:19 UTC
Labels: Bug
