### ISSUE TITLE
doesn't show the new chapters

### ISSUE THREAD

**Issue by KevinFrias051** [tachiyomiorg/tachiyomi-extensions#19088] opened 2023-11-23 22:55 UTC
### Source name

muslos no sekai

### Source language

spanish

### Describe your suggested feature

It doesn't show the new chapters

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by BrutuZ** [comment] 2023-11-23 22:58
Duplicate of #18894
> - [x] I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open or closed issue.

**Closed** 2023-11-23 23:00 UTC
Labels: Feature request
