### ISSUE TITLE
MangaHub 1.3.16 - Cannot read/download manga 

### ISSUE THREAD

**Issue by Rohan-Somadder** [tachiyomiorg/tachiyomi-extensions#12973] opened 2022-08-13 15:56 UTC
### Source information and language

MAngaHub 1.3.16 (English)

### Steps to reproduce

1. Try to read any chapter of manga from the mangahub source
2.  It doesn't download or allows reading online
3.  and shows an error download

### Expected behavior

Should be able to download/ read online

### Actual behavior

Field 'data' is required for type with serial name 'eu.kanade.tachiyomi.multisrc.mangahub.GraphQLDataDto', but it was missing

### Tachiyomi version

Stable 0.13.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-08-13 15:56
Duplicate of #12959

**Closed by arkon** 2022-08-13 15:56 UTC
Labels: Bug
