### ISSUE TITLE
[Bug] Reaper Scan: Error 404 even if the webview work and the site is Online

### ISSUE THREAD

**Issue by Terra00** [tachiyomiorg/tachiyomi-extensions#5654] opened 2021-02-06 17:57 UTC
## Device information
- Tachiyomi version: 10.8
- Android version: 10

## Source information
- Name: Genkan
- Extension version: 1.2.25

## Steps to reproduce
1. Update library
2. Check error notification
3. Check if the site is down or the manga is removed
4. Repeat

### Expected behavior
Update the library and if there is new chapter they download and notify me

### Actual behavior
They give the error 404 even when the web site is online and when the manga is there

## Other details
List of thing that i check before create this:
1) Uninstall and reinstall the app and the extension
2)Check if is only this source that have problem
![photo_2021-02-06_18-57-37](https://user-images.githubusercontent.com/53008550/107125963-356e8b00-68ad-11eb-8080-7aafdc1b7ff0.jpg)
![photo_2021-02-06_18-57-36](https://user-images.githubusercontent.com/53008550/107125964-36072180-68ad-11eb-8d2c-6b10db6b3769.jpg)

**Comment by Seishirou101** [comment] 2021-02-06 18:01
They changed the url for the manga, if it still exists on the site, you can just migrate from reaper scans to reaper scans to update the urls

**Comment by scb261** [comment] 2021-02-06 18:07
Duplicate of #5642

**Closed by scb261** 2021-02-06 18:07 UTC
Labels: bug
