### ISSUE TITLE
Mangakakalot incorrect chapter release date

### ISSUE THREAD

**Issue by EltonOng** [tachiyomiorg/tachiyomi-extensions#14779] opened 2023-01-03 07:55 UTC
### Source information and language

Managakakalot (EN)

### Steps to reproduce

1. Open Managakakalot
2. Open any manga

### Expected behavior

The release date should be the same as on the website.

### Actual behavior

![photo1672711525 (1)](https://user-images.githubusercontent.com/40973216/210317828-db9eac86-4097-4633-8483-b5796a1303d4.jpeg)
![photo1672711525](https://user-images.githubusercontent.com/40973216/210317830-e6be8e45-6c4e-4527-ad89-384dfaa8a6e7.jpeg)

### Tachiyomi version

0.14.2

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2023-09-15 17:46
Can't reproduce. Possibly fixed by #7257 , hard to say when the extension version is not provided.

Mangakakalot 1.4.8 matches the website:
![image](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/13540478/deee878a-622f-4bfe-8e50-9506bec83850)

**Closed by vetleledaal** 2023-09-15 17:46 UTC
Labels: Bug, Factory source
