### ISSUE TITLE
[Bug] <mangaswat>: <site protected, open webview>

### ISSUE THREAD

**Issue by ahmedgamal17** [tachiyomiorg/tachiyomi-extensions#7371] opened 2021-06-01 18:32 UTC
## Device information
- Tachiyomi version: 0.11.1
- Android version: 11(R)

## Source information
- Name: mangaswat
- Extension version: 1.2.4

## Steps to reproduce
opening the extension source mangaswat

### Expected behavior
manga list appear

### Actual behavior
manga doesn't appear 
it say Site protected ,Open WebView

## Other details
when i open it in  webview it works fine but not in the app
i followed this [link](https://tachiyomi.org/help/guides/troubleshooting/#diagnosis)  but it didn't help to fix it 

App version: 0.11.1 (standard, 0f3f1e9, 63, 2021-05-31T23:39Z)
Android version: 11 (SDK 30)
Android build ID: RKQ1.201022.002 test-keys
Device brand: Redmi
Device manufacturer: Xiaomi
Device name: sunny
Device model: M2101K7AG
Device product name: sunny_global

**Comment by alessandrojean** [comment] 2021-06-01 18:37
Duplicate of #6678.

**Closed by alessandrojean** 2021-06-01 18:37 UTC
Labels: bug
