### ISSUE TITLE
Olympus scanlation

### ISSUE THREAD

**Issue by julioxd123** [tachiyomiorg/tachiyomi-extensions#15472] opened 2023-02-25 04:00 UTC
### Source information and language

https://olympusscanlation.com/

### Source new URL

https://olympusscans.com/

### Other details

Esta página a echo un cambio total de su biblioteca y la app tachiyomi no puede ingresar correctamente a esta

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2023-02-26 02:32
Duplicate of #15330

**Closed by Seishirou101** 2023-02-26 02:32 UTC
Labels: Bug, Domain changed
