### ISSUE TITLE
[Source Request] <Senpai Edicione>

### ISSUE THREAD

**Issue by Elcrack14** [tachiyomiorg/tachiyomi-extensions#7752] opened 2021-06-19 15:09 UTC
## Source website
- Name: Senpai Edición 
- Link: https://senpaiediciones.com
- Language(s): Spanish (Es)

**Comment by Clouddark75** [comment] 2021-06-20 16:19
Duplicate of#7359

**Closed** 2021-06-20 16:19 UTC
Labels: Source Request
