### ISSUE TITLE
Cyanide and Happiness extractor returns 404s

### ISSUE THREAD

**Issue by SuperSonicHub1** [tachiyomiorg/tachiyomi-extensions#10451] opened 2022-01-13 17:30 UTC
### Source information

Cyanide & Happiness 1.2.3

### Steps to reproduce

1. Go to Browse > Sources > Cyanide & Happiness.
2. Get "no results found" error.

### Expected behavior

Should be populated with sources.

### Actual behavior

No sources. If you already have a Cyanide & Happiness source and try to refresh it, you'll get a 404.

### Tachiyomi version

App version: 0.12.3 (standard, e863e8c64, 69, 2021-10-07T00:06Z) 

### Android version

Android version: 12 (SDK 31)

### Other details

Android build ID: SQ1A.220105.002 Device brand: google Device manufacturer: Google Device name: sargo Device model: Pixel 3a Device product name: sargo

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-01-13 17:33
Duplicate of #10224

**Closed by arkon** 2022-01-13 17:33 UTC
Labels: Bug
