### ISSUE TITLE
Manga Demon: No Chapters Found

### ISSUE THREAD

**Issue by Spectrald** [tachiyomiorg/tachiyomi-extensions#19362] opened 2023-12-19 12:40 UTC
### Source information

Manga Demon 1.4.7

### Source language

English

### Steps to reproduce

1. Open Manga Demon
2. Click on any manga/manhwa

### Expected behavior

Should display manga/manhwa with chapters

### Actual behavior

Shows "No Chapters Found"

### Tachiyomi version

0.14.7

### Android version

Android 9

### Other details

When you open it via web view, the site works well and the mangas/manhwas are updated.
When you migrate a manga/manhwa that's from manga demon, it shows "No results found"

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2023-12-19 15:45
Duplicate of #19359

**Closed by vetleledaal** 2023-12-19 15:45 UTC
Labels: Bug
