### ISSUE TITLE
Nhentai problem

### ISSUE THREAD

**Issue by demon456blade** [tachiyomiorg/tachiyomi-extensions#13099] opened 2022-08-20 02:48 UTC
### Source information and language

Nhentai

### Steps to reproduce

So when I go to nhentai I can't seem to go in I tried trouble shooting deleting cookies , reinstalling nhentai and so on
![Screenshot_TachiyomiJ2K_2022-08-19-22-46-47-744](https://user-images.githubusercontent.com/82254389/185726205-94c7c25c-c4e1-45d0-a19d-19aab67e6e71.png)
![Screenshot_TachiyomiJ2K_2022-08-19-22-46-04-783](https://user-images.githubusercontent.com/82254389/185726207-642ca520-2d3a-4364-8af6-1d825bf954f8.png)

### Expected behavior

What should have happened is me being in nhentai being able to preview everything

### Actual behavior

What happens is not being able to access nhentai

### Tachiyomi version

Lates version

### Android version

Latest Android 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-08-20 02:49
Duplicate of https://github.com/tachiyomiorg/tachiyomi-extensions/issues/12784

**Closed by arkon** 2022-08-20 02:49 UTC
Labels: Bug
