### ISSUE TITLE
LA  EXTENCION DE MANHWA-LATINO NO DETECTA CAPÍTULOS 

### ISSUE THREAD

**Issue by Fran2184** [tachiyomiorg/tachiyomi-extensions#14769] opened 2023-01-02 23:09 UTC
### Source information and language

Manhwa-latino v1.3.20

### Steps to reproduce

Entro a la extecion de manhwa latino
Selecciono una serie
No muestra capítulos 

### Expected behavior

Al seleccionar una serie esta debería mostrar su listado de capítulos actuales

### Actual behavior

Después de seleccionar la serie esta dice 
No se encontraron capítulos 
Y en su lugar muestra 0 capítulos 

### Tachiyomi version

0.14.2

### Android version

Android 12

### Other details

![Screenshot_20230102-170459_Tachiyomi](https://user-images.githubusercontent.com/121770368/210283802-50c72470-3575-4bdf-94fa-b594c5973eb6.jpg)
![Screenshot_20230102-170450_Tachiyomi](https://user-images.githubusercontent.com/121770368/210283806-1bfa1fa5-2eba-4346-a7eb-35890629bff5.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2023-01-02 23:17
Duplicate of #14637

**Closed by alessandrojean** 2023-01-02 23:17 UTC
Labels: Bug
