### ISSUE TITLE
Source

### ISSUE THREAD

**Issue by Mingo3347** [tachiyomiorg/tachiyomi-extensions#14954] opened 2023-01-15 08:47 UTC
### Source name

Azora

### Source link

https://www.google.com/url?sa=t&source=web&rct=j&url=https://azoranov.com/&ved=2ahUKEwj9-9L6l8n8AhV-VKQEHSWjBAgQFnoECAoQAQ&usg=AOvVaw2-UQ5qc752Z-HYjHYsmj7E

### Language

Arabic

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment] 2023-01-15 08:59
Duplicate of #14925

**Closed by loocool2** 2023-01-15 08:59 UTC
Labels: Source request
