### ISSUE TITLE
MangaFire Extension Down And Not Working

### ISSUE THREAD

**Issue by CyberSlither** [tachiyomiorg/tachiyomi-extensions#17913] opened 2023-09-12 12:30 UTC
### Source information

MangaFire

### Source language

Multi

### Steps to reproduce

Two Separate Ways to generate an error 
1 Navigate : Browse -> Sources -> MangaFire
2 Navigate : Library -> (name of manga downloaded by MangaFire) -> (Refresh Page/Check For New Downloads)

### Expected behavior

Manga titles should be shown
Manga titles should be available to download
Downloaded Manga titles should be updated/refreshed
Manga titles should sync

### Actual behavior

1 Extension Shows "No results found"
2 Opens in WebView
3 Previously Downloaded Manga Load but fail to sync and update
4 Manga Browsing and Downloading in app Unavailable
5 When Previously downloaded manga is refreshed, "JsonDecodingException: Expected start of the object '(, but had 'EOF' instead at path: $ JSON input: ....ets/t2/min/all.js? 64fa640064faca17"></script></body> </html>" error is given via a pop up
6 Screenshot of error : 
![Tachiyomi error](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/144510745/eee4aa8e-34a4-4d04-ab20-cb8834d2f47a)
7 Not working on other devices as well

### Tachiyomi version

0.14.6

### Android version

Android 13

### Other details

This started less than a week ago and I think it might be because the website got a new UI?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [x] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2023-09-12 12:39
Duplicate of #17799

**Closed by Seishirou101** 2023-09-12 12:39 UTC
Labels: Bug
