### ISSUE TITLE
Manga chapters are not shown for any manga in the app

### ISSUE THREAD

**Issue by lokeshvs1106** [tachiyomiorg/tachiyomi-extensions#12353] opened 2022-06-28 09:37 UTC
### Source information

Early manga 1.3.17

### Steps to reproduce

Any manga i search in this extension. It shows only one chapter. In the website i can see all the remaining chapters but in the app it is not updating the chapters. It says no chapters found. Only one chapter without a number is displayed for all the mangas in this extension.

### Expected behavior

It should show the available chapters for the manga.

### Actual behavior

It shows only one chapter for any manga i search

### Tachiyomi version

0.13.4

### Android version

Android 12

### Other details

![Screenshot_2022-06-28-15-06-17-46_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/31844094/176146587-f96cfe86-9ef5-460a-adfb-9d3d7d1f1193.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-06-28 13:16
Duplicate of #12192

**Closed by arkon** 2022-06-28 13:16 UTC
Labels: Bug
