### ISSUE TITLE
Galaxy Action 

### ISSUE THREAD

**Issue by YYSS15** [tachiyomiorg/tachiyomi-extensions#18869] opened 2023-11-05 22:34 UTC
### Source name

Galaxy Action 

### Source link

https://galaxyaction.site/

### Source language

Arabic 

### Acknowledgements

- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension is not on [the removed sources list](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/REMOVED_SOURCES.md).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-11-05 22:37
For what it's worth, recreating issues very likely will not help anything get addressed any faster. The fastest way to actually get somebody to do it would be to contribute it yourself or find an interested developer that can read Arabic because there traditionally hasn't been one that's active in the community.

**Comment by arkon** [comment] 2023-11-05 22:37
Duplicate of #17831

**Closed** 2023-11-05 22:37 UTC
Labels: Source request, Duplicate

**Comment by urekxmazino** [comment] 2023-11-05 23:09
@arkon  it's already fixed in latest update,  they changed website and theme to different domain and theme and it's already fixed in latest version of the extension

**Comment by arkon** [comment] 2023-11-05 23:12
I'm not really in the loop, but I don't actually see anything in the repo with that domain, and the domain doesn't seem to redirect to something else?

**Comment by urekxmazino** [comment] 2023-11-05 23:16
@arkon  this website is related  to https://flixscans.com/webtoons/hm
which already has extensions and working  and
https://galaxyaction.site/ is abandoned site  they re upload all the work to flixscans.com that has active extension  جلاكسي مانغا
