### ISSUE TITLE
Mangasusu

### ISSUE THREAD

**Issue by lizze-p** [tachiyomiorg/tachiyomi-extensions#11233] opened 2022-03-24 20:35 UTC
### Describe why this should be added

Change domain :
https://194.233.87.209/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2022-03-24 20:40
Duplicate of #11019

**Closed by Seishirou101** 2022-03-24 20:40 UTC
Labels: Meta request
