### ISSUE TITLE
Nhentai.net failed to bypass cloudfare

### ISSUE THREAD

**Issue by breaking-loss** [tachiyomiorg/tachiyomi-extensions#13060] opened 2022-08-18 04:53 UTC
### Source information and language

Nhentai 1.3.35

### Steps to reproduce

1. Open tachiyomi
2. Go to browse
3. Click on sources
4. Click on nhentai
5. Click open in webview

### Expected behavior

When open in webview should be clicked it should pass the cloudfare test .

### Actual behavior

After opening in webview the cloudfare test should be passed and should take to the nhentai.net site .

### Tachiyomi version

0.13.6

### Android version

android 10

### Other details

I tried opening it with orbot enabled , orbot disabled ,using a VPN and just normally but all of it ends in failure .

With orbot enabled
![Screenshot_20220818-095918](https://user-images.githubusercontent.com/110153010/185296182-d713234b-aefd-4493-afec-0a44ea5ee99b.jpg)

With orbot disabled
![Screenshot_20220818-100300](https://user-images.githubusercontent.com/110153010/185296325-30cb2b8a-9c2c-4c0a-8799-d5d975a38ab4.jpg)

I can access the site with browser
![Screenshot_20220818-100101](https://user-images.githubusercontent.com/110153010/185296459-108af7d9-e4ab-42a1-a6f5-c03c939b9846.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by 12345axc** [comment] 2022-08-18 06:56
Same thing happens to me. Cloudflare only constantly reloading.

tested on Android 11

**Comment by DrPleaseRespect** [comment] 2022-08-18 07:51
I changed my useragent to a useragent that closely matches my phone (but not fully matches (different phone model but same android version)) and it worked for me

**Comment by arkon** [comment] 2022-08-18 13:03
Duplicate of #12784

**Closed by arkon** 2022-08-18 13:03 UTC
Labels: Bug

**Comment by breaking-loss** [comment] 2022-08-18 14:17
> I changed my useragent to a useragent that closely matches my phone (but not fully matches (different phone model but same android version)) and it worked for me


I did what @DrPleaseRespect suggested and it worked .I think it only affects those who have a custom ROM installed . Go to ( https://www.whatismybrowser.com/detect/what-is-my-user-agent/ ) and copy the user agent and paste it on tachiyomi>settings>advanced>useragent

**Comment by breaking-loss** [comment] 2022-08-18 14:18
@DrPleaseRespect What is the value that you can change in the user agent

**Comment by DrPleaseRespect** [comment] 2022-08-18 14:18
> > I changed my useragent to a useragent that closely matches my phone (but not fully matches (different phone model but same android version)) and it worked for me
> 
> 
> I did what @DrPleaseRespect suggested and it worked .I think it only affects those who have a custom ROM installed . Go to ( https://www.whatismybrowser.com/detect/what-is-my-user-agent/ ) and copy the user agent and paste it on tachiyomi>settings>advanced>useragent
> 


I'm on a stock samsung phone mate.

**Comment by DrPleaseRespect** [comment] 2022-08-18 14:20
> @DrPleaseRespect What is the value that you can change in the user agent 

I changed the phone model but same android version

(i.e SM-S908U to something different)
