### ISSUE TITLE
Meus Mangás: Changed their domain and name

### ISSUE THREAD

**Issue by Kirito-Senpai9** [tachiyomiorg/tachiyomi-extensions#14419] opened 2022-11-30 15:44 UTC
### Source information and language

Meus mangás 1.3.9

### Source new URL

https://seemangas.com/leitor

### Other details

A Meus Mangás mudou o nome e URL para Seemangás
Chan manga changed name and URL to Seemangás 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-12-20 13:19
Duplicate of #14218

**Closed by alessandrojean** 2022-12-20 13:19 UTC
Labels: Bug, Domain changed
