### ISSUE TITLE
Dragontea reading elements is not available. Doesn't work.

### ISSUE THREAD

**Issue by vule87** [tachiyomiorg/tachiyomi-extensions#18122] opened 2023-09-23 23:21 UTC
### Source information

Dragontea 1.4.33

### Source language

English

### Steps to reproduce

![inbound6646514111300674192](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/40471595/e0839fa6-197c-4f29-9a13-689167a3a060)
When clicked on manga, error pops up

### Expected behavior

Open to actual read

### Actual behavior

Does not open

### Tachiyomi version

Latest

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by DchanN** [comment] 2023-09-24 13:29
Duplicate of #17616

**Closed** 2023-09-24 13:35 UTC
Labels: Bug
