### ISSUE TITLE
qiximh：Failed to get the list of comics

### ISSUE THREAD

**Issue by hanxin1997** [tachiyomiorg/tachiyomi-extensions#10009] opened 2021-12-06 09:30 UTC
### Source information

qiximh 1.2.3

### Steps to reproduce

Searching for any comic or opening any of the recently updated comics will display http error 404

### Expected behavior

The search is successful, and the comic content list is obtained

### Actual behavior

Show http error 404

### Tachiyomi version

0.12.3-3999

### Android version

 Android 11

### Other details

无

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by anenasa** [comment] 2021-12-07 11:50
Searching works for me, but comics do not load probably because a trailing slash is missing in url.
Duplicate of #9718?

**Closed** 2021-12-07 12:15 UTC
Labels: Bug
