### ISSUE TITLE
Sekte Doujin: image couldn't be loaded

### ISSUE THREAD

**Issue by KiriyamaZaphkiel** [tachiyomiorg/tachiyomi-extensions#11874] opened 2022-05-15 13:35 UTC
### Source information

Sekte doujin

### Steps to reproduce

1. Open sekte doujin extension
2. Pick a title
3. Open one of the chapter
4. And it say image couldn't be loaded

### Expected behavior

The chapter suppose can be read

### Actual behavior

When i open on of the chapter from each title it say "the image couldn't be loaded"

### Tachiyomi version

Tachiyomi 0.13.4

### Android version

Android 12

### Other details

![SmartSelect_20220515-202640_Discord](https://user-images.githubusercontent.com/105593738/168475644-88940eab-cb99-4282-92bb-74709f2929e6.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2022-10-02 01:34
Can't reproduce. Images broken in the extension are also broken in WebView. Do you have any example manga and chapters where they work in WebView, but not in the extension?

**Comment by vetleledaal** [comment] 2022-11-29 12:04
Closing as there was no follow-up

**Closed by vetleledaal** 2022-11-29 12:04 UTC
Labels: Bug
