### ISSUE TITLE
Argos Scan:error updating chapters

### ISSUE THREAD

**Issue by Raidre** [tachiyomiorg/tachiyomi-extensions#12020] opened 2022-05-30 19:58 UTC
### Source information

Argos Scan 1.2.20

### Steps to reproduce

error updating new chapters

### Expected behavior

updated chapters

### Actual behavior

error updating chapters

### Tachiyomi version

13.4

### Android version

8.0.1

### Other details

no other details

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-05-30 20:16
Duplicate of #11950

**Closed by alessandrojean** 2022-05-30 20:16 UTC
Labels: Bug
