### ISSUE TITLE
MangaBuddy image doesn't load

### ISSUE THREAD

**Issue by hellbreakes** [tachiyomiorg/tachiyomi-extensions#14987] opened 2023-01-17 02:21 UTC
### Source information and language

MangaBuddy 1.3.12

### Steps to reproduce

1.Open MangaBuddy and open a manga
2. Open any chapter
3. The image is not loaded and reload sign is running continuously
4. After waiting for long time it says reload image
5.this goes on and on

### Expected behavior

Image should have been loaded 

### Actual behavior

Always asks. To reload image and does not open

### Tachiyomi version

0.14.3

### Android version

Android 12

### Other details

Even clicking on reload repeats the same cycle.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment] 2023-01-17 02:41
Duplicate of #14967

**Closed** 2023-01-17 02:50 UTC
Labels: Bug
