### ISSUE TITLE
Extension roumanwu error failed to load manga

### ISSUE THREAD

**Issue by kvnwong97** [tachiyomiorg/tachiyomi-extensions#17200] opened 2023-07-20 23:25 UTC
### Source information

Roumanwu 1.4.4

### Source language

Chinese

### Steps to reproduce

1. Can't load manga, chapter.

### Expected behavior

After selected the sources roumanwu, should come out the manga titles, cover.

### Actual behavior

After selected the sources roumanwu, should come out the manga titles.
BUT...
Show below error code after selected the sources.
![Screenshot_2023-07-21-07-15-52-00_afd66b7916d19a60815f56273408b73e](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/75885697/23ec7ab6-969e-43f3-b7ba-32fb7d7a7358)

### Tachiyomi version

0.14.6

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment] 2023-07-21 02:07
Duplicate of #17168

**Closed by stevenyomi** 2023-07-21 02:07 UTC
Labels: Bug
