### ISSUE TITLE
,مانجا ليك

### ISSUE THREAD

**Issue by TachiApp** [tachiyomiorg/tachiyomi-extensions#12062] opened 2022-06-04 00:18 UTC
### Source information

mangalek 1.2.21

### Steps to reproduce

Select manhua or any think to read
enter a chpater

### Expected behavior

The source not working "failed to bypass couldflare"
when read any chapter

### Actual behavior

Couldflare error

### Tachiyomi version

0.13.4

### Android version

Android 11

### Other details

![IMG_20220604_011629](https://user-images.githubusercontent.com/106177484/171968831-d07e45e6-f3b9-4265-9c92-0e6201977226.jpg)
That what's has happened .

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment] 2022-06-04 00:20
Duplicate of #11366

**Closed by loocool2** 2022-06-04 00:20 UTC
Labels: Bug
