### ISSUE TITLE
Mangaplex "no results found"

### ISSUE THREAD

**Issue by zeeberr** [tachiyomiorg/tachiyomi-extensions#16554] opened 2023-05-22 06:16 UTC
### Source information

MangaPlex 1.4.1

### Source language

English

### Steps to reproduce

1. Open Tachiyomi
2. Open Mangaplex extension

### Expected behavior

Showing lists of manhua/hwa

### Actual behavior

No results found

### Tachiyomi version

0.14.6

### Android version

Android 10

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by gohmTerm** [comment] 2023-08-10 06:23
I'm also having the same problem, the web view still seems to work though. Hope it gets fixed

**Comment by vetleledaal** [comment] 2023-09-14 07:26
Duplicate of #14308

**Closed by vetleledaal** 2023-09-14 07:26 UTC
Labels: Bug
