### ISSUE TITLE
MangaSwat: (no chapters found)

### ISSUE THREAD

**Issue by Tian-77** [tachiyomiorg/tachiyomi-extensions#17841] opened 2023-09-08 15:28 UTC
### Source information

ar.mangaswat 1.4.38

### Source language

"Arabic"

### Steps to reproduce

1. Try to open the source
2. Try to open any manhwa
3. "No chapters found" will appear
4. If any chapters are be found, it Will not be opened.

### Expected behavior

The chapters should show up and work

### Actual behavior

"no chapters found" shows up and the chapters are not opening.

### Tachiyomi version

1.9.3

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2023-09-09 03:19
Duplicate of #17748

**Closed by vetleledaal** 2023-09-09 03:19 UTC
Labels: Bug
