### ISSUE TITLE
[Bug] <manga1000, manga1001>: <cover image not showing, updates notifications not showing>

### ISSUE THREAD

**Issue by Anifan2021** [tachiyomiorg/tachiyomi-extensions#6018] opened 2021-03-01 12:17 UTC
## Device information
- Tachiyomi version: 10.9 
- Android version: 10

## Source information
- Name: MangaRaw
- Extension version: Manga Raw 1.2.1

## Steps to reproduce
1. New chapters show up on phone notification 
2. Open app to Updates
3. New chapter does not appear
4. Go to Manga1000 or Manga1001, new chapter is there but cover image is blank

### Expected behavior
New chapters should show up in Updates
Cover images should refresh

### Actual behavior
Describe what happens instead
See steps abovementioned

**Comment by scb261** [comment] 2021-03-01 12:28
Covers - duplicate of #5928
Updates - the app shows chapters in the Updates section only when they have dates, but the site doesn't have it

**Closed by scb261** 2021-03-01 12:28 UTC
Labels: bug
