### ISSUE TITLE
BlogTruyen source can't update new chapter

### ISSUE THREAD

**Issue by Kenatia** [tachiyomiorg/tachiyomi-extensions#13842] opened 2022-10-13 10:11 UTC
### Source information and language

BlogTruyen 1.2.9 (Vietnamese)

### Steps to reproduce

1. Check for updated all mangas from this source in the same time.

### Expected behavior

Should check for updates successfully 

### Actual behavior

HTTP error 429 (Too many requests)

### Tachiyomi version

r5018

### Android version

Android 11

### Other details

This source use cloudflare and block requests for a short period of time

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [ ] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment] 2022-10-14 01:53
duplicate of #13803

**Closed by Riztard** 2022-10-14 01:53 UTC
Labels: Bug
