### ISSUE TITLE
Manhwas.net error: content must not be null 

### ISSUE THREAD

**Issue by YagamiRyu** [tachiyomiorg/tachiyomi-extensions#14442] opened 2022-12-02 23:21 UTC
### Source information and language

"Manhwas.net 1.3.3 (Español)" 

### Steps to reproduce

1. No funciona la extension no muestra el contenido.

### Expected behavior

Deberia mostrar las portadas y mangas de la pagina.

### Actual behavior

Error; content must not be null

### Tachiyomi version

0.14.2

### Android version

Android 12

### Other details

![Screenshot_20221202-171723_Tachiyomi](https://user-images.githubusercontent.com/98830731/205405490-758d8c03-e0da-4b76-8ec2-40f8c22412ab.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2022-12-03 00:39
Duplicate of #13008

**Closed by vetleledaal** 2022-12-03 00:39 UTC
Labels: Bug
