### ISSUE TITLE
Mizu Mangás.

### ISSUE THREAD

**Issue by gatinhecomunista** [tachiyomiorg/tachiyomi-extensions#16292] opened 2023-05-03 23:23 UTC
### Source information

Mizu Mangás - Português

### Source language

Português

### Steps to reproduce

Está dando erro HTTP error 404. O site na web está funcionando, mas no app não está funcionando.

### Expected behavior

Deveria aparecer as obras.

### Actual behavior

Não está aparecendo as obras.

### Tachiyomi version

0.14.6

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2023-05-03 23:23
Duplicate of #16286

**Closed by alessandrojean** 2023-05-03 23:23 UTC
Labels: Bug
