### ISSUE TITLE
Manhuaren false with no value for response 

### ISSUE THREAD

**Issue by stevenkuek** [tachiyomiorg/tachiyomi-extensions#17030] opened 2023-07-05 13:46 UTC
### Source information

Manhuaren 1.4.9

### Source language

Chinese 

### Steps to reproduce

No able to refresh and update the manga
Showing no value for response 
Cannot reading 
Basically can't do anything 

### Expected behavior

Able refresh and update Manga 

### Actual behavior

currently not working 

### Tachiyomi version

0.14.6

### Android version

MIUI 14 base on Android 12

### Other details

{
  "errorResponse": {
    "code": 40005,
    "subCode": "",
    "message": "签名错误"
  }
}

簽名錯誤 mean wrong signature 
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment] 2023-07-05 14:07
Duplicate of #17008

**Closed by stevenyomi** 2023-07-05 14:07 UTC
Labels: Bug
