### ISSUE TITLE
DoujinDesu (id) No pages found

### ISSUE THREAD

**Issue by niveanyctra** [tachiyomiorg/tachiyomi-extensions#14514] opened 2022-12-11 02:10 UTC
### Source information and language

DoujinDesu 1.3.3 (Indonesia)

### Steps to reproduce

1.Open DoujinDesu
2.Cover image not showing
![Screenshot_2022-12-11-08-53-26-972_eu kanade tachiyomi](https://user-images.githubusercontent.com/113758640/206882951-3cafea88-f163-44b5-bcc7-6a0afa794d1b.jpg)
3.Open manga
![Screenshot_2022-12-11-08-54-11-977_eu kanade tachiyomi](https://user-images.githubusercontent.com/113758640/206882982-f2f37ce4-1786-47d0-ad12-4c601391d721.jpg)
4.Open chapters
![Screenshot_2022-12-11-09-00-19-131_eu kanade tachiyomi](https://user-images.githubusercontent.com/113758640/206883012-a5928b89-1d65-41ba-968f-4fb0dc49a40e.jpg)

### Expected behavior

Cover image that appears, and read manga normally

### Actual behavior

manga covers that don't appear and can't open chapters in all manga with pop ups that appear "No pages found"

### Tachiyomi version

0.14.2

### Android version

Android 12

### Other details

But when I open the website with web view, the website looks normal and can be accessed

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment] 2022-12-11 07:41
Duplicate of #14004

**Comment by niveanyctra** [comment] 2022-12-11 07:57
> Duplicate of
> #14004 for chapter images doesn't load 
> #11662 for cover doesn't load

makasih bro, semoga cepet pulih lagi sih

**Closed** 2022-12-11 13:53 UTC
Labels: Bug
