### ISSUE TITLE
[Bug] <SekaiKomik>: <HTTP Error 403>

### ISSUE THREAD

**Issue by ellodandra** [tachiyomiorg/tachiyomi-extensions#7457] opened 2021-06-04 16:05 UTC
## Device information
- Tachiyomi version: 0.10.12
- Android version: 7.1.1

## Source information
- Name: Sekai Komik
- Extension version: 1.2.12

## Steps to reproduce
1. HTTP Error 403

### Expected behavior
Error 403 and Error 1020 in webview

### Actual behavior
After updated to the latest version i can't open this extension because HTTP Error 403. I try troubleshooting buy I Can't work and i check the webview but it cant even though in website Sekai Komik its normal.

## Other details
![Screenshot_2021-06-04-23-00-00-56](https://user-images.githubusercontent.com/81138524/120831003-4c866680-c589-11eb-8ea8-c2f5835255d2.png)

**Comment by h-hyuuga** [comment] 2021-06-06 07:19
Duplicate of #7492

**Comment by arkon** [comment] 2021-10-02 16:25
Presumably superseded by #8220

**Closed by arkon** 2021-10-02 16:25 UTC
Labels: Bug
