### ISSUE TITLE
[Bug] sakte doujin: i cant open the manga

### ISSUE THREAD

**Issue by uwuux** [tachiyomiorg/tachiyomi-extensions#6708] opened 2021-04-26 02:52 UTC
When i open the manga i get instantly out, and its say nothing, no error sign.

**Comment by curche** [comment] 2021-04-26 11:26
duplicate of #6710 

do make sure to fill the template while making an issue next time (and not completely remove it)

**Closed** 2021-04-26 12:17 UTC
Labels: bug
