### ISSUE TITLE
happymh can't bypass cloudflare

### ISSUE THREAD

**Issue by mojunisme** [tachiyomiorg/tachiyomi-extensions#13016] opened 2022-08-16 07:20 UTC
### Source information and language

happymh 1.2.2

### Steps to reproduce

showing can't bypass cloudflare when open or download a chapter 

### Expected behavior

open or download normally

### Actual behavior

showing can't bypass cloudflare when open or download a chapter 

### Tachiyomi version

0.13.6

### Android version

android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment] 2022-08-16 11:13
Duplicate of #13011

**Closed** 2022-08-16 12:06 UTC
Labels: Bug

**Comment by junyaotan020517** [comment] 2022-08-17 05:51
> Duplicate of #13011

the problem occur today

**Comment by TheKingTermux** [comment] 2022-08-17 05:57
> the problem occur today

Go to webview > Resolve the chapta

**Comment by junyaotan020517** [comment] 2022-08-17 06:00
> > the problem occur today
> 
> Go to webview > Resolve the chapta

i resolve the chapta on my browser and on tachi webview but still the same i think is the default user agent string problem. i change it to Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Mobile Safari/537.36
and now it can be used

**Comment by lrmalaysia** [comment] 2022-08-18 16:31
> > > the problem occur today
> > 
> > 
> > Go to webview > Resolve the chapta
> 
> i resolve the chapta on my browser and on tachi webview but still the same i think is the default user agent string problem. i change it to Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Mobile Safari/537.36 and now it can be used

can you guide how to change? Settings> Advanced > DND over HTTPS?

**Comment by mojunisme** [comment] 2022-08-18 23:28
you need to update to 0.13.6

**Comment by mojunisme** [comment] 2022-08-18 23:30
> > > > the problem occur today
> > > 
> > > 
> > > Go to webview > Resolve the chapta
> > 
> > 
> > i resolve the chapta on my browser and on tachi webview but still the same i think is the default user agent string problem. i change it to Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Mobile Safari/537.36 and now it can be used
> 
> can you guide how to change? Settings> Advanced > DND over HTTPS?

you need to update to 0.13.6 first
