### ISSUE TITLE
Asura scans

### ISSUE THREAD

**Issue by blank27** [tachiyomiorg/tachiyomi-extensions#16336] opened 2023-05-06 13:08 UTC
### Source information

Asura scans 1.4.45

### Source language

English 

### Steps to reproduce

Some of the page not found 404

### Expected behavior

Some of the page not found 404

### Actual behavior

Some of the page not found 404

### Tachiyomi version

1.4.45

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-05-06 14:05
Duplicate of #16251

**Closed by arkon** 2023-05-06 14:05 UTC
Labels: Bug
