### ISSUE TITLE
Download issue

### ISSUE THREAD

**Issue by GladRedFox719** [tachiyomiorg/tachiyomi-extensions#18998] opened 2023-11-16 10:44 UTC
### Source information

ManhwaTop

### Source language

English

### Steps to reproduce

I'm just downloading my favorite manhwa and I got this.

### Expected behavior

![Screenshot_20231116_123358_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/96375823/55b8a207-8c57-4d48-8707-a4e9c532503b)
![Screenshot_20231116_123451_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/96375823/d908a67a-d294-4556-96ca-d8a427fbbf39)

### Actual behavior

![Screenshot_20231116_123418_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/96375823/011edbc1-f9d4-4509-92d3-a59ebef0f68d)

### Tachiyomi version

0.14.7

### Android version

Android 13

### Other details

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi-extensions/files/13376500/tachiyomi_crash_logs.txt)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2023-12-11 15:24
Duplicate of #15595

**Closed by vetleledaal** 2023-12-11 15:24 UTC
Labels: Bug
