### ISSUE TITLE
[Bug] <MangaRaw>: <cannot download earlier chapter>

### ISSUE THREAD

**Issue by isorahm** [tachiyomiorg/tachiyomi-extensions#5964] opened 2021-02-23 01:54 UTC
---

## Device information
- Tachiyomi version: v0.10.9
- Android version: 10

## Source information
- Name: MangaRaw
- Extension version: 1.2.1

## Steps to reproduce
1. Open a Manga page.
2. Select a little bit earlier chapter for downloading (not the newest)
3. No further more , and stuck at the progress with 0/n..

### Expected behavior
All the chapter may allowed to be downloaded.

### Actual behavior
The progress stucked at 0/n

**Comment by scb261** [comment] 2021-02-23 01:57
Duplicate of #5941

**Closed by scb261** 2021-02-23 01:57 UTC
Labels: bug
