### ISSUE TITLE
happymh(嗨皮漫画) image loading issue 

### ISSUE THREAD

**Issue by HYChin** [tachiyomiorg/tachiyomi-extensions#19468] opened 2023-12-29 04:40 UTC
### Source information

Happymh 1.4.5

### Source language

Chinese

### Steps to reproduce

Open up comic from said source, won't load. Pop out some error like HTTP 403

### Expected behavior

Image should be load normally 

### Actual behavior

Unable to load images from source properly in app

### Tachiyomi version

0.14.7

### Android version

Android 14 

### Other details

![Screenshot_2023-12-29-12-14-09-441_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/125426885/92064eed-1fc4-459c-b022-1a0ede8dd0ca)
![Screenshot_2023-12-29-12-13-59-321_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/125426885/b9c40b04-e412-4792-ae03-06b47634849c)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment] 2023-12-29 05:36
You opened duplicate from your last Issue #19466 and duplicate of #19457

**Comment by arkon** [comment] 2023-12-29 15:16
Duplicate of #19457

**Closed by arkon** 2023-12-29 15:16 UTC
Labels: Bug, Duplicate
