### ISSUE TITLE
Too many follow-up requests: 21

### ISSUE THREAD

**Issue by Sharkgsn** [tachiyomiorg/tachiyomi-extensions#11996] opened 2022-05-27 16:31 UTC
### Source information

Neox Scanlator 1.2.33

### Steps to reproduce

1. Vou em fontes
2. Clico em recentes
3. Aparece o erro "Too many follow-up requests: 21"

### Expected behavior

Deveria abrir com os lançamentos recentes.

### Actual behavior

Só aparece o erro "Too many follow-up requests: 21"

### Tachiyomi version

O.13.4

### Android version

Android 9

### Other details

Não atualiza os capítulos já salvos na biblioteca.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-05-27 16:33
>  I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open issue.

Please actually read what you acknowledge instead of just checking all the boxes.

Duplicate of #11953.

**Closed by alessandrojean** 2022-05-27 16:33 UTC
Labels: Bug
