### ISSUE TITLE
nHentai, Remember last used filter. 

### ISSUE THREAD

**Issue by MatteCrystal** [tachiyomiorg/tachiyomi-extensions#5546] opened 2021-01-24 21:37 UTC
As of now nHentai by default opens with all manga sorted by most popular of all time no matter what. This kind of sucks since most popular of all time doesn't change that often so most users are just seeing the same old stuff everyday. Every time I use the app I have to click filter, sort by most recent, and add some of my favorite tags.

Instead these filters should remember your last used filter or better yet give you one of the 2 following options. 

1: Allow the users last used filter to be the default filter each time they use the app
2. Allow the user to setup there own default filter that is applied each time they open the app.

**Comment by arkon** [comment] 2021-01-24 21:38
Duplicate of https://github.com/tachiyomiorg/tachiyomi/issues/1484

**Closed by arkon** 2021-01-24 21:38 UTC
Labels: enhancement
