### ISSUE TITLE
Phoenix Fansub

### ISSUE THREAD

**Issue by KasukeLp23** [tachiyomiorg/tachiyomi-extensions#8929] opened 2021-09-01 17:36 UTC
### Source information

Phoenix Fansub 1.2.11 - Spanish

### Steps to reproduce

**1.** Open extension
**2.** Open any manga
**3.** Below message appears "No address associated with hostname" 

### Expected behavior

Chapters appear normally

### Actual behavior

No chapters appear and displays the above message

### Tachiyomi version

J2K v1.2.1

### Android version

Android 7

### Other details

In Webview the URL is not the one indicated apparently missing "**/manga**/". 

For example:
When entering the manga webview the url indicates: **https://phoenixfansub.comwizard-of-arsenia/** , while on the web the correct one is **https://phoenixfansub.com/manga/wizard-of-arsenia/**

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Clouddark75** [comment] 2021-09-01 19:34
Duplicate of #8866.

**Comment by Clouddark75** [comment] 2021-09-02 15:35
@curche, can you close this and #8863? Thanks and sorry for the tag!

**Comment by curche** [comment] 2021-09-02 15:39
#8866 was closed. Is the extension working now? if not, we'll keep this open

**Comment by Crallpro** [comment] 2021-09-04 12:41
Please fix it is one of the best extensions

**Closed** 2021-09-06 10:19 UTC
Labels: Bug
