### ISSUE TITLE
[Source Request] <Mangadig>

### ISSUE THREAD

**Issue by davidtuning** [tachiyomiorg/tachiyomi-extensions#5113] opened 2020-12-12 23:45 UTC
It will be nice if this one can be add. 
## Source Website
- Name: Mangadig 
- Link: https://mangadig.com/
- Language(s): en

Thanks and happy holidays!

**Comment by HaruSasaki** [comment] 2020-12-17 11:25
If look at the interface, i thought this website is using the same theme as CoCoManhua.

**Comment by davidtuning** [comment] 2020-12-23 02:45
> If look at the interface, i thought this website is using the same theme as CoCoManhua.

So there's no hope for adding it to any addon?

**Comment by JustMe2277** [comment] 2021-06-21 17:08
Hope these people will kind enough to see & recheck this again,  if it can be make as an  extension.

Thank you.

**Comment by hyoretsu** [comment] 2021-08-12 14:30
Re-bumping this, some aggregator stole chapters from here and it seems I've finally found the only site that has all chapters of Boy in A Girl's High School. (If it really can't be added, just close the issue)

**Comment by alessandrojean** [comment] 2021-08-12 14:36
Don't keep bumping issues. This is an open source project, it will get added when someone have time and wants to work on it, no ETA.

**Comment by hyoretsu** [comment] 2021-08-12 14:55
It's just a matter of words. I was about to open a new issue to request this source, which'd then be closed in favor of this one, essentially bumping it. Nor was I hurrying for an ETA or something, but it was never disclosed if it's actually possible/"planned" or not, seeing how it's been open for 8 months.

**Comment by alessandrojean** [comment] 2021-08-12 15:03
> but it was never disclosed if it's actually possible/"planned" or not

Clarifying this part, if the issue is still opened it means it's possible to add it as a source, but no one did it yet.

**Closed** 2021-11-06 13:15 UTC
Labels: Source request
