### ISSUE TITLE
Hiperdex No chapters found

### ISSUE THREAD

**Issue by kingmj2000** [tachiyomiorg/tachiyomi-extensions#9147] opened 2021-09-20 08:26 UTC
### Source information

Hiperdex 1.2.15

### Steps to reproduce

1. Open any hiperdex manga (from source or library)
2.  Refresh (if in library) or just open (if in source)
3. Issue here:- No chapters found (even though previous chapters are available in library and downloadable. Manga covers are also available in both source & library)
Note:- All the chapters & mangas are visible in webview.

### Expected behavior

All chapters are loaded (if in source)
New Chapters are loaded & updated (if from library)

### Actual behavior

No chapters loaded (in source)
Chapters aren't updated (in library)

### Tachiyomi version

TachiyomiSY 1.7.0

### Android version

Android 11

### Other details

![Screenshot_2021-09-20-13-59-13-775_eu kanade tachiyomi sy](https://user-images.githubusercontent.com/91054160/133974817-2555597a-1068-45af-ae4d-d431f0bac32e.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment] 2021-09-20 08:55
Duplicate of #9142

**Closed** 2021-09-20 08:55 UTC
Labels: Bug
