### ISSUE TITLE
add new extension name mangareader.to

### ISSUE THREAD

**Issue by Bikeam-tech** [tachiyomiorg/tachiyomi-extensions#10183] opened 2021-12-21 12:55 UTC
### Source name

mangareader

### Source link

https://mangareader.to/home

### Language

english

### Other details

this is a new site from popular anime streaming site (zoro.to). this site name is mangareader.to. this site provides an ads-free reading experience, fast content update with vast genres and is safe to use.
![Screenshot (600)](https://user-images.githubusercontent.com/55379619/146933427-69e398df-737c-4820-976f-80feea5dd102.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2021-12-21 12:56
> I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open issue.

Duplicate of #9112

**Closed by alessandrojean** 2021-12-21 12:56 UTC
Labels: Source request
