### ISSUE TITLE
Mangadex completed oneshot filtering

### ISSUE THREAD

**Issue by NorseFenris** [tachiyomiorg/tachiyomi-extensions#14845] opened 2023-01-08 04:49 UTC
### Source information and language

Mangadex v1.3.176

### Steps to reproduce

1. Add a series which only consists of a oneshot. (Example of a title this happens on: [Boku no kotori-san](https://mangadex.org/title/b65df494-fef8-41a9-8e47-f679bc6a6e5f/boku-no-kotori-san))
2. Mark oneshot as read.
3. Try filtering the series in the library to only show "completed" series.

### Expected behavior

The manga should now be visible when viewing all the completed titles in the library.

### Actual behavior

It is labeled as ongoing/publication finished and does not show in the filtering.

### Tachiyomi version

0.14.3

### Android version

Android 13

### Other details

This probably happens cause the extension reads the "last chapter" text on a title page and checks the chapter list for that chapter. On a oneshot title the last chapter text will be "chapter 1", while the actual chapter list will name the only existing chapter as "oneshot". Hence the extension doesn't find the "chapter 1" in the list and labels it "publication finished" instead of "completed".

A check for the format tag "oneshot" could be made and just check if a chapter in the right language exists in the list. No matter what it's called it will 99% be the oneshot chapter in the list.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2023-01-10 20:05
The extension already marks as complete if the title has a "Oneshot" tag and not an "Anthology" tag on Mangadex. So that entry needs to be marked as Oneshot in the Dex site, I can mark it for you.

https://github.com/tachiyomiorg/tachiyomi-extensions/blob/a00ed03e639c36c930c6f3ccf643d4fddc80e0ff/src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/MangaDexHelper.kt#L163-L164

Closing it since the extension is working as expected.

**Comment by alessandrojean** [comment] 2023-01-10 20:11
Actually it's not marking it since the `aggregate` endpoint is marking it as "Volume 0" instead of "No volume" (which the extension uses for now). Will reopen so the extension handles this case as well.

https://api.mangadex.org/manga/b65df494-fef8-41a9-8e47-f679bc6a6e5f/aggregate?translatedLanguage[]=en

**Comment by alessandrojean** [comment] 2023-01-10 20:15
![image](https://user-images.githubusercontent.com/14254807/211652623-df8db85b-8cc8-4dcc-a232-710a95a1084c.png)

Confirmed with some people, this is bad data on Dex side. These chapters need to be under the "No volume" section as well, but they're incorrectly under the "Volume 0" section. The extension shouldn't handle this case as it's bad data. You can easily fix this by reporting it to the MangaDex team.

**Closed by alessandrojean** 2023-01-10 20:15 UTC
Labels: Bug

**Comment by NorseFenris** [comment] 2023-01-10 20:17
Ok, I know what to do now, thanks.
