### ISSUE TITLE
AllPornComic captcha keeps reloading

### ISSUE THREAD

**Issue by ArchCelestial** [tachiyomiorg/tachiyomi-extensions#12607] opened 2022-07-17 09:17 UTC
### Source information

AllPornComic  English 1.3.21

### Steps to reproduce

When you go to AllPornComic webview to do the captcha, the captcha continuously reloads and if you go to the website in a normal browser, the website loads without any problem.

### Expected behavior

I should be able to complete the captcha in webview and be able to open it in Tachiyomi.

### Actual behavior

The captcha in webview continuously reloads and doesn't ever let me into the website.

### Tachiyomi version

0.13.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2022-07-17 12:37
Duplicate of #9318

**Closed by vetleledaal** 2022-07-17 12:38 UTC
Labels: Bug
