### ISSUE TITLE
CopyManga extension keeps showing "Missing Argument"

### ISSUE THREAD

**Issue by GodSavior** [tachiyomiorg/tachiyomi-extensions#9130] opened 2021-09-19 05:47 UTC
### Source information

CopyManga 1.2.15

### Steps to reproduce

Whenever i try to open a manga, it will show the error message of "Missing Argument"

### Expected behavior

The chapter list should be shown when i open a manga.

### Actual behavior

The chapter list doesnt load but the error of "Missing Argument" comes out instead.

### Tachiyomi version

0.12.2

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment] 2021-09-19 06:20
>    I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open issue.

Duplicate of #9114

**Closed by curche** 2021-09-19 06:20 UTC
Labels: Bug

**Comment by GodSavior** [comment] 2021-09-19 06:33
It was solved yesterday in the new update...but it happens again in a few hours after the new extension update was pushed...So i think it is not duplicated...
