### ISSUE TITLE
Extension not working - unable to load on applying filters or on text search. Several library entries not updating

### ISSUE THREAD

**Issue by MayankKr10** [tachiyomiorg/tachiyomi-extensions#13066] opened 2022-08-18 14:47 UTC
### Source information and language

Toonily 1.3.31

### Steps to reproduce

Issue 1:
1. Got to browse
2. Perform text search

Issue 2:
1. Go to browse and select Toonily extension
3. Apply any filter and/or perform text search in this extension

### Expected behavior

Issue 1:
Expected: Manga/comics should load based on search

Issue 2:
Expected: List of comics/manga should be displayed

### Actual behavior

Issue 1:
Observation: For this extension - No results found - encountered for any search

Issue 2:
Observation: No results found - for any filter/search and retry also doesn't work

### Tachiyomi version

0.13.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2022-08-18 14:51
Duplicate of #12968

**Closed by Seishirou101** 2022-08-18 14:51 UTC
Labels: Bug
