### ISSUE TITLE
Japscan stuck download

### ISSUE THREAD

**Issue by oktapodia** [tachiyomiorg/tachiyomi-extensions#12701] opened 2022-07-23 03:17 UTC
### Source information and language

Japscan 1.3.30

### Steps to reproduce

Try to download any chapter from japscan source, the problem is still there.

Follow #12491 

### Expected behavior

Can download new chapters

### Actual behavior

Stuck on download

### Tachiyomi version

R4631

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-07-23 03:35
Duplicate of #12672

**Closed by alessandrojean** 2022-07-23 03:35 UTC
Labels: Bug
