### ISSUE TITLE
Hitomi.la ReferenceError: identifier 'gg' undefined

### ISSUE THREAD

**Issue by ChillyCrimson45** [tachiyomiorg/tachiyomi-extensions#11561] opened 2022-04-22 05:03 UTC
### Source information

Hitomi.la 1.2.16

### Steps to reproduce

Any Kind Of Access To The Website's Posts
1. Open Hitomi.la
2. Pick Any Doujins
3. The Error And Cannot Be Downloaded Or Read

### Expected behavior

It Should Open/Download

### Actual behavior

It Didn't Open/Download And It Showed The Error Message

### Tachiyomi version

0.13.3

### Android version

Android 7.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-04-22 11:58
Duplicate of #10319

**Closed by arkon** 2022-04-22 11:58 UTC
Labels: Bug
