### ISSUE TITLE
403 error opening hitomila

### ISSUE THREAD

**Issue by haotianliang** [tachiyomiorg/tachiyomi-extensions#10465] opened 2022-01-15 05:22 UTC
### Source information

tachiyomi-arm64-v8a-v0.12.3.apk

### Steps to reproduce

404 error opening hitomila

### Expected behavior

Page appears

### Actual behavior

404 error opening hitomila

### Tachiyomi version

0.12.3

### Android version

Android11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-01-15 13:50
Duplicate of #10466

**Closed by arkon** 2022-01-15 13:50 UTC
Labels: Bug
