### ISSUE TITLE
Cant search or preview the mangas in MangaHub

### ISSUE THREAD

**Issue by iamdboss** [tachiyomiorg/tachiyomi-extensions#12926] opened 2022-08-10 08:08 UTC
### Source information and language

MangaHub 

### Steps to reproduce

I open the extension to search a manga. But it says http error 403

### Expected behavior

Can search the manga and preview

### Actual behavior

![Screenshot_2022-08-10-16-01-46-526_eu kanade tachiyomi](https://user-images.githubusercontent.com/75558174/183849386-b4ee3c6a-a3c8-492b-82d9-874ff4f527a0.jpg)

### Tachiyomi version

0.13.5

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Firecto** [comment] 2022-08-10 10:11
I am having the same issue.
Favorited manga from mangahub is still readable

**Comment by arkon** [comment] 2022-08-10 12:22
Duplicate of #12929

**Closed by arkon** 2022-08-10 12:22 UTC
Labels: Bug
