### ISSUE TITLE
Manhwa18.net extension not working

### ISSUE THREAD

**Issue by perfectblu** [tachiyomiorg/tachiyomi-extensions#14063] opened 2022-10-31 15:35 UTC
### Source information and language

Manhwa18.net is broken

### Steps to reproduce

Open source

### Expected behavior

Manhwas that are on the web should be loaded/visible

### Actual behavior

App shows "No results found". In webview version everything OK.

### Tachiyomi version

0.14.1

### Android version

11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-10-31 21:13
Duplicate of #11466

**Closed by alessandrojean** 2022-10-31 21:13 UTC
Labels: Bug
