### ISSUE TITLE
Olympus Scanlation (new URL)

### ISSUE THREAD

**Issue by JhulShock** [tachiyomiorg/tachiyomi-extensions#15551] opened 2023-03-02 04:55 UTC
### Source information and language

Olympus Scanlation 1.4.28 (Spanish)

### Source new URL

https://olympusscans.com/

### Other details

Old URL : https://olympusscanlation.com/
New URL: https://olympusscans.com/ 

![image](https://user-images.githubusercontent.com/21696690/222334408-e38013cb-db33-4c50-9da0-6014a4987b17.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment] 2023-03-02 05:01
Duplicate of #15330

**Closed by curche** 2023-03-02 05:01 UTC
Labels: Bug, Domain changed
