### ISSUE TITLE
1stkiss Error 429

### ISSUE THREAD

**Issue by fuentez145** [tachiyomiorg/tachiyomi-extensions#11289] opened 2022-04-01 00:39 UTC
### Source information

1st kiss 1.2.23

### Steps to reproduce

1. Clicking the all updates or refresh
2. ALL 1St kiss manga auto error 429

### Expected behavior

All manga is 1st kiss should be updated.

### Actual behavior

But instead it always shows error since yesterday.

### Tachiyomi version

Stable 0.13.1

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-04-01 00:41
> I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open issue.

Duplicate of #11280

**Closed by alessandrojean** 2022-04-01 00:41 UTC
Labels: Bug
