### ISSUE TITLE
Asura Scans changed the url of some of their entries

### ISSUE THREAD

**Issue by Fares-Metwaly** [tachiyomiorg/tachiyomi-extensions#16357] opened 2023-05-07 15:32 UTC
### Source information

Asura Scans 1.4.45

### Source language

English

### Steps to reproduce

1. Go to any entry from the list below 
"- Doctor’s Rebirth
    - Dungeon Odyssey
    - Ending Maker
    - Genius of the Unique Lineage
    - Heavenly Grand Archive’s Young Master
    - Heavenly Sword’s Grand Saga
    - Helmut: The Forsaken Child
    - I Grow Stronger By Eating!
    - My Daughter is the Final Boss
    - My School Life Pretending To Be a Worthless Person
    - Omniscient Reader’s Viewpoint
    - Player Who Can’t Level Up
    - Reaper of the Drifting Moon
    - Regressor Instruction Manual
    - Reincarnation of the Suicidal Battle God
    - Return Of The Shattered Constellation
    - Superhuman Battlefield
    - The Heavenly Demon Can’t Live a Normal Life
    - The Novel’s Extra (Remake)
    - The Return of the Crazy Demon
    - The World After The End
    - Villain To Kill
    - Worthless Regression
    - Youngest Scion of the Mages"
    2. Open a chapter or try to update the entry
    3. Open webview

### Expected behavior

Upon number 2 it should update the entry or open the chapter
Upon number 3 it should open the site with the chapters

### Actual behavior

Upon number 2 it fails and does an "Error 404"
Upon number 3 it goes to a fail page with "Error 404"

### Tachiyomi version

0.14.6 

### Android version

8.1.0 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by mobi2002** [comment] 2023-05-07 15:41
duplicate of #16251

**Closed** 2023-05-07 16:38 UTC
Labels: Bug
