### ISSUE TITLE
LynxScans : Not Loading

### ISSUE THREAD

**Issue by I-Am-C0der** [tachiyomiorg/tachiyomi-extensions#15936] opened 2023-04-02 09:39 UTC
### Source information

LynxScans 1.4.6

### Source language

English

### Steps to reproduce

1.Install LynxScans 1.4.6
2.Select LynxScans in Browse->Source

### Expected behavior

This should show list of Manhwa/Manga available in the site

### Actual behavior

**But it is showing "No results found"**

**Note:** The webview is working without any issues.

![Lynx Scan Error](https://user-images.githubusercontent.com/51527183/229344868-90e2a8fd-f5bd-43b7-9c5b-dd56f3d34c9e.jpg)

### Tachiyomi version

0.14.5

### Android version

Android 11

### Other details

The webview is working without any issues.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2023-04-02 09:44
Duplicate of #15507

**Closed by Seishirou101** 2023-04-02 09:44 UTC
Labels: Bug
