### ISSUE TITLE
Manhwa18 404 error 

### ISSUE THREAD

**Issue by fawadkhan121** [tachiyomiorg/tachiyomi-extensions#10130] opened 2021-12-16 22:29 UTC
### Source information

Manhwa 18 1.2.6

### Steps to reproduce

Open app select manhwa 18 source and manhw should appear 

### Expected behavior

Manhwa and chapters should apper on app 

### Actual behavior

Web view is working fine but app is giving 404 error because manhwa 18 changed their site layout 

### Tachiyomi version

0.12.3

### Android version

11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2021-12-16 22:31
Duplicate of #9935

**Closed by arkon** 2021-12-16 22:31 UTC
Labels: Bug
