### ISSUE TITLE
Copymanga: Website changed

### ISSUE THREAD

**Issue by 362516282** [tachiyomiorg/tachiyomi-extensions#10703] opened 2022-02-05 05:29 UTC
### Source information

tachiyomi-zh.copymanga-v1.2.22.apk

### Steps to reproduce

Open the Extension Page or open it in the Webview
wait for it to load
jump to www.copymanga.org and show error 404
if open www.copymanga.org, you can see the page just like before

### Expected behavior

Main page or the selected manga should have been showing up after opening

### Actual behavior

![Screenshot 2022-02-05 132331](https://user-images.githubusercontent.com/36665073/152629902-800d0c60-ea54-42ae-b830-e3c54ff7e929.png)
![Screenshot_20220205_132154_eu kanade tachiyomi de](https://user-images.githubusercontent.com/36665073/152629903-e78a8b48-05c5-452f-af9b-295c92f45cf3.jpg)

then open www.copymanga.org
![Uploading Screenshot 2022-02-05 132657.png…]()

### Tachiyomi version

Preview r4136

### Android version

Android 11

### Other details

The original website is attacked, so they change the website to www.copymanga.org

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2022-02-05 05:33
Duplicate of #10658

**Closed by Seishirou101** 2022-02-05 05:33 UTC
Labels: Bug
