### ISSUE TITLE
[Bug] <japscan>: <not possible to read or download>

### ISSUE THREAD

**Issue by Diego10pedro** [tachiyomiorg/tachiyomi-extensions#7072] opened 2021-05-17 21:10 UTC
## Device information
- Tachiyomi version: 0.10.12 
- Android version: 10 

## Source information
- Name: japscan
- Extension version: 1.2.26

## Steps to reproduce
1. Search a manga 
2. Try to read or download 

### Expected behavior
Search, read, download a chapter or manga

### Actual behavior
NOT possible to read, download or search à chapter or manga with this source

**Comment by h-hyuuga** [comment] 2021-05-17 21:12
Duplicate of #7017 ?

**Closed** 2021-05-17 21:16 UTC
Labels: bug

**Comment by Diego10pedro** [comment] 2021-05-17 21:17
> Duplicate of #7017 ?

Arf, sorry, I didn't see it.
