### ISSUE TITLE
Yugenmangas error 400

### ISSUE THREAD

**Issue by CSamael** [tachiyomiorg/tachiyomi-extensions#19333] opened 2023-12-16 18:48 UTC
### Source information

1.4.29

### Source language

Spanish 

### Steps to reproduce

1 open extension 
2 the page gives error 400

### Expected behavior

1 open extension 
2 show all mangas and chapters the web have 

### Actual behavior

Instead of the page of the extension load show error 400
![Screenshot_20231216_134741_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/154016860/d8b81ff4-8be1-43d4-96d7-d5cebbfb9f76)

### Tachiyomi version

0.14.7

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2023-12-16 19:15
Duplicate of #19240

**Closed by vetleledaal** 2023-12-16 19:15 UTC
Labels: Bug
