### ISSUE TITLE
Manga fire not working 

### ISSUE THREAD

**Issue by vedant079** [tachiyomiorg/tachiyomi-extensions#18251] opened 2023-09-29 15:23 UTC
### Source information

Mangafire 1.4.2

### Source language

English 

### Steps to reproduce

Open mangafire in browse
![Screenshot_2023-09-29-20-50-03-982_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/115918884/aed2f7af-7251-4ae9-90f4-e779d5e46f46)

### Expected behavior

Should show all titles

### Actual behavior

Not working 

### Tachiyomi version

0.14.6

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-09-29 16:31
Duplicate of #17715

**Closed by arkon** 2023-09-29 16:31 UTC
Labels: Bug
