### ISSUE TITLE
Manga Gohan. HTTP error400

### ISSUE THREAD

**Issue by ONE223** [tachiyomiorg/tachiyomi-extensions#11758] opened 2022-05-06 15:42 UTC
### Source information

Manga Gohan 1.2.21

### Steps to reproduce

Http error400

### Expected behavior

![Screenshot_20220506-233404](https://user-images.githubusercontent.com/68263164/167165952-64f440f2-7a00-4d5e-b668-93df4eea06ed.png)

### Actual behavior

![Uploading Screenshot_20220506-233352.png…]()

### Tachiyomi version

0.13.4

### Android version

Android11

### Other details

None

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ONE223** [comment] 2022-05-06 15:43
![Uploading Screenshot_20220506-233352.png…]()

**Comment by alessandrojean** [comment] 2022-05-06 17:45
Duplicate of #11701

**Closed by alessandrojean** 2022-05-06 17:45 UTC
Labels: Bug
