### ISSUE TITLE
Asura scan not working 

### ISSUE THREAD

**Issue by Hawksaran** [tachiyomiorg/tachiyomi-extensions#17138] opened 2023-07-16 15:27 UTC
### Source information

Asura scan 1.4.48

### Source language

English 

### Steps to reproduce

Null point exception error
![Screenshot_2023-07-16-20-56-28-97_79aa9bf7c61e266c5f841e42245e214b](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/132247482/1e694a3c-9edf-4535-a2f7-860f3cd16601)

### Expected behavior

Usually the page opens perfectly 

### Actual behavior

Now it says no page found and null exception 

### Tachiyomi version

R5933

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment] 2023-07-16 15:32
duplicate of #17136

**Closed** 2023-07-16 15:39 UTC
Labels: Bug
