### ISSUE TITLE
Mad Scientists 

### ISSUE THREAD

**Issue by Traserr** [tachiyomiorg/tachiyomi-extensions#8297] opened 2021-07-27 19:24 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

Mad Scientists 

### Source link

https://mad-scientistss.blogspot.com/?m=1

### Language

Arabic

### Other details

Plz add it uts my best

**Comment by alessandrojean** [comment] 2021-07-27 19:30
Another duplicate of #2635.

Stop opening duplicate issues, this won't make the source gets added faster.

**Closed by alessandrojean** 2021-07-27 19:30 UTC
Labels: Source request
