### ISSUE TITLE
MangaSee and Mangalife display manga title "μ & I" as "&#956 & I"

### ISSUE THREAD

**Issue by sillysack69** [tachiyomiorg/tachiyomi-extensions#8748] opened 2021-08-22 15:19 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.12.1

### Android version

Android 8

### Source information

MangaSee 1.2.26 and MangaLife 1.2.22

### Steps to reproduce

Searching for the title as either "μ & I", "mu and I" or "myuu and I" or any combination of these brings up the manga title as "&#956 & I".

### Expected behavior

Should display manga title "μ & I".

### Actual behavior

Manga title "μ & I" is rendered as "&#956 & I".

**Comment by Arraiment** [comment] 2021-08-22 22:17
Duplicate of #5963

**Closed** 2021-08-22 22:20 UTC
Labels: Bug
