### ISSUE TITLE
[Bug] <Hitomi.la extension Doesn't load online view and download>

### ISSUE THREAD

**Issue by Mecatoski** [tachiyomiorg/tachiyomi-extensions#5441] opened 2021-01-16 01:44 UTC
## Device information
App version: 0.10.7 (standard, c87ba62, 53)
Android version: 8.1.0 (SDK 27)
Android build ID: O11019
Device brand: BLU
Device manufacturer: BLU
Device name: A290Q
Device model: Advance 5.2
Device product name: Advance_5_2

Most of my manga in favorites of hitomi.la extension, it does not load the visualization and it cannot download them either, it simply does not load anything

**Comment by Devy-U** [comment] 2021-01-16 09:22
To add onto this. I'm able to view/download most (if not all) newly uploaded manga but not manga uploaded sometime in 2019 and before. I'm able to view and download everything just fine on PC with both the site's own downloader and JDownloader 2 program.

Some examples that only return a "Retry" when you try to view it:
Arisu by Zucchini (Uploaded in 2015)
Ai's | Peeping Love by uo denim (Uploaded in 2017)
Essex to Akarui Saimin Seikatsu | A Cheerful Hypnosis Life with Essex by oriue wato (Uploaded in 2019)
Ohara no Kyuujitsu | Ohara's Day Off by alp (Uploaded in 2019)

App version: 0.10.7 (standard, c87ba62, 53)
Android version: 8.1.0 (SDK 27)
Android build ID: OPM7.181205.001
Device brand: google
Device manufacturer: LGE
Device name: bullhead
Device model: Nexus 5X
Device product name: bullhead

**Comment by scb261** [comment] 2021-01-16 12:28
Duplicate of #4679

**Closed** 2021-01-16 15:04 UTC
Labels: bug
