### ISSUE TITLE
ManhwaID 18+

### ISSUE THREAD

**Issue by uzumakhiadi** [tachiyomiorg/tachiyomi-extensions#10251] opened 2021-12-27 15:51 UTC
### Source name

ManhwaID 18+

### Source link

https://manhwaid.org/

### Language

Indonesia

### Other details

Manhwa 18+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2021-12-27 15:54
Duplicate of #10097

**Closed by arkon** 2021-12-27 15:54 UTC
Labels: Source request

**Comment by uzumakhiadi** [comment] 2021-12-27 15:56
> Duplicate of #10097

 this is not a duplicate, this is a different website. 
Please checking

**Comment by arkon** [comment] 2021-12-27 15:57
It's literally the same URL
