### ISSUE TITLE
[Bug] HentaiCafe (FoolSlide) : No Thumbnails Loaded

### ISSUE THREAD

**Issue by lightspect** [tachiyomiorg/tachiyomi-extensions#5650] opened 2021-02-06 16:38 UTC
## Device information
- Tachiyomi version: 0.10.8
- Android version: 10
- Device: Oneplus 5T

## Source information
- Name: HentaiCafe (FoolSlide) 
- Extension version:  1.2.59

## Steps to reproduce
1. Open the app
2. Go to the Browse section
3. Choose HentaiCafe in the Sources tab

### Expected behavior
Thumbnails is shown for each manga while browsing or choosing a manga

### Actual behavior
No thumbnails is shown for each manga while browsing or choosing a manga

## Other details
WebView still show everything fine

**Comment by scb261** [comment] 2021-02-06 16:52
Should have also specified your device, since it's not reproduceable by all users

I can reproduce as well:

Tachiyomi version: 0.10.8
Android version: 5.1
Device: Huawei TIT-U02

Cover won't show up in neither Browse, Latest or single manga page

**Comment by MercerBoi** [comment] 2021-02-07 12:28
Facing the same issue.
- Tachiyomi Version: 0.10.8
- Android Version: 10
- Device: Motorola One Fusion Plus.

Also facing this for HentaiFox, but there the cover does load when you tap on an entry and let the info page load, after which returning to the catalogue shows only that entry's cover being loaded, while the rest are blank.

Also should be noted, these issues weren't present before updating. Not sure whether this is just a coincidence or due to the update.

**Comment by scb261** [comment] 2021-02-07 21:28
Logcat
```
02-07 23:27:33.232 17088-17088/eu.kanade.tachiyomi.debug W/Glide: Load failed for MangaThumbnail(manga=eu.kanade.tachiyomi.data.database.models.MangaImpl@95fcadb5, coverLastModified=0) with size [720x454]
    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
02-07 23:27:33.233 17088-17088/eu.kanade.tachiyomi.debug W/Glide: Load failed for MangaThumbnail(manga=eu.kanade.tachiyomi.data.database.models.MangaImpl@95fcadb5, coverLastModified=0) with size [200x300]
    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
```

**Comment by jopejoe1** [comment] 2021-06-06 06:49
This should be closed as HentaiCafe went down.

**Closed** 2021-06-06 13:17 UTC
Labels: bug
