### ISSUE TITLE
[Source Request] MangaPlex

### ISSUE THREAD

**Issue by pakweebly** [tachiyomiorg/tachiyomi-extensions#6743] opened 2021-04-28 16:06 UTC
## Device information
* Tachiyomi version: 0.10.11
* Android version: 9
* Device: Oppo A31

## Source information
* Source name: MangaPlex
* Source website: https://mangaplex.com
* Language: English

**Comment by keinezeit8** [comment] 2021-04-28 16:53
duplicate of  #4226

**Closed** 2021-04-28 17:18 UTC
