### ISSUE TITLE
Manhwas.net

### ISSUE THREAD

**Issue by Stevenss20907** [tachiyomiorg/tachiyomi-extensions#7960] opened 2021-07-03 15:51 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

Manhwas.net

### Source link

https://manhwas.net/es

### Language

Español 

### Other details

![20210703_085246](https://user-images.githubusercontent.com/86885343/124359880-72387700-dbec-11eb-850b-1f136d651fd9.jpg)

**Comment by Stevenss20907** [comment] 2021-07-03 15:57
Hello good, I am new in the group and I wanted to ask you if it is possible to put these pages and send a capture in the app, please are my good ones with many manhwas and manga I would thank you very much and if possible that an a.d.m answer me thanks

**Comment by Riztard** [comment] 2021-07-03 16:08
read the first acknowledgement, duplicate of #5347

**Closed** 2021-07-03 16:09 UTC
Labels: Source request
