### ISSUE TITLE
How to fix this?

### ISSUE THREAD

**Issue by ByChrsM** [tachiyomiorg/tachiyomi-extensions#10089] opened 2021-12-13 05:19 UTC
### Source information

Mangaowl 1.2.23

### Steps to reproduce

Stuck in :
Java.lang Exception: Failed to bypass Cloudflare

### Expected behavior

![Screenshot_20211213-115807](https://user-images.githubusercontent.com/91451128/145756292-0e3bfc4b-2a4c-4f1e-8cc6-deb4589de03a.png)

### Actual behavior

![Screenshot_20211213-115550_1](https://user-images.githubusercontent.com/91451128/145756367-9401ca86-3115-4531-8d12-ffc3f0de8b98.jpg)
![Screenshot_20211213-115632](https://user-images.githubusercontent.com/91451128/145756426-c89f41a6-4291-4182-aeef-0fbe8e23bfd6.png)
![Screenshot_20211213-115640_1](https://user-images.githubusercontent.com/91451128/145756440-ad799905-785a-481c-b12f-af3c8ee7cb26.jpg)
![Screenshot_20211213-115706](https://user-images.githubusercontent.com/91451128/145756461-9f19b1a5-b601-4e73-bbfe-3a42d9d20f2c.png)

Still stuck in : Java.lang Exception: Failed to bypass Cloudflare

### Tachiyomi version

0.12.3

### Android version

Android 6

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2021-12-13 18:49
Duplicate of #8456

**Closed by alessandrojean** 2021-12-13 18:49 UTC
Labels: Bug
