### ISSUE TITLE
Manga Reader

### ISSUE THREAD

**Issue by Hasan-01** [tachiyomiorg/tachiyomi-extensions#9326] opened 2021-10-02 13:14 UTC
### Source name

Mangareader.to

### Source link

https://mangareader.to/

### Language

English

### Other details

It is a really fast and ads free site. It has almost all the population manga, manhwa, One-shot, Light Novel, Manhua, Doujinshi and Comic. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2021-10-02 13:51
Duplicate of #9112

**Closed by arkon** 2021-10-02 13:51 UTC
Labels: Source request
