### ISSUE TITLE
Failed to bypass cloudfare / no results found

### ISSUE THREAD

**Issue by damnthethe** [tachiyomiorg/tachiyomi-extensions#12744] opened 2022-07-26 10:47 UTC
### Source information and language

toongod-english

### Steps to reproduce

even though I follow the steps of this problem going to webview is too difficult to do because of massive ads everytime I click.

### Expected behavior

unlike other extension its easy for them to load 

### Actual behavior

while the toongod extension it always said failed to bypass cloudfare or no results found

### Tachiyomi version

0.13.5

### Android version

Android 7.0

### Other details

![Screenshot_20220726-184725](https://user-images.githubusercontent.com/110007383/180988690-7f4158ac-673f-4d3d-9d7e-af82626e3d9f.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment] 2022-07-26 11:25
Duplicate of #11665

**Closed** 2022-07-26 11:44 UTC
Labels: Bug
