### ISSUE TITLE
Browsing MangaDex source instantly crashes Tachiyomi

### ISSUE THREAD

**Issue by TheGershon** [tachiyomiorg/tachiyomi-extensions#16992] opened 2023-07-02 21:54 UTC
### Source information

MangaDex 1.4.182

### Source language

Multi

### Steps to reproduce

Browse -> Sources -> MangaDex

### Expected behavior

Source opens and allows one to browse titles / search

### Actual behavior

Tachiyomi instantly closes completely and returns to app launcher

### Tachiyomi version

0.14.6-5882 (standard, 3125d7870, 103, 2023-07-01T21:09Z)

### Android version

10

### Other details

Reinstalling the source doesn't fix the issue, nor does clearing cookies. Other sources don't have this issue.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2023-07-02 21:57
Duplicate of #16991

**Closed by Seishirou101** 2023-07-02 21:57 UTC
Labels: Bug
