### ISSUE TITLE
API

### ISSUE THREAD

**Issue by ALCFE** [tachiyomiorg/tachiyomi-extensions#13113] opened 2022-08-20 15:22 UTC
### Source information and language

Mangahub 1.3.19

### Steps to reproduce

API REACH LIMIT
1.It should never happen before update
2.after update this problem start 

### Expected behavior

This happen many times when I try download manga from mangahub

### Actual behavior

It keep saying API REACH LIMIT,I don't know this can happen before something like this never happen before update 

### Tachiyomi version

"0.13.6"

### Android version

Android 11

### Other details

I can't download chapter anymore and it keep saying API REACH LIMIT and when I wait around 10 it can download again but few chapter only . Please fix this problem now

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-08-20 15:24
Duplicate of #13040

**Closed by alessandrojean** 2022-08-20 15:24 UTC
Labels: Bug
