### ISSUE TITLE
[Source Request] <manga.club>

### ISSUE THREAD

**Issue by alexphilip0019** [tachiyomiorg/tachiyomi-extensions#6700] opened 2021-04-25 01:40 UTC
Name: manga.club
Url: https://manga18.club/
Lang: en,korean

**Comment by jopejoe1** [comment] 2021-06-01 05:11
Duplicate of #5253

**Comment by jopejoe1** [comment] 2021-06-01 05:30
Or just mislabelled

**Comment by alexphilip0019** [comment] 2021-06-01 06:40
Duplicate of https://github.com/tachiyomiorg/tachiyomi-extensions/issues/5253

**Closed** 2021-06-01 06:40 UTC
Labels: Source Request
