### ISSUE TITLE
[Source Request] <Davey Scans>

### ISSUE THREAD

**Issue by Ciel-kun** [tachiyomiorg/tachiyomi-extensions#6902] opened 2021-05-08 12:30 UTC
## Source website
- Name: Davey Scans
- Link: https://daveyscans.com/
- Language(s): Indonesian

## Other details
- I have checked that the extension does not already exist:
  - In the list of existing extensions in the application

**Comment by Riztard** [comment] 2021-05-08 12:38
duplicate of #6901

**Closed by Riztard** 2021-05-08 12:38 UTC
Labels: Source Request, duplicate
