### ISSUE TITLE
Voyce.me

### ISSUE THREAD

**Issue by king2815** [tachiyomiorg/tachiyomi-extensions#8406] opened 2021-08-05 04:52 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

Voyce.me

### Source link

https://www.voyce.me/

### Language

English

### Other details

VoyceMe host the highest quality English language comics, novels, and mangas! If you are a creator sign up and start posting in minutes! We offer the best opportunities to generate revenue and also promote all creators!

**Comment by loocool2** [comment] 2021-08-05 04:53
Duplicate of #6560

**Closed by loocool2** 2021-08-05 04:53 UTC
Labels: Source request
