### ISSUE TITLE
Mangakakalot: Some chapter images doesn't load

### ISSUE THREAD

**Issue by catarox32** [tachiyomiorg/tachiyomi-extensions#11513] opened 2022-04-18 06:50 UTC
### Source information

Mangakalot 1.2.8

### Steps to reproduce

I load a manga to read and then I can read the first to pages of the chapter perfectly but i just doesn't load from the third page. And this goes for every manga from that source .

![Uploading Screenshot_2022-04-18-12-18-35-540_eu.kanade.tachiyomi.jpg…]()

### Expected behavior

I expect for all the pages to load properly without any issue because due to this i always have to read from original source website.

### Actual behavior

The pages load normally .

### Tachiyomi version

0.13.2

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alekc** [comment] 2022-04-21 16:19
Cannot reproduce?

**Comment by Seishirou101** [comment] 2022-05-13 03:29
usually fixed by doing the troubleshooting steps. otherwise like alekc said it may only an issue with you.

**Closed by Seishirou101** 2022-05-13 03:29 UTC
Labels: Bug
