### ISSUE TITLE
[Source Request] <Sempai Ediciones>

### ISSUE THREAD

**Issue by Jose1159** [tachiyomiorg/tachiyomi-extensions#7542] opened 2021-06-08 12:43 UTC
## Source website
- Name: Sempai Ediciones 
- Link: http://senpaiediciones.com/
- Language(s): Spanish (ES)

**Comment by alessandrojean** [comment] 2021-06-08 15:45
Duplicate of #7359.

**Closed by alessandrojean** 2021-06-08 15:45 UTC
Labels: Source Request
