### ISSUE TITLE
MangaOwl: no pages found

### ISSUE THREAD

**Issue by Fujin-sama** [tachiyomiorg/tachiyomi-extensions#10492] opened 2022-01-17 15:22 UTC
### Source information

MangaOwl 1.2.24

### Steps to reproduce

no pages found

### Expected behavior

The chapter should open after clicking the open button

### Actual behavior

No pages found
![272017611_3167697846804592_7359488136482997260_n](https://user-images.githubusercontent.com/97900048/149796283-3534b34c-99e8-4a34-8d33-f1c1293b1dfd.jpg)

### Tachiyomi version

0.12.3

### Android version

Android 9 

### Other details

It was functioning 2 days ago and i tried to open some chapters it says no pages found.
![272017611_3167697846804592_7359488136482997260_n](https://user-images.githubusercontent.com/97900048/149796503-786c8078-5c02-4e2d-a5e4-39f915635db9.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment] 2022-01-17 15:25
>  I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open issue.

Duplicate of #10464

**Closed by curche** 2022-01-17 15:25 UTC
Labels: Bug
