### ISSUE TITLE
MangaHub: API Rate Limit Excessed

### ISSUE THREAD

**Issue by Davidbolt121199** [tachiyomiorg/tachiyomi-extensions#16676] opened 2023-06-07 03:38 UTC
### Source information

MangaHub 1.4.31

### Source language

English

### Steps to reproduce

Unable to read manga and manhwa due to API rate limit excessed.

1. It shows reloading page when click on any chapter.
2. Then it shows "API rate limit excessed! Go to mangahub.io to continue reading!"
3. New or old chapters shows same issue.
4. Even after clearing cache and cookies it shows  "API rate limit excessed!
![image](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/121578582/4f263501-16ac-411e-af92-1d99ddfeeee2)
![image](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/121578582/94afd6c1-00a7-44b1-9b0b-2867e76be0a1)

### Expected behavior

All manga and manhwa chapters should have been able to read without any problem.

### Actual behavior

It shows "API rate limit excessed! Go to mangahub.io to continue reading!"
![image](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/121578582/71aba0a2-f2d9-4c69-b46e-66131d83cc55)
![image](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/121578582/ec49201c-9147-40d7-86e7-7a4c9fb9909a)

### Tachiyomi version

0.14.6

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment] 2023-06-07 04:12
Duplicate of #16481

**Closed by loocool2** 2023-06-07 04:12 UTC
Labels: Bug
