### ISSUE TITLE
mange.ae can't fetch page from the source

### ISSUE THREAD

**Issue by RayMiles94** [tachiyomiorg/tachiyomi-extensions#8486] opened 2021-08-09 08:23 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.12.1

### Android version

9.2

### Source information

Manga.ae

### Steps to reproduce

1. install manga.ae
2. go to any manga
3. select any chapitre 
4. error to fetch pages

### Expected behavior

i can read manga from manga.ae

### Actual behavior

i can't read  manga from manga.ae

### Other details

nothing

**Comment by Arraiment** [comment] 2021-08-09 09:18
I'll work on this, you can close the issue because its a duplicate of #7796

**Closed** 2021-08-09 09:43 UTC
Labels: Bug
