### ISSUE TITLE
No results found

### ISSUE THREAD

**Issue by PrinceBlackstaIV** [tachiyomiorg/tachiyomi-extensions#11191] opened 2022-03-21 01:37 UTC
### Source information

Readcomicbookonline

### Steps to reproduce

1. Open extension
2. No results found
3. Can't read already bookmarked comics either

### Expected behavior

Show full library of available comicz

### Actual behavior

No results found at the startup

### Tachiyomi version

Newest

### Android version

Android 8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-03-21 01:48
Duplicate of #11141.

**Closed by alessandrojean** 2022-03-21 01:48 UTC
Labels: Bug
