### ISSUE TITLE
Reaper Scans Extention is broken

### ISSUE THREAD

**Issue by ShawkikIslam** [tachiyomiorg/tachiyomi-extensions#13760] opened 2022-10-08 07:35 UTC
### Source information and language

Reaper Scans 1.3.31 (All)

### Steps to reproduce

The site migrated into new server.
Though,their site URL is same,the extension isn't working anymore.Technically,it broke.

### Expected behavior

It should have start working again after site became "operational" from "down"

### Actual behavior

![Screenshot_2022-10-08-13-35-04-475_eu kanade tachiyomi](https://user-images.githubusercontent.com/74912756/194695924-b9bfcbf8-e873-4a31-a919-dc361e80537d.jpg)

### Tachiyomi version

0.13.6

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by I-Am-C0der** [comment] 2022-10-08 11:12
Duplicate of #13747

**Closed** 2022-10-08 12:01 UTC
Labels: Bug
