### ISSUE TITLE
Erreur au lancement d'un chapitre sur japscan 

### ISSUE THREAD

**Issue by Expericam** [tachiyomiorg/tachiyomi-extensions#16905] opened 2023-06-28 16:56 UTC
### Source information

Japscan 1.4.40

### Source language

Français

### Steps to reproduce

Étape 1 lancement d'un chapitre d'un webtoon sur japscan

### Expected behavior

Lancer le chapitre 

### Actual behavior

Message d'erreur : "Attendais 2 chaînes de recherche dans zjs, à trouvé 0"

### Tachiyomi version

0.14.6

### Android version

Emui 12.0.0

### Other details

![Screenshot_20230628_184024_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/100787945/2addc94a-3086-4366-ac15-d4270b97deaa)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2023-06-28 17:01
Duplicate of #16898

**Closed by alessandrojean** 2023-06-28 17:01 UTC
Labels: Bug

**Comment by Krylanc3lo** [comment] 2023-06-28 18:05
Hello,

it seems that japscan changed something in their base64 unscrambling JS, the script is not able to find the keys anymore. Maybe @Rajh has an idea ? I am trying but no luck so far.
