### ISSUE TITLE
Rawdevart closed

### ISSUE THREAD

**Issue by NorseFenris** [tachiyomiorg/tachiyomi-extensions#14849] opened 2023-01-08 18:14 UTC
### Source information and language

Rawdevart v 1.3.4

### Steps to reproduce

Go to browse
Select rawdevart
open webview

### Expected behavior

Rawdevart opens

### Actual behavior

Nothing loads or Endevart loads

### Tachiyomi version

0.14.3

### Android version

Android 13

### Other details

Information from their facebook says the site closed.

They are building a completely new site with different features and code. Will be nothing like the old site. So this extension might as well be pulled.

![Screenshot_20230108_190842_Firefox Beta](https://user-images.githubusercontent.com/66540317/211212062-58c3c6c2-0d9e-4806-9489-087144dca4f5.jpg)

New site is endevart

![Screenshot_20230108_191651_Firefox Beta](https://user-images.githubusercontent.com/66540317/211212240-a121f325-34e6-4713-96b8-17bd7c5038a1.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Hasster1** [comment] 2023-01-11 07:49
Duplicate of https://github.com/tachiyomiorg/tachiyomi-extensions/issues/14645

**Closed** 2023-01-11 07:51 UTC
Labels: Bug
