### ISSUE TITLE
wnacg bug

### ISSUE THREAD

**Issue by RX93CN** [tachiyomiorg/tachiyomi-extensions#17606] opened 2023-08-20 02:38 UTC
### Source information

wnacg 1.4.14

### Source language

Chinese

### Steps to reproduce

打开对应插件显示Java.io.IOException:网址已自动更新，请重启，或者能刷新出页面时，再下拉，也会时不时出现

### Expected behavior

能正常显示页面，而不是网址已自动更新，请重启

### Actual behavior

webview 可以正常加载，插件页面提示网址已自动更新，请重启

### Tachiyomi version

0.14.6

### Android version

Android 12

### Other details

已经更新站点，并且3个站点都已测试过，均有出现网址已自动更新提示，使用vpn下拉显示过多，同样会有这个提示
![Screenshot_2023-08-20-10-01-54-632_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/110704357/ddec1534-ff21-4cb1-b3ac-e60400511ee7)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment] 2023-08-20 03:36
需要使用桌面端 User Agent。

**Comment by stevenyomi** [comment] 2023-08-20 03:36
Duplicate of #17266

**Closed by stevenyomi** 2023-08-20 03:36 UTC
Labels: Bug
