### ISSUE TITLE
Nhentai failed to bypass cloudflare 

### ISSUE THREAD

**Issue by YouBoi234** [tachiyomiorg/tachiyomi-extensions#13072] opened 2022-08-19 02:41 UTC
### Source information and language

Nhentai 1.3.35

### Steps to reproduce

Not able to bypass the CloudFlare from the extension . Using browser is able to bypass but not inside the App.
Visit the website through the APP Cannot bypass the cloudflare.

### Expected behavior

Able to open the extension through the app and the webrowser through the app

### Actual behavior

Its always looping in the bypassed cloudflare through the extension and the webrowser of the app

### Tachiyomi version

0.13.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-08-19 02:42
Duplicate of #12784

**Closed by arkon** 2022-08-19 02:42 UTC
Labels: Bug
