### ISSUE TITLE
Cannot open the Comic or manhwa even though the web is still active

### ISSUE THREAD

**Issue by xeanz** [tachiyomiorg/tachiyomi-extensions#16273] opened 2023-05-02 14:07 UTC
### Source name

Doujindesu

### Source language

indonesia

### Source link

https://212.32.226.234/

### Other details

i already activate my dns, the web is still active, but i cannot read and download from from that web

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2023-05-02 14:57
Likely duplicate of #14004

**Closed by alessandrojean** 2023-05-02 14:57 UTC
Labels: Source is down
