### ISSUE TITLE
Copy Manga doesn't work correctly

### ISSUE THREAD

**Issue by mojunisme** [tachiyomiorg/tachiyomi-extensions#10689] opened 2022-02-04 07:49 UTC
### Source information

CopyManga 1.2.22

### Steps to reproduce

1. renew the manga in copymanga source

### Expected behavior

1. renew the copymanga extension to connected with the right website.

### Actual behavior

404 error

### Tachiyomi version

0.13.1

### Android version

Android 12

### Other details

CopyManga website is just working normally.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment] 2022-02-04 08:26
> I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open issue.

Duplicate of #10658

**Closed by curche** 2022-02-04 08:26 UTC
Labels: Bug
