### ISSUE TITLE
Issue 429

### ISSUE THREAD

**Issue by ReachedTheApex** [tachiyomiorg/tachiyomi-extensions#14857] opened 2023-01-09 03:36 UTC
### Source information and language

1stkiss 1.3.34 English

### Steps to reproduce

Library/ category update

### Expected behavior

Pull updates for new chapters

### Actual behavior

Error page produced showing http error 429 

### Tachiyomi version

App version: 0.14.3 

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2023-01-09 04:03
Duplicate of #14850

**Closed by alessandrojean** 2023-01-09 04:03 UTC
Labels: Bug
