### ISSUE TITLE
Mangalek

### ISSUE THREAD

**Issue by 5OSA** [tachiyomiorg/tachiyomi-extensions#18261] opened 2023-09-30 03:00 UTC
### Source information

Mangalek 1.4.33

### Source language

Arabic 

### Steps to reproduce

It's opening in chrome with another link
https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://manga-lek.net/&ved=2ahUKEwjNifeUq9GBAxU5RKQEHZnQBk8QFnoECAgQAQ&usg=AOvVaw1UFFFDFyszWcGAleWAc5Dn

### Expected behavior

![Screenshot_20230930_055606_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/103575956/0793c6f9-247e-4c34-a9da-00a7d59ed4c9)

### Actual behavior

Http error 404 

### Tachiyomi version

0.14.6

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2023-09-30 03:22
Duplicate of #18124

**Closed by Seishirou101** 2023-09-30 03:22 UTC
Labels: Bug
