### ISSUE TITLE
Mangapark Extension, search not working

### ISSUE THREAD

**Issue by ahmedzs321** [tachiyomiorg/tachiyomi-extensions#19212] opened 2023-12-06 02:34 UTC
### Source information

Mangapark 1.4.18

### Source language

English

### Steps to reproduce

1. Search manga by title
2. Receive no results

### Expected behavior

I should receive some kind of result

### Actual behavior

I am receiving no results. It does not matter if I search from within the source or globally, no results are being found in mangapark when they should be there.

### Tachiyomi version

0.14.7

### Android version

Android 14

### Other details

Manga that are already added to library still receive updates and opening the extension source to browse and/or filter manga still populates the available manga. The only thing that is not working is the search function. This may be due to the recent update to the mangapark website itself to version 5.2.x. It seems updates to the site are still rolling out (almost daily), so it may be better to wait some time before handling the issue.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2023-12-06 21:24
Search for v3 doesn't exist any more, the site redirects to v5 whenever you search. In a roundabout way, this is a duplicate of #15310

**Closed by vetleledaal** 2023-12-06 21:24 UTC
Labels: Bug
