### ISSUE TITLE
[Feature Request] <mangadex>: <different scans choice>

### ISSUE THREAD

**Issue by dmswd** [tachiyomiorg/tachiyomi-extensions#5978] opened 2021-02-24 08:19 UTC
## What feature should be added to this source?
The ability to choose scans based on the most viewed scans
Explain why this should be added
Many people complain about duplicate chapters and I use an Arabic extension called Gmanga
And in its settings you can choose either to display all scans or display the scan with the most views
My request is that I suggest implementing this feature in mangadex

**Comment by Seishirou101** [comment] 2021-03-03 14:16
Duplicate of tachiyomiorg/tachiyomi#969

**Closed** 2021-03-03 14:20 UTC
Labels: enhancement

**Comment by scb261** [comment] 2021-03-03 14:57
Filter by most views actually should be implemented on extension side. And it shouldn't be too hard to implement, the api returns views along with chapter list. Should I reopen the issue?

**Comment by Seishirou101** [comment] 2021-03-03 15:05
I don't think it'll be the same way the op particular wants. If done on the extension side, it'll be something akin to what mangapark does, I think... but if you want to implement it, I don't see why not.

**Comment by CarlosEsco** [comment] 2021-03-03 15:18
filtering by views also means that you are filtering on stale db data unless you refresh the chapter list
