### ISSUE TITLE
No chapter found 

### ISSUE THREAD

**Issue by Nurullahgrlk** [tachiyomiorg/tachiyomi-extensions#13233] opened 2022-08-27 20:22 UTC
### Source information and language

Webtoon TR 1.3.24(Turkish)

### Steps to reproduce

The webtoon is no longer read from this source.  Although there is a section on the site, the application says "No section found". 
![Screenshot_2022-08-27-23-17-08-534_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/97397847/187046730-978b6d59-2ffe-413b-9285-1a186c78a0e8.jpg)

### Expected behavior

The webtoon is no longer read from this source.  Although there is a section on the site, the application says "No section found". 
![Screenshot_2022-08-27-23-17-08-534_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/97397847/187046730-978b6d59-2ffe-413b-9285-1a186c78a0e8.jpg)

### Actual behavior

The webtoon is no longer read from this source.  Although there is a section on the site, the application says "No section found". 
![Screenshot_2022-08-27-23-17-08-534_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/97397847/187046730-978b6d59-2ffe-413b-9285-1a186c78a0e8.jpg)

### Tachiyomi version

 0.13.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-08-27 20:42
Duplicate of #11371

**Closed by alessandrojean** 2022-08-27 20:42 UTC
Labels: Bug
