### ISSUE TITLE
Mangas pw: Problem with the chapters of every series in this extension

### ISSUE THREAD

**Issue by MontblancNoland** [tachiyomiorg/tachiyomi-extensions#8582] opened 2021-08-16 05:43 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.12.1

### Android version

Android 10

### Source information

Mangas pw 1.2.4

### Steps to reproduce

1.- Open the extension
2.- Select a manga series
3.- Appears an incorrect chapter from another manga

### Expected behavior

It should be the correct chapter of the manga

### Actual behavior

It appears a random chapter from a random manga

### Other details

It only happens with Mangas pw extension

**Comment by curche** [comment] 2021-08-16 06:00
Duplicate of #7970

**Closed** 2021-08-16 06:00 UTC
Labels: Bug
