### ISSUE TITLE
MangaHub: Unable to read manga due to API rate limit excessed 

### ISSUE THREAD

**Issue by PheonixGamer09** [tachiyomiorg/tachiyomi-extensions#16493] opened 2023-05-19 04:11 UTC
### Source information

MangaHub 1.4.31

### Source language

English

### Steps to reproduce

1. When open any Manga and Manhwa it shows reloading and then it shows API rate limit excessed.
2. 
![Screenshot_2023-05-18-15-20-09-653_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/128516302/544579ed-ce36-47ce-9936-51271b2d8d21)
![Screenshot_2023-05-18-15-20-17-964_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/128516302/7141cd99-e8f0-4122-8f63-a97859e7ccee)

### Expected behavior

Instead of showing API rate limit in every chapter or new uploaded chapter. It shows have shown Manga and Manhwa chapter pages properly.

### Actual behavior

It shows"API rate limit excessed". Please resolve this issue.
![Screenshot_2023-05-19-07-25-00-459_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/128516302/31d2c005-9813-49b8-8f1b-82bf28155a59)
![Screenshot_2023-05-19-07-24-52-479_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/128516302/67c89ddd-c0a5-4204-8387-268670ebbb04)

### Tachiyomi version

0.14.6

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment] 2023-06-07 04:12
Duplicate of #16481

**Closed by loocool2** 2023-06-07 04:12 UTC
Labels: Bug
