### ISSUE TITLE
Disaster Scans - HTTP Error 404

### ISSUE THREAD

**Issue by I-Am-C0der** [tachiyomiorg/tachiyomi-extensions#16651] opened 2023-06-01 13:24 UTC
### Source information

Disaster Scans 1.4.31

### Source language

English

### Steps to reproduce

1. Go to Tachiyomi App
2. Go to "Browse"
3. Under Source --> Select "Disaster Scans" (If not availabe install it from Extensions)

### Expected behavior

Able to view new chapters of available Manhua

### Actual behavior

Getting the below error -
**HTTP Error 404: Check website in WebView**

### Tachiyomi version

0.14.6

### Android version

Android 11

### Other details

**NOT CLOUDFLARE ISSUE**
**NOTE:** WebView is working without any issue. 

![Disaster Scan](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/51527183/f15067be-7f53-4d70-8bb7-b8791e6b7e85)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by MassinLaj** [comment] 2023-06-01 19:21
Duplicate of https://github.com/tachiyomiorg/tachiyomi-extensions/issues/16596

**Closed** 2023-06-02 02:02 UTC
Labels: Bug
