### ISSUE TITLE
HTTP 400 error 

### ISSUE THREAD

**Issue by akshar2324** [tachiyomiorg/tachiyomi-extensions#8969] opened 2021-09-04 18:38 UTC
### Source information

1st Kiss 1.2.16

### Steps to reproduce

when opening it showing
HTTP error 400 : check website in webview
![Screenshot_20210905_000413](https://user-images.githubusercontent.com/90042795/132104715-4b0b3bda-95be-49ed-8469-ce0fb4db5faf.jpg)

### Expected behavior

it should show all manga and manhwa 
![Screenshot_20210905_000515](https://user-images.githubusercontent.com/90042795/132104735-e5818a12-1af4-420c-b8fe-630c2c51a682.jpg)

### Actual behavior

when opening it showing
HTTP error 400 : check website in webview
![Screenshot_20210905_000413](https://user-images.githubusercontent.com/90042795/132104715-4b0b3bda-95be-49ed-8469-ce0fb4db5faf.jpg) 

### Tachiyomi version

0.12.1

### Android version

Android 9

### Other details

it's only happen in this extension 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment] 2021-09-04 18:46
Duplicate of #8939 
> I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open issue.

**Closed by curche** 2021-09-04 18:46 UTC
Labels: Bug
