### ISSUE TITLE
Redirect broke extension. New URL

### ISSUE THREAD

**Issue by ihave3settings** [tachiyomiorg/tachiyomi-extensions#19085] opened 2023-11-23 19:15 UTC
### Source information

Read One Piece Manga Online 1.4.3

### Source language

English

### Source new URL

https://ww10.readonepiece.com/manga/one-piece/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2023-11-23 20:32
Duplicate of #19075. ww8 redirects to ww10 just fine, so something else is faulty.
```bash
~ ❱ curl -Ls -o /dev/null -w '%{url_effective}\n' https://ww8.readonepiece.com/chapter/one-piece-chapter-1099/
https://ww10.readonepiece.com/chapter/one-piece-chapter-1099/
```

**Closed by vetleledaal** 2023-11-23 20:32 UTC
Labels: Bug, Domain changed
