### ISSUE TITLE
Hentai20 failed to bypass cloudflare

### ISSUE THREAD

**Issue by Hounddraco** [tachiyomiorg/tachiyomi-extensions#11830] opened 2022-05-12 03:30 UTC
### Source information

Hentai20 1.2.21

### Steps to reproduce

Open hentai20 go to a manhwa try to open a chapter

### Expected behavior

A chapter should load

### Actual behavior

You are kicked back to the chapter select screen with failed to bypass cloudflare at bottom of screen

### Tachiyomi version

0.13.4

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment] 2022-05-12 03:45
Duplicate of #11770

**Closed by loocool2** 2022-05-12 03:45 UTC
Labels: Bug
