### ISSUE TITLE
Manhwas-raw extension some text appeared

### ISSUE THREAD

**Issue by Musang13** [tachiyomiorg/tachiyomi-extensions#14222] opened 2022-11-10 18:31 UTC
### Source information and language

Manhwa-raw 1.3.25 (Multi)

### Steps to reproduce

1. Before the extension update Manhwas-raw is fine
2. When i view some Mamhwa and refresh to update the chapter 'some text appeared'
3. when the Manhwa that im first time to read and click it and after loading some text appeared and says "lateinit property title has not been initialized" and the discription is gone/no discription

### Expected behavior
If im refresh to update new chapter it should be like outher extension that no text appeared and the discription didn't gone if im click the manhwa that im first time to read, but the manhwa that i already reas is just "text" appeard only.

### Actual behavior

This after extension update.
![Screenshot_2022-11-10-20-22-04-69](https://user-images.githubusercontent.com/90293695/201177121-7905684b-559c-4de2-abf4-dd55f096ea0d.jpg)

### Tachiyomi version

0.14.2

### Android version

Android 8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment] 2022-11-11 05:48
duplicate of #14214

**Closed by Riztard** 2022-11-11 05:48 UTC
Labels: Bug
