### ISSUE TITLE
Pages not found

### ISSUE THREAD

**Issue by houxemiya** [tachiyomiorg/tachiyomi-extensions#12065] opened 2022-06-04 11:42 UTC
### Source information

MangaSwat 1.2.20

### Steps to reproduce

1.open a chapter
2.said pages not found

### Expected behavior

Normally it work fine

### Actual behavior

It gives "page not found"

### Tachiyomi version

0.13.4

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment] 2022-06-04 11:55
Duplicate of #10318

**Closed by curche** 2022-06-04 11:55 UTC
Labels: Bug
