### ISSUE TITLE
Doujindesu & Sektedoujin cant opened

### ISSUE THREAD

**Issue by gundamwin38** [tachiyomiorg/tachiyomi-extensions#11510] opened 2022-04-18 02:55 UTC
### Source information

Doujindesu 1.2.2 & Sektedoujin 1.2.16

### Steps to reproduce

1.open source
2.select doujindesy
3.doesn't find any results, just host name not verified. Even i use DoH the result just ssl handshake aborted.

### Expected behavior

This should show the lastest update of doujindesu

### Actual behavior

Doesn't find any results just host name not verified. Even i use DoH the result just ssl handshake aborted.

### Tachiyomi version

0.13.3

### Android version

10

### Other details

Thanks.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment] 2022-04-18 14:41
Duplikasi dari #11401, #11411 dan #11270 / Duplicate of #11401, #11411 and #11270
Alasan / Reason
Ganti domain / They change the domain

**Comment by alessandrojean** [comment] 2022-04-18 14:42
Closing since it's partially a duplicate.

Please also open one ticket per source next time.

**Closed by alessandrojean** 2022-04-18 14:42 UTC
Labels: Bug

**Comment by TheKingTermux** [comment] 2022-04-18 14:46
> Closing since it's partially a duplicate.
> 
> Please also open one ticket per source next time.

Roger that

**Comment by TheKingTermux** [comment] 2022-04-18 14:47
For Doujindesu #11439 
For Sekte Doujin #11270
