### ISSUE TITLE
Myreadingmanga broken chapters

### ISSUE THREAD

**Issue by akmalmeaw** [tachiyomiorg/tachiyomi-extensions#8960] opened 2021-09-04 08:06 UTC
### Source information

Myreadingmanga 1.2.43

### Steps to reproduce

1. Open in the webview
2. Settling the chapta

### Expected behavior

1. Can read the chapters in taciyomi

### Actual behavior

1. It work in myreadingmanga web
2. The chapters broken

### Tachiyomi version

0.12.1

### Android version

Android 11

### Other details

![Screenshot_20210904-155516_Tachiyomi](https://user-images.githubusercontent.com/64727356/132087645-625a3d97-c52a-4ee2-a12a-3dfc56072ec2.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Arraiment** [comment] 2021-09-04 08:14
Duplicate of #8830

**Closed** 2021-09-04 10:41 UTC
Labels: Bug
