### ISSUE TITLE
Kuaikanmanhua returns emoji without error message 

### ISSUE THREAD

**Issue by Arifrhmn2743** [tachiyomiorg/tachiyomi-extensions#17305] opened 2023-07-29 09:11 UTC
### Source information

Kuaikanmanhua 1.4.10

### Source language

Chinese 

### Steps to reproduce

1. Install the extension and open it
2. When opening the latest page and popular page the extension returns the emoji, without error
3. When the open in webview is clicked, the site is working properly

### Expected behavior

It should shows the latest and popular manga sections

### Actual behavior

It only shows the emoji wihout an error message 
![Screenshot_20230729-160418_Quickstep](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/68379379/6ba37463-90b0-4811-afb8-73089708b7a7)
![Screenshot_20230729-160423_Quickstep](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/68379379/50e8f27f-d42d-47bb-a064-a185f223645e)

### Tachiyomi version

Stable 0.14.6

### Android version

Android 12

### Other details

I tried opening with windscribe vpn, but still not working

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment] 2023-08-05 22:18
Duplicate of #17403

**Closed by stevenyomi** 2023-08-05 22:18 UTC
Labels: Bug
