### ISSUE TITLE
Source Website Structure Changed

### ISSUE THREAD

**Issue by DraconioSchiffer** [tachiyomiorg/tachiyomi-extensions#19092] opened 2023-11-24 14:30 UTC
### Source information

ReadJujutsuKaisenMangaOnline 1.4.4

### Source language

English

### Steps to reproduce

Open "Jujutsu Kaisen" manga from the extension 
![Screenshot_20231124_092850_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/39329663/9d239fb7-c08d-4885-a134-3d20a2ff1747)

### Expected behavior

Should display all chapters and allow reading.

### Actual behavior

Does not display any chapter.

### Tachiyomi version

0.14.7

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by DraconioSchiffer** [comment] 2023-11-24 14:32
![Screenshot_20231124_093202_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/39329663/8a01f33e-6bb6-4dcf-a025-bccd1cadd033)
Website has added a new "Read" button.

**Comment by vetleledaal** [comment] 2023-11-24 14:38
Duplicate of #19075

**Closed by vetleledaal** 2023-11-24 14:37 UTC
Labels: Bug
