### ISSUE TITLE
Site link outdated (new domain)

### ISSUE THREAD

**Issue by Straf30nD3mand** [tachiyomiorg/tachiyomi-extensions#9309] opened 2021-10-01 15:05 UTC
### Source information

Mangaworld (ita)

### Steps to reproduce

When you try to open any of the mangas on the app an error appears, probably because the site changed his domain

### Expected behavior

When you try to open any of the mangas on the app an error appears, probably because the site changed his domain

### Actual behavior

The site changed his domain from https://www.mangaworld.io/ to https://www.mangaworld.in/ 

### Tachiyomi version

0.12.2

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2021-10-01 15:08
Duplicate of #9291

Please read the acknowledgement section you checked.

>  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Closed by alessandrojean** 2021-10-01 15:08 UTC
Labels: Bug
