### ISSUE TITLE
Http 429 error

### ISSUE THREAD

**Issue by Asdefasko** [tachiyomiorg/tachiyomi-extensions#18952] opened 2023-11-13 10:51 UTC
### Source information

999 hentai 1.4.4

### Source language

English 

### Steps to reproduce

My manga channel isnt openning

### Expected behavior

Opening 

### Actual behavior

Dont open

### Tachiyomi version

0.14.7

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2023-11-13 10:53
Duplicate of #18950

**Closed by vetleledaal** 2023-11-13 10:53 UTC
Labels: Bug
