### ISSUE TITLE
xcalibr scans mirrored chapters/pages problem. 

### ISSUE THREAD

**Issue by NotPageD** [tachiyomiorg/tachiyomi-extensions#10170] opened 2021-12-20 04:24 UTC
### Source information

xCaliBR Scans 1.2.14

### Steps to reproduce

1.open up calibr scans extension
2.read any new chapters that's been updated on any series
3.try to read it

### Expected behavior

it would just work normally as intended

### Actual behavior

the chapters/pages are mirrored

### Tachiyomi version

tachiyomisy preview r422

### Android version

android 11

### Other details

if you view the chapters in webview the problem will go away, it seems that they recently implemented the mirrored pages a couple of days ago. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2021-12-20 11:58
Duplicate of #10077

**Closed by Seishirou101** 2021-12-20 11:58 UTC
Labels: Bug
