### ISSUE TITLE
not working extension 

### ISSUE THREAD

**Issue by ShinasKoya** [tachiyomiorg/tachiyomi-extensions#12583] opened 2022-07-14 12:50 UTC
### Source information

webtoonXYZ

### Steps to reproduce

when clicked it will just load and a notifier shows an error...
even the manhwa updates are blocked

### Expected behavior

when clicked , it should show the manhwa list

### Actual behavior

it is showing nothing and also a notifier shows a error writing " failed to bypass cloudflare"
and also manhwa updates are stopped.
as mentioned in cloud flare trouble shooting, the web is not even opening...
please help🥲

### Tachiyomi version

App version: 0.13.5

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-07-14 12:50
Duplicate of #6738

**Closed by arkon** 2022-07-14 12:50 UTC
Labels: Bug
