### ISSUE TITLE
MangaBuddy: Broken Chapters

### ISSUE THREAD

**Issue by semiya5** [tachiyomiorg/tachiyomi-extensions#15745] opened 2023-03-17 13:25 UTC
### Source information and language

MangaBuddy 1.4.13

### Steps to reproduce

Open extension
Open a series
Open a chapter

### Expected behavior

Should load all pages

### Actual behavior

Loads only first 2 pages

### Tachiyomi version

SY503, r5620

### Android version

Android 12

### Other details

Unsure if this is related to #15744 but just in case it isn't, made this separate request

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by DchanN** [comment] 2023-03-17 16:51
should same with #15744 title issue like wrong because chapter not missing, (the one missing it's page inside chapter), and Actual behavior both issues related Only 2 pages load / show up.

**Comment by FaTe-code** [comment] 2023-03-17 20:29
Same with J2K 1.6.4, ext 1.4.13.

**Comment by ranqianchen** [comment] 2023-03-18 02:48
same

**Comment by AyatoHigashi7** [comment] 2023-03-18 03:50
Same

**Comment by scb261** [comment] 2023-03-18 13:28
Duplicate of #15744

**Closed** 2023-03-18 13:37 UTC
Labels: Bug
