### ISSUE TITLE
Extension japscan filtrer not working 

### ISSUE THREAD

**Issue by GogerN01** [tachiyomiorg/tachiyomi-extensions#16159] opened 2023-04-24 17:35 UTC
### Source information

Japscan 

### Source language

French 

### Steps to reproduce

Extension japscan > settings > montrer uniquement les chapitres traduit en français

### Expected behavior

Not showing only translated chapitres in french 

### Actual behavior

Extension is showing raw or eng chapitres 

### Tachiyomi version

1.6.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2023-04-24 23:30
Duplicate of #16158

**Closed by alessandrojean** 2023-04-24 23:30 UTC
Labels: Bug
