### ISSUE TITLE
MangaStic Issue

### ISSUE THREAD

**Issue by ADPtechs** [tachiyomiorg/tachiyomi-extensions#15285] opened 2023-02-09 14:04 UTC
### Source information and language

MangaStic

### Steps to reproduce

Can't browse mangastic library

### Expected behavior

Can see all manga in mangastic library

### Actual behavior

It become blank
![Screenshot_2023-02-09-20-57-27-599_eu kanade tachiyomi](https://user-images.githubusercontent.com/74719050/217834220-1bd44f6c-5189-4653-b785-f14ed0b082c0.jpg)

### Tachiyomi version

0.14.4

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ADPtechs** [comment] 2023-02-11 17:24
the manga URL seems changed

**Comment by vetleledaal** [comment] 2023-02-21 20:29
Duplicate of #14407

**Closed by vetleledaal** 2023-02-21 20:29 UTC
Labels: Bug, Factory source
