### ISSUE TITLE
Reaper Scans not working

### ISSUE THREAD

**Issue by Keitio** [tachiyomiorg/tachiyomi-extensions#14819] opened 2023-01-06 06:49 UTC
### Source information and language

Reaper Scans 1.3.40

### Steps to reproduce

The source loads indefinitely even in webview while it works in a browser

### Expected behavior

The source should load

### Actual behavior

It loads indefinitely 

### Tachiyomi version

0.14.2

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AriaMoradi** [comment] 2023-01-06 07:45
Duplicate of #13936

**Comment by Isnao** [comment] 2023-01-06 07:54
It seems to be a related to Cloudflare
Here are some pictures
![Screenshot_20230106-085206](https://user-images.githubusercontent.com/6361573/210955769-a992b56c-e288-4aa4-9a75-5b6add007268.png)
![Screenshot_20230106-085145](https://user-images.githubusercontent.com/6361573/210955773-b5f90d3c-e769-4c1d-92f9-8f04ff622e82.png)

**Comment by Keitio** [comment] 2023-01-06 10:12
Not a duplicate, it worked flawlessly for me when the servers aren't down but does not work at all since their latest host change (finished a few hours ago)
Probably a cloudflare issue, but I don't see the message you have i just get a timeout

**Comment by notjl** [comment] 2023-01-06 11:06
I having the same "Failed to bypass Cloudfare" error

**Comment by takomine** [comment] 2023-01-06 11:30
You can just bypass Cloudflare in WebView and then view the manga lists.

The problem is that the images don't load when you open a chapter.

**Comment by alessandrojean** [comment] 2023-01-06 12:23
It is a duplicate, yes, exactly same issue. So closing this one.

**Closed by alessandrojean** 2023-01-06 12:23 UTC
Labels: Bug
