### ISSUE TITLE
Megabanana (Read comics in Spanish)

### ISSUE THREAD

**Issue by GGa363** [tachiyomiorg/tachiyomi-extensions#8543] opened 2021-08-13 03:38 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

Megabanana

### Source link

https://megabanana.mx/

### Language

Spanish

### Other details

I would like to suggest an extension to read comics in Spanish

Quisiera sugerir una extensión para leer comics en español

**Comment by alessandrojean** [comment] 2021-08-13 03:48
Do not open duplicate issues, last one was already closed and this website will not get added, read the comment I made earlier.

Duplicate of #8532.

**Closed by alessandrojean** 2021-08-13 03:48 UTC
Labels: Source request
