### ISSUE TITLE
Mangabuddy updated of list failure

### ISSUE THREAD

**Issue by Rkyl3** [tachiyomiorg/tachiyomi-extensions#13259] opened 2022-08-29 03:36 UTC
### Source information and language

Mangabuddy 1.3.10

### Steps to reproduce

Every time i updated my list not every list of mine get updated 

### Expected behavior

it should updated all the list of my mangabuddy

### Actual behavior

It doenst even updated half of them 

### Tachiyomi version

1.8.5

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by DchanN** [comment] 2022-08-29 04:37
Problem from #12613 tbh it's still ongoing issue but mod closed as fixed, u can read section comment to know the reason why http 429 happen

**Comment by vetleledaal** [comment] 2022-08-29 05:59
Duplicate of #13182

**Closed by vetleledaal** 2022-08-29 05:59 UTC
Labels: Bug
