### ISSUE TITLE
Manhwas.net 1.3.3 spanish problems

### ISSUE THREAD

**Issue by OliverSDL** [tachiyomiorg/tachiyomi-extensions#14434] opened 2022-12-01 20:40 UTC
### Source information and language

Manhwas.net 1.3.3 spanish 

### Steps to reproduce

actualizar cualquier manwha
ir a la fuente de extensión

### Expected behavior

el manhwa debería actualizarse correctamente
debería mostrar todo el contenido de la fuente

### Actual behavior

no actualiza lo deseado y recibí el siguiente mensaje "org.jsoup.nodes.Element.select First(java.lang.String)"

no muestra el contenido de la fuente y muestra el mensaje de "contenido nulo"

### Tachiyomi version

0.14.2

### Android version

11

### Other details

the page had a change in appearance, however in web view it works correctly

![Screenshot_2022-12-01-14-38-52-640_eu kanade tachiyomi](https://user-images.githubusercontent.com/104814374/205155026-d6bdb493-cce9-4d58-bc48-2a83e579bbaa.jpg)

![Screenshot_2022-12-01-14-38-41-515_eu kanade tachiyomi](https://user-images.githubusercontent.com/104814374/205155049-a02f8082-4749-4087-9ec1-1900dad25ba1.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2022-12-01 21:00
Duplicate of #13008

**Closed by vetleledaal** 2022-12-01 21:00 UTC
Labels: Bug

**Comment by JustAHarmlessAle** [comment] 2022-12-03 03:23
Bro, recomiendas madam?
