### ISSUE TITLE
Chapters doesn't open

### ISSUE THREAD

**Issue by MRmustafa478** [tachiyomiorg/tachiyomi-extensions#16955] opened 2023-07-01 15:42 UTC
### Source information

MangaSwat 1.4.34

### Source language

Arabic

### Steps to reproduce

1.the source open manhwas probably
2.chapters still update 
3. Chapters can't be open
4. Chapters can't be downloaded
5. WebView open and work probably 

### Expected behavior

Chapters should open 

### Actual behavior

Chapters don't open 

### Tachiyomi version

0.14.6

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2023-07-01 15:47
Please do provide more meaningful information such as the errors you're getting. "Chapter's can't be opened" doesn't describe the error causing this issue.

**Comment by 7allom** [comment] 2023-07-01 16:22
#16952 they changed their domain

**Comment by MRmustafa478** [comment] 2023-07-01 16:26
When you open the chapter's from MangaSwat it's say [ the image couldn't be lauded ] and retry is useless

> Please do provide more meaningful information such as the errors you're getting. "Chapter's can't be opened" doesn't describe the error causing this issue.

When you open the chapter's from MangaSwat it's say [ the image couldn't be lauded ] and retry is useless

**Comment by MRmustafa478** [comment] 2023-07-01 16:26
> #16952 they changed their domain

They doesn't

**Comment by MRmustafa478** [comment] 2023-07-01 16:27
It's still ( https://swatmanga.me )

**Comment by arkon** [comment] 2023-07-01 16:29
Opening the old URL very obviously redirects to the other URL.

Duplicate of #16952

**Closed by arkon** 2023-07-01 16:29 UTC
Labels: Bug
