### ISSUE TITLE
Está página tiene varios Doujin traducidos al español que otras páginas no lo tienen

### ISSUE THREAD

**Issue by Analero** [tachiyomiorg/tachiyomi-extensions#10203] opened 2021-12-23 05:19 UTC
### Source name

Adulto.LeerManga

### Source link

https://adult.leermanga.xyz/

### Language

Español

### Other details

Esta extensión me gusta mucho,puedo decir que esta extensión les servirá para los latinos 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by jopejoe1** [comment] 2021-12-23 07:14
Duplicate of #9540

**Closed** 2021-12-23 13:23 UTC
Labels: Source request
