### ISSUE TITLE
扩展插件buon dua无法下载内容

### ISSUE THREAD

**Issue by 2936747557** [tachiyomiorg/tachiyomi-extensions#12943] opened 2022-08-11 11:11 UTC
### Source information and language

buon dua 1.2.1

### Steps to reproduce

1.打开tachiyomi
2.打开buon dua扩展插件
3.下载内容

### Expected behavior

应该开始下载内容

### Actual behavior

无法下载，显示红色叹号，无论是重新开始下载还是重新开始行

### Tachiyomi version

0.13.5

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment] 2023-07-01 17:55
Duplicate of #11330

**Closed by stevenyomi** 2023-07-01 17:55 UTC
Labels: Bug
