### ISSUE TITLE
Manhwa.ae: wrong domain name (manga.ae real one)

### ISSUE THREAD

**Issue by shipoxx** [tachiyomiorg/tachiyomi-extensions#7906] opened 2021-06-28 10:52 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android 11

### Source information

مانغا العرب 1.2.7

### Steps to reproduce

![534EBF01-AB73-4D2C-BBC3-4429CEEE7AF4](https://user-images.githubusercontent.com/61906880/123625094-49d50500-d807-11eb-8adb-9dacc52a07db.jpeg)
![BAEA64D0-78D6-4EF3-992A-0505E15B40D5](https://user-images.githubusercontent.com/61906880/123625111-4e012280-d807-11eb-9fd4-88190957bdda.jpeg)

### Expected behavior

Manga.ae

### Actual behavior

Manhwa.ae

### Other details

The domain that you use here is “manhwa.ae” and this is not the domain of the main site because this domain is no longer working, according to Mary, so the problem is with the hosting. In general, the domain is a wrong site because the main domain is “manga.ae” And it works fine!

**Comment by shipoxx** [comment] 2021-06-28 10:55
https://github.com/tachiyomiorg/tachiyomi-extensions/issues/7796

**Comment by Riztard** [comment] 2021-07-05 07:07
> #7796

just comment/give more info in there then, Duplicate of #7796

**Closed** 2021-07-05 07:08 UTC
Labels: Bug
