### ISSUE TITLE
Kisslove: no chapters found

### ISSUE THREAD

**Issue by Endowpea** [tachiyomiorg/tachiyomi-extensions#17137] opened 2023-07-16 12:36 UTC
### Source information

Kisslove 1.4.10

### Source language

Japanese

### Steps to reproduce

update chapters

### Expected behavior

load chapter list

### Actual behavior

shows no chapter found

### Tachiyomi version

0.14.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment] 2023-07-20 11:32
Duplicate of #17126

**Closed by stevenyomi** 2023-07-20 11:32 UTC
Labels: Bug
