### ISSUE TITLE
Http error 429

### ISSUE THREAD

**Issue by Xanxus7898** [tachiyomiorg/tachiyomi-extensions#14875] opened 2023-01-10 03:20 UTC
### Source information and language

1st kiss 1.3.34

### Steps to reproduce

Tried refreshing my library but it displayed an error "HTTP error 429". I checked on how to resolve this and it said to raise a ticket so that a rate limit can be added to prevent IP bans in the future

### Expected behavior

My library should be updated

### Actual behavior

Error happened and can't read.

### Tachiyomi version

0.14.3

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2023-01-10 03:30
Duplicate of #14850

**Closed by alessandrojean** 2023-01-10 03:30 UTC
Labels: Bug
