### ISSUE TITLE
[Source Request] <Siyah Melek>

### ISSUE THREAD

**Issue by onursedef** [tachiyomiorg/tachiyomi-extensions#5457] opened 2021-01-16 18:51 UTC
## Source Website
- Name: Siyah Melek
- Link: https://siyahmelek.com/
- Language(s): Turkish

## Other Details
Adult Webtoons

**Comment by scb261** [comment] 2021-01-16 19:00
Duplicate of #4890

**Closed** 2021-01-17 15:31 UTC
Labels: Source Request
