### ISSUE TITLE
Request Vyvymanga change Base URL

### ISSUE THREAD

**Issue by MizukiHikari** [tachiyomiorg/tachiyomi-extensions#14643] opened 2022-12-23 13:17 UTC
### Source information and language

VyvyManga 1.3.3 (English)

### Source new URL

https://vyvymanga.net/

### Other details

Need to change base url from .com into .net

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by DchanN** [comment] 2022-12-23 14:00
Duplicate of #14632

**Closed** 2022-12-23 14:28 UTC
Labels: Bug, Domain changed
