### ISSUE TITLE
Pms scans changed domains because of internal problems

### ISSUE THREAD

**Issue by NotPageD** [tachiyomiorg/tachiyomi-extensions#13018] opened 2022-08-16 13:29 UTC
### Source information and language

PMScans 1.3.18

### Steps to reproduce

Open the extension up

### Expected behavior

Open normally

### Actual behavior

404 error

### Tachiyomi version

TachiyomiSY 1.8.5

### Android version

Android 11

### Other details

The new domain name is rackusreads.com

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by keinezeit8** [comment] 2022-09-05 07:52
duplicate of #12796

**Closed** 2022-09-05 12:29 UTC
Labels: Bug
