### ISSUE TITLE
Extension Issue

### ISSUE THREAD

**Issue by Zurimorinkashi** [tachiyomiorg/tachiyomi-extensions#9143] opened 2021-09-20 01:07 UTC
### Source information

Hiperdex 1.2.15

### Steps to reproduce

There's an issue in hiperdex.
1. When I visit the latest, there's no chapters found.
2. But when I visit the webview, it's okay. Anyone knows the issue?

### Expected behavior

So the thing is, I click the titles, so the chapters should appear, but there's none.

### Actual behavior

No chapter appeared, when I click the titles.

### Tachiyomi version

0.12.3

### Android version

Android 8.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by BulaLoaf** [comment] 2021-09-20 04:14
Same issue here on Android 11.
Replication:
1. Go to Hiperdex in Tachiyomi
2. Select a new manga that you have never selected before
3. No pages found error occurs
4. Go to webview for Hiperdex
5. Select same manga
6. Chapters show up

**Comment by FourTOne5** [comment] 2021-09-20 05:17
Duplicate of #9142

**Closed** 2021-09-20 05:18 UTC
Labels: Bug
