### ISSUE TITLE
Komik Cast: No pages found

### ISSUE THREAD

**Issue by Lopeyou** [tachiyomiorg/tachiyomi-extensions#12147] opened 2022-06-10 03:40 UTC
### Source information

KomikCast Ver 1.3.25

### Steps to reproduce

1.Pilih dan bukalah salah satu manga yang ada di ekstensi bersangkutan
2.Kemudian pencet salah satu chapter

### Expected behavior

Tidak ada lagi "Halaman tidak ditemukan," inilah yang menyebabkan ekstensi bersangkutan tidak dapat dipakai dalam artian tidak bisa baca manga di ekstensi tersebut. Semoga masalah tersebut bisa diperbaiki sehingga ekstensi bisa digunakan.

### Actual behavior

saat memilih chapter pada komik untuk dibaca selalu muncul tulisan "Halaman tidak ditemukan,"

### Tachiyomi version

0.13.4 (standard, 42eaaa4, 80, 2022-04-22T21:37Z)

### Android version

9 (SDK 28)

### Other details

Sorry i copy paste this word.but the problem is the same what i copy and paste

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-06-10 03:54
Duplicate of #9275

**Comment by Riztard** [comment] 2022-06-10 04:00
bit different issue from #9275 is for specific manga & chapter

**Comment by Lopeyou** [comment] 2022-06-10 05:07
> Duplicate of #9275

Thanks

**Comment by arispati** [comment] 2022-06-10 12:59
@Riztard,  I think the main problem is because "komikcast" changed the way to show the chapter images, now they put the images list in javascript variable, not in HTML element. This causes all comics to be unreadable.

Do you have a solution regarding this??

<img width="956" alt="Screen Shot 2022-06-10 at 19 48 21" src="https://user-images.githubusercontent.com/13604647/173068530-687bc10f-37b7-429a-b8ec-0b3425392152.png">
<img width="1022" alt="Screen Shot 2022-06-10 at 19 48 38" src="https://user-images.githubusercontent.com/13604647/173068590-0d98778a-3685-4277-9672-3f6373d5cd92.png">
<img width="1409" alt="Screen Shot 2022-06-10 at 19 48 52" src="https://user-images.githubusercontent.com/13604647/173068568-6a0761b9-e62d-4f2f-95d9-c87fc2a7e92b.png">

**Comment by algifarrr** [comment] 2022-06-10 19:27
Just wait to be fix,
 Komikcast changer their body area for image, so Extension cant read and scrape

**Closed** 2022-06-11 15:37 UTC
Labels: Bug
