### ISSUE TITLE
Lolicon

### ISSUE THREAD

**Issue by TheKingTermux** [tachiyomiorg/tachiyomi-extensions#14208] opened 2022-11-09 21:49 UTC
### Source information and language

Lolicon (EN)

### Steps to reproduce

Open lolicon source
No results found 

### Expected behavior

Showing a comic

### Actual behavior

Error results not found 

### Tachiyomi version

0.14.2

### Android version

Android 11

### Other details

Proff:
![Screenshot_2022-11-10-04-47-19-60_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/50316075/200948978-7dcf9a0f-51c5-4463-af78-da38000b73b0.jpg)
![Screenshot_2022-11-10-04-47-22-15_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/50316075/200948987-fd00a6b2-8f76-4fa2-87b7-7989ce75f18a.jpg)
![IMG_20221110_044813](https://user-images.githubusercontent.com/50316075/200948992-44d2f32f-d04b-48a1-ba10-9671aa740972.jpg)

Note : i just censored the manga because it contains NSFW

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2022-11-28 22:02
Duplicate of #12211 , feel free to post the images in that issue, but it's not really necessary

**Closed by vetleledaal** 2022-11-28 22:02 UTC
Labels: Bug, Factory source
