### ISSUE TITLE
Mangaarabic

### ISSUE THREAD

**Issue by shipoxx** [tachiyomiorg/tachiyomi-extensions#10014] opened 2021-12-06 16:17 UTC
### Source name

Mangaarabic

### Source link

https://mangarabic.com

### Language

Arabic

### Other details

I have searched the existing issues and this is a new request :)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by hani1998** [comment] 2021-12-07 03:14
A site I requested previously, I hope it will be added if you will

**Comment by loocool2** [comment] 2021-12-07 03:26
Duplicate of #9512

**Closed by loocool2** 2021-12-07 03:26 UTC
Labels: Source request
