### ISSUE TITLE
WeLoveManga: Image Loading Forever

### ISSUE THREAD

**Issue by Donnie-B** [tachiyomiorg/tachiyomi-extensions#9123] opened 2021-09-19 00:40 UTC
### Source information

WeLoveManga 1.2.7

### Steps to reproduce

1. Open chapters in any WeLoveManga

### Expected behavior

Image should load properly

### Actual behavior

The loading icon turning forever

### Tachiyomi version

0.12.2

### Android version

Android 9

### Other details

Can still properly view the image using web view.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment] 2021-09-19 04:14
Duplicate of #9120

**Closed by loocool2** 2021-09-19 04:14 UTC
Labels: Bug
