### ISSUE TITLE
Reaper Scans ID

### ISSUE THREAD

**Issue by ellodandra** [tachiyomiorg/tachiyomi-extensions#15483] opened 2023-02-26 04:48 UTC
### Source information and language

Reaper Scans ID 1.4.39

### Source new URL

https://shinigami.id/

### Other details

![Screenshot_20230226-114748](https://user-images.githubusercontent.com/81138524/221392873-7c43028d-8f80-4e38-920f-57ad0d65724e.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2023-02-26 04:58
Duplicate of #15408

**Closed by Seishirou101** 2023-02-26 04:58 UTC
Labels: Bug, Domain changed

**Comment by droidsix** [comment] 2023-02-28 04:49
will get extension update?
