### ISSUE TITLE
[Source Request] <Bilibili Comics> [API Endpoints Given]

### ISSUE THREAD

**Issue by FourTOne5** [tachiyomiorg/tachiyomi-extensions#7078] opened 2021-05-18 14:24 UTC
## Source website
- Name: Bilibili Comics
- Link: https://www.bilibilicomics.com/
- Language(s): en

## Other details
You can find basic API endpoint example (in python) in [FourTOne5/bilibilicomics-scraper](https://github.com/FourTOne5/bilibilicomics-scraper) you can find more endpoints after a little research.

**Comment by Silvermane06** [comment] 2021-05-19 00:58
Seems like this is a duplicate of #6686 , though it does give a link for endpoint which the other didn't. 

I suggest that you put that as a comment as well in the other topic in case this one gets closed for being a duplicate.

**Closed** 2021-05-19 12:02 UTC
Labels: Source Request
