### ISSUE TITLE
Downloaded chapter unreadable, puzzled

### ISSUE THREAD

**Issue by Kiwizpatate** [tachiyomiorg/tachiyomi-extensions#10179] opened 2021-12-20 22:38 UTC
### Source information

Japscan.ws

### Steps to reproduce

Hi, thx for the app.
For this source some downloaded chapters are unreadable. 
For exemple, all chapters from BLUE GIANT SUPREME
https://www.japscan.ws/manga/blue-giant-supreme/

the beginning of BLUE GIANT is working fine, but not the end

The beginning of ushijima yamikin is also working fine, but not the end again.

Are they encoded or something?

1. Chapter download is fine.
2. Open chapter ok
3. Each images of the chapter are puzzled. Impossible to read.
4. Checking Online chapters from the website are readable. 

### Expected behavior

Readable chapter

### Actual behavior

Unreadable chapter

### Tachiyomi version

Version from last summer with problem. Updated today with problem

### Android version

Emui 11 huawei

### Other details

Online chapters from the website are readable. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2021-12-20 22:54
Duplicate of #9374

**Closed by arkon** 2021-12-20 22:54 UTC
Labels: Bug

**Comment by Kiwizpatate** [comment] 2021-12-20 23:14
Thank you. Scrambled was the word I were looking for. Can't find any topic
with puzzled or unreadable. Thank you.

Do you have any idea how to fix that?
