### ISSUE TITLE
Uzaymanga no results found

### ISSUE THREAD

**Issue by kaankapar** [tachiyomiorg/tachiyomi-extensions#19328] opened 2023-12-15 19:53 UTC
### Source information

Uzaymanga 1.4.33

### Source language

Turkish

### Steps to reproduce

1.browse
2.sources
3.uzaymanga 
4.it does not show the manhwa titles it has translated even thought the web view shows that the site works

### Expected behavior

sjould display a list of manhwas it has translated

### Actual behavior

![Screenshot_2023-12-15-22-52-15-975_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/145402173/28f6289f-abe3-4a4b-9c83-31bcd7cb51e0)

### Tachiyomi version

0.14.7

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2023-12-15 20:22
Duplicate of #19280

**Closed by vetleledaal** 2023-12-15 20:22 UTC
Labels: Bug
