### ISSUE TITLE
Baozimh.org image couldnt be loaded

### ISSUE THREAD

**Issue by samanta-widjaja** [tachiyomiorg/tachiyomi-extensions#15228] opened 2023-02-04 08:47 UTC
### Source information and language

Baozhimh.org 1.3.28

### Steps to reproduce

1. Update library
2. Title 病娇暴君改拿绿茶剧本 chapter 173 is found and download
3. In notification http error 403
4. Open in tachiyomi webview is fine and  show up
5. View through app show error image couldnt be loaded

### Expected behavior

Image should be show and can be download

### Actual behavior

Download error and image couldnt be shown

### Tachiyomi version

0.14.3

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment] 2023-08-07 16:29
Duplicate of #15228

**Closed by stevenyomi** 2023-08-07 16:29 UTC
Labels: Bug
