### ISSUE TITLE
mangaswat: no pages found

### ISSUE THREAD

**Issue by Mohamed-Ahmed-64597** [tachiyomiorg/tachiyomi-extensions#12053] opened 2022-06-03 08:10 UTC
### Source information

MangaSwat 1.2.20

### Steps to reproduce

1-click chapter and wait for pages to load

### Expected behavior

The pages of the chapter should load for reading.

### Actual behavior

Jumps back to chapter list with a notif. saying that there were no pages found.

### Tachiyomi version

0.13.4

### Android version

Android 11

### Other details

I have already cleared the cache and cookies and everything. I also tried to load up on webview and it works perfectly find and even loads up the chapters there. This happens with most of the titles from mangaswat that I could find saved in my library. It was also working fine right before the issue started (i.e I was finishing a chapter and loading a new one when it occurred).

![image](https://user-images.githubusercontent.com/52131683/171814999-24c268f1-2fff-443b-84a1-1edf687b7cb8.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2022-06-03 08:29
Duplicate of #10318

**Closed by Seishirou101** 2022-06-03 08:29 UTC
Labels: Bug
