### ISSUE TITLE
 Allporncomic failed to bypass cloud flare 

### ISSUE THREAD

**Issue by Mtkmanjaro** [tachiyomiorg/tachiyomi-extensions#12118] opened 2022-06-07 22:11 UTC
### Source information

Allporncomic 1.3.21

### Steps to reproduce

open allporncimic 
after some time loading pop-up a message saying failed to bypass cloud flare

### Expected behavior

load the content 

### Actual behavior

unable to read anything 

### Tachiyomi version

tachiyomi 0.13.4

### Android version

12

### Other details

even in web View mode the cloud flare is stuck in a loop

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-06-07 23:12
Duplicate of #9318

**Closed by alessandrojean** 2022-06-07 23:12 UTC
Labels: Bug
