### ISSUE TITLE
Manhuafast: Late updates on tachi latest panel

### ISSUE THREAD

**Issue by uniqueunique7x7** [tachiyomiorg/tachiyomi-extensions#16726] opened 2023-06-12 03:33 UTC
### Source information

Manhuafast 1.4.31

### Source language

English 

### Steps to reproduce

1.Browse
2.Latest

### Expected behavior

Up to date with webview latest updates

### Actual behavior

12 13 hour late update in tachi compared to webview

### Tachiyomi version

1.4.31

### Android version

13

### Other details

Mangas will update on global refresh just not up to date with webview .. 12 13 hour late in latest panel of tachiyomi

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-06-23 02:16
Duplicate of #16296

**Closed by arkon** 2023-06-23 02:16 UTC
Labels: Bug
