### ISSUE TITLE
mangakio changed their URL

### ISSUE THREAD

**Issue by euijoonyeo** [tachiyomiorg/tachiyomi-extensions#15447] opened 2023-02-22 15:28 UTC
### Source information and language

"mangakio 1.4.29 (English)"

### Source new URL

https://mangakio.me/

### Other details

Mangakio changes URL so many times 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2023-02-22 15:31
Duplicate of #15102

**Closed by vetleledaal** 2023-02-22 15:31 UTC
Labels: Bug, Domain changed
