### ISSUE TITLE
[Bug] <tcbscans>: <no results found>

### ISSUE THREAD

**Issue by Titus30** [tachiyomiorg/tachiyomi-extensions#6998] opened 2021-05-13 06:49 UTC
## Device information
- Tachiyomi version: App version: 1.6.2 (standard, e500d0beb, 17)
Preview build: 370
Android version: 11 (SDK 30)

## Source information
- Name: TCB scans
- Extension version: 1.2.3

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
Describe what should have happened
Show content

### Actual behavior
Describe what happens instead
No results found

**Comment by jopejoe1** [comment] 2021-05-13 07:57
Duplicate of #6869

**Closed** 2021-05-13 10:38 UTC
Labels: bug
