### ISSUE TITLE
Mangahub weird chapter bug

### ISSUE THREAD

**Issue by SwiftGrim** [tachiyomiorg/tachiyomi-extensions#15323] opened 2023-02-12 02:17 UTC
### Source information and language

Mangahub

### Steps to reproduce

Chapter are showing over 10000 chapters

### Expected behavior

Shows perfect chapters of each webtoons

### Actual behavior

Mixed chapter with 10000 included 

### Tachiyomi version

0.14.4

### Android version

Android 10

### Other details

![Screenshot_20230212_061330_eu kanade tachiyomi](https://user-images.githubusercontent.com/100683056/218289319-6e45ddb7-0393-4c58-823d-4a7d15bd120b.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-02-12 02:19
Duplicate of #15200

**Closed by arkon** 2023-02-12 02:19 UTC
Labels: Bug
