### ISSUE TITLE
Yaoi Manga Online: No Pages Found 

### ISSUE THREAD

**Issue by Yazhkx** [tachiyomiorg/tachiyomi-extensions#11297] opened 2022-04-01 18:01 UTC
### Source information

Yaoi Manga Online 1.2.2

### Steps to reproduce

1. Click Browse
2. Select Yaoi Manga Online under the Sources list
3. Search for any manga/manhua/manhwa

### Expected behavior

Once your chosen manga/hwa/hua has been selected, the list of available chapters should appear at the bottom of the page

### Actual behavior

Instead of a list there appears only one chapter named 'Chapter,' and upon clicking it, it would only show that there are 'No Pages Found'

### Tachiyomi version

Stable 0.13.1

### Android version

EMUI 12

### Other details

Chapter are available and readable on the main website but not on the extension

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-04-01 18:05
Duplicate of #11175

**Closed by alessandrojean** 2022-04-01 18:05 UTC
Labels: Bug
