### ISSUE TITLE
Zerobyw changed url

### ISSUE THREAD

**Issue by Anifan2021** [tachiyomiorg/tachiyomi-extensions#15424] opened 2023-02-21 00:49 UTC
### Source information and language

Zero搬运网 Chinese

### Source new URL

http://www.zerobyw1060.com/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2023-02-21 20:14
Duplicate of #15134

**Closed by vetleledaal** 2023-02-21 20:14 UTC
Labels: Bug, Domain changed
