### ISSUE TITLE
API token issue in mangahub

### ISSUE THREAD

**Issue by krish0117** [tachiyomiorg/tachiyomi-extensions#13169] opened 2022-08-24 17:17 UTC
### Source information and language

Mangahub 1.3.20

### Steps to reproduce

A manhwa or manhua after some chapters it says API token issue 

### Expected behavior

Normally is shows the particular chapter 

### Actual behavior

But it says API token issue 

### Tachiyomi version

0.13.6

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2022-08-24 17:41
Duplicate of #13144

**Closed by Seishirou101** 2022-08-24 17:41 UTC
Labels: Bug
