### ISSUE TITLE
MangaSusu error

### ISSUE THREAD

**Issue by Satriouz** [tachiyomiorg/tachiyomi-extensions#11380] opened 2022-04-08 12:11 UTC
### Source information

1.2.13

### Steps to reproduce

1. When I click on Extension, it says : 
194.233.87.209: NXDOMAIN
2. And I can't see anything and the web can load in the webview version

### Expected behavior

Yes as usual, please fix this problem 🙏

### Actual behavior

I also don't really understand maybe they changed the domain or something

### Tachiyomi version

0.13.1

### Android version

Android 10 

### Other details

MangaSusu can't open and it says 194.233.87.209: NXDOMAIN. Domain MangaSusu now : https://www.mangasusu.co.in
![Screenshot_20220408-190706](https://user-images.githubusercontent.com/76560973/162432934-f627a777-df63-4964-bc77-8947c1a75454.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-04-08 14:14
Duplicate of #11019

**Closed by alessandrojean** 2022-04-08 14:14 UTC
Labels: Bug
