### ISSUE TITLE
[Bug] <tumangaonlien>: <http error 403>

### ISSUE THREAD

**Issue by slendcraft** [tachiyomiorg/tachiyomi-extensions#7044] opened 2021-05-16 04:44 UTC
## Device information
- Tachiyomi version: 0.10.12
- Android version: 6

## Source information
- Name: tumangaonline
- Extension version: tumangaonline

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
Load the tumangaonline extension

### Actual behavior
Http error 403

## Other details
N-I alrady waited like 2 days but it dosent load

**Comment by alessandrojean** [comment] 2021-05-18 16:41
Seems to be a duplicate of #6888.

**Closed by alessandrojean** 2021-05-18 16:41 UTC
Labels: bug
