### ISSUE TITLE
Meus Mangás: extension error

### ISSUE THREAD

**Issue by Orionv1** [tachiyomiorg/tachiyomi-extensions#14258] opened 2022-11-14 14:43 UTC
### Source information and language

Meus Mangás 1.3.9 Português(brasil

### Steps to reproduce

Maybe need an extension update

### Expected behavior

You should open the chapters for reading

### Actual behavior

1. Does not load recent mangas
 2. Does not load chapters
 3. Extension does not work in general

### Tachiyomi version

0.14.2

### Android version

Android 9

### Other details

Maybe need an extension update

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-11-14 14:58
Duplicate of #14218

**Closed by alessandrojean** 2022-11-14 14:58 UTC
Labels: Bug
