### ISSUE TITLE
MG Komik: chapter images do not load

### ISSUE THREAD

**Issue by Mozzaru** [tachiyomiorg/tachiyomi-extensions#14638] opened 2022-12-22 17:41 UTC
### Source information and language

Mg komik 1.3.28

### Steps to reproduce

I want to read, then it keeps loading and doesn't open the image, then it's like in the video, the internet is normal and in other extensions it runs smoothly
Source : https://mgkomik.com/

### Expected behavior

I want to read, then it keeps loading and doesn't open the image, then it's like in the video, the internet is normal and in other extensions it runs smoothly

### Actual behavior

I want to read, then it keeps loading and doesn't open the image, then it's like in the video, the internet is normal and in other extensions it runs smoothly

### Tachiyomi version

0.14.2

### Android version

Android 11

### Other details

https://user-images.githubusercontent.com/100791931/209193889-0ce1b850-36ba-45f2-96ac-bf52d9f0876d.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2022-12-23 01:56
/edit-title "MG Komik: chapter images do not load"

**Comment by Riztard** [comment] 2022-12-23 12:24
duplicate of #10188

**Closed by Riztard** 2022-12-23 12:24 UTC
Labels: Bug, Factory source

**Comment by Mozzaru** [comment] 2022-12-23 12:39
@Riztard will it be fixed?

**Comment by Riztard** [comment] 2022-12-23 13:15
¯\_(ツ)_/¯

**Comment by Mozzaru** [comment] 2022-12-23 17:16
@TheKingTermux Can you fix the mgkomik extension, bro? for other devs thanks

**Comment by TheKingTermux** [comment] 2022-12-23 17:31
> @TheKingTermux sorry 🙏
> Can you fix the mgkomik extension, bro?
>  for other devs thanks

Well
This error is over 1 years back
And my answer is I can't do that 
Because my laptop is being repaired right now

Fin (⁠・⁠–⁠・⁠;⁠)⁠ゞ

**Comment by Mozzaru** [comment] 2022-12-23 17:33
@TheKingTermux thanks 🙏

**Comment by Mozzaru** [comment] 2022-12-23 17:35
@TheKingTermux If you use Android GitHub, what should be edited? Fork the extension, hehe approximately

**Comment by TheKingTermux** [comment] 2022-12-23 17:36
> @TheKingTermux thanks 🙏

Thanks for your understanding

**Comment by TheKingTermux** [comment] 2022-12-23 17:40
> @TheKingTermux If you use Android GitHub, what should be edited? Fork the extension, hehe approximately

If you want to fork ekstension repo, you just use chrome and uses desktop mode

**Comment by Mozzaru** [comment] 2022-12-23 17:47
@TheKingTermux then what needs to be edited?
