### ISSUE TITLE
[Source Request] <Giant in the Playground>

### ISSUE THREAD

**Issue by packersjlong** [tachiyomiorg/tachiyomi-extensions#5330] opened 2021-01-06 02:19 UTC
https://www.giantitp.com/comics/oots.html
- Name: Order of the Stick
- Link: [Giant in the Playground](https://www.giantitp.com/comics/oots.html)
- Language(s): English

## Other Details
?

**Comment by scb261** [comment] 2021-01-06 09:41
Duplicate of #2885

**Closed** 2021-01-06 13:07 UTC
Labels: Source Request
