### ISSUE TITLE
Java.text.ParseException 

### ISSUE THREAD

**Issue by bman-95** [tachiyomiorg/tachiyomi-extensions#15954] opened 2023-04-03 19:00 UTC
### Source information

ManhwaClub 1.4.5

### Source language

English

### Steps to reproduce

1. Enter source.
2. Check Latest.
3. Enter any manhwa.
4. Search for  updates.

### Expected behavior

The chapters should be updated.

### Actual behavior

Throws java error - > java.text.ParseException: Unparsable date: "2 hours ago".

### Tachiyomi version

Stable 1.9.0 tachiomySY

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment] 2023-04-03 20:14
Duplicate of #13237

**Closed** 2023-04-03 20:14 UTC
Labels: Bug, Duplicate

**Comment by bman-95** [comment] 2023-04-03 20:33
Will this be fixed?
