### ISSUE TITLE
Hentaidexy still not work

### ISSUE THREAD

**Issue by BLACKxSUN** [tachiyomiorg/tachiyomi-extensions#14511] opened 2022-12-10 09:31 UTC
### Source information and language

Hentaidexy 1.3.29 English

### Steps to reproduce

1. Open tachiyomi
2. Open hentaidexy
3. 
![Screenshot_20221209-190955_Tachiyomi](https://user-images.githubusercontent.com/93000786/206843326-dd8138b3-2408-4097-bfb3-248884d0bb95.jpg)

### Expected behavior

Nothing

### Actual behavior

Nothing

### Tachiyomi version

0.14.2

### Android version

Android 9

### Other details

After the update that came yesterday nothing change

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by BLACKxSUN** [comment] 2023-01-17 14:54
Still no one can fix it?

**Comment by stevenyomi** [comment] 2023-01-30 11:00
Duplicate of #15167

**Closed by stevenyomi** 2023-01-30 11:00 UTC
Labels: Bug, Factory source
