### ISSUE TITLE
مانجا ليك Failed to bypass Cloudflare

### ISSUE THREAD

**Issue by BLACKxSUN** [tachiyomiorg/tachiyomi-extensions#11395] opened 2022-04-08 22:06 UTC
### Source information

1.2.21 مانجا ليك

### Steps to reproduce

1.go to "مانجا ليك" source
2.open any manga
3.open any chapter
4. Show the issue "Failed to bypass Cloudflare"

### Expected behavior

Should open the chapters

### Actual behavior

The chapters don't work

### Tachiyomi version

0.13.1

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-04-08 22:08
Duplicate of #11366

**Closed by alessandrojean** 2022-04-08 22:08 UTC
Labels: Bug

**Comment by BLACKxSUN** [comment] 2022-04-08 22:20
> Duplicate of #11366

Why you close it there's nothing in #11366
