### ISSUE TITLE
Ghost Fansub

### ISSUE THREAD

**Issue by Kitsunera** [tachiyomiorg/tachiyomi-extensions#17963] opened 2023-09-15 18:49 UTC
### Source name

Ghost Fansub

### Source link

https://ghostfansub.online/

### Source language

Turkish 

### Other details

18+/NSFW= YES

### Acknowledgements

- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension is not on [the removed sources list](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/REMOVED_SOURCES.md).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2023-09-15 19:19
Uses Madara theme
```kt
SimpleDateFormat("MMM d, yyyy", Locale("tr"))
```

**Comment by scb261** [comment] 2023-09-15 19:42
Duplicate of #16032

For some reason the bot used wrong issue number

**Closed** 2023-09-15 19:42 UTC
Labels: Source request, do-not-autoclose, Duplicate
