### ISSUE TITLE
Copymanga extension doesn't work

### ISSUE THREAD

**Issue by txyyh** [tachiyomiorg/tachiyomi-extensions#8938] opened 2021-09-02 14:53 UTC
### Source information

Copymanga v1.2.11

### Steps to reproduce

Search new manga, Then click into the details page.
Or
Reading any manga.

### Expected behavior

It should works fine, can get the details of a manga,can show the pictures.

### Actual behavior

It simply doesn't work,What I get shows below
![Screenshot_2021-09-02-22-05-31-106_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/41893946/131865168-c4831262-1588-4be8-af21-875034c3ebb2.jpg)
![Screenshot_2021-09-02-22-05-55-693_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/41893946/131865183-3fbf469e-582c-42f4-8d33-8c5f05ad7b14.jpg)

PS: the manga showed in first picture have added to bookshelf before this extension break.

### Tachiyomi version

Tachiyomi 0.12.1 TachiyomiJ2K 1.2.1

### Android version

MIUI China Stable 12.0.11.0 based on Android 10

### Other details

I have saved a TachiyomiJ2K drmp crash log.
If it's necessary, please let me know.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment] 2021-09-02 14:55
> I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open issue.

Duplicate of #8934

**Closed by curche** 2021-09-02 14:55 UTC
Labels: Bug
