### ISSUE TITLE
The Image Couldn't be Loaded

### ISSUE THREAD

**Issue by Hnsu8** [tachiyomiorg/tachiyomi-extensions#12779] opened 2022-07-29 10:14 UTC
### Source information and language

Mangahub 1.3.13 English

### Steps to reproduce

I just open it or trying to read the uodate but it show that it cant be loaded

### Expected behavior

This should happen to Loaded 

### Actual behavior

Of being loaded

### Tachiyomi version

1.8.3

### Android version

11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment] 2022-07-29 10:46
>  I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open issue.

Duplicate of https://github.com/tachiyomiorg/tachiyomi-extensions/issues/12773

**Closed by curche** 2022-07-29 10:46 UTC
Labels: Bug
