### ISSUE TITLE
Broken Extension

### ISSUE THREAD

**Issue by ellodandra** [tachiyomiorg/tachiyomi-extensions#10245] opened 2021-12-27 06:52 UTC
### Source information

World Romance Translation 1.2.16

### Steps to reproduce

1. Error 404

### Expected behavior

Fix the broken extension

### Actual behavior

When i open this extension i cant see the manga list because Error 404 and then i try open in webview it work but when i open again in tachiyomi it doesn't work

### Tachiyomi version

0.12.3

### Android version

Android 7.1.1

### Other details

![Screenshot_2021-12-27-13-49-19-96](https://user-images.githubusercontent.com/81138524/147443441-a356acab-1856-4fba-b3f9-5c354102901c.png)
![Screenshot_2021-12-27-13-19-46-52](https://user-images.githubusercontent.com/81138524/147443463-a6cc23ff-0c5e-499c-9ddf-14859f306088.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment] 2021-12-27 09:09
Duplicate of #10216
ngapa bikin lagi bambang

**Closed by Riztard** 2021-12-27 09:09 UTC
Labels: Bug
