### ISSUE TITLE
Readcomiconline

### ISSUE THREAD

**Issue by ed0fl3da** [tachiyomiorg/tachiyomi-extensions#11227] opened 2022-03-23 09:45 UTC
### Source information

Readcomiconline

### Steps to reproduce

Enter readcomiconline

### Expected behavior

You can read comics

### Actual behavior

There aren't comics

### Tachiyomi version

Latest

### Android version

Latest

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by sandroj23** [comment] 2022-03-23 10:10
Have exactly the same problem, says "no results found"

**Comment by curche** [comment] 2022-03-23 11:05
> I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open issue

Duplicate of #11141

**Closed by curche** 2022-03-23 11:05 UTC
Labels: Bug
