### ISSUE TITLE
Mangago.me

### ISSUE THREAD

**Issue by Delmarcop52** [tachiyomiorg/tachiyomi-extensions#14984] opened 2023-01-16 22:27 UTC
### Source information and language

Mangago 1.3.8

### Steps to reproduce

I has to search and the to make the cover images of each manga 

### Expected behavior

The cover images of the manga come up automatically in mangago extension 

### Actual behavior

I have to make the cover images pop up in the extension myself 

### Tachiyomi version

0.14.3

### Android version

Motorola 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by zbue** [comment] 2023-01-16 23:27
Duplicate of #14920

**Closed** 2023-01-16 23:56 UTC
Labels: Bug
