### ISSUE TITLE
Copy manga error message

### ISSUE THREAD

**Issue by BillyChen8051** [tachiyomiorg/tachiyomi-extensions#9131] opened 2021-09-19 06:14 UTC
### Source information

Copymanga 1.2.15

### Steps to reproduce

1.update manga database

### Expected behavior

Success updating the manga database

### Actual behavior

Error message "Missing argument"

### Tachiyomi version

0.12.2

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment] 2021-09-19 06:20
> I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open issue.

Duplicate of #9114

**Closed by curche** 2021-09-19 06:20 UTC
Labels: Bug

**Comment by whghjyh** [comment] 2021-09-19 08:21
![_Z{VI)FKZ{YJ}04I`I1`P6L](https://user-images.githubusercontent.com/66399190/133920544-69446770-1fa3-4733-a77f-4defa3576e96.jpg)
What this picture says is "Please don't get the link of copymanga and remove the extension of copy".
