### ISSUE TITLE
[Bug] <ManhuaScan>: <manga saved from this source doesn’t open>

### ISSUE THREAD

**Issue by ladysoftlighting** [tachiyomiorg/tachiyomi-extensions#7029] opened 2021-05-15 06:10 UTC
## Device information
- Tachiyomi version: 0.10.12 (standard, 6aff438, 59)
- Android version: 11 (SDK 30)

## Source information
- Name: ManhuaScan
- Extension version: 1.2.4

## Steps to reproduce
1. Open manga from the source in library
2. Manga should open

### Expected behavior
The manga from this source, which has been saved in the library, should open

### Actual behavior
There is a error message saying "No pages found" when I open manga from this source

## Other details
The Webview works fine. I can read manga when I go to the Webview, but the manga does not work in the app. I have tried troubleshooting and even unistalled and reinstalled the extension, but it doesn't work.

**Comment by h-hyuuga** [comment] 2021-05-15 11:10
Duplicate of #7011

**Closed** 2021-05-15 12:32 UTC
Labels: bug
