### ISSUE TITLE
baizimanhua: replace cdn host

### ISSUE THREAD

**Issue by rhjdvsgsgks** [tachiyomiorg/tachiyomi-extensions#17402] opened 2023-08-05 21:35 UTC
### Source information

1.4.20

### Source language

chinese

### Steps to reproduce

open any manga

### Expected behavior

load image succeed

### Actual behavior

timeout when getting img

### Tachiyomi version

1.14.6

### Android version

android 11

### Other details

in the recent days. baozimanhua enabled a new img cdn : s?.baozimh.com . but they didnt update the url in the html. instead, they use a obfuscated js to replace old img cdn host s?.baozicdn.com to s?.baozimh.com .

now we have few options:
1. decrypted the js and replace the old host by the new host from js
2. replace old host with a fixed value s?.baozimh.com . and add a option to override this value
3. grab the img url from a headless webview which have js enabled

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment] 2023-08-05 21:43
Duplicate of #17322

**Closed by stevenyomi** 2023-08-05 21:43 UTC
Labels: Bug
