### ISSUE TITLE
"Failed to bypass cloudflare" issue 

### ISSUE THREAD

**Issue by Key-explanation** [tachiyomiorg/tachiyomi-extensions#13117] opened 2022-08-21 01:33 UTC
### Source information and language

NHentai 1.3.35

### Steps to reproduce

.

### Expected behavior

The library should appear when I click on the source

### Actual behavior

Instead, it says "Failed to bypass cloudflare"

### Tachiyomi version

0.13.6

### Android version

Android 11 

### Other details

Here is a screenshot:
![Screenshot_2022_0821_062252](https://user-images.githubusercontent.com/103259523/185771618-54ff923d-2c7b-48fe-82d1-ca18890776aa.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by raziel100** [comment] 2022-08-21 03:05
This is a duplicated of issue #12784 and a workaround from this issue is there as well

**Comment by TheKingTermux** [comment] 2022-08-21 10:16
Duplicate of #12784

**Closed** 2022-08-21 13:43 UTC
Labels: Bug
