### ISSUE TITLE
[Bug] Jmana doesn't load: chapter lists load, but pages in chapters don't

### ISSUE THREAD

**Issue by handy-cap** [tachiyomiorg/tachiyomi-extensions#5208] opened 2020-12-20 04:37 UTC
## Device information
- Tachiyomi version: 0.10.7 
- Android version: 10

## Source information
- Name: JMana
- Extension version: 1.2.11

## Steps to reproduce
1. Open any manga using the Latest(or any other page) button
2. Click into any chapter of that manga

### Expected behavior
Pages should be loaded with their images

### Actual behavior
Nothing loads, and the 'retry' button appears

## Other details
I am using the URL override to
https://jmana05.jmana2.net
, which is used by jmana at time of writing.

I have used jmana before, about 6 months ago, without this happening.

(Suggestion: I dont know how the image loading process works, but maybe it has something to do with the odd URLs of manga chapters?
Manga: https://jmana05.jmana2.net/book?bookname=XX
Chapter: https://jmana05.jmana2.net/bookdetail?bookname=XX&bookdetail=YY
)

**Comment by Riztard** [comment] 2021-01-04 07:57
duplicate of #4344

**Comment by handy-cap** [comment] 2021-01-04 08:16
Dup

**Closed** 2021-01-04 08:16 UTC
Labels: bug
