### ISSUE TITLE
[Bug] <Kuaikanmanhua>: <unable to view in app>

### ISSUE THREAD

**Issue by tsunaliew** [tachiyomiorg/tachiyomi-extensions#4554] opened 2020-10-08 06:49 UTC
## Device information
- Tachiyomi version: Stable 0.10.5
- Android version: Android Version 10

## Source information
- Name: Kuaikanmanhua
- Extension version: 1.2.2

## Steps to reproduce
Opening a chapter

### Expected behavior
Chapter opens

### Actual behavior
Black page with retry button

## Other details
How it appear on the app:

![Screenshot_20201008-142655_Tachiyomi](https://user-images.githubusercontent.com/8689637/95424525-56fa4d00-0975-11eb-800e-4c0f2378a593.jpg)
![Screenshot_20201008-142921_Tachiyomi](https://user-images.githubusercontent.com/8689637/95424526-58c41080-0975-11eb-911c-8bdd3a075cf7.jpg)

How it appear on the WebView:

![Screenshot_20201008-142642_Chrome](https://user-images.githubusercontent.com/8689637/95424562-64173c00-0975-11eb-990a-70730e9438c6.jpg)
![Screenshot_20201008-144051_Tachiyomi](https://user-images.githubusercontent.com/8689637/95424568-65e0ff80-0975-11eb-8f90-39a9dc58934e.jpg)

**Comment by scb261** [comment] 2021-02-12 17:11
Duplicate of #3335

**Closed by scb261** 2021-02-12 17:11 UTC
Labels: bug
