### ISSUE TITLE
you are detected using a party application in web Shinigami Indonesian

### ISSUE THREAD

**Issue by anarchysense** [tachiyomiorg/tachiyomi-extensions#18548] opened 2023-10-14 08:08 UTC
### Source information

Shinigami 1.4.34

### Source language

Indonesia

### Steps to reproduce

Sorry, you have been blocked
You are unable to access shinigami.

-Your Client Bad
-Cloudflare Working

Why have I been blocked?

When you are detected using a party application, if you are not using a third party application, please confirm with the site administrator

### Expected behavior

Tachiyomi should be able to access the Shinigami web

### Actual behavior

but tachiyomi is blocked from accessing the shinigami web

### Tachiyomi version

0.14.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by RoSiCyBeR** [comment] 2023-10-14 10:30
The user agent maybe get blocked

**Comment by TheKingTermux** [comment] 2023-10-16 01:29
Duplicate of #18506

**Closed** 2023-10-16 02:05 UTC
Labels: Bug
