### ISSUE TITLE
[Bug] <Source Name>: <short description>

### ISSUE THREAD

**Issue by RickCypher** [tachiyomiorg/tachiyomi-extensions#7467] opened 2021-06-04 20:22 UTC
**Device information**
Tachiyomi version: 0.10.12
Android version: 10

**Source information**
Name: Tsuki Mangás
Extension version: 1.2.16

**Problem:**
HTTP Error 403 and Error 1020 in webview

**Comment by alessandrojean** [comment] 2021-06-04 20:23
Duplicate of #7421.

Por favor, leia minha resposta neste outro issue.

**Closed by alessandrojean** 2021-06-04 20:23 UTC
Labels: bug

**Comment by RickCypher** [comment] 2021-06-04 20:27
Nem tinha reparado, obrigado!
