### ISSUE TITLE
[Bug] Mangadex: incorrect language

### ISSUE THREAD

**Issue by plW0lf** [tachiyomiorg/tachiyomi-extensions#7181] opened 2021-05-22 15:55 UTC
## Device information
- Tachiyomi version: 0.10.12
- Android version: 11

## Source information
- Name: Mangadex
- Extension version: 1.2.113

## Steps to reproduce
1. Make sure to have only english language enabled in extension
2. Open one of the manga from Mangadex source (e.g. Fairy Tale)
3. Check titles of chapter

### Expected behavior
Listed chapters should be in only one language (english)

### Actual behavior
Listed chapters are in multiple languages

**Comment by arkon** [comment] 2021-05-22 15:55
Duplicate of #7179; update your extension.

**Comment by Riztard** [comment] 2021-05-22 15:56
If you were running into the issue where MangaDex's recent API update caused chapters of all languages to be shown for manga, update your extension, and then update your library again to remove the chapters

**Closed by arkon** 2021-05-22 15:55 UTC
Labels: bug
