### ISSUE TITLE
Komikindo.id  | The old domain needs improvement to be Komikindo.pro

### ISSUE THREAD

**Issue by cyberhome404** [tachiyomiorg/tachiyomi-extensions#15584] opened 2023-03-04 09:59 UTC
### Source information and language

KomikindoID 1.4.8 (Indonesia)

### Source new URL

https://komikindo.pro/

### Other details

![Screenshot_2023-03-04-16-51-28-138_eu kanade tachiyomi](https://user-images.githubusercontent.com/46006177/222893650-fbe331b5-573d-44da-89d7-783c1c7db626.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2023-03-06 20:38
Duplicate of #15425

**Closed by Seishirou101** 2023-03-06 20:38 UTC
Labels: Bug, Domain changed
