### ISSUE TITLE
HentaiHere title always showing Home

### ISSUE THREAD

**Issue by PahleviEins** [tachiyomiorg/tachiyomi-extensions#14340] opened 2022-11-22 03:40 UTC
### Source information and language

HentaiHere English 1.3.3

### Steps to reproduce

First Step : Normal when opening the extension
Second Step : when selecting the title, the page always be refreshed
Issue : after refresh, the title always shows "Home"

### Expected behavior

After selecting the title, the name of the manga should be showing the same when opening.

### Actual behavior

The title always change to "Home", even after restarting the application.

### Tachiyomi version

0.14.2

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2022-11-28 22:12
Duplicate of #14196

**Closed by vetleledaal** 2022-11-28 22:12 UTC
Labels: Bug
