### ISSUE TITLE
[Bug] <Komikcast>: <Image not Found>

### ISSUE THREAD

**Issue by adisptr13** [tachiyomiorg/tachiyomi-extensions#7297] opened 2021-05-30 03:24 UTC
## Device information
- Tachiyomi version: 0.10.2
- Android version: 11

## Source information
- Name: Komikcast
- Extension version: 1.2.9

## Steps to reproduce
1. The image didn't loaded

### Expected behavior
Image was always retry 

### Actual behavior
After an update to 1.2.9 the image cover was fixed, but can't read the manhwa/manga the image was always retry

## Other details
![Screenshot_20210530-101858_Tachiyomi](https://user-images.githubusercontent.com/84905600/120090998-18e2b100-c131-11eb-9531-92257102d3a3.jpg)

**Comment by Riztard** [comment] 2021-05-30 05:17
Duplicate of #7296

**Closed by Riztard** 2021-05-30 05:17 UTC
Labels: bug
