### ISSUE TITLE
[Bug] <ManhuaScans>: <Page not found>

### ISSUE THREAD

**Issue by Akazotik** [tachiyomiorg/tachiyomi-extensions#7011] opened 2021-05-13 21:55 UTC
---

## Device information
- Tachiyomi version: r3354
- Android version: 10

## Source information
- Name: ManhuaScans
- Extension version: 1.2.4

## Steps to reproduce
1. Open any manga
2. Open any chapter

### Expected behavior
Open or download chapters

### Actual behavior
Page not found

## Other details
![Screenshot_2021-05-14-00-55-42-082_eu.kanade.tachiyomi.debug.jpg](https://user-images.githubusercontent.com/39062952/118192655-215b9c00-b44f-11eb-8046-2dd690c2ec73.jpg)

**Comment by smanunciacion** [comment] 2021-05-13 22:32
![2A0F5C18-A90A-47B7-9D5E-DD965B7049D1](https://user-images.githubusercontent.com/84158024/118195506-30ffc400-b400-11eb-9b15-b281aff2c39a.jpeg)

Similar issue. Web preview is fine and the updates, do update. However, when resuming reading, “No Page Found”.

**Comment by h-hyuuga** [comment] 2021-05-13 22:32
Duplicate of #7005 ?

**Comment by arkon** [comment] 2021-05-13 22:50
I'll keep this one open since it at least spelled the source name correctly.

**Comment by akmalmeaw** [comment] 2021-05-14 09:54
What happen to this source?? Its the best source ever. Hope people can fix this

**Comment by CrepeTF** [comment] 2021-05-14 11:03
Wait for someone to come along to fix it, no ETA

**Comment by rururubie** [comment] 2021-05-14 15:17
does anyone knows how to fix it???

**Closed** 2021-05-16 17:35 UTC
Labels: bug
