### ISSUE TITLE
Extensión no funciona

### ISSUE THREAD

**Issue by DarkDissaster** [tachiyomiorg/tachiyomi-extensions#10531] opened 2022-01-21 04:22 UTC
### Source information

Dragontranslation 1.2.19

### Steps to reproduce

1. Abro La aplicación
2. Intento leer o descargar un manga de dicha extensión 

### Expected behavior

Espero poder leer o descargar los mangas de dicha extensión 

### Actual behavior

Los mangas no cargan y no están enumerados tampoco hay como descargarlos

### Tachiyomi version

0.12.3

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-01-21 04:34
Duplicate of #10435

**Closed by alessandrojean** 2022-01-21 04:34 UTC
Labels: Bug
