### ISSUE TITLE
Lezhin Comics

### ISSUE THREAD

**Issue by mazyuin** [tachiyomiorg/tachiyomi-extensions#9741] opened 2021-11-05 07:36 UTC
### Source name

Lezhin Comics

### Source link

https://www.lezhinus.com

### Language

English

### Other details

Pleasee make this extension so that i can read using tachiyomi. I don't like lezhin user interface when i read 😭
P.s. i hope this extension can see mature comics and download the episodes without getting banned/suspended.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment] 2021-11-05 07:37
Duplicate of #9410

**Closed by loocool2** 2021-11-05 07:37 UTC
Labels: Source request
