### ISSUE TITLE
Mikoroku Pages Not Found

### ISSUE THREAD

**Issue by EvilCrow1210** [tachiyomiorg/tachiyomi-extensions#19423] opened 2023-12-25 10:54 UTC
### Source information

Mikoroku 1.4.8

### Source language

Indonesia

### Steps to reproduce

1. Open Mikoroku Extension
2. Choose any manga
3. Choose newest chapter
4. And Pages Not Found

### Expected behavior

Pages of new chapter should Appear

### Actual behavior

But it show "Pages Not Found", Even if you open it in webview, the page appears correctly

### Tachiyomi version

0.14.7

### Android version

Android 11

### Other details

If you open it in webview the page appears fine but if you open it directly in the extension it doesn't appear

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment] 2023-12-25 14:38
Duplicate of #19113

**Closed** 2023-12-25 14:52 UTC
Labels: Bug
