### ISSUE TITLE
Issue with coomer and kemono

### ISSUE THREAD

**Issue by BruhJuiceWater** [tachiyomiorg/tachiyomi-extensions#18639] opened 2023-10-21 06:30 UTC
### Source information

Coomer 1.4.7
Kemono 1.4.7

### Source language

English 

### Steps to reproduce

Try to search or open anything 

### Expected behavior

List chapters and give search results 

### Actual behavior

Show now results and instead show a message 
![Screenshot_20231020_232343_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/148611143/0ea993a8-cf11-4d63-a098-b40fa41d00d7)

### Tachiyomi version

App version: 0.14.6 

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2023-10-21 11:14
Duplicate of #18617, addressed by #18638.

**Closed by vetleledaal** 2023-10-21 11:14 UTC
Labels: Bug
