### ISSUE TITLE
Heroxia cannot search comics 

### ISSUE THREAD

**Issue by Kiki88x** [tachiyomiorg/tachiyomi-extensions#14559] opened 2022-12-15 06:50 UTC
### Source information and language

Heroxia 1.3.21 (indonesia) 

### Steps to reproduce

1. Open heroxia
2. Search comic
3. List library appears from the keywords 

### Expected behavior

The library should pop up the keywords comic, because in the original web have the comics, but its not. It same library nothing change even i refresh the library. 

### Actual behavior

Library still the same content, nothing has change. Can't do anything. 

### Tachiyomi version

0.14.2

### Android version

Android 9

### Other details

![Screenshot_20221215-154923](https://user-images.githubusercontent.com/70476061/207792112-dbb8f891-9ca2-4432-88e4-a2504704fb9d.png)
![Screenshot_20221215-154948](https://user-images.githubusercontent.com/70476061/207792171-352701e7-5268-4ef6-9b72-e01d7368ea3f.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2022-12-15 19:58
Duplicate of #14555
Don't post NSFW screenshots on GitHub

**Closed by vetleledaal** 2022-12-15 19:58 UTC
Labels: Bug, Factory source
