### ISSUE TITLE
A Pair of 2+ "HTTP error 404" on app, but works in Webview

### ISSUE THREAD

**Issue by RazredgeBR** [tachiyomiorg/tachiyomi-extensions#15653] opened 2023-03-09 16:50 UTC
### Source information and language

A Pair of 2+ (English) 1.4.28

### Steps to reproduce

Trying to explore the source, or search. Nothing is generating a response. Opening the page in WebView works, but even after viewing it this way, going back to the extension, the same error occurs. Changing User Agent Strings did not give any different results.

### Expected behavior

The list of popular/latest translations should appear, and allow for the user to browse.

### Actual behavior

Error 404. No matter how, it will always 404. Changing user agent did nothing.

### Tachiyomi version

App version: 0.14.5 (standard, b690de5, 98, 2023-02-19T20:35Z)

### Android version

Android version: 13 (SDK 33)

### Other details

![Imagem do WhatsApp de 2023-03-09 à(s) 13 45 20](https://user-images.githubusercontent.com/82561645/224096506-ca9f4077-85ff-46c8-aa39-d2bae990f776.jpg)
![Imagem do WhatsApp de 2023-03-09 à(s) 13 44 46](https://user-images.githubusercontent.com/82561645/224096523-f3305581-a74f-4839-a446-1b74a580199d.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment] 2023-03-09 16:54
Duplicate of #15542

**Closed by loocool2** 2023-03-09 16:54 UTC
Labels: Bug
