### ISSUE TITLE
MangArabic

### ISSUE THREAD

**Issue by yemenihandsome** [tachiyomiorg/tachiyomi-extensions#10065] opened 2021-12-10 07:20 UTC
### Source name

MangArabic

### Source link

https://mangarabic.com/

### Language

Arabic

### Other details

Please, please, add this resource, it's a great resource 🥺

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by hani1998** [comment] 2021-12-10 07:23
Oh yeah, we hope you'll add it to a really great source

**Comment by hani1998** [comment] 2021-12-10 07:23
Oh yeah, we hope you'll add it to a really great source

**Comment by hani1998** [comment] 2021-12-10 07:23
Oh yeah, we hope you'll add it to a really great source

**Comment by curche** [comment] 2021-12-10 07:50
Duplicate of #9512

**Closed by curche** 2021-12-10 07:50 UTC
Labels: Source request
