### ISSUE TITLE
EarlyManga chapters not showing

### ISSUE THREAD

**Issue by Avesr** [tachiyomiorg/tachiyomi-extensions#9967] opened 2021-12-01 13:40 UTC
### Source information

EarlyManga 1.2.16

### Steps to reproduce

1. Open "The beginning after the end"(others also affected by this ) in the library section or in the browse;
2. Select any manga

### Expected behavior

Load the manga/manhwa and can be read.

### Actual behavior

 Says "Unable to resolve host "earlymanga org.https": no address associated with host name" and doesn't show any chapters

### Tachiyomi version

0.12.3

### Android version

Android 10

### Other details

Don't show author and doesn't work on web view either

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2021-12-15 03:19
Duplicate of #9188

**Closed by Seishirou101** 2021-12-15 03:19 UTC
Labels: Bug
