### ISSUE TITLE
Toonily can't search

### ISSUE THREAD

**Issue by Marinx211** [tachiyomiorg/tachiyomi-extensions#13024] opened 2022-08-16 14:03 UTC
### Source information and language

Toonily 1.3.31

### Steps to reproduce

When i search some manhwa I can't search but the source is working only search is not

### Expected behavior

![Screenshot_20220816_220150](https://user-images.githubusercontent.com/106808221/184899048-6689cd48-33c5-45d8-a546-4a271c5ad4cf.jpg)

### Actual behavior

![Screenshot_20220816_220201](https://user-images.githubusercontent.com/106808221/184899098-f55da20a-2e88-4776-8d70-6e72b7bf847b.jpg)

### Tachiyomi version

0.13.5

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2022-08-16 14:04
Duplicate of #12968

**Closed by Seishirou101** 2022-08-16 14:04 UTC
Labels: Bug
