### ISSUE TITLE
Gmanga chapter page don't load

### ISSUE THREAD

**Issue by Xocv** [tachiyomiorg/tachiyomi-extensions#9158] opened 2021-09-20 22:59 UTC
### Source information

Gmanga 1.2.6

### Steps to reproduce

1-Open gmanga in tachiyomi
2-go to any manga
3-open any chapter
4- issue is here

### Expected behavior

The page should load

### Actual behavior

The page doesn't load

### Tachiyomi version

Tachij2k 1.3.1

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2021-09-20 23:07
Duplicate of #9125

**Closed** 2021-09-20 23:07 UTC
Labels: Bug
