### ISSUE TITLE
[Source Request] <DaveyScans>

### ISSUE THREAD

**Issue by Ayanokouji-kun** [tachiyomiorg/tachiyomi-extensions#6940] opened 2021-05-10 06:07 UTC
## Source website
- Name: Davey Scans
- Link: https://daveyscans.com/
- Language(s): Indonesia

## Other details
- I have checked that the extension does not already exist:
  - In the list of existing extensions in the application

**Comment by Riztard** [comment] 2021-05-10 12:41
duplicate of #6901

**Closed by Riztard** 2021-05-10 12:41 UTC
Labels: Source Request, duplicate
