### ISSUE TITLE
NSFW missing

### ISSUE THREAD

**Issue by Neko014** [tachiyomiorg/tachiyomi-extensions#8928] opened 2021-09-01 17:01 UTC
### Source information

Mangadex 1.2.130

### Steps to reproduce

NSFW +18 doesn't show up, it doesn't show up in searches too, mangadex, all nsfw option all turned on, in tachiyomi settings and extension settings, it doesn't show up

### Expected behavior

NSFW +18 to show up mangadex searches and in general

### Actual behavior

NSFW +18 not showing up

### Tachiyomi version

0.12.1

### Android version

Android 10

### Other details

If this report is already up and issuing a fix pls close this thread

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2021-09-01 17:25
Duplicate of #8179

**Comment by arkon** [comment] 2021-09-01 17:44
Nevermind, apparently MangaDex changed something.

**Comment by CrepeTF** [comment] 2021-09-01 19:31
@arkon I checked with a pornhwa on my end and it seems like it's not showing up on dex search either?
![image](https://user-images.githubusercontent.com/70870719/131732358-d2dfebc4-ba1e-4cc2-847b-51cc2bd45ade.png)

**Comment by CrepeTF** [comment] 2021-09-01 19:34
Nevermind, MangaDex changed the NSFW filter.

**Comment by paulo27ms** [comment] 2021-09-01 20:41
`contentRating[]
Array of strings
Default: ["safe","suggestive","erotica"]
Items Enum: "safe" "suggestive" "erotica" "pornographic"`
Guess chapter lists need to check this now to show pornographic chapters.

**Closed** 2021-09-08 19:38 UTC
Labels: Bug
