### ISSUE TITLE
Tachiyomi problem

### ISSUE THREAD

**Issue by Arielfontoura** [tachiyomiorg/tachiyomi-extensions#13043] opened 2022-08-17 11:45 UTC
### Source information and language

1manga.co

### Steps to reproduce

They are blocking my downloads

### Expected behavior

I use to download normaly

### Actual behavior

I can't download anymore

### Tachiyomi version

0.13.6

### Android version

Android11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-08-17 13:20
Duplicate of #13040 probably, considering the lack of useful detail here.

**Closed by arkon** 2022-08-17 13:20 UTC
Labels: Bug
