### ISSUE TITLE
Error 429 

### ISSUE THREAD

**Issue by Mehshad3** [tachiyomiorg/tachiyomi-extensions#14855] opened 2023-01-09 01:12 UTC
### Source information and language

1 kiss (EN)

### Steps to reproduce

Mercenary enrollment
Memorize
Omniscient reader's viewpoint 

### Expected behavior

It usually updates the material completely without any error 

### Actual behavior

But it's saying that 12or more updates have failed when I clicked to see what was wrong it said error 429

### Tachiyomi version

Tachiyomi stable 0.14.3

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment] 2023-01-09 03:23
Duplicate of #14850

**Closed by loocool2** 2023-01-09 03:23 UTC
Labels: Bug
