### ISSUE TITLE
Mangaowl cannot bypass or bypassing not popping up

### ISSUE THREAD

**Issue by Mystique0414** [tachiyomiorg/tachiyomi-extensions#8662] opened 2021-08-20 04:16 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.12.1

### Android version

Android 10

### Source information

Mangaowl 1.2.22

### Steps to reproduce

1. The usual opening the app and choosing the manga you want to read from your library for example the manga titled "Whose baby is it" Mangaowl extension (I test loading it without clicking the webview first cause in the past when I tried it it always says java bypassing but nothing pop up and since there's no update on the chapter it just load and done but this new version the chapters do update when there's a new chapter for example chapter 154 then new update chapter 155(I did not get the chance to take a ss of it) so anyways that happen but I thought it was good and nice update but..)
2. I open the webview to load the bypass but there's none popping up so I open the chapter (155) and still no bypassing happen so I thought it did bypass with at ease
3. click X and go back to the library manga so I can read directly on the tachiyomi chapter
4. clicking chapter 155..

### Expected behavior

I expect it to load the chapter since there's no bypassing happening and read at ease the same as downloading the chapter too

### Actual behavior

Well this happen instead 😅 when I click the chapter on tachiyomi (ch 155 of whose baby is it) it loads but it exits saying java needs bypassing but I already gone to the webview and click the ch there as well, even if how many times I did it in the webview its still the same outcome even when downloading it😔

### Other details

![1629431313359](https://user-images.githubusercontent.com/40486255/130177584-03a2f264-ba83-49a4-8c59-7782bbc33ddf.png)

![1629431385021](https://user-images.githubusercontent.com/40486255/130177596-2cf9fdf2-918d-4cfb-a7ea-60fb48941d1a.png)

![1629431427539](https://user-images.githubusercontent.com/40486255/130177616-75850b6a-8bf4-4ad3-aa08-fcb22bc76225.png)

![1629431440648](https://user-images.githubusercontent.com/40486255/130177633-dc75c064-cc3b-4a53-8bb7-fd40d18c72e8.png)

![1629431494564](https://user-images.githubusercontent.com/40486255/130177707-81cf2f9e-7358-4662-a7aa-b2a8cc670bc6.png)

![1629431582061](https://user-images.githubusercontent.com/40486255/130177876-0bf405ea-87d2-4803-873e-ee394a5232c9.png)

![1629431611404](https://user-images.githubusercontent.com/40486255/130177910-0249ac2f-fafa-4493-9678-32a31b2a04b6.png)
 
![1629431560264](https://user-images.githubusercontent.com/40486255/130178212-6f119e72-beeb-4f23-8a52-4c79610774d5.png)
![1629431540776](https://user-images.githubusercontent.com/40486255/130178223-03cf5242-4c83-40af-9eb9-29b3bea5cc0d.png)

here are the screenshots.

**Comment by Ajwkjaj** [comment] 2021-08-22 06:26
We have the same issue, even i did follow the trouble shooting guide

**Comment by Ajwkjaj** [comment] 2021-08-22 06:30
Its the best extension for me. It happened two days ago too :(

**Comment by arkon** [comment] 2021-10-02 16:31
Duplicate of #8456

**Closed by arkon** 2021-10-02 16:31 UTC
Labels: Bug
