### ISSUE TITLE
Manga.pw (error al mostrar los capitulos) 

### ISSUE THREAD

**Issue by Jose1159** [tachiyomiorg/tachiyomi-extensions#8158] opened 2021-07-17 13:34 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1 

### Android version

Android 10

### Source information

Manga.pw 1.2.4

### Steps to reproduce

Error al gargar los Episodios

![Screenshot_20210717_082523_eu.kanade.tachiyomi.jpg](https://user-images.githubusercontent.com/78783435/126038778-c34ca94f-a5a7-4d72-acfc-f004a03cedb7.jpg)

![Screenshot_20210717_082504_eu.kanade.tachiyomi.jpg](https://user-images.githubusercontent.com/78783435/126038782-0e8d607d-7acf-4a94-92cd-38803fd046d5.jpg)

### Expected behavior

. 

### Actual behavior

. 

### Other details

.

**Comment by alessandrojean** [comment] 2021-07-17 13:38
Duplicate of #7970.

**Closed by alessandrojean** 2021-07-17 13:38 UTC
Labels: Bug
