### ISSUE TITLE
HTTP error 429

### ISSUE THREAD

**Issue by HenDreYll** [tachiyomiorg/tachiyomi-extensions#11320] opened 2022-04-03 16:10 UTC
### Source information

1st Kiss 1.2.23

### Steps to reproduce

When updating library there's always updates failed.

### Expected behavior

Updated/New Chapters should be able to read.

### Actual behavior

Instead the library updates always fails so I'm unable to read the new chapters.

### Tachiyomi version

0.13.1

### Android version

Android 8.1.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-04-03 16:29
Duplicate of #11315

Update your extensions.

**Closed by arkon** 2022-04-03 16:29 UTC
Labels: Bug

**Comment by HenDreYll** [comment] 2022-04-03 16:31
> 

Already updated

**Comment by curche** [comment] 2022-04-03 17:49
> Source information 
> 1st Kiss 1.2.23
> Already updated

but there's a new one now...
![2022-04-03_23-18](https://user-images.githubusercontent.com/72807749/161441159-c8c8837e-5ca3-4fc6-b03b-bc4b4a003114.png)

Check the website or refresh your extensions list to check for updates
https://tachiyomi.org/extensions/#en.firstkissmanga
