### ISSUE TITLE
hiperdex url change

### ISSUE THREAD

**Issue by WidowmakerJRM** [tachiyomiorg/tachiyomi-extensions#15278] opened 2023-02-08 16:22 UTC
### Source information and language

Hiperdex 1.3.35 english

### Source new URL

https://1sthiperdex.com/

### Other details

hiperdex switched its url from "https://hiperdex.com" to "https://1sthiperdex.com"

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2023-02-08 16:28
Duplicate of #15244

**Closed by alessandrojean** 2023-02-08 16:28 UTC
Labels: Bug, Domain changed
