### ISSUE TITLE
Doujindesu error 

### ISSUE THREAD

**Issue by Kiki88x** [tachiyomiorg/tachiyomi-extensions#14053] opened 2022-10-30 22:12 UTC
### Source information and language

Doujindesu

### Steps to reproduce

1. Open doujindesu
2. Try open the comic
3. There is no cover picture
4. Try open the chapter
5. There is no picture appear

### Expected behavior

When we open every extension, cover comic always popup, and when we want to read any chapter the pictures pop up too. 

### Actual behavior

![Screenshot_20221031-065926](https://user-images.githubusercontent.com/70476061/198903929-e92078f7-972a-46ce-ae0a-0a811b63b031.png)
![Screenshot_20221031-065949](https://user-images.githubusercontent.com/70476061/198903935-0815d40a-d8dd-4b1e-abb8-3f11f3da0f52.png)

There's no picture appearing in every section. 

### Tachiyomi version

0.14.1

### Android version

Android 9

### Other details

Every update always like this. Im sorry for the report... 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-10-30 22:23
Duplicate of #11662

**Closed by alessandrojean** 2022-10-30 22:23 UTC
Labels: Bug
