### ISSUE TITLE
Kirei Cake don't work

### ISSUE THREAD

**Issue by SqueezedByte** [tachiyomiorg/tachiyomi-extensions#14280] opened 2022-11-17 08:06 UTC
### Source information and language

Kirei Cake English 1.3.3

### Steps to reproduce

Try to get the list of manga from extension o even in the webview.

The page on mangadex still exist though

https://mangadex.org/group/5fa94491-6f6f-4d53-b8ff-4a4967ac40b5/kirei-cake?tab=feed

### Expected behavior

Show the list of manga

### Actual behavior

It show nothing

### Tachiyomi version

0.14.2

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment] 2022-11-17 10:27
Duplicate of #14089

**Closed by AntsyLich** 2022-11-17 10:27 UTC
Labels: Bug
