### ISSUE TITLE
Error 429

### ISSUE THREAD

**Issue by LycNeptune** [tachiyomiorg/tachiyomi-extensions#13256] opened 2022-08-29 01:55 UTC
### Source information and language

Mangamax 1.3.8

### Steps to reproduce

Happen when i refresh the library, then it will be happen

### Expected behavior

Normally all of it will refreshed without any crash log

### Actual behavior

It will make a crash log at so many manga and error 429

### Tachiyomi version

0.1.3.6

### Android version

Android 7

### Other details

It happen when i refresh my library

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Rkyl3** [comment] 2022-08-29 03:47
Lol we have the same problem

**Comment by vetleledaal** [comment] 2022-08-29 05:58
Duplicate of #13182

**Closed by vetleledaal** 2022-08-29 05:58 UTC
Labels: Bug
