### ISSUE TITLE
Issue:API Rate Limit Reach

### ISSUE THREAD

**Issue by Cyynii** [tachiyomiorg/tachiyomi-extensions#13108] opened 2022-08-20 13:29 UTC
### Source information and language

Mangahub 1.3.19

### Steps to reproduce

Mangahub isnt the only one who have this also other extensions

### Expected behavior

Maybe fixing the extension should fix it i think,It kinda annoys me i just wanna read mangas

### Actual behavior

Instead of moving in the next chapter the Api thing pops up in a random chapter,I dont know if it's a bug or just the extension/website having a problem

### Tachiyomi version

0.13.6

### Android version

Android 11

### Other details

![IMG_20220820_212149](https://user-images.githubusercontent.com/111644326/185748084-d40e0667-24df-4f1d-87db-2adda418a158.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-08-20 14:29
Duplicate of #13040

**Closed by alessandrojean** 2022-08-20 14:29 UTC
Labels: Bug
