### ISSUE TITLE
HTTP 429 Error

### ISSUE THREAD

**Issue by RitsuAikawa** [tachiyomiorg/tachiyomi-extensions#12440] opened 2022-07-05 03:54 UTC
### Source information

Mangabuddy 1.3.9

### Steps to reproduce

![Screenshot_20220705-104744_Chrome](https://user-images.githubusercontent.com/108710139/177245774-913a60aa-d719-43be-b891-9fdace77593e.jpg)

### Expected behavior

The manga or manhwa i update is not completed. The one I skipped is for a completed manhwa or manga. So the ongoing one must be update

### Actual behavior

But the update failed. Before this won't happened

### Tachiyomi version

0.13.4

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by DchanN** [comment] 2022-07-05 04:07
Duplicate of #12397

**Closed** 2022-07-05 12:14 UTC
Labels: Bug
