### ISSUE TITLE
Mangahub API Limit Reached

### ISSUE THREAD

**Issue by 77k4** [tachiyomiorg/tachiyomi-extensions#13056] opened 2022-08-17 22:55 UTC
### Source information and language

Mangahub 1.3.19

### Steps to reproduce

1. Open any manga on Mangahub source
2. Read several chapters 
3. After certain point " API rate limit excessed! Go to Mangahub.io to continue reading" will appear and cannot read manga anymore

### Expected behavior

Can continue read manga on mangahub source.

### Actual behavior

Cannot read for more than several chapters of a manga before message appears.

### Tachiyomi version

0.13.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Chronosishere** [comment] 2022-08-17 23:22
Previously this issue was labelled as JSON error but after the Mangahub extension update it's labelled as API LIMIT REACHED. 
User cannot read chapters from the app but can read through WEBVIEW. 
After some time user is again able to read through App but after only 2 or 3 Chapter/Manhwa the issue is reproduced.
User is also unable to DOWNLOAD the chapters while the issue persists, API LIMIT REACHED.

**Comment by raziel100** [comment] 2022-08-18 00:24
i believe that this is basicaly the same issue in #13040

**Comment by arkon** [comment] 2022-08-18 13:04
Duplicate of #13040

**Closed by arkon** 2022-08-18 13:04 UTC
Labels: Bug
