### ISSUE TITLE
mangazure

### ISSUE THREAD

**Issue by velvetcrowee** [tachiyomiorg/tachiyomi-extensions#8425] opened 2021-08-06 21:40 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

mangazure

### Source link

https://www.mangazure.com/

### Language

turkish

### Other details

I opened it again because there was no detail. 

this site contains many manga 
We can think of it as combining the manga from 4-5 Turkish manga sites. and they have fast services 
If you look at the site, manga or any webtoon is uploaded every day. so we can think of it like the old madara plugin, like having 5 in 1 plugin. this is a site that hosts a lot of manga. And since the site is active, I hope many Turkish readers like it.

**Comment by hanshiro69** [comment] 2021-08-07 15:43
pls added

**Comment by alessandrojean** [comment] 2021-08-08 16:00
Duplicate of #7293

**Closed by alessandrojean** 2021-08-08 16:00 UTC
Labels: Source request
