### ISSUE TITLE
[Feature Request] Local Source: Adding an option to change local source directory

### ISSUE THREAD

**Issue by BaccanoMob** [tachiyomiorg/tachiyomi-extensions#6694] opened 2021-04-24 15:15 UTC
I noticed that there is an option to change the download location. Is there are any possibilities to implement a custom directory for the local source?

I download in batches and switch between devices to avoid wasting data. An option to change the local source directory would be easier when I open using an emulator in my PC and saves time copying. 

Also might be useful for people who lack space in the phone and want it at a different folder could benefit from this as well.

**Comment by Seishirou101** [comment] 2021-04-24 15:28
wrong repo, but duplicate of [#2081](https://github.com/tachiyomiorg/tachiyomi/issues/2086)

**Closed** 2021-04-24 15:31 UTC
Labels: enhancement
