### ISSUE TITLE
[Source Request] <WebtoonTR>

### ISSUE THREAD

**Issue by hanshiro6l6** [tachiyomiorg/tachiyomi-extensions#7776] opened 2021-06-20 23:55 UTC
## Source website
- Name: WebtoonTR
- Link: https://trwebtoon.com/
- Language(s): Turkish

**Comment by loocool2** [comment] 2021-06-21 00:09
Do not repost issues. Also a duplicate of #4733

**Closed by loocool2** 2021-06-21 00:09 UTC
Labels: Source Request
