### ISSUE TITLE
[Bug] <Leviatan scan>: <404 no pages found>>

### ISSUE THREAD

**Issue by Poncow5** [tachiyomiorg/tachiyomi-extensions#6173] opened 2021-03-13 22:36 UTC
---

## Device information
- Tachiyomi version: 0.10.9
- Android version: 5

## Source information
- Name: levaitan scan
- Extension version: 1.2.2

## Steps to reproduce
1. Updating any manhwa from the leviatan scan
2. Try to browse any chapter

### Expected behavior
The chapter should be Updated without any issue.

### Actual behavior
It shows the "404 No pages found" error notification.

## Other details
The pages show up in webview.

**Comment by scb261** [comment] 2021-03-13 22:38
Duplicate of #6162

**Closed by scb261** 2021-03-13 22:38 UTC
Labels: bug
