### ISSUE TITLE
MangaStic not searching for any manga or manhua

### ISSUE THREAD

**Issue by ArchCelestial** [tachiyomiorg/tachiyomi-extensions#14874] opened 2023-01-09 23:49 UTC
### Source information and language

MangaStic 1.3.28

### Steps to reproduce

1. Open up the MangaStic source
2. Search for anything.
3. HTTP error 400. Check webview.

### Expected behavior

It should allow me to search any of the manga or manhua that exist on the site.

### Actual behavior

If you search anything under the source. It says HTTP error 400. Check webview. If you check webview, everything is fine. No matter what ever setting I toggle, the source doesn't work.

### Tachiyomi version

0.14.3

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by samanta-widjaja** [comment] 2023-01-13 21:32
It changes its url to mangastic.in

**Comment by vetleledaal** [comment] 2023-02-21 20:29
Duplicate of #14407

**Closed by vetleledaal** 2023-02-21 20:29 UTC
Labels: Bug, Factory source
