### ISSUE TITLE
Pages not found error from MangaOwl extension

### ISSUE THREAD

**Issue by tdogubo** [tachiyomiorg/tachiyomi-extensions#11937] opened 2022-05-22 11:34 UTC
### Source information

MangaOwl 1.2.25

### Steps to reproduce

Trying to read manhwa on mangaOwl

### Expected behavior

The manhwa should open in the app after loading.

### Actual behavior

Pages not found error pops up instead

### Tachiyomi version

0.13.4

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-05-22 12:44
Do not open duplicate issues.

Duplicate of #11212

**Closed by alessandrojean** 2022-05-22 12:44 UTC
Labels: Bug

**Comment by tdogubo** [comment] 2022-05-22 13:37
> Do not open duplicate issues.
> 
> Duplicate of #11212

Apologies
