### ISSUE TITLE
Url change

### ISSUE THREAD

**Issue by bopbop206** [tachiyomiorg/tachiyomi-extensions#14364] opened 2022-11-24 05:08 UTC
### Source information and language

Nettruyen 1.3.12 (tiếng việt)

### Source new URL

https://www.nettruyenon.com/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment] 2022-11-24 11:48
Duplicate of #14345

**Closed by AntsyLich** 2022-11-24 11:48 UTC
Labels: Bug, Domain changed
