### ISSUE TITLE
WebtoonXYZ: can't bypass CloudFlare in app

### ISSUE THREAD

**Issue by ara8ara** [tachiyomiorg/tachiyomi-extensions#13102] opened 2022-08-20 04:51 UTC
### Source information and language

WebtoonXYZ 1.3.27 (english)

### Steps to reproduce

1. open the source
2. can't bypass CloudFlare
3. try to open it in webview and I can bypass the CloudFlare
4. retry the source in app many times but still can't bypass CloudFlare

### Expected behavior

Display manga and update existing manga in library from source

### Actual behavior

failed to bypass CloudFlare

### Tachiyomi version

0.13.6

### Android version

Android 10

### Other details

can't bypass CloudFlare in WebtoonXYZ, I try to open it in webview and it open nicely, 
I try to change the user-agent but still can't bypass it.

![Screenshot_20220820-113036](https://user-images.githubusercontent.com/15099415/185729288-a8fdd5c7-6695-47fc-a806-3450654c47c6.png)

![Screenshot_20220820-113110](https://user-images.githubusercontent.com/15099415/185729299-b45298bb-a7dc-45d1-b1e9-aee7e7b8f5d0.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2022-08-20 05:55
Duplicate of #6738

**Closed by vetleledaal** 2022-08-20 05:55 UTC
Labels: Bug
