### ISSUE TITLE
[Source Request] <hatsukimanga.com>

### ISSUE THREAD

**Issue by Antoniiano10** [tachiyomiorg/tachiyomi-extensions#7351] opened 2021-05-31 18:42 UTC
Note that#hatsukimanga.com# Source website
- Name: Hatsuki Manga
- Link: hatsukimanga.com
- Language(s): Español

## Other details

Exelente pagina de mangas

**Comment by alessandrojean** [comment] 2021-05-31 20:57
Duplicate of #4282.

**Closed by alessandrojean** 2021-05-31 20:57 UTC
Labels: Source Request
