### ISSUE TITLE
Kavita: Missing entries on the results

### ISSUE THREAD

**Issue by apoorv569** [tachiyomiorg/tachiyomi-extensions#14912] opened 2023-01-12 16:13 UTC
### Source information and language

Kavita Multi 1.3.9

### Steps to reproduce

1. Install the `Tachiyomi` app from https://tachiyomi.org/download/
2. Install the `Kavita` plugin.
3. Connect the plugin to your server via `OPDS` link.
4. Go to the `Browse` section and click on the plugin to view books.

### Expected behavior

Should show all the books from the server.

### Actual behavior

Only shows 2 books.

### Tachiyomi version

0.14.3

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ThePromidius** [comment] 2023-01-12 18:43
Kavita extension does not support epub type of books.

**Comment by alessandrojean** [comment] 2023-01-13 20:28
Closing as it seems to be expected behavior. If the missing books aren't EPUBs, please comment and give more information so the issue can be reopened.

**Closed by alessandrojean** 2023-01-13 20:28 UTC
Labels: Bug

**Comment by apoorv569** [comment] 2023-01-15 09:28
> Closing as it seems to be expected behaviour. If the missing books aren't EPUBs, please comment and give more information so the issue can be reopened.

This is not and should not be the expected behaviour. Expected behaviour should be that formats are supported and shown.

**Comment by ThePromidius** [comment] 2023-01-15 09:58
Why would they be showed if they can't be read. That would be misleading.

Epubs are not supported because they are not images. Which is the only thing tachiyomi can display so far.
