### ISSUE TITLE
Error en la extensión Martial manga 

### ISSUE THREAD

**Issue by Marco-kun** [tachiyomiorg/tachiyomi-extensions#8363] opened 2021-08-02 02:59 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android 11

### Source information

Martial manga

### Steps to reproduce

La extencion Martial manga dice a ver cambiado de página y ahora paso a ser https://olympusscanlation.com/

### Expected behavior

Así que pido que ojalá cambien la extencion por la actual la cual seria olympus scanlation 

### Actual behavior

Cuando se meten a la extencion no aparecen niun manga solo un anuncio que dicen que cambiaron de pág así que espere ojalá lo arreglen pronto 
![Screenshot_2021-08-01-22-56-44-516_eu kanade tachiyomi](https://user-images.githubusercontent.com/85567345/127798773-ed68b7a2-0787-4c24-8e15-9833604bc0b4.jpg)
Adjunto lo que aparece al usar esa extencion

**Comment by alessandrojean** [comment] 2021-08-02 03:27
Duplicate of #8019

**Closed by alessandrojean** 2021-08-02 03:27 UTC
Labels: Bug
