### ISSUE TITLE
Toonily chapters arent updating

### ISSUE THREAD

**Issue by Firefistdante** [tachiyomiorg/tachiyomi-extensions#9111] opened 2021-09-18 02:58 UTC
### Source information

Toonily

### Steps to reproduce

New chapters dont pop up in the extension even though it does on the site

### Expected behavior

Update frequently 

### Actual behavior

Not updating 

### Tachiyomi version

0.12.2

### Android version

9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2021-09-18 02:59
Duplicate of #9109

**Closed** 2021-09-18 02:59 UTC
Labels: Bug
