### ISSUE TITLE
Toongod.com

### ISSUE THREAD

**Issue by Israld** [tachiyomiorg/tachiyomi-extensions#12947] opened 2022-08-11 20:15 UTC
### Source information and language

ToonGod v1.3.26 (english)

### Steps to reproduce

1.Update to the latest version
2.install extension

### Expected behavior

should show the list of manga

### Actual behavior

manga not showed
![Screenshot (Aug 12, 2022 03_21_22)](https://user-images.githubusercontent.com/110901776/184235454-f3ef9d52-cfba-4d84-a520-b14f2ab439de.png)

### Tachiyomi version

1.8.5

### Android version

Android 10

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-08-13 14:16
Duplicate of #12952

**Closed by arkon** 2022-08-13 14:16 UTC
Labels: Bug
