### ISSUE TITLE
Extensión Atlantis Scan don't respond 

### ISSUE THREAD

**Issue by Unknoweird** [tachiyomiorg/tachiyomi-extensions#18913] opened 2023-11-10 12:54 UTC
### Source information

Atlantis Scan 1.4.31

### Source language

Spanish 

### Steps to reproduce

1. Enter
2. HTTP Error 404

### Expected behavior

Enter and search anything 

### Actual behavior

HTTP Error 404 open in WebView 

### Tachiyomi version

TachiJ2K 1.7.3

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2023-11-11 10:18
Duplicate of #18892

**Closed by vetleledaal** 2023-11-11 10:18 UTC
Labels: Bug
