### ISSUE TITLE
 no chapters found

### ISSUE THREAD

**Issue by Akashi123-deep** [tachiyomiorg/tachiyomi-extensions#16747] opened 2023-06-15 22:59 UTC
### Source information

MangaSwat 1.4.33

### Source language

Arabic

### Steps to reproduce

when I updated the manga that has MangaSwat as an extension , the message ' no chapters found ' come out 
- the website is fine 
- there are new chapter but as I said when I updated the message came out 
- the extension work fine 
![IMG_20230615_234754](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/102795903/d4fe7198-52ae-471e-9e79-df3d236c7c81)
![IMG_20230615_234754](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/102795903/edb21b2a-4582-452e-ac4a-82631295e64e)

### Expected behavior

it should show me the new chapters in the app

### Actual behavior

instead it doesn't 

### Tachiyomi version

0.14.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-06-17 02:26
Duplicate of #16740

**Closed by arkon** 2023-06-17 02:26 UTC
Labels: Bug
