### ISSUE TITLE
[Bug] <Mangadex>: <HTTP error 502>

### ISSUE THREAD

**Issue by Blaze9676** [tachiyomiorg/tachiyomi-extensions#6048] opened 2021-03-03 01:39 UTC
**PLEASE READ THIS**

I acknowledge that:

- I have updated:
  - To the latest version of the app (stable is v0.10.9)
  - All extensions
- I have tried the troubleshooting guide: https://tachiyomi.org/help/guides/troubleshooting-problems/
- If this is an issue with the app itself, that I should be opening an issue in https://github.com/tachiyomiorg/tachiyomi
- I have searched the existing issues and this is new ticket **NOT** a duplicate or related to another open issue
- For source requests, I have checked the list of existing extensions including the multi-source spreadsheet: https://tachiyomi.org/extensions/
- I will fill out the title and the information in this template

Note that the issue will be automatically closed if you do not fill out the title or requested information.

## Device information
- Tachiyomi version: latest
- Android version: 10

## Source information
- Name: Mangadex
- Extension version: latest

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
Describe what should have happened

### Actual behavior
Describe what happens instead

**Comment by scb261** [comment] 2021-03-03 11:51
Duplicate of #6012

For future: use actual version instead of mysterious `latest`

**Closed by scb261** 2021-03-03 11:51 UTC
Labels: bug
