### ISSUE TITLE
[Bug] <Tumangaonline>: <http error 404>

### ISSUE THREAD

**Issue by Teph96** [tachiyomiorg/tachiyomi-extensions#7199] opened 2021-05-24 05:40 UTC
## Device information
- Tachiyomi version: 0.10.12
- Android version: Redmi Note 9

## Source information
- Name: Tumangaonline
- Extension version: latest

## Steps to reproduce
1. Install Tumangaonline 
2. Enter extension

### Issue
The app does'nt connect to the extension, error 404, I can't search nathing on the extension

![Screenshot_2021-05-23-23-39-30-110_eu kanade tachiyomi](https://user-images.githubusercontent.com/78838027/119301721-28896380-bc20-11eb-8fbd-c8fb9f9c475f.jpg)

**Comment by Natillax** [comment] 2021-05-24 12:18
I have the same problem too... :(
A weird problems happens too with mangas.pw (mangas.in) that always shows the same chapter in every manga and is hentai, I think, not the manga you were looking for.

**Comment by h-hyuuga** [comment] 2021-05-24 12:51
Duplicate of #6888

**Closed** 2021-05-24 13:07 UTC
Labels: bug
