### ISSUE TITLE
MG Komik (ID): Failed to Open Chapter

### ISSUE THREAD

**Issue by Rizer01** [tachiyomiorg/tachiyomi-extensions#12505] opened 2022-07-09 14:19 UTC
### Source information

MG Komik 1.3.23

### Steps to reproduce

Trying to read any chapter with the mgkomik extension gives back a Failed to Bypass Cloudflare . Webview works. List Chapter Work

### Expected behavior

Being able to read and download the chapter.

### Actual behavior

I cant open any manga in this extension because it says "Failed to Bypass the Cloudflare" , but when I open in webview it running normally

### Tachiyomi version

0.3.15

### Android version

Android 7

### Other details

No Screenshot

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by DchanN** [comment] 2022-07-09 14:59
Duplicate of #11727

**Closed** 2022-07-09 15:06 UTC
Labels: Bug
