### ISSUE TITLE
Failed to bypass cloudflare on Nhentai

### ISSUE THREAD

**Issue by datmemz** [tachiyomiorg/tachiyomi-extensions#13095] opened 2022-08-20 01:08 UTC
### Source information and language

Nhentai 1.3.35

### Steps to reproduce

Opening the Nhentai source refreshes on repeat and returns a failed to bypass cloudflare message

### Expected behavior

It should give the user the result titles of the extension

### Actual behavior

Instead it a returns a failed to bypass cloudflare message

### Tachiyomi version

0.13.6

### Android version

10

### Other details

![Screenshot_20220820-090422_Tachiyomi](https://user-images.githubusercontent.com/111542489/185723445-e60b4a67-6da7-42c8-a424-36b55182acd4.png)
Even the recommended troubleshooting methods does not work to bypass cloudflare

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Yoswice** [comment] 2022-08-20 01:17
Mine is the same as that but mine wont even bypass the cloudfair even when I go to open in webview

**Comment by alessandrojean** [comment] 2022-08-20 01:23
Duplicate of #12784

**Closed by alessandrojean** 2022-08-20 01:23 UTC
Labels: Bug
