### ISSUE TITLE
Muctau has changed to bibimanga.com

### ISSUE THREAD

**Issue by Eckasexy** [tachiyomiorg/tachiyomi-extensions#12236] opened 2022-06-18 23:13 UTC
### Source information

Muctau 1.3.22

### Steps to reproduce

1 go to browse
2 extension "muctau"
3 click webview to see changed in link

### Expected behavior

It will show bibimanga.com instead of muctau.com

### Actual behavior

It will show bibimanga.com instead of muctau.com

### Tachiyomi version

0.13.4

### Android version

Android 10

### Other details

I think there domain or link has change. Can anyone update that in tachiyomi? Thank you. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by zbue** [comment] 2022-06-24 10:31
Duplicate of https://github.com/tachiyomiorg/tachiyomi-extensions/issues/12213

**Closed** 2022-06-24 10:47 UTC
Labels: Bug
