### ISSUE TITLE
OLYMPUS SCANLATION 

### ISSUE THREAD

**Issue by ChulinOf** [tachiyomiorg/tachiyomi-extensions#15498] opened 2023-02-27 01:40 UTC
### Source information and language

Olympusscanlation.com 

### Source new URL

https://olympusscans.com/

### Other details

Hi, I wanted to tell you friend that the server of https://olympusscanlation.com/ It is no longer available as the site will shut down today and open a new server https://olympusscans.com/ Will it be that someone could update The extension of Olympus Scanlation  so we can continue enjoying this great app

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2023-02-27 01:46
Duplicate of #15330

**Closed by alessandrojean** 2023-02-27 01:46 UTC
Labels: Bug, Domain changed
