### ISSUE TITLE
Slime Read 

### ISSUE THREAD

**Issue by Mynameluis** [tachiyomiorg/tachiyomi-extensions#18339] opened 2023-10-03 09:22 UTC
### Source name

Slime Read

### Source link

https://slimeread.com/

### Source language

PT BR 

### Other details

18+: yes

### Acknowledgements

- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension is not on [the removed sources list](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/REMOVED_SOURCES.md).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2023-10-03 09:35
Duplicate of #17307

> Some stuff are locked under login, like the listing of series in their site, and also their API seems to be very well hidden, and using CSS selectors is hard as they're using TailwindCSS. Gonna close it for now.

**Closed by alessandrojean** 2023-10-03 09:35 UTC
Labels: Source request
