### ISSUE TITLE
Mangakakalot chapters not loading

### ISSUE THREAD

**Issue by ockerjj** [tachiyomiorg/tachiyomi-extensions#17146] opened 2023-07-16 21:12 UTC
### Source information

Mangakakalot 1.4.8

### Source language

English

### Steps to reproduce

1. Open manga through Mangakakalot
2. Open new chapter
3. Flip beyond page 2
4. Attempt to download the chapter

### Expected behavior

The pages after page 2 load properly
OR
The chapter downloads as usual

### Actual behavior

The pages give a "The image couldn't be loaded error"
OR
The chapter stops downloading after two pages

### Tachiyomi version

0.14.6

### Android version

Android 12

### Other details

This does not occur if the chapter was downloaded already. This issue has been occuring consistently for several weeks.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2023-07-20 20:09
Can't reproduce on the 5 most popular manga. What manga and chapter are you having issues with? Are you using the default User-Agent?

**Comment by ockerjj** [comment] 2023-07-21 17:12
I am using the default user-agent. Some series I was having trouble with are Kinnikuman, Majin Tantei Nougami Neuro, and Konjiki No Gash!! 2.
When I checked them again, however, they don't seem to be having problems anymore. I'm not sure why; I haven't changed any settings or applied any new updates.

**Comment by Seishirou101** [comment] 2023-07-21 17:22
you probably had expired image links or something a long those lines and it was refreshed at a later point. Usually this is fixed clearing cache. Closing since issue is no longer relevant.

**Closed by Seishirou101** 2023-07-21 17:22 UTC
Labels: Bug

**Comment by vetleledaal** [comment] 2023-07-21 18:26
I was able to replicate the issue, but only transiently for Kinnikuman and Konjiki No Gash!! 2. My theory is that uncommonly accessed images are much slower to access and you end up hitting the 30s read timeout. Tapping retry usually fixes this.

There is no rate limiting in the extension, the site itself is making it slow (intentionally or not). Outside of raising the timeout, there is not much that can be done from Tachiyomi's side.
