### ISSUE TITLE
[Bug] <Toonily / skymanga (madara).>: <doesn't work properly and can't download>

### ISSUE THREAD

**Issue by yamato44** [tachiyomiorg/tachiyomi-extensions#5607] opened 2021-01-31 17:53 UTC
Device information
Tachiyomi version: 0.10.7.
Android version: 5.
Device: samsung.

Source information
Source name: Toonily / skymanga (madara).
Source extension version: 1.2.176

Steps to reproduce
Open toonily or skymanga .
Error message.

Issue/Request
when i open toonily or skymanga it load for a few moments and gives this message ( java.lang. Expection: Failed to bypass cloudflare ) and even when i open it in webview it doesn't work and view is ugly and I can't download

![Screenshot_2021-01-31-18-22-50](https://user-images.githubusercontent.com/77173618/106393025-dc0de400-63f4-11eb-8b9b-af36b7f98d51.png)
![Screenshot_2021-01-31-18-22-02](https://user-images.githubusercontent.com/77173618/106393024-d9ab8a00-63f4-11eb-9bdc-d14100e940e4.png)
![Screenshot_2021-01-31-18-25-46](https://user-images.githubusercontent.com/77173618/106393026-dd3f1100-63f4-11eb-9d12-c74877dc2459.png)

Other details
Other sources update properly.

**Comment by arkon** [comment] 2021-01-31 17:55
Is your WebView updated?

**Comment by arkon** [comment] 2021-01-31 17:55
Duplicate of #5605

**Closed** 2021-01-31 17:56 UTC
Labels: bug
