### ISSUE TITLE
[Bug] <MangaDex>: <Opening language specific setting causes app to crash>

### ISSUE THREAD

**Issue by Mangavillia** [tachiyomiorg/tachiyomi-extensions#6855] opened 2021-05-06 03:31 UTC
## Samsung Galaxy s10
- Tachiyomi version: 0.10.12
- Android version: 11

## Source information
- Name: MangaDex
- Extension version: 1.2.106

## Steps to reproduce
1. Open MangaDex extension settings
2. Pick any language and tap the setting gear icon

### Expected behavior
Show setting options for that language

### Actual behavior
App crashes

## Other details
Not that major an issue, but FYI

**Comment by arkon** [comment] 2021-05-06 03:34
Duplicate of #6850

**Closed by arkon** 2021-05-06 03:34 UTC
Labels: bug
