### ISSUE TITLE
Doujindesu - images chapter not found

### ISSUE THREAD

**Issue by miurishi** [tachiyomiorg/tachiyomi-extensions#16086] opened 2023-04-17 21:37 UTC
### Source information

Doujindesu 1.4.3

### Source language

Indonesia 

### Steps to reproduce

1. It shows "no page found" when open manga/manhwa chapter
2. Manga/manhwa cover always go blank when manga/manhwa is open

### Expected behavior

1. All images in manga/manhwa chapter is showing properly
2. All manga/manhwa cover is showing properly

### Actual behavior

All images in the manga/manhwa chapter is not showing
All manga/manhwa chapter shows "no page found" alert

### Tachiyomi version

0.14.6

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2023-04-18 00:30
Duplicate of #11662 and #14004.

**Closed by alessandrojean** 2023-04-18 00:30 UTC
Labels: Bug
