### ISSUE TITLE
Chapters Not Loading 

### ISSUE THREAD

**Issue by Yaoimkay** [tachiyomiorg/tachiyomi-extensions#14994] opened 2023-01-17 09:51 UTC
### Source information and language

Mangabuddy 1.3.12 (English)

### Steps to reproduce

Go to browse
Tap extensions
Install mangabuddy
Open it and try reading a manga

### Expected behavior

![Screenshot_20230117-104201](https://user-images.githubusercontent.com/122871171/212865636-351ce440-9903-4dd2-805e-92f5e4187f54.png)

### Actual behavior

![Screenshot_20230116-222924](https://user-images.githubusercontent.com/122871171/212865705-8e2b8bc2-cf66-478f-ae13-0f7e73584c71.png)

### Tachiyomi version

0.14.3

### Android version

Android 7

### Other details

I can't seem to read new mangas in my tachiyomi app
Keeps loading but no pictures seen
What could be the problem
Is anyone having the same issue

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment] 2023-01-17 10:16
Duplicate of #14967

**Closed** 2023-01-17 10:20 UTC
Labels: Bug
