### ISSUE TITLE
Requesting Tachiyomi Extension

### ISSUE THREAD

**Issue by Yaoiislife** [tachiyomiorg/tachiyomi-extensions#9081] opened 2021-09-16 03:17 UTC
### Describe your suggested feature

Can we add an additional website?

It is called Mangabuddy and their website is https://mangabuddy.com/

I do hope that we would be able to download the chapters. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment] 2021-09-16 03:39
Duplicate of #8908

**Closed by loocool2** 2021-09-16 03:39 UTC
Labels: Feature request
