### ISSUE TITLE
Japscan: Stuck downloads

### ISSUE THREAD

**Issue by oktapodia** [tachiyomiorg/tachiyomi-extensions#12491] opened 2022-07-09 03:06 UTC
### Source information

Japscan 1.3.29

### Steps to reproduce

Just launch tachiyomi, update the library with your mangas and you will see that the the new chapters stay in the download list forever, they don't download themselves, no problem with other sources

### Expected behavior

New chapters downloads automatically

### Actual behavior

The new chapters do not download from the japscan sourcechapters

### Tachiyomi version

R4553

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-07-09 03:09
Duplicate of #11992

**Comment by oktapodia** [comment] 2022-07-09 11:56
@arkon I thought that it was related to the source, do you think it is the app?

**Comment by arkon** [comment] 2022-07-09 13:05
Whoops I thought the other issue was also Japscan.

**Comment by oktapodia** [comment] 2022-07-09 17:19
Here's some of the logs when clicking on the download button, no obvious error seen

```
2022-07-09 13:05:21.796 15430-15430/? D/Activity: dispatchKeyEvent to eu.kanade.tachiyomi.ui.main.MainActivity@44a4e5a will call onBackPressed
2022-07-09 13:05:21.816 15430-15430/? I/Quality: Skipped: false 1
2022-07-09 13:05:21.825 1545-1545/? I/OPE-[OPlusOSyncPerfConfigs]: isRightContentFps 30
2022-07-09 13:05:21.830 2713-2738/? D/OplusDisplayPolicy: eu.kanade.tachiyomi.debug, no change cutoutMode: 0
2022-07-09 13:05:21.840 15430-15430/? I/Quality: Skipped: false 2
2022-07-09 13:05:21.851 15430-15430/? I/Quality: Skipped: false 1
2022-07-09 13:05:21.859 1545-1545/? I/OPE-[OPlusOSyncPerfConfigs]: isRightContentFps 120
2022-07-09 13:05:21.893 15430-15430/? I/Quality: Skipped: false 2
2022-07-09 13:05:21.900 1545-1545/? I/OPE-[OPlusOSyncPerfConfigs]: isRightContentFps 30
2022-07-09 13:05:21.909 1545-1545/? I/OPE-[OPlusOSyncPerfConfigs]: isRightContentFps 120
2022-07-09 13:05:21.913 1545-1545/? D/OplusSurfaceFlinger: RESOLUTION > bounds(0,0,1440,3216), frame(0,0,1440,3216) FHD(1080, 2412), QHD(1440, 3216) mCurrentResolution=1 orientation = 0
2022-07-09 13:05:22.133 15430-15430/? I/Quality: Skipped: true 1
2022-07-09 13:05:22.176 1545-1545/? I/OPE-[OPlusOSyncPerfConfigs]: isRightContentFps 30
2022-07-09 13:05:22.178 21286-21286/? W/adbd: timeout expired while flushing socket, closing
2022-07-09 13:05:22.437 21286-23374/? W/adbd: timed out while waiting for FUNCTIONFS_BIND, trying again
2022-07-09 13:05:22.437 21286-23374/? I/adbd: UsbFfs: connection terminated: monitor thread finished
2022-07-09 13:05:22.438 21286-21286/? I/adbd: UsbFfs: already offline
2022-07-09 13:05:22.438 21286-21286/? I/adbd: destroying transport UsbFfs
2022-07-09 13:05:22.439 21286-21286/? I/adbd: UsbFfsConnection being destroyed
2022-07-09 13:05:22.468 21286-21291/? I/adbd: opening control endpoint /dev/usb-ffs/adb/ep0
2022-07-09 13:05:22.471 21286-21291/? I/adbd: UsbFfsConnection constructed
2022-07-09 13:05:22.472 21286-23386/? I/adbd: UsbFfs-monitor thread spawned
2022-07-09 13:05:22.582 1545-1979/? D/VRR [OTI]: handleIdle from 0 to 1
2022-07-09 13:05:22.582 1545-1979/? D/VRR [OTI-HW]: isStateReady 0
2022-07-09 13:05:22.582 1545-1979/? D/VRR [OTI-HW]: rate range: min {id=4, hwcId=4, fps=60.00, width=1440, height=3216 group=1} cur {id=7, hwcId=7, fps=120.00, width=1440, height=3216 group=1} max {id=7, hwcId=7, fps=120.00, width=1440, height=3216 group=1}
2022-07-09 13:05:22.582 1545-1979/? D/VRR [OTI-HW]: keep rate.
2022-07-09 13:05:22.582 1545-1979/? D/VRR [OTI-ADFR]: getBestCvtRate 60, modeTypeIsReady 1, currentFps 120
2022-07-09 13:05:22.582 1545-1979/? D/VRR [OTI-ADFR]: cvtTargetRate change from 0 to 60
```

**Comment by oktapodia** [comment] 2022-07-10 02:01
I think that you were actually right @arkon , same issue with mangas origines source now.

**Comment by oktapodia** [comment] 2022-07-10 21:45
Seems to not progress after this point https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/src/fr/japscan/src/eu/kanade/tachiyomi/extension/fr/japscan/Japscan.kt#L401 

Progressing (logging more) if this is removed, I am not a java developer so it is a bit difficult for me to handle and understand the cyclic barrier thing.

**Closed** 2022-07-17 14:20 UTC
Labels: Bug
