### ISSUE TITLE
AllHentai

### ISSUE THREAD

**Issue by Gostik21** [tachiyomiorg/tachiyomi-extensions#18316] opened 2023-10-02 04:12 UTC
### Source information

1.4.42

### Source language

Russian

### Steps to reproduce

1) I'm opening AllHentai extention
2) I'm opening a manga and click on chapter
 

### Expected behavior

Chapter of manga is open

### Actual behavior

java.net.UnknownHostException: Unable to resolve host "z.allhen.online": No address associated

### Tachiyomi version

0.14.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by SnackBreak2925** [comment] 2023-10-02 17:49
Same problem. Website URL "z.allhen.online" changed to "24.allhen.online". You can change URL in extension settings, but reader when you start reading reader trying to connect "z.allhen.online"
I also think this is a bug

**Comment by vetleledaal** [comment] 2023-10-03 20:19
Duplicate of #15091

**Closed by vetleledaal** 2023-10-03 20:19 UTC
Labels: Bug
