### ISSUE TITLE
Cloudflare

### ISSUE THREAD

**Issue by YouBoi234** [tachiyomiorg/tachiyomi-extensions#12481] opened 2022-07-08 03:46 UTC
### Source information

Nhentai 1.3.34

### Steps to reproduce

Cloudflare error

### Expected behavior

Cloudflare Error

### Actual behavior

Cloudflare error

### Tachiyomi version

0.13.4

### Android version

Android 11

### Other details

I tried everything but it still cloudflare error 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by kazma777** [comment] 2022-07-08 06:44
![Screenshot_2022-07-08-14-42-42-70](https://user-images.githubusercontent.com/108920672/177932643-9c4e219b-ec61-48b8-a437-492b440b523a.jpg)
Pls somebody help us

**Comment by vetleledaal** [comment] 2022-07-08 07:21
Duplicate of #12405

**Closed** 2022-07-08 10:53 UTC
Labels: Bug
