### ISSUE TITLE
[Bug] <Mangasee>: chapter that won't load nor download.

### ISSUE THREAD

**Issue by NotPageD** [tachiyomiorg/tachiyomi-extensions#6140] opened 2021-03-11 08:36 UTC
## Device information
App version: 1.5.0 (TachiyomiSY, standard, 0413d50,)
Android version: 8.0.0 (SDK 26) 

## Source information
- Name: Mangasee
- Extension version: 1.2.17

## Steps to reproduce
Load any chapter of any manga 
Download any chapter of any manga

### Expected behavior
It's suppose to load and show the contents of the chapter
It's suppose to download the contents of the chapter

### Actual behavior
Retry button pops up and even if you try to retry it again and again, it wont work.
This error pops up "Invalid URL Host: JQuery(document).ready(function(n){window.his" and etc etc etc.

**Comment by Riztard** [comment] 2021-03-11 09:43
duplicate of #6136

**Closed by Riztard** 2021-03-11 09:43 UTC
Labels: bug
