### ISSUE TITLE
vomic不能使用

### ISSUE THREAD

**Issue by kongbai257** [tachiyomiorg/tachiyomi-extensions#16895] opened 2023-06-27 22:57 UTC
### Source information

vomic 1.4.1

### Source language

Chinese

### Steps to reproduce

vomic源的两个镜像网站一个不能看，一个会报错。现在vomic漫画大部分只有在你来社区能看。

### Expected behavior

可以重新修一下这个源吗？

### Actual behavior

修改一下源

### Tachiyomi version

0.14.6 

### Android version

Andorid 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by anenasa** [comment] 2023-06-28 03:02
Duplicate of #16625

**Closed** 2023-06-28 05:55 UTC
Labels: Bug
