### ISSUE TITLE
[Source Request] <MangaXY>

### ISSUE THREAD

**Issue by hotboymrt** [tachiyomiorg/tachiyomi-extensions#6070] opened 2021-03-05 05:32 UTC
## Source website
- Name: MangaXY
- Link: https://mangaxy.com/
- Language(s): Vietnamese

## Other details
Source Manhwa 18+

**Comment by scb261** [comment] 2021-03-05 09:37
Duplicate of #5575

**Closed by scb261** 2021-03-05 09:37 UTC
Labels: Source Request
