### ISSUE TITLE
TCB scans: noresult

### ISSUE THREAD

**Issue by Darkwing32** [tachiyomiorg/tachiyomi-extensions#7891] opened 2021-06-26 19:35 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

1.0.17

### Android version

Android 10

### Source information

TCB Scans

### Steps to reproduce

Open the the extension

### Expected behavior

Shows you the manga

### Actual behavior

No results

### Other details

I've noticed the extension has been broken for a few months now can someone pls fix it

**Comment by mnabid** [comment] 2021-06-27 15:20
duplicate of #6869

**Closed** 2021-06-27 15:36 UTC
Labels: Bug
