### ISSUE TITLE
LH Translations Error 404 in app but not in Webview

### ISSUE THREAD

**Issue by hjdrm** [tachiyomiorg/tachiyomi-extensions#8962] opened 2021-09-04 09:02 UTC
### Source information

LH Translation 1.2.7

### Steps to reproduce

1. Click on latest in LH Translation
2. It says Error 404, Try webview
3. Click Webview, the site is doing fine. 

### Expected behavior

After clicking the 'latest' in LH Translation, it should show the manga updates.

### Actual behavior

Shows Error 404 after clicking 'Latest'

### Tachiyomi version

0.12.1

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Arraiment** [comment] 2021-09-05 09:02
Fix in the works #8896, duplicate of #8727

**Closed** 2021-09-05 13:18 UTC
Labels: Bug
