### ISSUE TITLE
Manga-TR: Page Not Loading

### ISSUE THREAD

**Issue by ArminArlert31** [tachiyomiorg/tachiyomi-extensions#18142] opened 2023-09-25 13:23 UTC
### Source information

Manga-TR 1.4.9

### Source language

Turkish

### Steps to reproduce

1) Manga-TR open
2) Try to open any manga 
3) page not loading error 

### Expected behavior

pages need to be loaded 

### Actual behavior

pages not loading 

### Tachiyomi version

Stable 0.14.16

### Android version

Android 12

### Other details

Please update the extansion

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2023-12-11 15:06
Duplicate of #16013

**Closed by vetleledaal** 2023-12-11 15:06 UTC
Labels: Bug
