### ISSUE TITLE
MangaSwat :There are no pages

### ISSUE THREAD

**Issue by yemenihandsome** [tachiyomiorg/tachiyomi-extensions#12095] opened 2022-06-06 13:50 UTC
### Source information

MangaSwat 1.3.21

### Steps to reproduce

1- Go to the source
 2- Open manga chapters

### Expected behavior

Chapter must be opened

### Actual behavior

The chapter did not open, it appears that there are no pages
![Screenshots_2022-06-06-16-44-31](https://user-images.githubusercontent.com/87826849/172173822-0618d27a-97cd-4f10-a81a-2f452e3d1b7d.png)

### Tachiyomi version

0.13.4

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-06-06 13:53
Duplicate of #10318

**Closed by arkon** 2022-06-06 13:53 UTC
Labels: Bug
