### ISSUE TITLE
Gmanga not loading new chapters

### ISSUE THREAD

**Issue by alucard61** [tachiyomiorg/tachiyomi-extensions#10214] opened 2021-12-24 09:04 UTC
### Source information

GMANGA 1.2.8

### Steps to reproduce

When i refresh manga to get new chapter it show me 
HTTP error 103 
Index: 4, size: 2

### Expected behavior

New chapter shows

### Actual behavior

HTTP error 103
Index: 4, size: 2

### Tachiyomi version

0.12.3

### Android version

Android 10

### Other details

All the arabic sources act the same 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2021-12-24 12:15
Duplicate of #10178

**Closed by alessandrojean** 2021-12-24 12:15 UTC
Labels: Bug
