### ISSUE TITLE
Mangaowl: Failed to bypass cloudfare

### ISSUE THREAD

**Issue by sabbyby** [tachiyomiorg/tachiyomi-extensions#8502] opened 2021-08-10 08:41 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.12.1

### Android version

Android 8

### Source information

Mangaowl

### Steps to reproduce

1. Open a manga
2. Does not load
3. Result in failure to bypass cloudfare

### Expected behavior

Works properly

### Actual behavior

Failed to bypass cloudfare. 

### Other details

![20210810_164021](https://user-images.githubusercontent.com/88506198/128836078-d31238df-fa6e-4739-9c5b-e3a07998975c.jpg)

**Comment by CVIUS** [comment] 2021-08-10 09:36
duplicate of #8456

**Closed** 2021-08-10 10:23 UTC
Labels: Bug
