### ISSUE TITLE
[Bug] <MangaOwl>: <Failed to bypass Cloudfare>

### ISSUE THREAD

**Issue by frostydasnowman** [tachiyomiorg/tachiyomi-extensions#5280] opened 2020-12-30 10:18 UTC
It's been a month or two and MangaOwl still doesn't load; no matter how many times I open it on Webview and come back to refresh my libraries, it still says I failed to bypass Cloudfare. I can't browse new chapters unless I visit the MangaOwl on webview or my browser. Please fix this. I love MangaOwl.

**Comment by scb261** [comment] 2020-12-30 11:15
Duplicate of #4552, make sure you're using the latest version of the app, extension, and WebView. If still doesn't work - blame the site for using such Cloudflare

**Closed** 2020-12-30 11:46 UTC
Labels: bug
