### ISSUE TITLE
HTTP Error 429 1st Kiss (EN)

### ISSUE THREAD

**Issue by K1rachan** [tachiyomiorg/tachiyomi-extensions#11292] opened 2022-04-01 05:40 UTC
### Source information

1st Kiss English 1.2.23

### Steps to reproduce

1. Open the app
2. Trying to update the mangas
3. Error message "HTTP Error 429"

### Expected behavior

The mangas getting updated when ther is a new chapter

### Actual behavior

The mangas didn't got updated when ther are new chapters.

### Tachiyomi version

0.13.1

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment] 2022-04-01 06:04
>  I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open issue.

Duplicate of #11280

**Closed by curche** 2022-04-01 06:04 UTC
Labels: Bug
