### ISSUE TITLE
Issue in mangaswat

### ISSUE THREAD

**Issue by 7allom** [tachiyomiorg/tachiyomi-extensions#12754] opened 2022-07-27 10:05 UTC
### Source information and language

Mangaswat 1.3.22 arabic

### Steps to reproduce

When open any chapter in that source
It shows a message
![Screenshot_20220727_130341](https://user-images.githubusercontent.com/97411710/181220969-74d8256f-cb69-4475-830b-3e39b27d75a2.jpg)

### Expected behavior

It should open the chapter 

### Actual behavior

It didn't open

### Tachiyomi version

1.8.4

### Android version

8.1.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment] 2022-07-27 10:08
>  I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open issue.

Duplicate of #12183

**Closed by curche** 2022-07-27 10:08 UTC
Labels: Bug
