### ISSUE TITLE
Zinchamanga 

### ISSUE THREAD

**Issue by Delmarcop52** [tachiyomiorg/tachiyomi-extensions#15915] opened 2023-03-31 14:16 UTC
### Source information and language

Zinchamanga 

### Steps to reproduce

1. I changed dns

### Expected behavior

The manga covers show up

### Actual behavior

It keeps saying that java security certpath

### Tachiyomi version

0.14.3

### Android version

Motorola 

### Other details

Manga is not showing up 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment] 2023-03-31 14:41
Duplicate of #15738

**Closed by stevenyomi** 2023-03-31 14:41 UTC
Labels: Bug
