### ISSUE TITLE
InariManga

### ISSUE THREAD

**Issue by Suiren5** [tachiyomiorg/tachiyomi-extensions#13025] opened 2022-08-16 14:20 UTC
### Source information and language

InariManga 1.3.16

### Steps to reproduce

No funciona, deberian aparecer los manhwas y aparece en blanco 
![Screenshot_2022-08-16-13-49-27-246_eu kanade tachiyomi](https://user-images.githubusercontent.com/104227072/184903118-ff7f3073-c37e-4a22-882c-9ae109e7d92c.jpg)

### Expected behavior

Deberían aparecer los manhwas

### Actual behavior

No aparece y sale error, como si no estuviera conectado con la pagina

### Tachiyomi version

0.13.6

### Android version

Miui 12.5.8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2022-10-01 23:41
Duplicate of #12523

**Closed by vetleledaal** 2022-10-01 23:41 UTC
Labels: Bug
