### ISSUE TITLE
Zahard extension not working

### ISSUE THREAD

**Issue by priyanshu-singhania** [tachiyomiorg/tachiyomi-extensions#16024] opened 2023-04-11 09:36 UTC
### Source information

Zahard 1.4.7

### Source language

English

### Steps to reproduce

Http error 404 on trying to browse Zahard
![Screenshot_20230411_144945_TachiyomiSY](https://user-images.githubusercontent.com/44305006/231117697-bec7c952-ad06-4055-80e3-956a1231ed73.jpg)
![Screenshot_20230411_145044_TachiyomiSY](https://user-images.githubusercontent.com/44305006/231117713-55ca5256-7982-402c-b04a-8467c9886d18.jpg)

### Expected behavior

On browsing zahard, content should have been shown.

### Actual behavior

But since, zahard website domain has changed from "zahard.top" to "zahard.xyz"
App is unable to redirect and no content is fetched from the website.

### Tachiyomi version

0.14.5

### Android version

Android 11

### Other details

The problem is the lack of redirection.
Thus, if the domain of zahard extension is changed from zahard.top to zahard.xyz
Then this will solve the problem and content will be fetched.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by scb261** [comment] 2023-04-11 10:13
Duplicate of #13491

**Closed by scb261** 2023-04-11 10:13 UTC
Labels: Bug
