### ISSUE TITLE
KomikIndoID all comic Image broken 

### ISSUE THREAD

**Issue by Subadrunz** [tachiyomiorg/tachiyomi-extensions#13837] opened 2022-10-13 00:08 UTC
### Source information and language

KomikIndoID 1.3.6 (Indonesia) 

### Steps to reproduce

1. Use komikIndoID extension
2. Choose any manga in there

### Expected behavior

Normal as usual 

### Actual behavior

Image could not be loaded (broken) 

### Tachiyomi version

0.13.6

### Android version

Android 12

### Other details

![IMG_20221013_070359](https://user-images.githubusercontent.com/107401290/195469812-1785a004-10da-4a16-9645-47d1a9165cc4.jpg)
![IMG_20221013_070507](https://user-images.githubusercontent.com/107401290/195469819-19a179d5-66b5-4e6d-9807-52977ad3c566.jpg)
![IMG_20221013_070552](https://user-images.githubusercontent.com/107401290/195469820-58dd6cd1-9765-477d-80f0-ec40fbeb5131.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment] 2022-10-13 01:12
duplicate of #13815

**Closed by Riztard** 2022-10-13 01:12 UTC
Labels: Bug
