### ISSUE TITLE
[Bug] FMReader (Hanascan): Domain and website unavailable

### ISSUE THREAD

**Issue by FoxInFlame** [tachiyomiorg/tachiyomi-extensions#5610] opened 2021-01-31 20:16 UTC
## Device information
- Tachiyomi version: 0.10.7
- Android version: 10 (EMUI 10.0.0)

## Source information
- Name: HanaScan (RawQQ), from the aggregator FMReader
- Extension version: 1.2.26

## Steps to reproduce
1. Install the FMReader extension
2. Open the HanaScan source

### Expected behavior
Manga (and the associated website at hanascan.com) should load.

### Actual behavior
The website has been down for over a month, and Tachiyomi shows the message: "Unable to resolve host hanascan.com: No address associated with hostname."

## Other details
I do not know of any replacement website (or whether they renamed themselves to something else), but I hope they did - HanaScan (RawQQ) had the most reliable collection of raw manga.

**Comment by Riztard** [comment] 2021-02-01 04:32
its not a bug until you really know if they change website =.=

**Comment by OncePunchedMan** [comment] 2021-02-01 08:33
could be they changed domain to hanascan.xyz

**Comment by scb261** [comment] 2021-02-07 22:57
I'm not sure why the author reacted with heart, hanascan.xyz doesn't look like new domain. HanaScan in FMReader is Japan source, while hanascan.xyz has English translations with watermarks from different site

**Comment by Riztard** [comment] 2021-03-22 17:17
ill just close this till there is link to their new website, maybe dead scan

**Closed by Riztard** 2021-03-22 17:17 UTC
Labels: bug
