### ISSUE TITLE
Mangás Chan: Covers does not load

### ISSUE THREAD

**Issue by MicOliv** [tachiyomiorg/tachiyomi-extensions#12852] opened 2022-08-03 09:56 UTC
### Source information and language

Mangás Chan 1.3.14

### Steps to reproduce

enter any manga and wait for it to load the chapters, but when it exits the image will no longer load nor will you be able to change it to any other image you want

### Expected behavior

manga images should be loaded

### Actual behavior

the images do not load

### Tachiyomi version

0.13.5

### Android version

Android 11

### Other details

the scan site is normal, including the chapters are not giving error, only the images

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by MicOliv** [comment] 2022-08-04 17:06
I don't know if I understood so I'm sorry, what's wrong are the covers of the manga that don't load, I went to the extension's website and tried to save a cover of a manga but it's like it doesn't have an image but at the same time it does, and even if I change it to one that I have on my own tachiyomi it doesn't work, it's like I don't have a space to put images

**Comment by MicOliv** [comment] 2022-08-07 22:55
I just saw here on the extension site that you can save manga cover images, and I've already updated tachiyomi and even so the covers don't load and you can't save

**Comment by Lucasmoura777** [comment] 2022-08-10 22:55
I was looking to see if anyone had reported this issue, I'm also having this issue

**Comment by Lucasmoura777** [comment] 2022-08-12 11:56
Alessandojean, will someone fix it? I really like this extension because new chapters always launch quickly in this extension, if the manga covers load it will be perfect

**Comment by alessandrojean** [comment] 2022-08-12 12:17
It will be fixed when I have some free time, there's no ETA. Contributors work on issues when they want/have time for it. Wait for it or just migrate to better sources.

**Comment by alessandrojean** [comment] 2022-08-19 22:14
Not able to reproduce, it was probably fixed by the merge of WpMangaStream and WpMangaReader.

Feel free to open a new issue if the problem start happening again.

**Closed by alessandrojean** 2022-08-19 22:14 UTC
Labels: Bug
