### ISSUE TITLE
[Source Request ] <m.alimanhua.com> Chinese 

### ISSUE THREAD

**Issue by khunsdata** [tachiyomiorg/tachiyomi-extensions#6732] opened 2021-04-27 20:37 UTC
## Source website
- Name: alimanhua
- Link: http://m.alimanhua.com
- Language(s): Chinese

**Comment by keinezeit8** [comment] 2021-04-28 09:26
duplicate of   #6527

**Closed** 2022-02-05 22:01 UTC
Labels: Source request
