### ISSUE TITLE
InariManga

### ISSUE THREAD

**Issue by Suiren5** [tachiyomiorg/tachiyomi-extensions#15331] opened 2023-02-12 10:10 UTC
### Source information and language

InariManga 1.4.24

### Steps to reproduce

No se reproduce los manhwas de la fuente, ya que se cambio el formato de origen

### Expected behavior

Se deberían poder leer los manhwas de la extension

### Actual behavior

No se puede leer ningun manhwa, sale como si no existieran

### Tachiyomi version

0.14.4

### Android version

Miui 13.0.4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2023-02-21 20:24
Duplicate of #12523

**Closed by vetleledaal** 2023-02-21 20:24 UTC
Labels: Bug, Factory source
