### ISSUE TITLE
Add two sources

### ISSUE THREAD

**Issue by yamato44** [tachiyomiorg/tachiyomi-extensions#8782] opened 2021-08-23 17:50 UTC
### Source name

"Manga18.club" - "raws.mangazuki.co" and "mangazuki.co"

### Source link

"Manga18.club" - "raws.mangazuki.co" and "mangazuki.co"

### Language

"English" "raw"

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment] 2021-08-23 17:52
duplicate of #5253 and mangazuki already exists. Please use search.

**Closed by loocool2** 2021-08-23 17:52 UTC
Labels: Source request
