### ISSUE TITLE
Missing sources in Mangafire

### ISSUE THREAD

**Issue by SYKKUN0** [tachiyomiorg/tachiyomi-extensions#17891] opened 2023-09-10 18:39 UTC
### Source information

Mangafire

### Source language

English

### Steps to reproduce

Clicking the main source shows nothing in either popular, latest, or filter categories

![Screenshot_20230911-022055](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/107177818/1e5191da-e69b-415c-8115-250ff2b87aa3)

Some sources be found in the bookmark and are still available to read and access

![Screenshot_20230911-023059](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/107177818/8d771955-c6e5-4c0f-b6b2-449c0f45fe5d)
2
![Screenshot_20230911-023107](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/107177818/085089fa-5dfe-4724-9a97-52c2c15a3694)

But there seems to be a problem when it comes to updating the chapter

### Expected behavior

It should be able to do this 

![Screenshot_20230911-023321](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/107177818/c223a5a8-b654-4e9c-af31-b45571a29e46)

And chapters be updated like this
![Screenshot_20230911-023531](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/107177818/871a50da-20bd-4b86-9adf-912d00d848bc)

### Actual behavior

But in reality, it shows nothing
![Screenshot_20230911-022055](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/107177818/2bbf8bf0-e91f-4e4a-b8d2-fa065efbacc2)

And in the updating, it says: 

JsonDecodingException: Expected start of the object '{, but had 'EOF instead at path: 
WebView 
Romance Shoujo Fantasy 
JSON input: .....ets/t2/min/all.js? 64fd070064fdb4f9"></script></body> </ 
口 
Resume 
I1> 

![Screenshot_20230911-023052](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/107177818/3525084b-ae20-4afe-8307-b7be9bb3e12a)

### Tachiyomi version

0.14.6

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2023-09-10 18:48
Duplicate of #17715

**Closed by alessandrojean** 2023-09-10 18:48 UTC
Labels: Bug
