### ISSUE TITLE
Reaperscan not working 

### ISSUE THREAD

**Issue by Hawksaran** [tachiyomiorg/tachiyomi-extensions#16766] opened 2023-06-17 03:47 UTC
### Source information

Reaper Scans 1.4.43

### Source language

English 

### Steps to reproduce

![Screenshot_2023-06-17-09-15-00-01_79aa9bf7c61e266c5f841e42245e214b](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/132247482/af07935e-49e4-4a37-996c-39e8a3955dcd)

Reaper Scan shows no results found 

### Expected behavior

Usually the app updates normally

### Actual behavior

But today this happened 
![Screenshot_2023-06-17-09-15-00-01_79aa9bf7c61e266c5f841e42245e214b](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/132247482/a20b9674-88a5-45f8-b81c-7ed4daa9d67b)

### Tachiyomi version

R5839

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by I-Am-C0der** [comment] 2023-06-17 09:15
Duplicate of #16756

**Closed** 2023-06-17 12:32 UTC
Labels: Bug
