### ISSUE TITLE
GMANGA: Solve the partial problem of error 103

### ISSUE THREAD

**Issue by yemenihandsome** [tachiyomiorg/tachiyomi-extensions#10891] opened 2022-02-21 19:23 UTC
### Source information

GAMANGA 1.2.9 

### Steps to reproduce

Log in to the source
 manga selection
 Open manga chapters

### Expected behavior

Chapter must be opened

### Actual behavior

Automatic exit and error 101

 Note that some mangoes open naturally
 While some manga does not open

### Tachiyomi version

0.13.1

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-02-21 19:25
Duplicate of #10793

**Closed by arkon** 2022-02-21 19:25 UTC
Labels: Bug
