### ISSUE TITLE
Magus manga Can’t load manga

### ISSUE THREAD

**Issue by 7allom** [tachiyomiorg/tachiyomi-extensions#13093] opened 2022-08-19 23:45 UTC
### Source information and language

Magus manga 1. 3.25 Arabic

### Steps to reproduce

When open it from browse it says:
![Screenshot_20220820-024432](https://user-images.githubusercontent.com/97411710/185720007-2867a414-00b0-4efe-903e-3905948e308d.jpg)

### Expected behavior

. 

### Actual behavior

. 

### Tachiyomi version

1.8.5

### Android version

8.1.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-08-19 23:48
Duplicate of #11081

**Closed by alessandrojean** 2022-08-19 23:48 UTC
Labels: Bug

**Comment by 7allom** [comment] 2022-08-19 23:58
> Duplicate of #11081

This issue is very old
How do i solve it

**Comment by alessandrojean** [comment] 2022-08-19 23:58
You wait for someone to fix it, no ETA.
