### ISSUE TITLE
Pages won't load

### ISSUE THREAD

**Issue by Jaren1112** [tachiyomiorg/tachiyomi-extensions#14600] opened 2022-12-19 03:19 UTC
### Source information and language

Realm scans, English 1.3.25

### Steps to reproduce

If you open Realmscans with Tachi and check the books it's all good until you open the chapters and the pages won't open
![Screenshot_20221219-005950](https://user-images.githubusercontent.com/120999275/208340714-b7b5a1d1-a3a4-49f2-bb8e-b25a06fea8fb.jpg)

### Expected behavior

Normally the pages will load almost instantly 

### Actual behavior

The pages will load but after a minute it will stop and say "the image couldn't be loaded" "retry"

### Tachiyomi version

0.14.2

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by nart4hire** [comment] 2022-12-19 11:47
Experiencing the same issue

**Comment by vetleledaal** [comment] 2022-12-19 16:25
Duplicate of #14338

**Closed by vetleledaal** 2022-12-19 16:25 UTC
Labels: Bug
