### ISSUE TITLE
PC Version with cloud save when.

### ISSUE THREAD

**Issue by chocoblin** [tachiyomiorg/tachiyomi-extensions#8029] opened 2021-07-09 07:51 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Describe why this should be added

For people who have trouble reading for hours on a small screen that of a mobile phone, and who stay the whole day on their laptops or desktops, this would be a boon!

All we need is a pc version of tachiyomi, not on any app player like bluestacks, but actual .exe application.
It should sport a cloud save feature so that we can sync our settings, reading progress, trackers, etc. on the go between our multiple devices.
Backing up and restoring takes sooooo long each time. That's why I request the cloud sync feature. But I understand it can be troublesome as these would require servers from your part. It can be skipped, but would be a great feature imo.

Hope my wish comes true!

**Comment by loocool2** [comment] 2021-07-09 07:53
wrong repo and this is a duplicate of https://github.com/tachiyomiorg/tachiyomi/issues/912 and some other issues anyway

**Closed by loocool2** 2021-07-09 07:53 UTC
Labels: Meta request

**Comment by chocoblin** [comment] 2021-07-09 08:08
> wrong repo and this is a duplicate of [tachiyomiorg/tachiyomi#912](https://github.com/tachiyomiorg/tachiyomi/issues/912) and some other issues anyway

that issue only talks about cloud. my request was primarily pc version. what is the right repo

**Comment by loocool2** [comment] 2021-07-09 08:10
tachiyomiorg/tachiyomi is the correct repo. PC support has been denied as of https://github.com/tachiyomiorg/tachiyomi/issues/2587

**Comment by chocoblin** [comment] 2021-07-09 08:20
oh i'm sorry. didn't notice the 'extensions' text. thought this was the base tachiyomi repo my bad.
