### ISSUE TITLE
Hitomi.la extention error

### ISSUE THREAD

**Issue by taizi02** [tachiyomiorg/tachiyomi-extensions#11013] opened 2022-03-04 23:44 UTC
### Source information

Latest hitomi.la extention

### Steps to reproduce

1.install the extention.
2. open it.

### Expected behavior

the goods should show up.

### Actual behavior

Http error 403: visit in webview.
i should have been able to browse em goodies using the app extention but somehow it doesnt work. using browsers like google chrome to browse the site works fine but the extention does not.

### Tachiyomi version

0.13.1

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-03-04 23:45
Please follow the instructions before opening new issues.

Duplicate of #10319

**Closed by arkon** 2022-03-04 23:45 UTC
Labels: Bug
