### ISSUE TITLE
Manga MundoDrama

### ISSUE THREAD

**Issue by edmxn** [tachiyomiorg/tachiyomi-extensions#12041] opened 2022-06-02 01:19 UTC
### Source name

Manga MundoDrama

### Source link

https://manga.mundodrama.site/

### Language

Spanish

### Other details

![Screenshot_20220601-191819_Opera](https://user-images.githubusercontent.com/101371218/171527145-bd7d5d9d-aeec-4c68-a8df-c3f0b5e5f822.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2022-06-16 15:53
Uses Madara theme

**Comment by vetleledaal** [comment] 2022-07-19 11:00
Duplicate of #8362, already implemented in #8597

**Closed by vetleledaal** 2022-07-19 11:00 UTC
Labels: Source request, Factory source
