### ISSUE TITLE
mangabuddy source isn't working

### ISSUE THREAD

**Issue by armiahelmy** [tachiyomiorg/tachiyomi-extensions#14983] opened 2023-01-16 22:17 UTC
### Source information and language

MangaBuddy 1.3.12

### Steps to reproduce

it's not working anymore just keeps reloading

### Expected behavior

it should load manga normally

### Actual behavior

it is stuck on loading

### Tachiyomi version

j2k 1.6.0

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment] 2023-01-16 22:19
>  I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open or closed issue.

Duplicate of #14967

**Closed by curche** 2023-01-16 22:19 UTC
Labels: Bug
