### ISSUE TITLE
Mangakakalot.fun

### ISSUE THREAD

**Issue by vncrack** [tachiyomiorg/tachiyomi-extensions#13000] opened 2022-08-15 13:19 UTC
### Source information and language

Mangakakalot.fun 1.3.7

### Steps to reproduce

1. Choose mangakakalot.fun source
2. Open a manga

### Expected behavior

Chapter loads normally

### Actual behavior

Unexpected JSON token at offset 111

### Tachiyomi version

0.13.6

### Android version

Android 12

### Other details

Mangapark v3 also affected

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2022-08-15 13:27
Duplicate of #12982 and your mangapark one has already been reported.

**Closed by Seishirou101** 2022-08-15 13:27 UTC
Labels: Bug
