### ISSUE TITLE
[Feature Request] <MangaKatana>: <add multi include/exclude option in filter>

### ISSUE THREAD

**Issue by bungadrum** [tachiyomiorg/tachiyomi-extensions#5893] opened 2021-02-17 08:27 UTC
Great that you added filter in MangaKatana wheter Official/Unofficial, but can you plz add the option to select multiple genres. Right now you can only pick one option to display. Or could you add the option to exclude genre that you don't want to appear. For example I don't want Yaoi, Manhwa or Webtoon to appear, but I can only select one option in the filter. Or could you add a box to paste the URL like in the website.

https://snipboard.io/MO5Kdv.jpg

**Comment by scb261** [comment] 2021-02-17 11:29
Duplicate of #5128

**Closed by scb261** 2021-02-17 11:29 UTC
Labels: enhancement
