### ISSUE TITLE
LynxScan error 404 on app but works on webview

### ISSUE THREAD

**Issue by semiyparxi** [tachiyomiorg/tachiyomi-extensions#15577] opened 2023-03-03 19:02 UTC
### Source information and language

LynxScans 1.4.6

### Steps to reproduce

1. Open Extension

### Expected behavior

1. Open Extension
2. Manhwa/Manga Library loads

### Actual behavior

1. Open Extension
2. It shows "HTTP error 404: Check website on Webview

### Tachiyomi version

0.14.5

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment] 2023-04-02 09:46
Duplicate of #15507

**Closed by stevenyomi** 2023-04-02 09:46 UTC
Labels: Bug
