### ISSUE TITLE
MangaFire: Broken JSON parsing

### ISSUE THREAD

**Issue by BigBearBulrok** [tachiyomiorg/tachiyomi-extensions#17799] opened 2023-09-05 09:23 UTC
### Source information

MangaFire 1.4.2

### Source language

English

### Steps to reproduce

1. Open Mangafire
2. Go to any Manga 
3. Scroll down, no chapter is found & the error note is found

--- Bonus ---
If you save any manga before the bug the chapter will appear
but went you go to Mangafire to looked at the save manga is no longer on your library 

https://github.com/tachiyomiorg/tachiyomi-extensions/assets/112532217/680aa040-f9ca-46cc-b29f-5cc28d633253

### Expected behavior

Shows the Manga that is in your library

![What supposed to look in Library](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/112532217/0fa5e95c-1c79-4163-a027-7357655e9a6d)

Shows the list of how many chapter there are on a Manga

![What supposed to look in Manga](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/112532217/400207e1-383d-45c3-86e2-2ca379e992ec)

### Actual behavior

Shows no Manga is in your library

![No Library on Mangafire](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/112532217/a17bd5c6-7a2c-47df-93fc-3d7c2cd51bf8)

Shows no chapter on any Manga and give you an error msg

![No Chapter on Mangafire](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/112532217/b3e99d0b-3d8e-4312-8e00-008637a2df37)

### Tachiyomi version

0.14.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by amf07** [comment] 2023-09-09 05:44
Update:
Still no response this time not showing anything even the Json error

**Comment by Neverdusk** [comment] 2023-09-09 14:37
Just want to chime in to say I'm also getting the same error. Nothing in my library from MangaFire will update, and no titles can be found in the extension when searching for a manga.

**Comment by vetleledaal** [comment] 2023-09-14 07:05
Looked a bit into this. Not too familiar with the extension structure used here, maybe someone else can work on it:

Fixes #17715:
```kt
override fun searchMangaSelector() = ".original.card-lg .unit .inner"

override fun searchMangaFromElement(element: Element) =
SManga.create().apply {
    element.selectFirst(".info > a")!!.let {
        setUrlWithoutDomain(it.attr("href"))
        title = it.ownText()
    }
    element.selectFirst(Evaluator.Tag("img"))!!.let {
        thumbnail_url = it.attr("src")
    }
}
```

Partial #17799:
```kt
override fun chapterListRequest(mangaUrl: String, type: String): Request {
    val id = mangaUrl.substringAfterLast('.')
    return GET("$baseUrl/ajax/manga/$id/$type/$langCode", headers)
}

override fun parseChapterElements(response: Response, isVolume: Boolean): List<Element> {
    val result = json.decodeFromString<ResponseDto2>(response.body.string()).result
    val document = Jsoup.parse(result)

    val elements = document.select("ul li")
    elements.forEach { it.attr("data-id", it.attr("data-number")) }
    return elements.toList()
}

@Serializable
class ResponseDto2(
    val result: String,
    val status: Int,
)
```

**Comment by amf07** [comment] 2023-09-18 12:50
Hi was wondering update to this I believed there's a lot of duplicate of posts with regard to this URL issues posted here.

**Comment by MikaelaMuller** [comment] 2023-09-18 23:03
Bumped issue
![Uploading Screenshot_20230919-065634_Aniyomi.png…]()

**Comment by CyberSlither** [comment] 2023-09-25 14:15
> Looked a bit into this. Not too familiar with the extension structure used here, maybe someone else can work on it:
> 
> Fixes #17715:
> 
> ```kotlin
> override fun searchMangaSelector() = ".original.card-lg .unit .inner"
> 
> override fun searchMangaFromElement(element: Element) =
> SManga.create().apply {
>     element.selectFirst(".info > a")!!.let {
>         setUrlWithoutDomain(it.attr("href"))
>         title = it.ownText()
>     }
>     element.selectFirst(Evaluator.Tag("img"))!!.let {
>         thumbnail_url = it.attr("src")
>     }
> }
> ```
> 
> Partial #17799:
> 
> ```kotlin
> override fun chapterListRequest(mangaUrl: String, type: String): Request {
>     val id = mangaUrl.substringAfterLast('.')
>     return GET("$baseUrl/ajax/manga/$id/$type/$langCode", headers)
> }
> 
> override fun parseChapterElements(response: Response, isVolume: Boolean): List<Element> {
>     val result = json.decodeFromString<ResponseDto2>(response.body.string()).result
>     val document = Jsoup.parse(result)
> 
>     val elements = document.select("ul li")
>     elements.forEach { it.attr("data-id", it.attr("data-number")) }
>     return elements.toList()
> }
> 
> @Serializable
> class ResponseDto2(
>     val result: String,
>     val status: Int,
> )
> ```

Hi, i was wondering what do with this code to fix the problem
Where do i have to paste this?

**Comment by Roy-deity** [comment] 2023-09-26 18:35
Someone please help this person to get mangafire fixed.

**Comment by vetleledaal** [comment] 2023-09-30 17:11
> Hi, i was wondering what do with this code to fix the problem Where do i have to paste this?

In `multisrc/overrides/mangareader/mangafire/src/MangaFire.kt`, it still requires additional changes. Read [CONTRIBUTING.md](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/CONTRIBUTING.md) first, then ask in #programming on Discord if you need help.

**Closed** 2023-10-01 22:19 UTC
Labels: Bug
