### ISSUE TITLE
change in manhwas.net

### ISSUE THREAD

**Issue by KuroNeko0118** [tachiyomiorg/tachiyomi-extensions#14415] opened 2022-11-30 04:21 UTC
### Source information and language

manhwas.net

### Steps to reproduce

They have made a change in the appearance of the manhwas.net page, therefore it no longer allows searching and/or updating

### Expected behavior

Allow updating and searching the content of manhwas.net

### Actual behavior

It fails in the search and page display

### Tachiyomi version

0.14.2

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by KasukeLp23** [comment] 2022-11-30 11:52
Yeah, the extension is not working.

**Comment by vetleledaal** [comment] 2022-11-30 14:33
Duplicate of #13008. The error is now "content must not be null", but this is essentially the same.

**Closed by vetleledaal** 2022-11-30 14:33 UTC
Labels: Bug
