### ISSUE TITLE
[Source Request] <Gekkou Scans>

### ISSUE THREAD

**Issue by luscarvalho** [tachiyomiorg/tachiyomi-extensions#5855] opened 2021-02-15 00:27 UTC
- Name: Gekkou Scans
- Link: http://leitor.gekkouscans.com.br/
- Language(s): Portuguese(Br)

**Comment by alessandrojean** [comment] 2021-02-15 01:11
Duplicate of #4458.

**Closed** 2021-02-15 01:15 UTC
Labels: Source Request
