### ISSUE TITLE
Chapter not showing

### ISSUE THREAD

**Issue by raytonic** [tachiyomiorg/tachiyomi-extensions#10965] opened 2022-02-28 14:17 UTC
### Source information

Dynasty-doujin 1.2.16

### Steps to reproduce

Open dynasty doujin and look for " touhou project doujin" and look at the chapter select

### Expected behavior

It should have shown a ton of different touhou doujin in chapter select

### Actual behavior

But it only shows 1 chapter

### Tachiyomi version

0.13.1

### Android version

Android 11

### Other details

https://imgur.com/a/35irHt0
How it looks like

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment] 2022-02-28 15:49
Duplicate of #10560

**Closed by curche** 2022-02-28 15:49 UTC
Labels: Bug
