### ISSUE TITLE
MangaHub: Unable to read Manga 

### ISSUE THREAD

**Issue by TysonBlaze009** [tachiyomiorg/tachiyomi-extensions#15613] opened 2023-03-06 17:54 UTC
### Source information and language

Mangahub 1.4.27(English) 

### Steps to reproduce

1. Unable to read manga
2. Manga chapter pages are not loading says "The Image couldn't be loaded".
3. Completed manga also shows "The Image couldn't be loaded" for all chapters.

### Expected behavior

All pages should have been uploaded properly.

### Actual behavior

In a chapter of any manga in between pages shows "The Image couldn't be loaded".

### Tachiyomi version

0.14.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2023-03-06 20:31
Duplicate of #14736

**Closed by Seishirou101** 2023-03-06 20:31 UTC
Labels: Bug

**Comment by TysonBlaze009** [comment] 2023-03-08 16:08
If you knew this issue has a duplicate then resolve it.
