### ISSUE TITLE
Reaper Scan No page

### ISSUE THREAD

**Issue by XY0511** [tachiyomiorg/tachiyomi-extensions#16797] opened 2023-06-20 12:33 UTC
### Source information

Reaper Scans 1.4.43

### Source language

English

### Steps to reproduce

1. Select a Title
2. Open a chapter
3. Wait for the load and the error "No Page Found"

### Expected behavior

There should've been pages

### Actual behavior

"No pages Found"

### Tachiyomi version

 0.14.6

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2023-06-20 12:37
Duplicate of #16756

**Closed by alessandrojean** 2023-06-20 12:37 UTC
Labels: Bug
