### ISSUE TITLE
[Source Request] MangaWorld ITA

### ISSUE THREAD

**Issue by shady1919** [tachiyomiorg/tachiyomi-extensions#6536] opened 2021-04-14 01:29 UTC
MangaWord (ITALIAN) extension doesn't work.
Please fix it

https://www.mangaworld.io/

**Comment by ilmastr0** [comment] 2021-04-14 01:38
Dai cazzo

**Comment by Riztard** [comment] 2021-04-14 10:15
duplicate of #6534

**Closed by Riztard** 2021-04-14 10:15 UTC
Labels: Source Request, duplicate
