### ISSUE TITLE
[Bug] <Toonily>: <failed>

### ISSUE THREAD

**Issue by kasakaka** [tachiyomiorg/tachiyomi-extensions#6511] opened 2021-04-12 11:14 UTC
toonily when downloading or browsing either shows failed to bypass cloudflair or timeout already tried the guide in the troubleshoot that the tachiyomi posted where i opened the webviewed but instead of showing the list i got the timeout screen

**Comment by CrepeTF** [comment] 2021-04-12 11:16
¯\_(ツ)_/¯ nothing else you can do then, cloudflare is out of our control

**Comment by fam007e** [comment] 2021-04-12 11:58
After updating webview app, it solves cloudfare verification bt entering the browse option after webview cloudfare verification causes "timeout"....
😦

**Comment by scb261** [comment] 2021-09-14 21:06
Duplicate of #5613

**Closed** 2021-09-14 21:26 UTC
Labels: Bug
