### ISSUE TITLE
Discord rpc for tachij2k

### ISSUE THREAD

**Issue by noteXw** [tachiyomiorg/tachiyomi-extensions#15937] opened 2023-04-02 09:52 UTC
### Source name

mangadex

### Source language

english

### Describe your suggested feature

please add discord rpc for tachij2k

### Other details

need that feature

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment] 2023-04-02 10:34
Duplicate of https://github.com/Jays2Kings/tachiyomiJ2K/issues/1464

**Closed by stevenyomi** 2023-04-02 10:34 UTC
Labels: Feature request

**Comment by noteXw** [comment] 2023-04-02 10:36
I wanna know about this bro how can i contact you ?

**Comment by BraveDude8** [comment] 2023-04-02 14:49
What does MangaDex have to do with Discord RPC?
