### ISSUE TITLE
Gmanga CRISIS!! 

### ISSUE THREAD

**Issue by AzoralD** [tachiyomiorg/tachiyomi-extensions#10332] opened 2022-01-04 15:08 UTC
### Source information

Gmanga

### Steps to reproduce

Gmanga is huge Arabic manga/manhwa/comic source at least in app, I don't hide Tachiyomi very bad with one of biggest manga community... 

### Expected behavior

Work, open manga, shows details and download chapters.. 

### Actual behavior

Nothing work..
When opened it shows 404 error..
![Screenshot_2022-01-04-17-52-36-55_5901a79de973a50c74cff4cbb6149856](https://user-images.githubusercontent.com/88720098/148078684-7c0d9ff5-9864-42d7-a656-60323703bafa.jpg)
When updating the manga.. 
![Screenshot_2022-01-04-18-05-41-60_5901a79de973a50c74cff4cbb6149856](https://user-images.githubusercontent.com/88720098/148079370-4af8563a-89e5-4abf-88f1-ffd2bcaddc00.jpg)

### Tachiyomi version

0.12.3

### Android version

11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-01-04 15:19
Duplicate of #10275 and #10161

**Closed by alessandrojean** 2022-01-04 15:19 UTC
Labels: Bug
