### ISSUE TITLE
Empire Webtoon HTTP error 400: Check website in webview

### ISSUE THREAD

**Issue by IslamAbdel** [tachiyomiorg/tachiyomi-extensions#12411] opened 2022-07-02 13:26 UTC
### Source information

Empire Webtoon 1.3.21

### Steps to reproduce

Open extension 
HTTP error 400: Check website appears 

### Expected behavior

It should open 
![Uploading Screenshot_2022-07-02-15-21-32-358_eu.kanade.tachiyomi.jpg…]()

### Actual behavior

HTTP error 400: Check website
![Screenshot_2022-07-02-15-21-49-048_eu kanade tachiyomi](https://user-images.githubusercontent.com/93197738/177002802-f06268d6-06e1-4c00-b753-9c8819aa416e.jpg)

### Tachiyomi version

App version: 0.13.4

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-07-03 18:23
Duplicate of #11426

**Closed by alessandrojean** 2022-07-03 18:23 UTC
Labels: Bug
