### ISSUE TITLE
Reaper Scans no pages found

### ISSUE THREAD

**Issue by nobile01** [tachiyomiorg/tachiyomi-extensions#16789] opened 2023-06-20 02:28 UTC
### Source information

en.reaperscans 1.4.43

### Source language

English 

### Steps to reproduce

Open any item in my library from Reaper Scans
Click on any chapter
Screen goes black for half a second then gives the notification "No pages found"
Click on WebView
I can see the comic and the chapters and even open each chapter there
I go back to my library and go to Browse
Open the Reaper Scans listing
Open any of their series even ones not in my library
Still cannot open any chapter 

### Expected behavior

I should be able to open each chapter not just on WebView 

### Actual behavior

I get the following notification 
![Screenshot_20230619-211303](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/111714391/29f2f91b-c4be-45fe-8ce9-963c955471fd)

### Tachiyomi version

App version: 0.14.6 (standard, c615f4d, 101, 2023-04-16T15:14Z) 

### Android version

Android version: 13 (SDK 33) Android build ID: TQ2A.230505.002 Device brand: google Device manufacturer: Google Device name: raven Device model: Pixel 6 Pro Device product name: raven

### Other details

Problem started happening sometime after June 15th.
I have uninstalled the extension and installed it again and the issue still happens.
I have tried changing the User Agent and it still happens .
I have also restarted my phone and switched between WiFi and mobile data. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2023-06-20 02:56
Duplicate of #16756

**Closed by Seishirou101** 2023-06-20 02:56 UTC
Labels: Bug

**Comment by nobile01** [comment] 2023-06-20 02:59
It's not a duplicate the other bug was while Reaper Scans website was down and wasn't showing any results. My problem isn't lack of results, it's the chapters not showing (the website is up, I had to wait a day to report this, since I didn't want it to be confused with the other issue)
