### ISSUE TITLE
Failed to Bypass Cloudflare

### ISSUE THREAD

**Issue by Ciel-kun** [tachiyomiorg/tachiyomi-extensions#11843] opened 2022-05-13 11:05 UTC
### Source information

MG Komik 1.2.22

### Steps to reproduce

Open MG Komik

### Expected behavior

I can read manga in MG Komik normally

### Actual behavior

![Screenshot_2022-05-13-18-00-56-85](https://user-images.githubusercontent.com/81224499/168270568-8ac2619a-3b7c-4500-b20a-0366f6ecea69.png)
![Screenshot_2022-05-13-18-03-22-38](https://user-images.githubusercontent.com/81224499/168270579-4ff7b40e-b1f3-4f86-bd9e-5a10c849605e.png)

### Tachiyomi version

0.13.4

### Android version

Android 7.1.1

### Other details

I can read it in webview normally but I cant read it on tachiyomi

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-05-13 18:55
Duplicate of #11727

**Closed by alessandrojean** 2022-05-13 18:55 UTC
Labels: Bug
