### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Nerannnn** [tachiyomiorg/tachiyomi-extensions#16642] opened 2023-05-31 22:42 UTC
### Source information

Nixmangàs 

### Source language

Português 

### Steps to reproduce

Os capítulos dos mangás não estão aparecendo

### Expected behavior

This shold hapen

### Actual behavior

This hapen instead

### Tachiyomi version

0.14.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-05-31 22:45
Duplicate of #16603

**Closed by arkon** 2023-05-31 22:45 UTC
Labels: Bug
