### ISSUE TITLE
[Source Request] <Manga-raw>

### ISSUE THREAD

**Issue by Warcrors** [tachiyomiorg/tachiyomi-extensions#6411] opened 2021-04-03 19:55 UTC
**

---

## Source website
- Name: manga-raw
- Link: www.manga-raw.club
- Language(s): en

## Other details
- Needed to be added asap**

**Comment by keinezeit8** [comment] 2021-04-18 18:50
duplicate of #3754

**Closed** 2021-04-18 18:57 UTC
Labels: Source Request
