### ISSUE TITLE
xcaliber scan mirror page

### ISSUE THREAD

**Issue by miyushibana** [tachiyomiorg/tachiyomi-extensions#10230] opened 2021-12-26 07:47 UTC
### Source information

1.2.14

### Steps to reproduce

open chapter

### Expected behavior

correct image 

### Actual behavior

in web view the images are not mirrored but in tachi they are mirrored 

### Tachiyomi version

0.12.3

### Android version

a11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2021-12-26 10:51
Duplicate of #10077

**Closed by alessandrojean** 2021-12-26 10:51 UTC
Labels: Bug
