### ISSUE TITLE
AnimeSama error 404

### ISSUE THREAD

**Issue by Urbexed** [tachiyomiorg/tachiyomi-extensions#16685] opened 2023-06-07 18:00 UTC
### Source information

AnimeSama 1.4.1

### Source language

French

### Steps to reproduce

Trying to explore the anime-sama catalog

### Expected behavior

View available manga 

### Actual behavior

Error 404

### Tachiyomi version

Latest tachi2jk

### Android version

12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Kreliam** [comment] 2023-06-09 20:22
Toujours que l'extension AnimeSama a un problème  😢

**Comment by Urbexed** [comment] 2023-06-10 15:39
> Toujours que l'extension AnimeSama a un problème 😢

🥲🥲

**Comment by Kreliam** [comment] 2023-08-30 19:05
> > Toujours que l'extension AnimeSama a un problème 😢
> 
> 
> 
> 🥲🥲

Passe moi ton Discord afin d'éviter ce genre d'incident 🤣 qui est de ma faute désolé

**Comment by Urbexed** [comment] 2023-08-31 11:33
> > > Toujours que l'extension AnimeSama a un problème 😢
> > 
> > 
> > 🥲🥲
> 
> Passe moi ton Discord afin d'éviter ce genre d'incident 🤣 qui est de ma faute désolé

Urbexed

**Comment by Urbexed** [comment] 2023-08-31 17:44
> ### Source information
> AnimeSama 1.4.1
> 
> ### Source language
> French
> 
> ### Steps to reproduce
> Trying to explore the anime-sama catalog
> 
> ### Expected behavior
> View available manga
> 
> ### Actual behavior
> Error 404
> 
> ### Tachiyomi version
> Latest tachi2jk
> 
> ### Android version
> 12
> 
> ### Other details
> _No response_
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
> * [x]  I have written a short but informative title.
> * [x]  I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
> * [x]  I have updated all installed extensions.
> * [x]  I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
> * [x]  If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
> * [x]  I will fill out all of the requested information in this form.

@KirinRaikage

**Comment by KirinRaikage** [comment] 2023-10-29 19:05
Duplicate of #16015

**Closed** 2023-10-29 19:23 UTC
Labels: Bug
