### ISSUE TITLE
Zerobyw URL change report

### ISSUE THREAD

**Issue by Zfeng-zhuang** [tachiyomiorg/tachiyomi-extensions#15588] opened 2023-03-04 20:21 UTC
### Source information and language

Zerobyw 1.4.13 (Chinese)

### Source new URL

http://www.zerobyw1060.com/

### Other details

![Screenshot_2023-03-05-04-20-48-09_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/67086289/222927020-b6e0c5ec-4d55-4b9f-8819-847708e0a384.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment] 2023-03-05 04:24
Duplicate of #15134

**Closed by stevenyomi** 2023-03-05 04:24 UTC
Labels: Bug, Domain changed
