### ISSUE TITLE
Asking to get mangaswat fixed

### ISSUE THREAD

**Issue by Atifsaid** [tachiyomiorg/tachiyomi-extensions#17130] opened 2023-07-16 02:34 UTC
### Source information

Mangaswat 1.4.34

### Source language

Arabic

### Steps to reproduce

This issue happend a lot it usually last for two weeks but this it took i while so im here to ask to fixed foever 

### Expected behavior

First it was : when i click on a chapter it shows me page numbers but it says no pages found when i try to download too 

### Actual behavior

Now :When i click to enter a chapter it get out of it immediately with no explanation and when i try to download 
It says No network connection available even tho i have 

### Tachiyomi version

0.14.6

### Android version

Android 12

### Other details

It only happens in this extension

I would really really appreciate it if you could help me with this extension cus i use it A lot thank in advance ♥️

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment] 2023-07-16 02:37
Duplicate of #16952

**Closed by loocool2** 2023-07-16 02:37 UTC
Labels: Bug
