### ISSUE TITLE
PMScans needs updating since it doesnt open in tachiyomi

### ISSUE THREAD

**Issue by VgX-LeGenDz** [tachiyomiorg/tachiyomi-extensions#15767] opened 2023-03-19 16:50 UTC
### Source information and language

PMScans needs to update to Rackusreads

### Source new URL

https://rackusreads.com/

### Other details

nothing works when you try and access pmscans

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2023-09-15 14:22
Duplicate of #14331

**Closed by vetleledaal** 2023-09-15 14:22 UTC
Labels: Bug, Domain changed
