### ISSUE TITLE
Sekaikomik Failed to Bypass Cloudflare

### ISSUE THREAD

**Issue by Nvbeh6** [tachiyomiorg/tachiyomi-extensions#11428] opened 2022-04-11 03:39 UTC
### Source information

Sekaikomik

### Steps to reproduce

1.Open Sekaikomik Extension
2.Failed to Bypass Cloudflare
3.Open Webview
4.Blank Screen

### Expected behavior

captcha should appear

### Actual behavior

There is no Captcha (Just Blank)

### Tachiyomi version

0.13.2

### Android version

Android 11

### Other details

Maybe Because Sekaikomik Change Their Domain To Sekaikomik.live

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment] 2022-04-11 05:02
Duplicate of #11379  and #8220

**Closed** 2022-04-11 07:19 UTC
Labels: Bug
