### ISSUE TITLE
[Source Request] Any plan to add mangapark v3?

### ISSUE THREAD

**Issue by crest1993** [tachiyomiorg/tachiyomi-extensions#7164] opened 2021-05-21 22:29 UTC
The source in mangapark v3 is more neatly organized not like in v2 when the source is mashed from fox duck rock (it's a mess).

## Source website
- Name: Mangapark v3
- Link: https://mangapark.net
- Language(s): English

**Comment by Seishirou101** [comment] 2021-05-22 00:21
duplicate of #6726

**Comment by Seishirou101** [comment] 2021-05-22 00:23
Duplicate of #6726

**Closed** 2021-05-22 00:29 UTC
Labels: Source Request
