### ISSUE TITLE
Manhuaren no value for response 

### ISSUE THREAD

**Issue by stevenkuek** [tachiyomiorg/tachiyomi-extensions#17199] opened 2023-07-20 22:51 UTC
### Source information

Manhuaren 1.4.12

### Source language

Chinese 

### Steps to reproduce

Cannot refresh chapter
When try to read it show no value for response

### Expected behavior

Should able refresh chapter and able to read 

### Actual behavior

Error no value for response 

### Tachiyomi version

0.14.6

### Android version

Android 12 

### Other details

{
  "errorResponse": {
    "code": 40005,
    "subCode": "",
    "message": "签名错误"
  }
}

*签名错误 mean wrong signature 

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment] 2023-07-21 02:07
Duplicate of #17170

**Closed by stevenyomi** 2023-07-21 02:07 UTC
Labels: Bug
