### ISSUE TITLE
Kissmanga - Unable to Read or Download Chapters

### ISSUE THREAD

**Issue by hemanthmannam** [tachiyomiorg/tachiyomi-extensions#11383] opened 2022-04-08 13:31 UTC
### Source information

Kisssmanga 1.2.21

### Steps to reproduce

Open Kissmanga
Try to Read or Download any Chapter from Any Manga

### Expected behavior

Shuould be able to Download and View Chapters and its Pages 

### Actual behavior

Cant Download or Read Chapters 

### Tachiyomi version

0.13.1

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by MikeZeDev** [comment] 2022-04-09 12:13
It works for me as long as long as i open Webview once to pass Cloudflare check. Are you able to see something in webview? 
I use android 11 and a VPN though.

**Comment by alessandrojean** [comment] 2022-04-10 19:22
> Cant Download or Read Chapters

Please be more specific, as this doesn't help much. Specify what errors do you get.

**Comment by TheKingTermux** [comment] 2022-04-11 05:08
Can enter via webview and tachiyomi DoS using Cloudflare
Android 11 and no VPN

**Comment by Beji-kun** [comment] 2022-04-12 01:55
Same problem with extension MangaDig ahhh I will create bug for this

**Comment by Seishirou101** [comment] 2022-05-13 03:32
Closing, as not able to reproduce. You can message back for the issue to be reopened or get help on discord.

**Closed by Seishirou101** 2022-05-13 03:32 UTC
Labels: Bug
