### ISSUE TITLE
Mangastic error 400

### ISSUE THREAD

**Issue by NotPageD** [tachiyomiorg/tachiyomi-extensions#12003] opened 2022-05-28 09:40 UTC
### Source information

Mangastic

### Steps to reproduce

Open up the extension

### Expected behavior

Should work normally

### Actual behavior

Shows error 400

### Tachiyomi version

Preview r456 TachiyomiSY

### Android version

Android 11

### Other details

It maybe because they changed domains to pukamanga.com, but i just used it so i dont know if the extension was already changed to account for that.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment] 2022-06-02 07:58
duplicate of #11879

**Closed by Riztard** 2022-06-02 07:58 UTC
Labels: Bug
