### ISSUE TITLE
[Bug] asgard1team : didn't work

### ISSUE THREAD

**Issue by zeredouni** [tachiyomiorg/tachiyomi-extensions#6227] opened 2021-03-20 16:45 UTC
Source information
Name:  Asgard Team
Extension version: 1.2.1
Language : arabic

The problem :

The website has been changed from  " Madara " to another template

**Comment by Riztard** [comment] 2021-03-21 07:39
duplicate of #4730

**Closed by Riztard** 2021-03-21 07:39 UTC
Labels: bug
