### ISSUE TITLE
[Bug] <japscan>: <can't download anymore, think that we have to change url >

### ISSUE THREAD

**Issue by Kawasmile** [tachiyomiorg/tachiyomi-extensions#7032] opened 2021-05-15 11:56 UTC
## Device information

* TachiyomiJ2K version: 1.0.17

* Android version: 10

## Source information

* Name: Japscan

* Extension version: 1.2.26

## Steps to reproduce

 1. Try to see/download any manga from this source. 

### Expected behavior
 should work.

### Actual behavior

Nothing happened 

### What to do ?
Can someone change the source url from https://www.japscan.se to https://www.japscan.ws please ?

https://github.com/tachiyomiorg/tachiyomi-ex...

**Comment by h-hyuuga** [comment] 2021-05-15 12:25
Duplicate of #7017

**Closed** 2021-05-15 12:33 UTC
Labels: bug
