### ISSUE TITLE
Bato.to image covers not loading

### ISSUE THREAD

**Issue by Jvlier** [tachiyomiorg/tachiyomi-extensions#18943] opened 2023-11-12 23:19 UTC
### Source information

Bato.to 1.4.32

### Source language

English

### Steps to reproduce

Open Bato.to source
No cover image load for any titles
Same issue in library from Bato.to titles 

### Expected behavior

Covers should load in source and in library

### Actual behavior

In above 2 descriptions

### Tachiyomi version

0.14.7

### Android version

Android 13

### Other details

![Screenshot_20231112_231226_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/84441821/d1584321-4411-463c-b629-d3ec3adbe737)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2023-11-12 23:23
Duplicate of #16712

**Closed by Seishirou101** 2023-11-12 23:23 UTC
Labels: Bug
