### ISSUE TITLE
Crunchyscan

### ISSUE THREAD

**Issue by Mitia99** [tachiyomiorg/tachiyomi-extensions#8419] opened 2021-08-06 13:04 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

Crunchyscan

### Source link

http://crunchyscan.fr

### Language

French

**Comment by V0IDgit** [comment] 2021-08-06 13:20
For precision, It's a WordPress-Madara-Based Website.

**Comment by Arraiment** [comment] 2021-08-07 06:20
Duplicate of #8336?

**Comment by Mitia99** [comment] 2021-08-07 06:23
@Arraiment You're right.I'll close this one then

**Closed** 2021-08-07 06:23 UTC
Labels: Source request, Factory source
