### ISSUE TITLE
[Source Request] <GTO The Great Site>

### ISSUE THREAD

**Issue by Hazyfade** [tachiyomiorg/tachiyomi-extensions#6017] opened 2021-03-01 12:15 UTC
## Source website
- Name: GTO The Great Site reader
- Link: https://reader.gtothegreatsite.net/comics
- Language(s): Italian

## Other details
There is an obsolete extension about this site on foolside

**Comment by scb261** [comment] 2021-03-01 12:22
Duplicate of #5472

**Closed by scb261** 2021-03-01 12:22 UTC
Labels: Source Request
