### ISSUE TITLE
Komik Cast: No pages found

### ISSUE THREAD

**Issue by binbinbinbin66** [tachiyomiorg/tachiyomi-extensions#12143] opened 2022-06-09 18:32 UTC
### Source information

komik cast 1.3.25

### Steps to reproduce

when i want to read manhwa ok komik cast but i cant read it because got bug or something, the bug is page not found
![Screenshot_2022-06-10-01-20-36-03_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/101515775/172918821-a362095e-4b3e-4027-bee7-51c6dc6c58e8.jpg)

### Expected behavior

i hope i can read from komik cast again

### Actual behavior

.

### Tachiyomi version

0.13.2 and 0.13.4

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-06-09 22:03
@TheKingTermux Have you tested if the extension was working before submitting your PR?

**Comment by alessandrojean** [comment] 2022-06-10 00:25
Nevermind, this seems to be an already existing issue before.

Duplicate of #9275.

**Closed by alessandrojean** 2022-06-10 00:25 UTC
Labels: Bug
