### ISSUE TITLE
Mangaowl

### ISSUE THREAD

**Issue by Haesoo2** [tachiyomiorg/tachiyomi-extensions#10548] opened 2022-01-22 14:04 UTC
### Source information

Mangaowl 1.2.24

### Steps to reproduce

There are no pages found.

### Expected behavior

There should be pages

### Actual behavior

This happened instead: When I Tap the unread chapter it says no pages found

### Tachiyomi version

0.12.3

### Android version

Andoid 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-01-22 14:05
Duplicate of #10464

**Closed by alessandrojean** 2022-01-22 14:05 UTC
Labels: Bug
