### ISSUE TITLE
Too many follow-up requer:21

### ISSUE THREAD

**Issue by Meiira** [tachiyomiorg/tachiyomi-extensions#11972] opened 2022-05-25 04:13 UTC
### Source information

Neox Scanlator 1.2.33

### Steps to reproduce

1- Sources menu
2- Tap the Neox Scanlator

### Expected behavior

Update manga/chapter

### Actual behavior

Erro Too many follow-up requer:21 

![Screenshot_20220525-012413_Tachiyomi](https://user-images.githubusercontent.com/106220343/170180179-46479f9a-0ab8-4558-8641-12e9b57a1524.jpg)

### Tachiyomi version

0.13.4

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-05-25 04:51
Duplicate of #11953

**Closed by alessandrojean** 2022-05-25 04:51 UTC
Labels: Bug
