### ISSUE TITLE
MangaFire 

### ISSUE THREAD

**Issue by iCeY3** [tachiyomiorg/tachiyomi-extensions#17870] opened 2023-09-10 09:29 UTC
### Source name

MangaFire 1.4.2

### Source language

Multi

### Source link

Mangafire.to

### Other details

Website upgraded to v2 and extension is down now

Please fix

Thanks 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2023-09-10 09:37
Duplicate of #17715

**Closed by vetleledaal** 2023-09-10 09:37 UTC
Labels: Source is down
