### ISSUE TITLE
Shinigami

### ISSUE THREAD

**Issue by Hyperhakuba** [tachiyomiorg/tachiyomi-extensions#15417] opened 2023-02-20 13:53 UTC
### Source information and language

ReaperScans 1.4.39 (multi)

### Source new URL

Shinigami.id

### Other details

They change their website address recently, i don't know why...

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2023-02-20 14:00
Duplicate of #15408

**Closed by alessandrojean** 2023-02-20 14:00 UTC
Labels: Bug, Domain changed
