### ISSUE TITLE
Mangaswat redirecting issue 

### ISSUE THREAD

**Issue by 7allom** [tachiyomiorg/tachiyomi-extensions#18305] opened 2023-10-01 20:07 UTC
### Source information

1.4.39

### Source language

Arabic

### Steps to reproduce

When entering any manhwa in webview it redirects to the main menu 

### Expected behavior

It should open the manhwa Webview page

### Actual behavior

It doesn't open webview and redirects to the main menu 

### Tachiyomi version

1.9.3

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment] 2023-10-01 23:44
Duplicate of #18175

**Closed** 2023-10-01 23:45 UTC
Labels: Bug, Duplicate
