### ISSUE TITLE
[Feature Request] <ReManga>: <authorization>

### ISSUE THREAD

**Issue by Nonamow** [tachiyomiorg/tachiyomi-extensions#6298] opened 2021-03-26 16:56 UTC
Well, I know that as I see now we can set username and password in settings. But I login with google account.
So my idea is login using WebView and then grab cookie (Does it work that way?). This is much more comfortable for the users then setting up user&pass in settings.

**Comment by scb261** [comment] 2021-03-26 19:30
> So my idea is login using WebView and then grab cookie (Does it work that way?)

It should. Did you have problems doing it?

**Comment by Nonamow** [comment] 2021-03-26 19:43
Oh... Yes, that seems like I have.

**Comment by scb261** [comment] 2021-03-26 19:48
Are you planning to give more details? I just logged in with google and accessed a locked manga without any problems.

**Comment by Nonamow** [comment] 2021-03-26 19:58
Also I can't logout, because WebView can't open menu with account. (I clicked at account logo, but nothing happened)

**Comment by scb261** [comment] 2021-03-26 20:01
Yeah, not all sites are good with WebView, you can clear cookies in advanced settings. Since you signed in, I guess the issue is resolved?

**Comment by Nonamow** [comment] 2021-03-26 20:01
No.

**Comment by Nonamow** [comment] 2021-03-26 20:04
Yes, I can login in WebView, but... what's the point if I haven't access in app.

**Comment by scb261** [comment] 2021-03-26 20:04
So far you asked for log in and log out. You successfully logged in, and logging out can't be really fixed on the extension or app side, just clear cookies in advanced settings to log out. So what's the issue?

**Comment by scb261** [comment] 2021-03-26 20:04
Access to what?

**Comment by Nonamow** [comment] 2021-03-26 20:06
Wait please. Firstly, I will try to relogin.

**Comment by Nonamow** [comment] 2021-03-26 20:10
> Access to what?

Access to lock manga.

**Comment by scb261** [comment] 2021-03-26 20:13
You should have say from the start and give examples. Right now it looks like you don't want it to be fixed with limited info you're giving.

**Comment by Nonamow** [comment] 2021-03-26 20:14
Sorry.

**Comment by Nonamow** [comment] 2021-03-26 20:20
What happened:
1: I'm login in WebView.
2: I'm find "locked" manga.
3: ...but Tachiyomi still can't see any chapter.

**Comment by Riztard** [comment] 2021-03-27 05:20
> Manga example: remanga.org/manga/i-dont-really-get-it-but-it-looks-like-i-was-reincarnated-in-an-another-world

i cant even open that page

**Comment by scb261** [comment] 2021-03-27 05:26
I can after logging in. There is actually some stuff going on about locked manga, but I couldn't figure it out since I see array in both cases, probably looked in the wrong place
https://github.com/tachiyomiorg/tachiyomi-extensions/blob/434db9fe35de12b56457f0060f495e84c9aebf34/src/ru/remanga/src/eu/kanade/tachiyomi/extension/ru/remanga/Remanga.kt#L259

**Comment by Nonamow** [comment] 2021-03-27 08:32
> i cant even open that manga page
can you?
> I can after logging in.
Probably the same.

**Comment by Nonamow** [comment] 2021-03-27 08:41
![IMG_20210327_114016](https://user-images.githubusercontent.com/46028249/112715447-47ee6380-8ef1-11eb-82de-d15e0a3de660.jpg)

**Comment by Nonamow** [comment] 2021-03-28 12:40
>Probably

...or not. Tachiyomi can see locked manga even if I'm not authorized, but not additional information and chapters. As at screenshot ↑, but then I was authorized.

Summing up, after test on physical and virtual devices:
I failed at get access with WebView:
![image](https://user-images.githubusercontent.com/46028249/112752424-9aa44a00-8fdb-11eb-84d1-c5a105d2c073.png)
I haven't tried to setting up user&pass in setting yet:
![image](https://user-images.githubusercontent.com/46028249/112752297-fc17e900-8fda-11eb-96ed-f19a5e4bc3f8.png)
...so I can't access the chapters.

**Comment by Nonamow** [comment] 2021-03-28 12:49
![image](https://user-images.githubusercontent.com/46028249/112752669-c673ff80-8fdc-11eb-807b-4833dc73647e.png)
This worked after creating a new account (no google) and entering it in the settings.

**Comment by scb261** [comment] 2021-03-29 07:54
So, I looked into it while fixing a different extension that uses similar process for logging in, the problem is that it doesn't use cookies for logging in. Instead it uses separate http headers and request/response bodies.

In other words, logging in needs to be done via extension and not via WebView. And I'm not sure if it possible to do with Google instead of login/password. And iirc there is also some legal problem with using Google services in Tachiyomi, not sure if it's applicable here.

Could also try adding a field for the token in settings (not sure if it will work), but only advanced users could use it, since they need to get the token via dev tools in a browser.

**Comment by Nonamow** [comment] 2021-03-29 12:59
I wasn't expecting this to be so hard. Mm... Theoretically, can we grab token from WebView? Can we... Can we intercept requests? Oh... Even if it possible it should be so hard...

P.s. Now I understand that I should have chosen a more... decorous manga example.

**Comment by Nonamow** [comment] 2021-03-29 14:56
...is it possible to hide password in settings like ********, and prohibit editing — only re-entering to protect password?

**Comment by e-shl** [comment] 2021-04-07 18:01
> login using WebView

only by extension tools

> possible to hide password in settings like ********

The extension was created when this possibility was not. Now it is possible (but we forgot)

**Comment by Nonamow** [comment] 2021-04-07 18:17
@e-shl, thanks.

**Comment by e-shl** [comment] 2021-04-07 18:25
Closed

**Closed** 2021-04-07 18:26 UTC
Labels: enhancement
