### ISSUE TITLE
BUG - Unexpected JSON in extension

### ISSUE THREAD

**Issue by kageoni-7** [tachiyomiorg/tachiyomi-extensions#12024] opened 2022-05-31 11:39 UTC
### Source information

ArgosScan

### Steps to reproduce

Browser ->
ArgosScan

### Expected behavior

When opened it is expected to show the chapters list

### Actual behavior

When open in:

1. Browser: Unexpected JSON token at offset 168: Unexpected symbom 'f' in numeric literal JSON input: .....56.296Z","getChapters":[{"id":"ff80b4cd-85d1-4497-84497f918.....

2. Webview: work normally

### Tachiyomi version

0.13.4

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-05-31 15:05
Duplicate of #11950

**Closed by alessandrojean** 2022-05-31 15:05 UTC
Labels: Bug
