### ISSUE TITLE
Manhwa ax

### ISSUE THREAD

**Issue by fawadkhan121** [tachiyomiorg/tachiyomi-extensions#9721] opened 2021-11-02 08:38 UTC
### Source name

Manhwa ax

### Source link

https://manhwax.com

### Language

English 

### Other details

Faster updating chapters 18 +

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2021-11-23 22:06
Don't open duplicate issues for the same source, it will not make the source to gets added faster.

Duplicate of #6375

**Closed by alessandrojean** 2021-11-23 22:06 UTC
Labels: Source request
