### ISSUE TITLE
Sekaikomik change their domain

### ISSUE THREAD

**Issue by YareYare05** [tachiyomiorg/tachiyomi-extensions#11490] opened 2022-04-16 13:27 UTC
### Source name

Sekaikomik

### Source link

https://www.sekaikomik.live/

### Language

Indonesia

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-04-16 13:31
Duplicate of #8220

**Closed by alessandrojean** 2022-04-16 13:31 UTC
Labels: Source request

**Comment by YareYare05** [comment] 2022-04-16 13:39
> Duplikat 
the guy was wrong he said the domain was changed to sekaikomik.me but it should be changed to sekaikomik.live (I don't know if my pronunciation is correct or not because I use google translate)

**Comment by alessandrojean** [comment] 2022-04-16 13:41
There's no problem. Someones that will work on it just needs to know the domain changed, and this issue is also linked there.
