### ISSUE TITLE
1stkissmanga error

### ISSUE THREAD

**Issue by samanta-widjaja** [tachiyomiorg/tachiyomi-extensions#9377] opened 2021-10-06 07:41 UTC
### Source information

1st Kiss 1.2.17

### Steps to reproduce

Open the latest. It show 403 error. And the chapter image always show retry

### Expected behavior

Show latest manga and download running

### Actual behavior

Latest show 403 and chapter image always show retry

### Tachiyomi version

0.12.3

### Android version

Android 7.1.1 and android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by shipoxx** [comment] 2021-10-06 22:53
Duplicate of #7810

**Comment by wilwil1000** [comment] 2021-10-08 03:34
Same problem here its started happening 2 days ago, tried unisntalling reinstalling everything, this ticket is new and not a dupe to so please dont freaking close it shipoxx and loli, 1st kiss mangas dont update and shows error http 403 when trying to open, webview works though (but i still cant see which manga was updated) so its really annoying to check them 1 by 1

**Comment by samanta-widjaja** [comment] 2021-10-10 19:54
I re open the issue. The problem is starting again

**Comment by CarlosEsco** [comment] 2021-10-16 12:09
> Are we still working on this? Bug is still there

This is an open source project, feel free to submit a fix.  Nobody is assigned issues

**Comment by Waseem-Almoliky** [comment] 2021-11-07 15:27
You can use mangafoxfull or isekaiscans until they kill the bug.

**Comment by yatosoul** [comment] 2021-11-07 15:46
AZManhwa has most of the same titles and no bug if you want to switch there until it's resolved

**Closed** 2022-08-01 14:39 UTC
Labels: Bug
