### ISSUE TITLE
Webtoon extension not working

### ISSUE THREAD

**Issue by amNuel0** [tachiyomiorg/tachiyomi-extensions#10004] opened 2021-12-05 13:44 UTC
### Source information

Webtoons.com 1.2.23

### Steps to reproduce

1.  I selected the webtoon from my library
2. Selected the new chapters to download
3. It doesn't download
An error message appears on my notification "java.securiry.cert.CertPathValidatorException: Trust anchor for certification path not found"

### Expected behavior

It should download the webtoon

### Actual behavior

I doesn't download
Error message "java.securiry.cert.CertPathValidatorException: Trust anchor for certification path not found"

### Tachiyomi version

0.12.3

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2021-12-05 14:07
Duplicate of #9977

**Closed by arkon** 2021-12-05 14:07 UTC
Labels: Bug
