### ISSUE TITLE
API key expired or invalid 

### ISSUE THREAD

**Issue by AustinGF279** [tachiyomiorg/tachiyomi-extensions#13151] opened 2022-08-23 06:01 UTC
### Source information and language

Mangahub 1.3.20 (English)

### Steps to reproduce

Open any unread chapter in a manga in mangahub, I haven't checked for read chspters
![Uploading Screenshot_20220823-112430_Tachiyomi.jpg…]()

### Expected behavior

Opens the chapter

### Actual behavior

Unknown error occurred (API key expired or invalid)

### Tachiyomi version

 0.13.6

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment] 2022-08-23 06:37
Duplicate of #13151

**Closed by loocool2** 2022-08-23 06:37 UTC
Labels: Bug
