### ISSUE TITLE
Error 429

### ISSUE THREAD

**Issue by Chashi2904** [tachiyomiorg/tachiyomi-extensions#12618] opened 2022-07-18 08:43 UTC
### Source information

MangaBuddy 

### Steps to reproduce

Try to update the library but it doesn't update although there are new chapters 

### Expected behavior

The new chapters should be updated 

### Actual behavior

The new chapters are not being update 

### Tachiyomi version

0.13.5 

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by DchanN** [comment] 2022-07-18 09:21
Duplicate of #12613 more likely @Chashi2904 you just open the same issue again, you already report this (#12613) 19 hours ago

**Closed** 2022-07-18 10:37 UTC
Labels: Bug
