### ISSUE TITLE
LHTranslations showing https error 404

### ISSUE THREAD

**Issue by Quicksilver08** [tachiyomiorg/tachiyomi-extensions#8893] opened 2021-08-29 15:49 UTC
### Source information

LHTranslations

### Steps to reproduce

When clicked on LHTranslations extension it shows https error 404 but site opens in webview fine

### Expected behavior

Extension should load titles 

### Actual behavior

Shows https error 404

### Tachiyomi version

0.12.1

### Android version

Android 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment] 2021-08-29 15:55
Duplicate of #8727

**Closed by loocool2** 2021-08-29 15:55 UTC
Labels: Bug
