### ISSUE TITLE
MangaYaro

### ISSUE THREAD

**Issue by ellodandra** [tachiyomiorg/tachiyomi-extensions#10238] opened 2021-12-26 13:02 UTC
### Source name

MangaYaro

### Source link

https://mangayaro.com/

### Language

Indonesian

### Other details

![Screenshot_2021-12-26-20-01-01-36](https://user-images.githubusercontent.com/81138524/147408938-2bd98337-a5d2-4331-acdb-881f588ec683.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2021-12-26 14:09
Duplicate of #8907

**Closed by arkon** 2021-12-26 14:09 UTC
Labels: Source request
