### ISSUE TITLE
Asura Raw is broken

### ISSUE THREAD

**Issue by thdelio** [tachiyomiorg/tachiyomi-extensions#10792] opened 2022-02-11 14:03 UTC
### Source information

Asura Raw 1.2.16

### Steps to reproduce

1. click in the extention
2. doesn't show de mangas

### Expected behavior

shows the mangas 

### Actual behavior

doesn't show the mangas

### Tachiyomi version

0.13.1

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2022-02-11 21:50
Duplicate of #10756

**Closed by Seishirou101** 2022-02-11 21:50 UTC
Labels: Bug
