### ISSUE TITLE
Shinigami.id

### ISSUE THREAD

**Issue by Satriouz** [tachiyomiorg/tachiyomi-extensions#15441] opened 2023-02-22 02:38 UTC
### Source name

Shinigami ID

### Source link

https://shinigami.id/

### Language

Indonesia

### Other details

Because ReaperScans ID has a new sponsor, ReaperScans has changed its name to Shinigami.id and has no relationship with ReaperScans anymore, and please make an extension

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2023-02-22 02:42
Duplicate of #15408

**Closed by Seishirou101** 2023-02-22 02:42 UTC
Labels: Source request
