### ISSUE TITLE
Too many requests

### ISSUE THREAD

**Issue by Wolfangss** [tachiyomiorg/tachiyomi-extensions#13346] opened 2022-09-04 20:58 UTC
### Source information and language

Leviatan Scans 1.3.35 English

### Steps to reproduce

1. Opened a manhwa
2. Tried to update
3. "Too many requests:21" popped up

### Expected behavior

Manhwa should get updated

### Actual behavior

Got Error

### Tachiyomi version

0.13.6

### Android version

Adnroid 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2022-09-05 01:28
Duplicate of #13345

**Closed by vetleledaal** 2022-09-05 01:28 UTC
Labels: Bug
