### ISSUE TITLE
problem when opening sekte komik

### ISSUE THREAD

**Issue by Pengamen1kaos** [tachiyomiorg/tachiyomi-extensions#13138] opened 2022-08-22 16:16 UTC
### Source information and language

Indonesia 1.3.21

### Steps to reproduce

1. can't load 

### Expected behavior

there must be a mnhwa or something 

### Actual behavior

please fix 

### Tachiyomi version

0.13.6

### Android version

Android 10

### Other details

no results found 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment] 2022-08-22 17:35
Duplicate of #12995

**Closed** 2022-08-22 17:41 UTC
Labels: Bug
