### ISSUE TITLE
Immortal Update: new chapters loading in broken

### ISSUE THREAD

**Issue by eak0mo** [tachiyomiorg/tachiyomi-extensions#11235] opened 2022-03-25 07:02 UTC
### Source information

Immortal Updates 1.2.19

### Steps to reproduce

1. open a new chapter updated in the app this week (21/03/22-25/03/22)
2. first image doesn't load,  others after load broken

### Expected behavior

images should load like on the website

### Actual behavior

new images will load like the attached images, 
![image](https://user-images.githubusercontent.com/34249609/160070601-f2690570-a496-4d57-9509-11ae4a515e0c.png)
![image](https://user-images.githubusercontent.com/34249609/160070613-3e9d415c-a9c5-4b4a-9a16-f8cf8b8443a6.png)

### Tachiyomi version

0.13.1

### Android version

android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2022-03-25 15:28
Duplicate of #11214

**Comment by CrepeTF** [comment] 2022-04-02 13:30
#11214

**Closed by CrepeTF** 2022-04-02 13:30 UTC
Labels: Bug
