### ISSUE TITLE
Nana english

### ISSUE THREAD

**Issue by Kiki88x** [tachiyomiorg/tachiyomi-extensions#15784] opened 2023-03-21 08:18 UTC
### Source information and language

Nana english (version 1.4.2)

### Source new URL

https://ksk.moe/

### Other details

Make this secret to prevent irodori & fakku to find out 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-03-21 13:16
Duplicate of #15457

**Closed by arkon** 2023-03-21 13:16 UTC
Labels: Bug, Domain changed
