### ISSUE TITLE
Is this bug..or what happened ?

### ISSUE THREAD

**Issue by Kiki88x** [tachiyomiorg/tachiyomi-extensions#13610] opened 2022-09-27 18:07 UTC
### Source information and language

Doujindesu

### Steps to reproduce

#1. First open tachiyomi
#2. Second Open doujindesu
#3. Third No result found. 

### Expected behavior

Normally read all comics even the web still active but in tachiyomi unreadable. 

### Actual behavior

No result found

### Tachiyomi version

App version: 0.13.6 (standard, 1f79444, 82, 2022-08-14T15:52Z) Android version: 9 (SDK 28) Android build ID: 47.2.C.1.126 Device brand: KDDI Device manufacturer: Sony Device name: SOV36 Device model: SOV36 Device product name: SOV36_jp_kdi

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment] 2022-09-27 22:04
Duplicate of #13444

**Closed** 2022-09-27 22:05 UTC
Labels: Bug
