### ISSUE TITLE
[Source Request] <Manhwaz.com>

### ISSUE THREAD

**Issue by AfanJurl** [tachiyomiorg/tachiyomi-extensions#6396] opened 2021-04-02 13:59 UTC
---

## Source 
- Name: Manhwaz
- Link: https://manhwaz.com/
- Language(s): English

## Other details
Mostly manhwas and isekai

**Comment by keinezeit8** [comment] 2021-04-18 20:25
duplicate of #6286

**Closed** 2021-04-18 20:27 UTC
Labels: Source Request
