### ISSUE TITLE
Downloading error in Buon Dua 1.2.1

### ISSUE THREAD

**Issue by esthapa** [tachiyomiorg/tachiyomi-extensions#11497] opened 2022-04-17 06:20 UTC
### Source information

Buon Dua 1.2.1

### Steps to reproduce

Downloading error.when we start to download it will halfly download and then suddenly becomes error

### Expected behavior

The thing should be downloaded

### Actual behavior

It shows that it is downloaded but it is an error.it is not actually downloaded

### Tachiyomi version

"0.13.3"

### Android version

"Android 11"

### Other details

Downloading issue

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-04-17 14:24
Duplicate of #11330

**Closed by alessandrojean** 2022-04-17 14:24 UTC
Labels: Bug
