### ISSUE TITLE
Webtoons.com extension error

### ISSUE THREAD

**Issue by fam007e** [tachiyomiorg/tachiyomi-extensions#9988] opened 2021-12-03 09:28 UTC
### Source information

Webtoons.com 1.2.32

### Steps to reproduce

Opening the browse option to get to the manhuas of extension for "webtoons.com".

### Expected behavior

Opens the manhuas.

### Actual behavior

Error message: "Cause already initialized".

### Tachiyomi version

Tachiyomi v8.6.5-AZ

### Android version

Android v5.1.1

### Other details

Tried installing the extension fresh after uninstalling and rebooting as well.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2021-12-04 14:52
Duplicate of #9977

**Closed by arkon** 2021-12-04 14:52 UTC
Labels: Bug
