### ISSUE TITLE
Sekte Doujin Can't Show Up The Image Of The Manga

### ISSUE THREAD

**Issue by Kycsq** [tachiyomiorg/tachiyomi-extensions#12387] opened 2022-06-30 22:11 UTC
### Source information

Sekte Doujin 1.3.18

### Steps to reproduce

1. Open any manga from Sekte Doujin
2. Select any chapter from that manga
3. Open that chapter

### Expected behavior

And it goes like this
![Screenshot_20220701-054913_Tachiyomi](https://user-images.githubusercontent.com/108495656/176787070-4a477382-79c7-4bfd-9d1d-468b26836be4.jpg)

### Actual behavior

It should be show up the image like normal

### Tachiyomi version

0.13.4 

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by mxsgx** [comment] 2022-07-01 09:29
Duplicate of #11874

**Closed** 2022-07-01 13:31 UTC
Labels: Bug
