### ISSUE TITLE
Manhuaren:  no value for response

### ISSUE THREAD

**Issue by Haojyin** [tachiyomiorg/tachiyomi-extensions#17120] opened 2023-07-15 18:31 UTC
### Source information

Manhuaren1.4.11

### Source language

Chinese

### Steps to reproduce

1.open  manhuaren
2. no value for response
3. Repeat 1 to 2

### Expected behavior

I don,t know why  i can,t use manhuaren.

### Actual behavior

I don,t know. I still can,t open manhuaren.

### Tachiyomi version

0.14.6  

### Android version

Android 13

### Other details

Plz fix this problem! Thx.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment] 2023-07-15 18:46
Duplicate of #17061

**Closed by stevenyomi** 2023-07-15 18:46 UTC
Labels: Bug
