### ISSUE TITLE
[Feature Request] <new section to get manga/manhwa recomandation>: <manga/manhwa recommadation feature>

### ISSUE THREAD

**Issue by ErenYeagar** [tachiyomiorg/tachiyomi-extensions#5690] opened 2021-02-08 10:19 UTC
Please add a section in app where it recommend us the good manga or manhwa 
Or it recommend the manga or manhwa based on users manga/manhwa which is currently being read now
By this feature it will be easy to find good manga or manhwa to read

**Comment by scb261** [comment] 2021-02-08 10:24
Duplicate of tachiyomiorg/tachiyomi/issues/376

**Closed by scb261** 2021-02-08 10:24 UTC
Labels: enhancement
