### ISSUE TITLE
Yonabar

### ISSUE THREAD

**Issue by 5OSA** [tachiyomiorg/tachiyomi-extensions#18259] opened 2023-09-30 02:46 UTC
### Source name

Yonabar

### Source language

العربية

### Source link

https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://yonabar.com/&ved=2ahUKEwjV1YqBqNGBAxUlUqQEHQxSCmoQFnoECBEQAQ&usg=AOvVaw2luBTTX9xelhwmXNc-3YJ9

### Other details

It's not working anymore 

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2023-09-30 03:20
Duplicate of #15169?

**Closed by Seishirou101** 2023-09-30 03:20 UTC
Labels: Source is down
