### ISSUE TITLE
[Source Request] <kuman55>

### ISSUE THREAD

**Issue by suvendu1997** [tachiyomiorg/tachiyomi-extensions#5852] opened 2021-02-14 19:12 UTC
---

## Source website
- Name: kuman55
- Link: http://m.kuman55.com/
- Language(s): chinese

## Other details
http://m.kuman55.com/23750/

**Comment by scb261** [comment] 2021-02-14 19:21
Duplicate of #4541

**Closed by scb261** 2021-02-14 19:21 UTC
Labels: Source Request
