### ISSUE TITLE
Hero Manhua: 404 Error in Search, Latest and Browse

### ISSUE THREAD

**Issue by alexporth** [tachiyomiorg/tachiyomi-extensions#8014] opened 2021-07-08 13:24 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android 10

### Source information

Hero Manhua 1.2.7

### Steps to reproduce

1. Goto Browse
2. Tap "Hero Manhua" either directly or latest
3. Get HTTP error 404
4. Click Open in WebView
5. See that the site works

### Expected behavior

The app should display the manga of the group.

### Actual behavior

A HTTP 404 error occurs.

**Comment by Clouddark75** [comment] 2021-07-08 21:16
Duplicate of #7449.

**Closed** 2021-07-08 21:28 UTC
Labels: Bug
