### ISSUE TITLE
problem opening Sekte komik

### ISSUE THREAD

**Issue by Pengamen1kaos** [tachiyomiorg/tachiyomi-extensions#13403] opened 2022-09-08 17:12 UTC
### Source information and language

Indonesia 1.3.25

### Steps to reproduce

1.when opening sekte komik there are no comics that I see only the words "result not found" 

### Expected behavior

1.it should be when i open sekte komik there is a manhwa/comic 

### Actual behavior

yeah as soon as you can please help 😄

### Tachiyomi version

0.13.6

### Android version

Android 10

### Other details

![Screenshot_20220908-234729_Tachiyomi](https://user-images.githubusercontent.com/111288479/189184052-71d0a97f-ab0c-4f00-9872-e954b43eff8d.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-09-08 21:34
Duplicate of #12995

**Closed by alessandrojean** 2022-09-08 21:34 UTC
Labels: Bug
