### ISSUE TITLE
Mangaowl only showing one chapter in chapter list.

### ISSUE THREAD

**Issue by Drakoney** [tachiyomiorg/tachiyomi-extensions#9894] opened 2021-11-22 04:18 UTC
### Source information

Mangaowl 1.2.22

### Steps to reproduce

Open comic
Chapter list only showing one chapter

### Expected behavior

Open comic 
should see all chapters

### Actual behavior

Opening the comic and it only showed obe chapter that is the latest.

### Tachiyomi version

0.12.3

### Android version

6

### Other details

My friend who also has the latest updated tachiyomi is experiencing the same problem
![Screenshot_2021-11-22-12-10-12](https://user-images.githubusercontent.com/84439474/142800531-79f65fcb-00ea-47e2-8bbf-bcdaebac69b4.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2021-11-22 04:27
Please actually do what the acknowledgements say when you check them. Update your extension.

**Comment by Seishirou101** [comment] 2021-11-22 04:27
Duplicate of #9871

**Closed** 2021-11-22 04:28 UTC
Labels: Bug

**Comment by vevinawynn** [comment] 2021-11-23 06:51
Please fix this asap, even my downloaded chapter disappeared T.T

**Comment by vevinawynn** [comment] 2021-11-23 06:57
This also happened to me before and after updating tachiyomi to 0.12.3
I have also updated mangaowl extension
I have deleted cache
