### ISSUE TITLE
MangaHub:Failed to load Pages 

### ISSUE THREAD

**Issue by PheonixGamer09** [tachiyomiorg/tachiyomi-extensions#16306] opened 2023-05-04 12:17 UTC
### Source information

MangaHub 1.4.28

### Source language

English

### Steps to reproduce

All Manga chapter pages are not loading. Instead it shows
![IMG_20230504_090039](https://user-images.githubusercontent.com/128516302/236200813-243b76f3-f657-4d49-b103-06a09160c4c2.jpg)

### Expected behavior

All manga chapter pages should have loaded just like in website.

### Actual behavior

It shows 
![Screenshot_2023-05-04-17-47-13-294_eu kanade tachiyomi](https://user-images.githubusercontent.com/128516302/236201379-e4b20684-36fc-4091-ae71-c2972d557513.jpg)
![Screenshot_2023-05-04-08-53-00-699_eu kanade tachiyomi](https://user-images.githubusercontent.com/128516302/236201392-2889597a-7da7-4c91-a7e9-499edb758582.jpg)

### Tachiyomi version

0.14.6

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2023-05-04 15:31
Duplicate of #16297

**Closed by Seishirou101** 2023-05-04 15:31 UTC
Labels: Bug
