### ISSUE TITLE
To many follow up requests

### ISSUE THREAD

**Issue by Driagis** [tachiyomiorg/tachiyomi-extensions#13101] opened 2022-08-20 04:01 UTC
### Source information and language

Asura scans - English 

### Steps to reproduce

1. Update/load library.
2. Wait
3. Updates failed to many follow up requests

### Expected behavior

Should update manga/manhwa

### Actual behavior

Does not update manga/manhwa

### Tachiyomi version

1.5.6

### Android version

Android 12

### Other details

Using tachij2k

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-08-20 04:06
Duplicate of #13014

**Closed by arkon** 2022-08-20 04:06 UTC
Labels: Bug
