### ISSUE TITLE
Cant load any manga

### ISSUE THREAD

**Issue by SaiIBar** [tachiyomiorg/tachiyomi-extensions#10231] opened 2021-12-26 07:49 UTC
### Source information

Gmanga 

### Steps to reproduce

Index 8 size 5 and size 2

### Expected behavior

Open manga

### Actual behavior

Nothing shown 

### Tachiyomi version

0.12.3

### Android version

Android 11

### Other details

There have always issues with gmanga and it's the best source of arab

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2021-12-26 10:52
Duplicate of #10161

**Closed by alessandrojean** 2021-12-26 10:52 UTC
Labels: Bug
