### ISSUE TITLE
Doujindesu tidak ada gambar sampulnya 

### ISSUE THREAD

**Issue by Mugenjin07** [tachiyomiorg/tachiyomi-extensions#11944] opened 2022-05-23 06:49 UTC
### Source information

Doujindesu 1.2.2

### Steps to reproduce

Saya tidak bisa pemerograman jadi saya ga tau harus gimana 

### Expected behavior

Seharusnya bisa seperti ini 

### Actual behavior

![Screenshot_20220523-144252_Tachiyomi](https://user-images.githubusercontent.com/82618225/169759730-c104569e-2132-4d2e-baf8-e68fcdcb52b5.png)
Tapi ketika membuka doujindesu gambar sampulnya tidak ada 

### Tachiyomi version

0.13.4

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment] 2022-05-23 10:57
Duplicate of #11662

**Closed** 2022-05-23 12:09 UTC
Labels: Bug
