### ISSUE TITLE
Manhwa18.com extension not working

### ISSUE THREAD

**Issue by alexphilip0019** [tachiyomiorg/tachiyomi-extensions#10053] opened 2021-12-09 10:35 UTC
### Source information

Manhwa18

### Steps to reproduce

Open manhwa18 
Shows http 404 error 
Webview is working the site is loading

### Expected behavior

Should display manga library

### Actual behavior

Error 404

### Tachiyomi version

0.12.3

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by fawadkhan121** [comment] 2021-12-09 16:13
Please some one fix this 🙏

**Comment by arkon** [comment] 2021-12-16 22:31
Duplicate of #9935

**Closed by arkon** 2021-12-16 22:31 UTC
Labels: Bug
