### ISSUE TITLE
MangaHub:Chapters Issue some pages say retry

### ISSUE THREAD

**Issue by Davidbolt121199** [tachiyomiorg/tachiyomi-extensions#14911] opened 2023-01-12 13:39 UTC
### Source information and language

Mangahub 1.3.22(English)

### Steps to reproduce

1. Chapter pages are not loaded. 
2. Some chapter pages say retry. 
3. Only one or two pages are loaded rest shows retry. 
4. It's been 2-3 weeks that this issue is showing. 

### Expected behavior

All pages should have been loaded properly. 

### Actual behavior

Recently updated chapters show this issue. 

### Tachiyomi version

0.14.2

### Android version

Android 12

### Other details

![Screenshot_2023-01-12-17-46-55-162_eu kanade tachiyomi](https://user-images.githubusercontent.com/121578582/212079277-ce478acf-09cf-4f68-bc74-9a193ec82e51.jpg)
![211206817-80cc4826-88fd-4976-bd95-88347c93787a](https://user-images.githubusercontent.com/121578582/212079560-f60979cc-98a5-48c5-98cb-a8f8eba6d41d.jpg)
![210123534-951010b2-314e-4086-a8b3-f88034135e4b](https://user-images.githubusercontent.com/121578582/212079727-54e2e128-9622-4bdc-a8e3-2f6f01496f8c.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2023-01-12 20:14
Duplicate of #14736

**Closed by alessandrojean** 2023-01-12 20:14 UTC
Labels: Bug
