### ISSUE TITLE
WIB Translation

### ISSUE THREAD

**Issue by ellodandra** [tachiyomiorg/tachiyomi-extensions#8457] opened 2021-08-08 07:56 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

WIB Translation

### Source link

https://www.wib.my.id/

### Language

Indonesia

### Other details

![Screenshot_2021-08-08-14-55-37-92](https://user-images.githubusercontent.com/81138524/128625149-715bd4ab-0a9f-4906-ba09-e7f0e228e09d.png)
WIB Translation not yet on tachiyomi, please add it

**Comment by HaruSasaki** [comment] 2021-08-08 11:37
Duplicate of #8146

**Closed** 2021-08-08 11:39 UTC
Labels: Source request
