### ISSUE TITLE
Error in arabic extension  مانجا ليك 

### ISSUE THREAD

**Issue by Abdo-ka** [tachiyomiorg/tachiyomi-extensions#14300] opened 2022-11-19 01:46 UTC
### Source information and language

 "مانجا ليك  v1.3.27 (Arabic)"

### Steps to reproduce

1. Open any manga 
2. Try download it or reading it 
3. Here is issue 

### Expected behavior

"Download it or read it but I can not "

### Actual behavior

This is happening  in the last update of this extension 

### Tachiyomi version

"0.14.2"

### Android version

"Android 10"

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-11-19 01:50
Duplicate of #14281

**Closed by alessandrojean** 2022-11-19 01:50 UTC
Labels: Bug
