### ISSUE TITLE
[Bug] <Mangakakalot, Manganelo>: <There's nothing showing up when I search nor when I click the source.>

### ISSUE THREAD

**Issue by Chestur** [tachiyomiorg/tachiyomi-extensions#5743] opened 2021-02-10 12:46 UTC
**

## Device information
- Tachiyomi version: 0.10.8
- Android version: 9

## Source information
- Name: Manganelo and Mangakakalot
- Extension version: 1.2.1

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
When I open the sources it shows manga. When I search for a certain manga it would show up if its available.
### Actual behavior
When I open the sources it says no results found. This also happens when I search for a manga

**Comment by scb261** [comment] 2021-02-10 12:48
Duplicate of #5719

**Closed by scb261** 2021-02-10 12:48 UTC
Labels: bug
