### ISSUE TITLE
Toonily "failed to bypass cloudflare"

### ISSUE THREAD

**Issue by CodeZero002** [tachiyomiorg/tachiyomi-extensions#10236] opened 2021-12-26 12:43 UTC
### Source information

Toonily 1.2.20

### Steps to reproduce

1. Open Toonily on Tachiyomi / Aniyomi
2. Then it will say "failed to bypass cloudflare"

### Expected behavior

The manga's will appear as it should.

### Actual behavior

It says "failed to bypass cloudflare"
![IMG_20211226_203954](https://user-images.githubusercontent.com/88552180/147408376-a586d727-2a59-460f-87e5-66d061413fef.jpg)

### Tachiyomi version

0.12.3.5

### Android version

Android 8

### Other details

![IMG_20211226_203954](https://user-images.githubusercontent.com/88552180/147408395-ee243c02-aa3f-44cc-8bc3-65aea9ee7d01.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2021-12-26 14:10
Duplicate of#5613

**Closed by arkon** 2021-12-26 14:10 UTC
Labels: Bug
