### ISSUE TITLE
Gmanga chapter pages don't load

### ISSUE THREAD

**Issue by Xocv** [tachiyomiorg/tachiyomi-extensions#9175] opened 2021-09-21 20:08 UTC
### Source information

Gmanga 1.2.6

### Steps to reproduce

Go to gmanga
Go to any manga
It loads the chapters
But when i open the chapter it say retry for all the pages in any manga

### Expected behavior

It should load the pages of the chapter

### Actual behavior

It doesn't load the pages of the chapter but it loads the chapters numbers and names

### Tachiyomi version

Tachij2k 1.3.1

### Android version

Android 10

### Other details

The issue is not in the chapters numbers or it doesn't load it's in the chapters i mean the pages of the manga

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2021-09-21 20:09
Duplicate of #9125

Stop opening duplicate issues.

**Closed by alessandrojean** 2021-09-21 20:09 UTC
Labels: Bug
