### ISSUE TITLE
Manga owl no page found

### ISSUE THREAD

**Issue by Gtrenderer** [tachiyomiorg/tachiyomi-extensions#10571] opened 2022-01-24 18:27 UTC
### Source information

Mangaowl 1.12.24

### Steps to reproduce

Attempt to open a chapter of my hero academia or dragon ball super

### Expected behavior

Open chapter to view for reading

### Actual behavior

Takes you back to chapter menu

### Tachiyomi version

12.3

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-01-24 18:39
Duplicate of #10464

**Closed by arkon** 2022-01-24 18:39 UTC
Labels: Bug
