### ISSUE TITLE
MangaDex: add filter by scanlation group

### ISSUE THREAD

**Issue by igorpc1** [tachiyomiorg/tachiyomi-extensions#11156] opened 2022-03-17 08:01 UTC
### Describe your suggested feature

It would be nice if we could filter chapters by which group did the scanlation

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment] 2022-03-17 08:03
Duplicate of https://github.com/tachiyomiorg/tachiyomi/issues/969

**Closed by loocool2** 2022-03-17 08:03 UTC
Labels: Feature request
