### ISSUE TITLE
Source not found

### ISSUE THREAD

**Issue by Princess137** [tachiyomiorg/tachiyomi-extensions#12160] opened 2022-06-11 14:57 UTC
### Source information

Komik cast 1.3.25

### Steps to reproduce

Can't read the new chapter (no pages found)

### Expected behavior

Web migration

### Actual behavior

Web view run normally

### Tachiyomi version

0.13.4

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-06-11 14:58
Duplicate of #12147

**Closed by alessandrojean** 2022-06-11 14:58 UTC
Labels: Bug
